### ISSUE TITLE
Add info to documentation that "block_store_path" is optional

### ISSUE THREAD

**Issue by baziorek** [hyperledger/iroha#1019]
During last di-weekly meeting Kamil said that we can disable using blocks as files, but we can enable storing them in database.
I've checked this by removing:
```
"block_store_path": "/tmp/block_store/"
```
from config file (of course no environment variable `IROHA_BLOCK_STORE_PATH` was set) and it worked - the node started up and database looked a little different but everything was working.

So I suggest to tell in documentation: https://iroha.readthedocs.io/en/main/configure/index.html that the parameter `IROHA_BLOCK_STORE_PATH` is optional now.

**Comment by LiraLemur** [comment]
@kamilsa can you please clarify what this is about? Is that expected behavior?

**Comment by kamilsa** [comment]
We should update in documentation:
`block_store_path sets path to the folder where blocks are stored.` -> `block_store_path sets path to the folder where blocks are stored. If this parameter is not set, blocks are stored in database`
