### ISSUE TITLE
Builder and Validator Improvement Proposal

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1031]
# Builders Improvement Proposal

## Moving Versus Copying

Current builders perform copy of whole builder during each setX() call, which has big performance impact. In cases where it is undesirable, it should be possible to specify whether builder should copy itself after each state change. To do that, we can use partial template instantiation:

```C++
#include <iostream>
#include <type_traits>

template<bool Copy, typename T> struct Transformer;

template<typename T>
struct Transformer<false, T> {
    T&& operator()(T &t) {
        // perform logic
        return std::move(t);
    }
};

template<typename T>
struct Transformer<true, T> {
    T operator()(const T &t) {
        T copy{t};
        // perform logic
        return copy;
    }
};

template <bool Copy>
class Builder {
  public:
    Builder() = default;
    Builder(Builder &&b) {
        std::cout << "moving\n";
    }

    Builder(const Builder &b) {
        std::cout << "copying\n";
    }

    Builder set() {
        return transform(*this);
    }

  private:
    Transformer<Copy, Builder> transform;
};


int main() {
    Builder<true> copyBuilder;
    Builder<false> moveBuilder;

    copyBuilder.set();
    moveBuilder.set();
    return 0;
}
```

This prints

```bash
copying
moving
```

It can be extended to other strategies by replacing bool with enum and providing more specializations of Transformer.

## Strategy for object instantiation

Object creation can fail, and there are several strategies to deal with the error. For internal use we may prefer returning Result-like construct, but as an interface to other languages, exception is a better choice. That is why we would like to implement ability to pass strategy of object building to builder.

```C++
#include <iostream>
#include <exception>
#include <utility>

template<typename T>
using Result = std::pair<T, std::string>;

template <typename ResultType, typename BuildFunction>
class Builder {
  private:
    BuildFunction build_function;
  public:
    using ReturnType = decltype(build_function(std::declval<ResultType>()));

    ReturnType build(int i) {
        ResultType object{i};
        return build_function(object);
    }

    Builder() = default;

    template <typename BF>
    explicit Builder(BF &&b): build_function{std::forward<BF>(b)} {}
};

template <typename T, typename BuildFunction>
Builder<T, BuildFunction> makeBuilder(BuildFunction &&bf) {
    return Builder<T, BuildFunction>(std::forward<BuildFunction>(bf));
}

template <typename T>
struct ExceptionBuilder {
    T operator()(const T& t) {
        if (t < 0) {
            throw std::invalid_argument("Exception in builder!");
        }
        return t;
    }
};

int main() {

    // construct with function object
    Builder<int, ExceptionBuilder<int>> exception_builder;

    // construct with lambda expression
    auto result_builder = makeBuilder<int>([](auto t) {
        if (t < 0) {
            return std::make_pair(0, "error in builder!");
        }
        return std::make_pair(t, "");
    });

    auto result = result_builder.build(2);
    std::cout << result.first << "\n" << result.second << "\n";
    return 0;
}
```

**Comment by Warchant** [comment]
>However, when we introduce the ability to replace field validator, we allow the creation of invalid objects.
It is a requirement

**Comment by nickaleks** [comment]
Can you provide an example of such test?

**Comment by muratovv** [comment]
About free functions for stateless validation.

I'm not sure that this approach suitable for stateless validation cause it leads to redundant complexity. For example, we want to build up stateless validation for the transaction. On the client side we need to check the schema of the transaction - boundary values for commands, a schema of the accounts an so on. But on the Iroha side, we need to validate schema and signatures. 
With free function approach, we will write combine by our self. But in fact, it is just a combination of validators.

About template arguments.

In terms of the design shared model objects are same dependency as others. Thus, we require mocks shared model object for testing purposes. And in this case, it very convenient way to use an explicit template parameter for testing purposes.
But maybe we need to come up with the improvement that able to handle calls unregistered in the builder and throw the exception.

Also, I can not understand from the report why composable way is not applied in the stateless validation. And what about auto checking via getters?

**Comment by nickaleks** [comment]
> I'm not sure that this approach suitable for stateless validation cause it leads to redundant complexity. For example, we want to build up stateless validation for the transaction. On the client side we need to check the schema of the transaction - boundary values for commands, a schema of the accounts an so on. But on the Iroha side, we need to validate schema and signatures.
With free function approach, we will write combine by our self. But in fact, it is just a combination of validators.

I do not understand what do you mean by redundant complexity? We cannot trust the client to send correct data, so we every time we accept a new transaction, we need to validate **everything**. With free functions, this will be as easy as calling validate(transaction)

> In terms of the design shared model objects are the same dependency as others. Thus, we require mocks shared model object for testing purposes. And in this case, it very convenient way to use an explicit template parameter for testing purposes.

Can you please provide an example where we need to mock object with _invalid_ data? I assume that we expect all components of Iroha to work only with correct values (that's why we do not perform stateless validation on each step of the pipeline)

**Comment by muratovv** [comment]
>redundant complexity
I mean there is need to write different functions of the combine by yourself.

>we need to validate everything
Sure u are totally correct. But this issue unrelated to my ideas.

>Can you please provide an example where we need to mock object with invalid data?
Just shallow search:
* https://github.com/hyperledger/iroha/blob/def7bc4f7efdf0c2d1c3caecccd2cf3efe0c889e/test/module/irohad/ordering/ordering_service_test.cpp#L121
* https://github.com/hyperledger/iroha/blob/def7bc4f7efdf0c2d1c3caecccd2cf3efe0c889e/test/module/irohad/consensus/yac/peer_orderer_test.cpp#L58
* https://github.com/hyperledger/iroha/blob/def7bc4f7efdf0c2d1c3caecccd2cf3efe0c889e/test/module/irohad/ametsuchi/ametsuchi_test.cpp#L185

But in fact, there are a lot of usages of mock objects in tests. And this is the convenient and correct approach.

**Comment by l4l** [comment]
> Just shllow search

That solved via Test*Builder as in your example, there's no usage of FieldValidator here

**Comment by nickaleks** [comment]
Updated proposal to include features for builders. Features for validators are WIP and will be added later

**Comment by nickaleks** [comment]
Builder prototype is at #1306
