### ISSUE TITLE
Permission Implementation Improvement

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1045]
# Permissions Implementation Improvement

This document provides an overview of a proposal to improve implementation of permissions in shared model.

_Note_: This document does not discuss current permission model, its scope is pure technical and does not affect behavior of the system.

## Permission Model

Each role has a set of permissions, associated with it. Additionally, each account can have so called _grantable permissions_, which are permissions given to it by some other account. Grantable permissions allow account to perform some actions on other account.

In order to execute a command, account needs to have certain permission. Each command has unique permissions for its execution. Also, some commands require additional permissions, e.g _transferAsset_ command requires destination account to have _can_receive_asset_ permission.

Each query has 3 distinct permissions associated with it. They allow executing query on a specific account, domain or globally.

For example account A can have permission to get balance of account A, so he will not have permission to get balance of account B, even if they belong to the same domain. However, if account A has _domain_ permission, to get balance, it would be possible to perform query on account B.

## Current Permission Implementation

Currently, all permissions in Iroha are implemented as strings. This has exactly one benefit - ease of use for developers. Strings are easy to debug and code working with strings is straightforward.

However, strings have several disadvantages. First of all it is easy to mistype them, for clients and developers. They need to be allocated and take up a lot of space. They are not type-safe and thus error-prone.

This proposal tries to solve given issues while maintaining ease of use.

## Enum Based implementation

Enum is a good choice for permissions, since they are just set of constants. It provides type-safety, efficiency, and clarity.

I propose we declare permission Enum - either one, or several for command, query, and grantable permissions, each command and query will have an associated permission as a static const variable of a class.

We would need to define mapping for protobuf and postgres enums. This could be done by assigning same integer values to corresponding permissions in all three enums and then simply performing static_cast. This way we can avoid defining giant switch-cases / maps.

One big issue with enums in C++ is that there is no idiomatic way to get string representation. There are several possible solutions to this issue:

1. Brute force - define mapping from each permission to string

2. Rely on implementation, such as protobuf to provide mapping. Define abstract class like PermissionPrinter, which will have virtual method toString(permission) and implement it for each backend of shared model. Since we can map protobuf enums to our enums, we can use protobuf reflection as one possible implementation.

3. Rely on things such as Boost Preprocessor or other code-generation solutions.

This issue is open for discussion and would like to hear an opinion of other developers.

**Comment by Warchant** [comment]
>It provides type-safety 

no. Unless, you use scoped enum.

I like defining some kind of singleton or static array `const char* map[] = {"permA", "permB"};
And cast to string like 

```
enum class Perm: uint32_t {A, B}; 
Perm a = Perm::A;
map[a]; // I am not sure actually, if it has implicit cast to int or not, but idea is like this
```

**Comment by nickaleks** [comment]
> no. Unless, you use scoped enum.

Of course we would use scoped enum. I did not mention that since it seems to obvious

**Comment by l4l** [comment]
So far I have 3 ideas for solving it issue (feel free to propose new one). The first two use additional strings as it is, the last one is prefer depend on the protobuf (thus less transport-agnostic, but more stable).
All the ways describe how define `enum Permission`, and related `toString` & `fromString` functions. Imo that should be enough for replacing (am I missing smth?).

p.s code may cause compile-errors, consider as pseudo-code

1. Macros. Yes, they are considered evilish but the solution is the most compact and has no code duplication at all.
**New permission** -> 1 LOC

```cpp
#define __PERM_SWITCH_TOSTR(r, _, elem) case Permission::elem: return ##elem;
#define __PERM_SWITCH_FROMSTR(r, _, elem) {##elem, Permission::elem}
#define PERM_DEF(perm_list)                                         \
  enum class Permission {                                          \
    perm_list                                                      \
    , NONE                                                         \
  };                                                               \
  inline const std::string toString(Permission p) {                \
    switch (p) {                                                   \
      BOOST_PP_SEQ_FOR_EACH(__PERM_SWITCH_TOSTR, _, perm_list)     \
    }                                                              \
    return "undefined";                                             \
  }                                                                \
  inline Permission fromString(const std::string s) {              \
    static std::map<std::string, Permission> m {                   \
      BOOST_PP_SEQ_FOR_EACH(__PERM_SWITCH_FROMSTR, _, perm_list)   \
    };                                                             \
  }

PERM_DEF((can_receive)
         (can_transfer)
         (can_create_domain)
         ...)
```

2. Constexpr maps, a lot of code duplication but compile-time (-> prob less error-prone), need to write function str -> enum (idk how to do it via templates). It is roughly same to the case enum+pair of methods, I don't show  this case, because constexpr-maps is a bit better (for toString)
**New permission** -> 4 LOC (enum + PermMap::s (x2) + fromString's map)

```cpp
enum class Permission {
  can_receive,
  can_transfer,
  can_create_domain,
};

template<Permission>
class PermMap {
  static const std::string s;
};

template<>
const std::string PermMap<Permission::can_receive>::s = "can_receive";

inline const std::string toString(Permission p) {
  return PermMap<p>::s;
}

inline Permission fromString(const std::string s) {
  static const std::map<std::string, Permission> m {
    {"can_receive", Permission::can_receive},
    {"can_transfer", Permission::can_transfer},
    {"can_create_domain", Permission::can_create_domain},
    ...
  };
  return m[s];
}
```

3. Depend on the protobuf, the most elegant way. The only problem that it highly depend on the transport so imo it is a bad thing to use. Also protobuf uses `enum` (NOT `enum class`, so weak typing  might be a huge problem in future)
**New permission** -> 0 LOC
Though protobuf updates may need some fixes

```cpp
using Permission = iroha::protocol::RolePermission;

inline const std::string toString(Permission p) {
  return iroha::protocol::RolePermission_Name(p);
}

inline Permission fromString(const std::string &s) {
  Permission p;
  iroha::protocol::RolePermission_Parse(s, &p);
  return p;
}
```

**Comment by neewy** [comment]
> In order to execute a command, account needs to have certain permission. 

Well, it has to have a _role_

**Comment by nickaleks** [comment]
It would be simpler to have switch case for toString, and do not implement fromString at all, since it is not needed much.

**Comment by neewy** [comment]
I thought that you need fromString operation for deserialization, e.g. in genesis block a role can be created

**Comment by nickaleks** [comment]
We use protobuf for deserealization

**Comment by neewy** [comment]
Good
