### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by walkero** [hyperledger/iroha#1081]
I got an error when I run **irohad**
`irohadh --config example/config.sample --genesis_block example/genesis.block --keypair_name example/node0` 
error message:
`what():    JSON parse error: eample.sample`

I built iroha at ubuntu docker environment：
`git clone -b develop --depth=1 https://github.com/hyperledger/iroha`
`sh run-iroha-dev.sh`
`cmake -H. -Bbuild; cmake --build build -- -j$(nproc)`
`make`

How can I solve this problem?

Thanks

**Comment by l4l** [comment]
Hmm, that is really strange, can be a rapidjson bug. I also have that behavior nevertheless the tests are green.
Try to add an empty new line at the example/config.sample, that solves the issue for me.

**Comment by walkero** [comment]
@l4l @luckychess thank you very much.
The problem had been solved by running irohad with right directory path
(I had a mistake using  wrong directory path before).

`pwd`
`/opt/iroha/bin`

`./irohad --config ../example/config.sample --genesis_block ../example/genesis.block --keypair_name ../example/node0

server is up!

**Comment by l4l** [comment]
Good, I close the issue then
