### ISSUE TITLE
Glossary still refers to Sumeragi, not YAC.

### ISSUE THREAD

**Issue by rpjday** [hyperledger/iroha#1090]
Should glossary not be updated to refer to YAC as current Iroha consensus mechanism?

**Comment by l4l** [comment]
These consensus have a lot of thing in common, so the terms may intersect.
Could you point out where is the inconsistency placed?

**Comment by l4l** [comment]
Good point, wiki isn't really maintained for now, so there may be a plenty of such outdated info

**Comment by neewy** [comment]
Hi @rpjday,
we are sorry to keep irrelevant things in our wiki and to confuse you by this discrepancy. 
For now we are migrating to ReadTheDocs and we will rewrite glossary from scratch:
http://iroha.readthedocs.io/en/latest/core_concepts/

**Comment by neewy** [comment]
We will delete all other public docs as we will publish read the docs with new release, stay tuned

**Comment by rpjday** [comment]
Excellent, thanks very much.
