### ISSUE TITLE
Automatically close old PRs and issues

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#1094]
https://github.com/probot/stale this tool can be used for automatic handling of old PRs and issues, so we don't need to check them manually. What do you think?

**Comment by l4l** [comment]
I think it is better (at least for now) to handle it by ourselves. It is not that many issues opened
Moreover it is possible ask the issuer to retest behavior with current commit and not just blindly close it after some time. Even if the bot may do it I am pretty sure there is a huge number of such a cases
