### ISSUE TITLE
error when trying to Launch irohad

### ISSUE THREAD

**Issue by jjacquet** [hyperledger/iroha#1129]
I am following the document to launch iroha https://hyperledger.github.io/iroha-api/?protobuf#prepare-configuration-file

It begins to run and then I get the following error:

```
[th: 3182][error] [StorageImpl:initConnection] << Connection localhost:6379 with Redis broken
[th: 3182][info] [IROHAD] << [Init] => storage
[th: 3182][error] [MAIN] << Failed to initialize storage
```

I'm wondering if this is coming from an initial problem when I run `./run-iroha-dev.sh ` I get this error:
```
adduser: Only root may add a user or group to the system.
chown: changing ownership of '/tmp/ccache': Operation not permitted
```

or is it that the port in the config file doesn't represent the port that my instance is running locally?

**Comment by Hatchi-San** [comment]
try sudo

**Comment by jjacquet** [comment]
once I'm in the iroha instance and I try to run: `irohad --config example/config.sample --genesis_block example/genesis.block --keypair_name example/node0` I get ` sudo: command not found`

**Comment by l4l** [comment]
Don't ever use sudo with irohad

May you specify the steps that you've done, like iroha's branch, container name pulled from dockerhub, building steps, etc. Anything that might be useful for reproduction

**Comment by l4l** [comment]
@jacquetring not sure that the adding a group may cause a problem at the build (though [it might be](https://github.com/moby/moby/issues/9976) a security issue)
I may guess that you don't have enough disk space, the only build may require nearly 10gb or even more. I am not able to say a lot based on your description, consider attaching building log (or some other related info)

**Comment by jacquetring** [comment]
@l4l Ok, I terminated the instance and started with an Ubuntu with 4CPUs, 16gb ram and 100gb  drive to avoid space and cpu limitations. As I was reinstalling all the dependancies I think I may have found where `sudo` was keeping me from launching properly. When I go to run `run-iroha-dev.sh` I get the following:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json?filters=%7B%22name%22%3A%7B%22iroha1000_node_1%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Iroha is mapped to host port 50051
Debugger is mapped to host port 20000

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

**Comment by l4l** [comment]
@jacquetring well, I was saying that sudo shouldn't be used for iroha launching blindly, docker obviously should use root privileges (or docker group). So either docker daemon should be started with root, or even simplier use sudo for your last usermod command

**Comment by l4l** [comment]
Topic issue was outdated as long as there is no redis usage now, moreover the docker images available at docker hub. Feel free opening a **new** issue if you still have problems with docker image building
