### ISSUE TITLE
Compile java example error

### ISSUE THREAD

**Issue by walkero** [hyperledger/iroha#1132]
Hi, I got an error when I built /opt/iroha/example/java

`cd /opt/iroha/example/java`
`./prepare.sh`
`	-- ccache enabled (/usr/bin/ccache)`
`	-- -DCMAKE_BUILD_TYPE=Debug`
`	……`
`	[ 80%] Built target shared_model_stateless_validation`
`	[ 90%] Built target bindings`
`	[ 90%] Building CXX object shared_model/bindings/CMakeFiles/irohajava.dir/bindingsJAVA_wrap.o`
`	/opt/iroha/example/java/build/shared_model/bindings/bindingsJAVA_wrap.cxx: In function 'jlong Java_irohaJNI_new_1Blob_1_1SWIG_12(JNIEnv*, jclass, jlong)':`
`	/opt/iroha/example/java/build/shared_model/bindings/bindingsJAVA_wrap.cxx:965:3: error: 'Bytes' was not declared in this scope`
`	   Bytes *arg1 = 0 ;`
`	   ^`
	
I built iroha at ubuntu docker environment：
	`git clone -b develop --depth=1 https://github.com/hyperledger/iroha`
	`sh run-iroha-dev.sh`
	`cmake -H. -Bbuild; cmake --build build -- -j$(nproc)`
	`make`
and installed  swig 4.0.0

How can I solve this problem?

Thanks

**Comment by luckychess** [comment]
Could you try to install latest stable swig (3.0.12)? Swig from master branch is a bit unstable sometimes.

**Comment by walkero** [comment]
hi luckychess,  thank you.

I tried to install swig (3.0.12), but I got same errors.

# unintall swig 4.0.0
cd /opt/iroha/swig
make uninstall

cd /opt/iroha
wget https://github.com/swig/swig/archive/rel-3.0.12.tar.gz
tar zxvf rel-3.0.12.tar.gz
cd swig-rel-3.0.12
./autogen.sh
./configure
make
make install

cd /opt/iroha/example/java
./prepare.sh
......
......
......
same errors

Thanks

**Comment by l4l** [comment]
swig should be installed on its own, try to remove every version of swig you installed before, clean the cache (all new files produced by prepare.sh) and run it once again

**Comment by walkero** [comment]
hi l4l, thank you.

I updated cmake version from 3.5.1 to 3.9.4 
in container ( hyperledger/iroha-docker-develop:v1 ).
now run:
`cd /opt/iroha/example/java`
`./prepare.sh` 
is OK.

then I run:
`gradle run`
receive errors:
`> Task :compileJava `
`/opt/iroha/example/java/TransactionExample.java:41: error: cannot find symbol`
`private static ModelCrypto crypto = new ModelCrypto();`
`                       ^`
`symbol:   class ModelCrypto`
`location: class TransactionExample`
``
`/opt/iroha/example/java/TransactionExample.java:42: error: cannot find symbol`
`private static ModelTransactionBuilder txBuilder = new ModelTransactionBuilder();`
`	                   ^`
`	  symbol:   class ModelTransactionBuilder`
`	  location: class TransactionExample`

How to solve this problem?

Thanks

**Comment by l4l** [comment]
@walkero As far as I know gradle allow extend the output via `--info`/`--debug` flags or similar. That logs might be very useful (and post it please at the gist or pastebin).
Also make sure you have fresh versions of java/gradle, that also may be the cause.
And try to run just `gradle build` before, anyway you need to launch an iroha instance before sending transactions

**Comment by walkero** [comment]
I have post debug message ( gradle --debug build > debug.txt 2>&1 )  at 
https://gist.github.com/walkero/f036f51cb376228e26351a2683bc2578

openjdk version "1.8.0_151"
Gradle 4.6

Thanks

**Comment by luckychess** [comment]
Could you please check example/java/build/shared_model/bindings folder? It should contain a bunch of .java files. If it does not could you remove example/java/build directory, then run ./prepare.sh again and put its log here?

**Comment by walkero** [comment]
@l4l thank you.

I checked example/java/build/shared_model/bindings folder，
there is no .java files:
![image](https://user-images.githubusercontent.com/5620886/38162803-858d2fde-351a-11e8-8d4c-48c01d942f5e.png)

I removed example/java/build directory, then run
`./prepare.sh`
again, now a bunch of .java files was created:
![image](https://user-images.githubusercontent.com/5620886/38162845-3ea7bdb8-351b-11e8-9825-2bf4d513620d.png)

then I run:
`gradle build`
BUILD SUCCESSFUL in 20s !

**Comment by walkero** [comment]
I run irohad at same container:
![image](https://user-images.githubusercontent.com/5620886/38162910-a45b079a-351c-11e8-9e11-d29ad4febc52.png)

and I run
![image](https://user-images.githubusercontent.com/5620886/38162918-12b9dbf8-351d-11e8-8fe8-c88233dd2cc7.png)
received 'Connection refused' error

Could you give me some advise?

thank

**Comment by walkero** [comment]
@l4l thank you very much

`gradle run` is successfully.
