### ISSUE TITLE
JavaScript library for Iroha

### ISSUE THREAD

**Issue by walkero** [hyperledger/iroha#1134]
Hello

Where can I download JavaScript library for Iroha 1.0 alpha?
It is a year ago `https://github.com/hyperledger/iroha-javascript` 

Thanks

**Comment by rishavpiku** [comment]
Hello, 

You can clone the repository primarily and then follow the steps as given (install with either npm/bower)
https://github.com/hyperledger/iroha-javascript
I hope that it works

**Comment by l4l** [comment]
#1098 is going to be merged, here is the node.js bindings. For now there no standalone (afaik) library, but not sure
ping @stinger112 @laSinteZ

**Comment by laSinteZ** [comment]
The standalone library for Node.js is being under heavy tests right now and is almost ready. We will release it publicaly when we merge #1098 
Also, we are preparing documentation for this standalone library, so you will know, how to use it, but you can already try it if you follow Readme from #1098 

[https://github.com/hyperledger/iroha-javascript](https://github.com/hyperledger/iroha-javascript) is relevant only for Iroha 0.75 and it won't work with the most recent releases, we will put a warning in a readme soon.

**Comment by l4l** [comment]
I close that issue as long as the pr was merged

**Comment by stinger112** [comment]
@rishavpiku @walkero 
We released standalone **iroha-lib** NPM package.
https://www.npmjs.com/package/iroha-lib

Library only for Mac and Linux. The code can be found [here](https://github.com/hyperledger/iroha/tree/develop/shared_model/packages/javascript).

It's in alfa stage, and we are open to your feedback. Thanks!

**Comment by walkero** [comment]
@stinger112 
 Whe I tried to install iroha-lib NPM package (# npm i iroha-lib ), 
receive error mesage：
`node-pre-gyp ERR! Tried to download(404): https://github.com/hyperledger/iroha-javascript/releases/download/0.0.5/node-v57-linux-x64-glibc.tar.gz 
`

then I goto website:
https://github.com/hyperledger/iroha-javascript/releases/tag/0.0.5
found there is no node-v57-linux-x64-glibc.tar.gz file exist,
only have a node-v59-linux-x64-glibc.tar.gz file.

thanks
