### ISSUE TITLE
Timeout bug with load without sleep

### ISSUE THREAD

**Issue by i1i1** [hyperledger/iroha#1136]
## Commit
[zfa6e655deb4270b76a8cdd26029341ab6fe56af0z](https://github.com/hyperledger/iroha/tree/fa6e655deb4270b76a8cdd26029341ab6fe56af0)

## How to reproduce
```sh
$ docker-compose up -d
$ python3 test.py # from here https://gist.github.com/i1i1/3069733eb32cdbdb4919144ad0a5b892
```
## Supposed cause
One of these:
- networking issue
- wsv deadlock
- consensus deadlock

**Comment by takemiyamakoto** [comment]
Someone should check to see if this issue still exists
