### ISSUE TITLE
Add metadata to Asset Definition

### ISSUE THREAD

**Issue by eadventurous** [hyperledger/iroha#1142]

**Comment by eadventurous** [comment]
And corresponding Instructions to manipulate it.

**Comment by Mingela** [comment]
@eadventurous expect this feature to be used in September/October

**Comment by Mingela** [comment]
Can we expand that with an opportunity to define the fields validation inside a metadata? I mean to impose 'strong types' for the structures metadata contains. So that when adding a field we could optionally define a format/mask/validation rule. That would be good for the scenario when a value gets modified.

**Comment by eadventurous** [comment]
> Can we expand that with an opportunity to define the fields validation inside a metadata? I mean to impose 'strong types' for the structures metadata contains. So that when adding a field we could optionally define a format/mask/validation rule. That would be good for the scenario when a value gets modified.

I think yes. @Mingela can you create and reference here an issue for it?

**Comment by Mingela** [comment]
> > Can we expand that with an opportunity to define the fields validation inside a metadata? I mean to impose 'strong types' for the structures metadata contains. So that when adding a field we could optionally define a format/mask/validation rule. That would be good for the scenario when a value gets modified.
> 
> I think yes. @Mingela can you create and reference here an issue for it?

https://github.com/hyperledger/iroha/issues/1371 it's there now, apologies for late reply
