### ISSUE TITLE
Prepare a tool that checks PostgreSQL and RocksDB WSVs for consistency

### ISSUE THREAD

**Issue by kamilsa** [hyperledger/iroha#1164]
To make sure state is consistent after migration from PostreSQL to RocksDB we need to have a tool that checks that:
1. All accounts have the same balance after migration
2. All accounts have the same permissions

Tool might be executed something like that:

```
wsv_checker --rocks-db <rocks db path> --postgres_path <postgres_path> --postgres-port <postgres port>

alice@iroha has different balances. Postgres: 42, RocksDB: 45
```

**Comment by kuvaldini** [comment]
## #1294
