### ISSUE TITLE
    Create Requirements for Block Explorer

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1168]
We should create a list of requirements for a block explorer. For example, searching by transaction hash, block number, block hash, etc.

**Comment by takemiyamakoto** [comment]
We should create a list of requirements for a block explorer. For example, searching by transaction hash, block number, block hash, etc.

**Comment by Mingela** [comment]
Relevant for the upcoming production phase of the project built on top of Iroha (planned for Q3 2021). Can we prioritize this a bit @takemiyamakoto ?

**Comment by takemiyamakoto** [comment]
https://wiki.hyperledger.org/display/iroha/Blockchain+Explorer
