### ISSUE TITLE
multiple peers guide

### ISSUE THREAD

**Issue by RadW2020** [hyperledger/iroha#1173]
I think this link is missing
https://github.com/hyperledger/iroha/blob/develop/docs/source/getting_started/index.rst#configuring-iroha-network

![imagen](https://user-images.githubusercontent.com/8538542/38172101-5afe7656-35a6-11e8-8209-e2fa8091ee50.png)

**Comment by muratovv** [comment]
Thank you for the issue.

Nice catch. I think missed link is the following: [link](http://iroha.readthedocs.io/en/latest/guides/deployment/#running-multiple-instances-peer-network).

We will fix it soon.

**Comment by neewy** [comment]
@RadW2020 please use this guide https://github.com/hyperledger/iroha/tree/master/deploy/ansible 🙏

**Comment by truongnmt** [comment]
@muratovv the link you provide is invalid

**Comment by laSinteZ** [comment]
Resolved in https://github.com/hyperledger/iroha/pull/1759
