### ISSUE TITLE
Resolve licensing issues discovered by Fossology scan

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/iroha#1183]
## Context

Hyperledger Iroha source files were scanned by The Linux Foundation utilizing Fossology to determine license for files contained in the following repositories:
  * https://github.com/hyperledger/iroha.git (develop branch)
  * https://github.com/hyperledger/iroha-api.git (docs branch)
  * https://github.com/hyperledger/iroha-scala.git (master branch)
  * https://github.com/hyperledger/iroha-ed25519.git (master branch)
  * https://github.com/hyperledger/iroha-dotnet.git (master branch)

From the Hyperledger Charter (https://www.hyperledger.org/about/charter) Section 13, all files that are included in Hyperledger projects should either be licensed with the Apache License, Version 2.0 for source code or Creative Commons Attribution 4.0 International License for documentation.

## Expected Behavior

All files should have license text included either directly or via a LICENSE file in the directory for files that cannot be modified to include a comment with the license text (think binary files).

## Actual Behavior

See results of scan: 
[iroha-2018-04.xlsx](https://github.com/hyperledger/iroha/files/1876860/iroha-2018-04.xlsx)

  * The most notable finding is at iroha/docs/source/conf.py. This file inaccurately describes Iroha's license as "CC-BY-NC-3.0". In addition to being the wrong license, this is a noncommercial-use-only license. If this file hasn't been modified or removed, it should be promptly changed by its author to list Iroha's license as Apache-2.0.
  * There are 2 files (sha3.c, in two directories) with a notice saying that they are partially public domain, but partially based on code from http://keccak.noekeon.org/. I haven't been able to find any details on that site about licenses for this "keccak" software. The developers will want to either confirm what license governs the "keccak" portions of this file, or else find an alternative with a specified open source license.
  * I did not see any references to CC-BY-4.0, Creative Commons Attribution 4.0. This is the Hyperledger project license for documentation files. The team will likely want to add CC-BY-4.0 notices to documentation files, in particular, the top-level README file for each repo. An example of how Fabric does this can be seen at the bottom of https://github.com/hyperledger/fabric/blob/release-1.1/README.md.
  * There are a very small number of files with non-Apache third party license (MIT, Zlib and public domain). These will likely not be particularly concerning, but will still be subject to GB approval as license exceptions.

## Possible Fix

For _ALL_ files that do not have a license included, the first step is to check with the contributor to ensure that the file can be released as Apache 2.0 or CC-BY-4.0.  If the contributor agrees, the file should be modified to include the license. You can utilize [SPDX Identifiers](https://spdx.org/) to represent the correct license.

For files with Attribution license, ideally, we would replace those with Apache 2.0 files and dependencies; otherwise, we will need to go to the Hyperledger Governing board for an exception.

For those non-modifiable files, you will need to include a LICENSE file in the directory containing the license that the files are covered by.  Here are a few examples of how this might be done:
* [OPNFV Apex](https://github.com/opnfv/apex/blob/master/LICENSE.rst) -- this is an example of explicitly calling out Apache 2.0 for source code and CC-BY-4.0 for docs.  
* [containerd](https://github.com/containerd/containerd/blob/master/README.md) -- see notice at bottom.  This also calls out the separate Apache / CC-BY-4.0 docs, and explicitly references the "docs" directory.

## Steps to Reproduce

Run the code through Fossology (contact tkuhrt at linuxfoundation dot org) to have the source re-run after the modifications.

## Existing issues

Closed issue #361 

## Your Environment

* Version used: Source code pulled from GitHub on April 3, 2018

**Comment by laSinteZ** [comment]
@tkuhrt 
Thank you for your time!
Considering listed issues:

1, 3: iroha/docs/source/conf.py will be fixed, as well as note about CC-BY-4.0, for docs in Readme after https://github.com/hyperledger/iroha/pull/1184 is merged

2: about sha3.c: it is stated that those files are in Public Domain and are based on other work. I have looked through Keccak repositories, and turns out that those files are based at https://github.com/gvanas/KeccakCodePackage which are also licensed as Public Domain, so I guess there is no issue. Please tell me if there is any.

4: We will ask for exceptions for all those files. (there are not that much of them)

We also will work on licensing all missed files soon and ask you to rerun the check again. 

Also, we will open issues and add all necessary info about licenses to other repos soon.

**Comment by tkuhrt** [comment]
@laSinteZ : Regarding the sha3.c license, we will need to include this in the list of files that will require an exception. Thanks for working through this.

**Comment by neewy** [comment]
@tkuhrt Tracy, could you please tell if this issue is stale or not? Do we need to open a ticket in HL Helpdesk for a rescan?

**Comment by l4l** [comment]
#1944 related

**Comment by tkuhrt** [comment]
@dhuseby will be running a new scan this week against the master branch. Results most likely next week.

**Comment by neewy** [comment]
Thanks!

**Comment by dhuseby** [comment]
I've got the results and will be filing new bugs in the Iroha JIRA.
