### ISSUE TITLE
Rename iroha lib and bin

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1185]
Egor Ivkov, [11.06.21 11:32]
Ok, so I guess the points on which we agreed:
1. Call iroha library - iroha_core
2. Call iroha binary - iroha

**Comment by s8sato** [comment]
Planning to do 3 steps
* Rename library [`iroha`](https://github.com/hyperledger/iroha/tree/ade579f1e480d6988794d15a2f022cc139e15302/iroha) -> `iroha_core`
* Rename binary [`iroha_cli`](https://github.com/hyperledger/iroha/tree/ade579f1e480d6988794d15a2f022cc139e15302/iroha_cli) -> `iroha`
* Make it consistent with [`README.md`](https://github.com/hyperledger/iroha/blob/ade579f1e480d6988794d15a2f022cc139e15302/README.md)

**Comment by s8sato** [comment]
Now renaming library `iroha` to `iroha_core`.
I have [5 "iroha"s ambiguous to me](https://github.com/s8sato/iroha/blob/0771df2374fef1def57ce547a18adceefc47ab0c/iroha.code-search).
How should we handle these?

**Comment by eadventurous** [comment]
> Now renaming library `iroha` to `iroha_core`. I have [5 "iroha"s ambiguous to me](https://github.com/s8sato/iroha/blob/0771df2374fef1def57ce547a18adceefc47ab0c/iroha.code-search). How should we handle these?

- The line about Metrics can be deleted as I remember it is outdated, we don't provide these metrics now.
- In conf.py I think it can be left as it is
- I don't have file `iroha.conf` locally, maybe @i1i1 you know what it is? I think this line can be deleted form gitignore
- `docker/` lines can also be removed from gitignore I think, we build right now inside of the container.
