### ISSUE TITLE
addAssetQuantity STATEFUL_VALIDATION_FAILED

### ISSUE THREAD

**Issue by walkero** [hyperledger/iroha#1191]
Hi, I coded a java program to access irohad,
I used admin@test  
created a new "bjb" domain, 
and created a "yuan#bjb" asset with 
`precision = 2;`
then tried to addAssetQuantity for "test@test" with 
```
amount = "30070";
assetName = "yuan#bjb";
precision = 2;
```

I received an error message:
```
Hash of the transaction: c9b36b64e9150e684715bca70fb26d4d95ed358161ce31530793ee84883b0df1
Status of the transaction is: STATEFUL_VALIDATION_FAILED
Your transaction wasn't committed
```

How can I solve this problem?

Thanks

**Comment by grimadas** [comment]
Hi! 
AddAssetQuantity for only for adding to the creator account.
If your creator is `admin@test` - addAssetQuantity must first be added to `admin@test` and then transferred to ```test@test```.

**Comment by walkero** [comment]
hi,
I solved this problem,
I has a mistake, I should pass
amount = "300.70";
but not
amount = "300.70";
in my java program.

thank you.

**Comment by grimadas** [comment]
In Java, Python and JS amount right now is represented as a string.  
```transferAsset("admin@test", "test@test", "coin#test", "Hi", "200.02") ```
