### ISSUE TITLE
Closing a websocket connection cleanly

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1195]
It is currently impossible to close the websocket connection normally. It should be done according to this spec, which is the version that browsers with current support implement:

    To close the connection cleanly, a frame consisting of just a 0xFF
    byte followed by a 0x00 byte is sent from one peer to ask that the
    other peer close the connection.

For now, the js client will force connections to terminate.

**Comment by eadventurous** [comment]
I think @0x009922 originally introduced this issue so we might ask him if more details are needed.

**Comment by eadventurous** [comment]
The issue seems to be that on our server side in `handle_subscription` we don't handle `Close` message.
