### ISSUE TITLE
Query replay attack

### ISSUE THREAD

**Issue by lebdron** [hyperledger/iroha#1212]
https://github.com/hyperledger/iroha/issues/1062 was referring to transaction replay, and because each transaction is stored in the blockchain, replays are prevented by looking up the blockchain index for the same transaction.

Since queries do not modify the state, each query is not stored in the blockchain, so the previous solution is not applicable for queries.

#### Timestamp validation:
1. use the timestamp to keep it unique
2. store the timestamp from the last query from an account and require that any new query have a newer timestamp than that
3. reject queries with a timestamp older than 10 minutes with respect to local server time
4. delete the last timestamp used in a query by an account after 10 minutes

#### Nonce validation:
This assumes that attacker can capture both request and reply, so that peer reply for the query is captured. User sends his first query to a node without nonce, and receives a signed reply with nonce from the peer. The nonce should be used for further interaction with the peer, so the next query from the used will contain the nonce it has received in previous reply from the peer. Nonce is updated on each query from the user. Each peer will maintain it's nonce for the user.

#### Gossip protocol:
MST gossip module can be reused, so that peers will share data last query data for each user without consensus. Timing attack has to be performed if attacker wants to replay the same query on different nodes.
In case malicious peer will want to share his state with invalid timestamps, latest query hash can be used the same way as in transaction replay handling, but peers can also validate this hash if they want, because we store public keys of users, and users sign query hash.

**Comment by l4l** [comment]
> 2. store the timestamp from the last query from an account and require that any new query have a newer timestamp than that

There is quite bad case for multiple devices for the same account. Only half of simultaneous queries will be returned. If the clients are considered as machines, not humans that case can be quite common. Also as long as clocks are not synchronized, it can be quite a bad case for the human as well:
1. User sends transaction
2. Query the tx via device_1
3. Querying the tx via device_2 cannot be done, until the clock of the device_2 reach the first query counter (e.g may need to wait up to 10 minutes in worse case)


I think necessary security should be provided just by the transport encryption.
Also I did get the gossip protocol, what do you mean here? The query can be performed without consensus right now, how mst module can help here?

**Comment by lebdron** [comment]
>The query can be performed without consensus right now, how mst module can help here?

The idea was that first two methods don't share the timestamp information between peers, so the query can be replayed on different nodes. Gossip protocol can be used to exchange this timestamp information between peers without consensus.
