### ISSUE TITLE
Add prometheus endpoint

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1216]
## Hello! 

It is great that you've decided to contribute to Hyperledger Iroha by telling us more about the issue you've encountered!

To report the issue here, please, try to **explain** it as thoroughly as possible and **include Iroha version and logs**, if you have any, as well as your **environment information**: OS, specifications etc.

**Comment by Mingela** [comment]
Should this be related to Telemetry?

**Comment by s8sato** [comment]
This #1576 endpoint may update the format to that of Prometheus

**Comment by s8sato** [comment]
S Sato, [2021/11/09 22:46]
[In reply to Sofiane]
I see. Then in the future we can leave /status as it is and create /metrics
