### ISSUE TITLE
Parallelizing Actors for message handling

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1218]
Design traits for actors for parallel message handling (for example for querying data).

**Comment by s8sato** [comment]
Maybe useful links:
- [Message-based Parallelism with Actors](https://www.lihaoyi.com/post/MessagebasedParallelismwithActors.html)
- [Classic Routing • Akka Documentation](https://doc.akka.io/docs/akka/snapshot/routing.html?language=scala)
- [Parallel processing with Scala and Akka Actors - Aleksandar Skrbic](https://aleksandarskrbic.github.io/akka-actors/)
