### ISSUE TITLE
 incompatible types

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1227]
hi ,when i use "getAccountTransactions",
i got the response,then i use this  

`"List<Transaction>` transactions =  queryResponse.getTransactionsResponse().getTransactionsList();"

but ,the rioha give me the error 
"TestIrohaTransaction.java:272: error: incompatible types: List<iroha.protocol.BlockOuterClass.Transaction> cannot be converted to List<Transaction>
onse().getTransactionsCoList<Transaction> res =  queryResponse.getTransactionsResponse().getTransactionsList();"

how can i slove this problem,thanks

**Comment by l4l** [comment]
Give a hint for future users what was the problem please
