### ISSUE TITLE
Request block hash instead of flooding peer with it

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1236]
**Pull vs. push for data syncing.**

Makoto: This is too much message passing. Instead, peers who want to sync should request randomly from peers that they know, rather than getting messages from other peers. It needs to be a "pull" modality, not push.

Egor:
So in terms of an algorithm:

    Every N seconds peer requests latest block hashes from a small random subset of all peers.
    Peers answer to this requests with their latest bock hashes
    Peer compares its own block hash to the received ones
    ...

Something like that?

**Comment by eadventurous** [comment]
This relates to `core/block_sync.rs`

**Comment by eadventurous** [comment]
The current implementation follows [this RFC](https://wiki.hyperledger.org/display/iroha/Block+Synchronization), and the proposed change should influence the `Gossiping` part in it. There is also a comment there dated from `Aug 05, 2020` about this.

**Comment by mversic** [comment]
I would propose something like this:
P - peer initiating sync
K - random subset of peers not including P
I - peer selected from K

1. P sends empty request to K to get blochain height from K. (Optionally, P can also send it's blockchain height and K will respond only if it's height is larger. but this seems unnecessary to me)
2. K responds with the height of it's blockchain copy
3. P waits for a short while(with timeout if some responses are not returned) to collect responses from K
4. P chooses I from K which has the most new blocks(by comparing blockchain heights)
5. P sends request to I to get the blocks and provides it's latest block hash in the request
6. I responds with new blocks

**Comment by eadventurous** [comment]
There is a problem with the proposed algorithm in that we do not operate in a trusted network and therefore the peer with the biggest height can:
1. Lie about the height
2. Provide invalid blocks - we can detect it when we receive and check them

Also we should not wait for their answers over TCP as it might deadlock the peer communication (although for a limited amount of time it can still influence consensus) - we should just message and forget. Peer will repeat these requests in the defined period.

So in general we can proceed with your algorithm I think but instead choose I randomly form peers with bigger height.

**Comment by eadventurous** [comment]
@takemiyamakoto maybe you also have some comments or suggestions for the proposed algorithm by Marin?

**Comment by mversic** [comment]
if we send request to get latest blocks to all K, we can have situation that you mentioned where new peer is added to the network and all K peers respond with entire blockchain which can be over 100G.

Would it help if we were to drop requests if sync is already in progress? If yes, then it seems to me that my first draft PR can do the same with smaller number of messages exchanged

**Comment by appetrosyan** [comment]
As an extra security, we can have a set of witness peers which for `3k+1` peers would be `k+1`. A witness peer is a peer that was proactively told about the new block and can verify the height.

**Comment by mversic** [comment]
draft PR proposal was:
1. P sends request to get latest blocks to all K
2. K peers respond with latest blocks 

with this addition that requests can be dropped by P if sync is already in progress, i.e. I established communication with one of the peers from K

**Comment by mversic** [comment]
@eadventurous I didn't mean to actually await for responses, but have those responses stored in a list (priority queue?) and have another thread which will periodically check the list and choose I

**Comment by mversic** [comment]
so peers are actually gossiping about their blockchain heights, and P sends periodically sync request to one of them

**Comment by mversic** [comment]
Let me try to explain better after thinking about it:
P - peer initiating sync
I - peer selected from O
O - other peers(all peers not including P)

1st process(gossiping blockchain heights):
- we can discuss how we want to do this but the idea is that every peer should have a structure containing heights of O(HashMap<PeerId, height>) out of which it chooses I
- (if this is not ok, we can have this structure reinitiated between sync requests so that it's size is len(K) and choose I from it)

2nd process:
1. P chooses I from O which has the most new blocks(by comparing blockchain heights).
2. P sends request to I to get the blocks and provides it's latest block hash in the request
3. I responds with new blocks

**Comment by mversic** [comment]
I'm not sure how to go about gossiping blockchain heights. Pull or push mechanism? With just it's own height or heights of all peers?

**Comment by mversic** [comment]
If payload is not large(I think it isn't?) I would propose:

1st process(gossiping blockchain heights):
1 - P sends it's copy of all blockchain heights to K

**Comment by eadventurous** [comment]
@mversic I checked:
> Would it help if we were to drop requests if sync is already in progress? If yes, then it seems to me that my first draft PR can do the same with smaller number of messages exchanged

Yes, we already drop when sync is in progress
