### ISSUE TITLE
How to build the hashes to get the transactions

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1239]
```
Choose what to do:
1. New transaction (tx)
2. New query (qry)
3. New transaction status request (st)
> : 2
Choose query:
1. Get all permissions related to role (get_role_perm)
2. Get Transactions by transactions' hashes (get_tx)
3. Get information about asset (get_ast_info)
4. Get Account's Transactions (get_acc_tx)
5. Get all current roles in the system (get_roles)
6. Get Account's Signatories (get_acc_sign)
7. Get Account's Assets (get_acc_ast)
8. Get Account Information (get_acc)
0. Back (b)
> : 2
Requested tx hashes: 1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714
Query is formed. Choose what to do:
1. Send to Iroha peer (send)
2. Save as json file (save)
0. Back (b)
> : 1
Peer address (0.0.0.0): localhost
Peer port (50051): 50051
[2018-04-17 01:36:18.620055321][th:53323][info] QueryResponseHandler [Transaction]
[2018-04-17 01:36:18.620143021][th:53323][info] QueryResponseHandler -Creator Id- admin@test
--------------------
```
these is the iroha-cli response.now ,i want to use the code to get the Transactions by the hashes.I don't konw how to build the `hashes`,this is my code ,but is does not worked!

```
HashVector hashes = new HashVector();
Hash h = new Hash("1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714");
hashes.add(h);
```
please ,help me ,thanks

**Comment by l4l** [comment]
Take a look there:
https://github.com/hyperledger/iroha/blob/ed665deb84aba285e2dfc217188bba8a9cc5ce2e/test/module/shared_model/bindings/QueryTest.java#L149-L155

**Comment by big-fish0** [comment]
@l4l thanks

**Comment by walkero** [comment]
hi @big-fish0 
when you use "2. Get Transactions by transactions' hashes (get_tx)" query,
please use hash code, return by "1. New transaction (tx)" ......
I think you couldn't get transactions by any wrong hash (non-existent transaction).

**Comment by l4l** [comment]
Ah, I noticed the problem, hash should be a binary string, not a hex, e.g:
instead `"1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714"`
should be `"\x19\x95\xc1\x3f\x6f\x9d\x7e\xa9\x7c\xb7\xe3\xf4\xe3\x36\x2e\xce\xd5\xcd\xb2\xe3\xd3\xb7\x21\x86\xeb\xfd\x2b\x42\x91\xb8\x87\x14"`

**Comment by big-fish0** [comment]
@walkero the hash code was returned by the iroha-cli,and use the same hash code ,iroha-cli can response the transaction

**Comment by big-fish0** [comment]
@l4l Thanks,but I still don't know how to put the String hash into the HashVector,could you give me a demo to get the transaction by the hashes

**Comment by big-fish0** [comment]
whatever I do ,the rioha always give me this response
```
transactions_response {
}
query_hash: "=[k&\356\025j\346\254S\036\277@\361s|\002S\350d\247\030\274\362Z\252\214\255^\370#\234"
```
is there anything wrong with my code that to build the HashVetcor
```
HashVector hv = new HashVector();
Hash hh = new Hash( new String(Blob.fromHexString("1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714").hex()));
hv.add(hh);
```

**Comment by luckychess** [comment]
@big-fish0 Actually binary strings are not supposed to be exposed outside. It's an issue and it will be fixed soon (probably this week).
About your last code snippet: it doesn't compile or it just doesn't return expected result?

**Comment by big-fish0** [comment]
@luckychess It doen't return en expected result.when i use iroha-cli,and use the hexString 
`1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714`
it gives me the Transaction Object.
```
Choose what to do:
1. New transaction (tx)
2. New query (qry)
3. New transaction status request (st)
> : 2
Choose query:
1. Get all permissions related to role (get_role_perm)
2. Get Transactions by transactions' hashes (get_tx)
3. Get information about asset (get_ast_info)
4. Get Account's Transactions (get_acc_tx)
5. Get all current roles in the system (get_roles)
6. Get Account's Signatories (get_acc_sign)
7. Get Account's Assets (get_acc_ast)
8. Get Account Information (get_acc)
0. Back (b)
> : 2
Requested tx hashes: 1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714
Query is formed. Choose what to do:
1. Send to Iroha peer (send)
2. Save as json file (save)
0. Back (b)
> : 1
Peer address (0.0.0.0): localhost
Peer port (50051): 50051
[2018-04-18 02:27:24.099178336][th:7020][info] QueryResponseHandler [Transaction]
[2018-04-18 02:27:24.099293935][th:7020][info] QueryResponseHandler -Creator Id- admin@test
--------------------
```

But in my code.
```
HashVector hv = new HashVector();
Hash hh = new Hash( new String(Blob.fromHexString("1995c13f6f9d7ea97cb7e3f4e3362eced5cdb2e3d3b72186ebfd2b4291b88714").hex()));
hv.add(hh);
```
It retuens this
```
transactions_response {
}
query_hash: "=[k&\356\025j\346\254S\036\277@\361s|\002S\350d\247\030\274\362Z\252\214\255^\370#\234"
```

**Comment by luckychess** [comment]
Well, better late than never - everything should be fine now.
