### ISSUE TITLE
Support both SCALE and JSON for API

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1240]
Let the client switch between the desired encoding perhaps.

**Comment by takemiyamakoto** [comment]
something like https://github.com/paritytech/substrate-api-sidecar

**Comment by Mingela** [comment]
Would ease integration and overall maintenance of client libs I guess. Also that lowers the entry threshold for the community.

**Comment by takemiyamakoto** [comment]
But not very much, to be honest, because any reasonable dev would use the SDKs and not write their own code to manage all APIs.

**Comment by Mingela** [comment]
SCALE is rather a Rust-bound thing, it's not really convenient to map its structures to other languages sometimes, so wrapping JSON would be straightforward in case no performance overhead is introduced. In case somebody wants integrate using a technology we don't provide as a library this would be plus too. I don't insist, just a nice to have issue.
