### ISSUE TITLE
Iroha Rust Client Async

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1256]
Make the Iroha rust client async

**Comment by dmitrivenger** [comment]
async not worth the effort.

**Comment by Arjentix** [comment]
@mversic suggested to add timeout checking in WebSocket closing process to be protected from malicious peer.
I think it also will be good to add timeout checking in all response reading

**Comment by appetrosyan** [comment]
On a side note @0x009922 requested that we consider Actix web interoperability.

**Comment by 0x009922** [comment]
For Query API, I could try to contribute with the following solution:

```rust
async fn find_all_domains() -> Result<Vec<Domain>> {
    let query = iroha_client.build_query_http(FindAllDomains::new()); // Making typed query params

    let response = http_client
        .request(query.method) // mapping all http-related params to custom http client
        .insert_headers(query.headers)
        .insert_query(query.query)
        .set_path(query.url)
        .set_timeout(query.timeout)
        .send(query.body)
        .await?;

    // mapping custom http-response to a one that the query can understand
    query.handle_response(response.into())?
}
```

I think the similar solution can be used for Transactions API as well, but maybe there are some pitfalls?

Alternative solution is to expose a function from `Client` like so:

```rust
struct HttpGenRequest {
    body: Vec<u8>,
    headers: HashMap<String, String>,
    query_params: HashMap<String, String>,
    url: String,
    // etc
}

struct HttpGenResponse {
    body: Vec<u8>,
    headers: HashMap<String, String>,
    status: Status,
    // etc
}

trait HttpAdapter {
    async fn request(req: HttpGenRequest) -> HttpGenResponse {
        // ...
    }
}

impl Client {
    pub async fn request_async<R>(request: R, http: HttpAdapter) -> Result<R::Output> {
        // ...
    }
}
```

It's possible to combine both default blocking api with default http client and api that accepts a custom transport. Also, this approach may be used to make websocket handling transport-agnostic and clean as well.
