### ISSUE TITLE
[Bug] Segmentation Fault on Negative Precision for CLI

### ISSUE THREAD

**Issue by srcmake** [hyperledger/iroha#1259]
OS: Ubuntu 16.04
Iroha Version: Develop branch.

![iroha](https://user-images.githubusercontent.com/34385198/39100388-b0603960-4657-11e8-9030-c93746776f96.png)

Steps to Reproduce: 
(I was following the procedure from the Getting Started guide [here](http://iroha.readthedocs.io/en/latest/getting_started/).)
0. Set up the Docker Network as specified in the tutorial. 
1. Open up a new terminal and login to the test domain using the CLI.
2. "Create a new transaction"
3. "Add Asset Quantity"
4. Choose an Account ID, Asset ID, and Amount. (See picture above for example values.)
5. Enter a negative precision amount.
6. Enter peer address and port. 

Result:
Segmentation fault (core dumped)
The CLI user is forced out. 

Expected Result:
The error (a negative precision) could be handled gracefully and simply say "Wrong format for precision" and take the user back to choosing an action to perform, similar to how adding a negative amount works:

![iroha2](https://user-images.githubusercontent.com/34385198/39100481-42dffec8-4659-11e8-8a5a-42e4e7277976.png)

Notes:
Maybe this bug affects all transactions that use "precision" and not just "16. Add Asset Quantity".

**Comment by l4l** [comment]
Indeed the cli error handling is very poor now, @srcmake 
You are very welcome to contribute to source code, I guess here is the line to be changed:
https://github.com/hyperledger/iroha/blob/61969d20d1e8d71c60f4417fe271c30cf2d6dce4/iroha-cli/interactive/impl/interactive_transaction_cli.cpp#L334
Take a look at [that page](https://guides.github.com/activities/forking/), that may help you with the pull request creation, consider forking from develop
Feel free to fix other issues as well and don't hesitate to ask for a help, if you need some

**Comment by luckychess** [comment]
CLI doesn't ask for precision anymore.
