### ISSUE TITLE
How to get all the permissions

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1266]
Now I want to check the  `SubtractAssetQuantity `function,but in all roles don't have the permission to do this .Where can i get the permission name.

**Comment by grimadas** [comment]
Right now we don't have the full list on the readthedocs. 
You can find all permissions here https://github.com/hyperledger/iroha/blob/develop/schema/primitive.proto
In your case the permission name is `can_subtract_asset_qty`

**Comment by big-fish0** [comment]
@grimadas  Thanks,If i want to create a new role,  I use `can_append_role` or `0`
```
 can_append_role = 0;
  can_create_role = 1;
  can_detach_role = 2;
  can_add_asset_qty = 3;
  can_subtract_asset_qty = 4;
  can_add_peer = 5;
  can_add_signatory = 6;
  can_remove_signatory = 7;
  can_set_quorum = 8;
  can_create_account = 9;
  can_set_detail = 10;
  can_create_asset = 11
```;

**Comment by l4l** [comment]
Seems resolved

**Comment by big-fish0** [comment]
@grimadas thanks very much!
