### ISSUE TITLE
Setup script to generate load for longevity stand

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1268]
We need a minimal script that would send transactions periodically to longevity stand and check that longevity stand has applied these changes. This is essential for Preview Release 1.

**Comment by eadventurous** [comment]
The script is ready but needs to be checked.

**Comment by eadventurous** [comment]
Script: https://github.com/soramitsu/iroha2-longevity-load-rs

Currently being integrated into longevity stand env.
