### ISSUE TITLE
Document Iroha metrics

### ISSUE THREAD

**Issue by kamilsa** [hyperledger/iroha#1280]
At the moment the only way to get list of metrics is to request them from the prometheus port and read text response containing help comments like that:

```
> curl http://127.0.0.1:5551/metrics
# HELP blocks_height Total number of blocks in chain
# TYPE blocks_height gauge
blocks_height 135543
# HELP peers_number Total number peers to send transactions and request proposals
# TYPE peers_number gauge
peers_number 7
# HELP number_of_domains Total number of domains in WSV
# TYPE number_of_domains gauge
number_of_domains 14
# HELP total_number_of_transactions Total number of transactions in blockchain
# TYPE total_number_of_transactions gauge
total_number_of_transactions 216499
# HELP number_of_signatures_in_last_block Number of signatures in last block
# TYPE number_of_signatures_in_last_block gauge
number_of_signatures_in_last_block 5
```

It would be convenient to add and maintaing list of all metrics in iroha readthedocs' documentation

**Comment by appetrosyan** [comment]
This applies to Iroha 2 as well.

**Comment by outoftardis** [comment]
@appetrosyan question about where to put this info

I found something similar in [API spec](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md#metrics). Should the info there be updated? Though I believe the information there is more up to date than here but I might be wrong.
Or do you want me to create a separate file with this info [as was done for Iroha 1](https://github.com/hyperledger/iroha/blob/main/docs/source/maintenance/metrics.rst#metrics) and refer to it from the API specifications?
