### ISSUE TITLE
Boost library not found Macos

### ISSUE THREAD

**Issue by sjashwin** [hyperledger/iroha#1304]
Running MacOs, not able to find the boost library.

**Comment by laSinteZ** [comment]
@sjashwin could you please explain? If you are planning to build Iroha, you need to install boost library (for example with homebrew) as stated in docs:
http://iroha.readthedocs.io/en/latest/guides/build.html#macos

**Comment by sjashwin** [comment]
Im looking to contribute to the project. Iroha runs fine. When I make changes to the code and compile it again I get a Fatal error 'boost/filesystem.hpp' file not found.

<img width="626" alt="screen shot 2018-05-06 at 10 03 21 am" src="https://user-images.githubusercontent.com/7351156/39674681-0ef981ee-5115-11e8-8a02-a756e2bce9da.png">


I've searched for work arounds. But couldn't find any.

**Comment by laSinteZ** [comment]
Please make sure that you have all the required dependencies installed or use `run-iroha-dev.sh` script to start a Docker environment with all dependencies. Also, please specify your version of Cmake and Boost library, if you have them installed.

**Comment by sjashwin** [comment]
Boost version is 1.67.0 and cmake version is 3.10.3

**Comment by laSinteZ** [comment]
@sjashwin could you also specify which version of Iroha you are building (master/develop branch) and send us all output of the build phase?

**Comment by lebdron** [comment]
@sjashwin Could you specify how did you install boost in the system, and how you run configure step before build?
You have found bugs in our build scripts, and it would be great if you fix them. We had the idea for such kind of bugs, but did not introduce a CI test for it yet.
The idea is that compiler should know about include paths for `.cpp` files.
Problem with `parser.cpp`:
