### ISSUE TITLE
Builder Design Prototype

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1306]
# Builder Design Prototype

Implementation of new builder can be found in this [branch](https://github.com/hyperledger/iroha/tree/feature/builders)

This document describes new builders design. Below you can read design goals and how to build your own builders.

## Design Goals

Main issues when designing builders are various conditions under which objects must be constructed. You might want to move or copy an object, throw an exception or return empty optional in case of failure etc. All of this created a lot of different solution to the same problems and resulted in a lot of builders, each one with slightly different design philosophy. This prototype aims to be the basis, under which structured and clear library of builders for model objects can be created.

When doing design we wanted to achieve following goals:

1. Copy or Move semantics specification.
2. Ability to specify build strategy.
3. Provide a way to construct model objects directly from transport objects.
4. Check that all necessary fields were set at compile-time.
5. Avoid code repetition in builders as much as possible.

Below you will find how to create new builders and use them.

## Writing Builders

To showcase how to write a builder for a model object, I will show the process of creating transaction builder, which has two setters - for creator account id and created time. This builder returns **shared_model::interface::Transaction** object.

### Step 1: Transport Builder

**shared_model::interface::Transaction** is an abstract class and thus cannot be constructed directly. We need to create a concrete implementation of a Transaction. This is the purpose of the _Transport Builder_ - it constructs concrete implementations of the shared model objects. In our case this will be 
ProtoTransactionBuilder. Any Transport Builder builder must implicitly follow following requirements in order to work with our builders for abstract objects:

1. It must accept as a template parameter SetterPolicy enum - this allows specifying what to do on each set - copy or move.
2. Must have static member SetterPolicy which is equal to template parameter.
3. Must have _using_ for an inner object type, for example ProtoTransactionBuilder has an inner object **shared_model::protocol::Transaction**
4. Must have build method which accepts no parameters and returns a concrete implementation of shared_model::interface::* type.
4. Must provide setter for each desired member.
5. Must provide _fromImplementation_ member which accepts inner object type parameter and copies it into an inner object.

Below is an example of ProtoTransactionBuilder implementation:
```C++
template <SetterPolicy SetterPolicy = SetterPolicy::Copy>
class ProtoTransactionBuilder {
 public:

  using ImplType = iroha::protocol::Transaction;

  auto build() & {
    return shared_model::proto::Transaction(transaction_);
  }

  auto build() && {
    return shared_model::proto::Transaction(std::move(transaction_));
  }

  auto creatorAccountId(const shared_model::interface::types::AccountIdType& id) {
    // makeBuilder is convinience function which copies or moves builder
    // depending on the SetterPolicy
    ProtoTransactionBuilder b = makeBuilder(*this); 
    b.transaction_.mutable_payload()->set_creator_account_id(id);
    return b;
  }

  auto createdTime(shared_model::interface::types::TimestampType created_time) {
    ProtoTransactionBuilder b = makeBuilder(*this);
    b.transaction_.mutable_payload()->set_created_time(created_time);
    return b;
  }

  auto fromImplementation(const iroha::protocol::Transaction &transaction) {
    ProtoTransactionBuilder b = makeBuilder(*this);
    b.transaction_ = transaction;
    return b;
  }

  static constexpr enum SetterPolicy kSetterPolicy = SetterPolicy;
 private:
  iroha::protocol::Transaction transaction_;
};
```

### Step 2: Builder for Abstract Object

Builder for an abstract object uses transport builder (described above), to construct implementation of an abstract object and put it into some polymorphic container (e. g. unique_ptr).
This builder has broader set of requirements:

1. Template arguments are:
    * BackendBuilder: Transport builder to be used
    * BuildPolicy: a functional object which will be executed during the build
    * S - integer used to verify if the builder has setted all the necessary fields. Do not specify it if you want all required fields to be checked.
2. Must inherit from BasicBuilder and forward *itself* and all its template parameters to BasicBuilder
3. Must **explicitly** inherit BasicBuilder's constructors
4. Must have enum required fields - specify names of the fields, which are required for an object and add TOTAL at the end.
5. Must provide _using_ for NextBuilder template alias which accepts integer and returns the same type, but with S set to template integer parameter.
6. Each setter must use transform function enum field template parameter. So creatorAccountId setter must call transform<CreatorAccountId>

An example of transaction builder implementation:
```C++
template <typename BackendBuilder,
          typename BuildPolicy,
          int S = 0>
class TransactionBuilder
    : public BasicBuilder<
          TransactionBuilder<BackendBuilder, BuildPolicy, S>,
          BackendBuilder,
          BuildPolicy,
          S> {
 public:
  using Base = BasicBuilder<
      TransactionBuilder<BackendBuilder, BuildPolicy, S>,
      BackendBuilder,
      BuildPolicy,
      S>;

  using Base::Base;

  enum RequiredFields { CreatedTime, CreatorAccountId, TOTAL };

  auto creatorAccountId(
      const shared_model::interface::types::AccountIdType &id) {
    return transform<CreatorAccountId>(*this, [this, &id](auto &b) {
      b = this->backend_builder_.creatorAccountId(id);
    });
  }

  auto createdTime(shared_model::interface::types::TimestampType created_time) {
    return transform<CreatedTime>(*this, [this, &created_time](auto &b) {
      b = this->backend_builder_.createdTime(created_time);
    });
  }

  template <int s>
  using NextBuilder = TransactionBuilder<BackendBuilder,
                                         BuildPolicy,
                                         s>;
};
```

### Step 3: Instantiate Builder

Now that we have both builder written we need to instantiate our transaction builder. Firstly define functional object for BuildPolicy:
```C++
template <typename T>
class DefaultPolicy {
 public:
  std::unique_ptr<shared_model::interface::Transaction> operator()(
      T &&transaction) const {
    return std::make_unique<T>(transaction.getTransport());
  }
};
```

Now instantiate our builder:

```C++
TransactionBuilder<ProtoTransactionBuilder<SetterPolicy::Move>,
                     DefaultPolicy<shared_model::proto::Transaction>,
                     SetterPolicy::Move>
```

This builder creates **unique_ptr<shared_model::interface::Transaction>** contaiining **shared_model::proto::Transaction**, each setter moves builder state.

We can use this builders simply as follows:

```C++
auto tx = builder.creatorAccountId("Peter").createdTime(1337).build();
```

**Comment by LiraLemur** [comment]
PR closed by the reporter. Builders are not needed mostly at this point.
