### ISSUE TITLE
refactor: make configuration precedence env -> file

### ISSUE THREAD

**Issue by petermetz** [hyperledger/iroha#1314]
Iroha version I'm observing this in: 1.20

Right now in the stock container the Postgres connection details are retrieved from the config.docker file with higher precedence than the environment variables. In my opinion this should be changed so that if in the environment variables it says `IROHA_POSTGRES_HOST=my-postgres.example.com` then that should override the value in the config file under the `pg_opt` property.

The current precedence order leads to the issue that the docker container has the pg host/port hard-coded in the image itself at build time which is not a problem as long as you have the ability to make "some-postgres" as a resolvable hostname on the network of your container, but this is troublesome if you are not using a dedicated docker network. (which is my case - I'm just binding the Postgres container to randomized host ports and also do not want to have to create a docker network just for this because it causes other problems that are specific to my use-case which is automated testing related). 

cc: @hxlaf @baziorek

**Comment by kuvaldini** [comment]
Sounds healthy. You describe right behavior. But our workgroup is busy with more important things. So if you could  know C++ PR is welcome. I believe it is not a big dial to read env var and overrite options from config file.

**Comment by petermetz** [comment]
@kuvaldini Got it, thank you for the response! I submitted the PR (see above). Special thanks to @baziorek who helped me debug a problem with the pull request!
