### ISSUE TITLE
Review And Update Docs

### ISSUE THREAD

**Issue by LiraLemur** [hyperledger/iroha#1321]
Check the documentation, add more about:
- [x] Building in Docker (instructions on new builder);
- [ ] Dockerhub docs update;
- [ ] Running different docker images instead of building (Burrow, Ursa etc);
- [x] Review other docs. 
- [ ] Add info about RDB?

**Comment by baziorek** [comment]
@LiraLemur I wanted to ask how Docker images are being created for Dockerhub, and now I don't have to ask, because it would be in documentation. Great!

**Comment by appetrosyan** [comment]
Iroha v1 is being deprecated
