### ISSUE TITLE
RFC for metrics list

### ISSUE THREAD

**Issue by eadventurous** [hyperledger/iroha#1331]
We should discuss which metrics need to be collected

**Comment by Mingela** [comment]
Relevant for the 'blockchain as a service' project.
We may consider both 'service' metrics like avg commitment time, current tps, avg block size etc and 'business metrics' such as ISI ranking, token holders ranking, users ranking (by transaction volume). Though those business ones rather consider realtime analytics.

**Comment by eadventurous** [comment]
Bulat, [10.06.21 15:56]
the list of metrics which can be usefull:
total number of blocks
total number of domains
total number of users per domain
total number of users
total number of transactions
number of successful(rejected) transactions
total number of queries (balance, etc)
number of successful(rejected) queries
average time of transactions (histogram)
average time of queries (histogram)
total amount of tokens
average amount of tokens in transactions (histogram)

Egor Ivkov, [10.06.21 16:00]
[In reply to Bulat]
Ok, this seems like the data that we might publish on our network telemetry server

Bulat, [10.06.21 16:10]
[In reply to Egor Ivkov]
yes, common metrics (especially business) is better to expose in separate server e.g telemetry, but exposing metrics in node is still useful for example: libp2p metrics, cpu time per task

Egor Ivkov, [10.06.21 16:13]
[In reply to Bulat]
Yes, I think we might expose some node administration specific metrics on the node itself. We don't have a libp2p layer, so what networking metrics would you advice that they have?

Bulat, [10.06.21 16:19]
[In reply to Egor Ivkov]
The first which came to mind:
total number of connected peers
number of requests
requests duration (histogram)
total number of active connection (ws, http)

**Comment by eadventurous** [comment]
Transferred these comments from telegram
