### ISSUE TITLE
Is there some description for the permissions

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1341]
Now i want to create some new roles with permissions，but i don't know the correct means to the permissions.

**Comment by l4l** [comment]
No, these docs are missing. I think it will be fixed soon
You may take a look at the permission list in the [sources](https://github.com/hyperledger/iroha/blob/develop/shared_model/validators/permissions.hpp)

**Comment by l4l** [comment]
That work proposed in #1395, so I'm closing that issue

**Comment by igor-egorov** [comment]
@big-fish0, permissions description is now available here - https://iroha.readthedocs.io/en/latest/maintenance/permissions.html
