### ISSUE TITLE
Docker image: iroha:develop libaddress_sorting.so error

### ISSUE THREAD

**Issue by walkero** [hyperledger/iroha#1347]
There is an issue when I pulled hyperledger/iroha:develop docker image, and launch irohad

```
docker run -it --name iroha \
-p 50051:50051 \
-v /home/wh/iroha/example:/opt/iroha_data \
-v blockstore:/tmp/block_store \
--network=iroha-network \
--entrypoint=/bin/bash \
hyperledger/iroha:develop

root@d34d70499473:/opt/iroha_data# irohad --config config.docker --genesis_block genesis.block --keypair_name node0
irohad: error while loading shared libraries: libaddress_sorting.so: cannot open shared object file: No such file or directory
```

**Comment by laSinteZ** [comment]
@walkero thank you for your report! We are investigating this issue and will fix it soon :)

**Comment by laSinteZ** [comment]
@walkero since #1355 is merged, everything works fine now (I've checked it as well). I am closing this, but if you still have – please, reopen it. Don't forget to `docker pull hyperledger/iroha:develop` to have the newest image.
