### ISSUE TITLE
iroha-cli boost lib exception

### ISSUE THREAD

**Issue by 5HARK** [hyperledger/iroha#1362]
After install [ansible](http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu) inside [iroha docker container](https://store.docker.com/community/images/hyperledger/iroha), iroha-cli can't generate genesis_block from peers.list.

on pure docker image(hyperledger/iroha:develop) it works well without any problems.

custom Dockerfile
```
FROM hyperledger/iroha:develop

# install ansible
RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update && apt-get install -y ansible
WORKDIR /usr/src/app
```

peers.list
```
abcdabcd7438.cafe24.com:10001
abcdabcd7438.cafe24.com:10002
abcdabcd7438.cafe24.com:10003
abcdabcd7438.cafe24.com:10004
abcdabcd7438.cafe24.com:10005
abcdabcd7438.cafe24.com:10006
abcdabcd7438.cafe24.com:10007
abcdabcd7438.cafe24.com:10008
abcdabcd8915.cafe24.com:10001
abcdabcd8915.cafe24.com:10002
abcdabcd8915.cafe24.com:10003
abcdabcd8915.cafe24.com:10004
```

![screenshot_20180521_182949](https://user-images.githubusercontent.com/12772303/40303477-daba0ce4-5d2d-11e8-9fa8-7a9f885862aa.png)

**Comment by 5HARK** [comment]
it same in my host system.

![screenshot_20180521_203733](https://user-images.githubusercontent.com/12772303/40305797-0a534606-5d37-11e8-8edf-3b3db90d3d02.png)

**Comment by efemai** [comment]
I am experiencing the same error detailed here above. I tried on both Ubuntu 16.04 and Ubuntu 18.04.
```
$ ./iroha-cli -genesis_block -peers_address peer.list 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::out_of_range> >'
  what():  bimap<>: invalid key
Aborted (core dumped)
```

**Comment by lebdron** [comment]
Fixed in https://github.com/hyperledger/iroha/pull/1351 , please report if any new issues appear.
