### ISSUE TITLE
Build stuck at 32 percent on mac. make fails right after. Following documentation

### ISSUE THREAD

**Issue by rohankk2** [hyperledger/iroha#1380]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
test/module/shared_model/backend_proto/CMakeFiles/shared_proto_util_test.dir/build.make:62: recipe for target 'test/module/shared_model/backend_proto/CMakeFiles/shared_proto_util_test.dir/shared_proto_util_test.o' failed
make[2]: *** [test/module/shared_model/backend_proto/CMakeFiles/shared_proto_util_test.dir/shared_proto_util_test.o] Error 4
CMakeFiles/Makefile2:7936: recipe for target 'test/module/shared_model/backend_proto/CMakeFiles/shared_proto_util_test.dir/all' failed
make[1]: *** [test/module/shared_model/backend_proto/CMakeFiles/shared_proto_util_test.dir/all] Error 2

No idea how to fix this.

**Comment by muratovv** [comment]
Hello, Rohan.

Generally, the problem occurs when C++ doesn't have enough of RAM. If you use Docker for building Iroha, please, increase RAM capacity for Docker container. If this trick wouldn't help, decrease the number of threads in Cmake building process. For example:
```
cmake -H. -Bbuild && cmake --build build -- -j2
``` 
where `2` is a number of threads.

**Comment by takemiyamakoto** [comment]
What memory amount is recommended?

**Comment by l4l** [comment]
It takes around 10GB with 8 threads for me. It will probably will take up to 2GB for one thread
