### ISSUE TITLE
Fix iroha_client_cli::events

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#1395]
# Fix iroha_client_cli::events

[cause code]: https://github.com/hyperledger/iroha/blob/c33c4b3ba80a132b4667b0b7312c41061533894e/iroha_client_cli/src/main.rs#L168-L169

- [Fix iroha_client_cli::events](#fix-iroha_client_clievents)
  - [Expected Behavior](#expected-behavior)
  - [Actual Behavior](#actual-behavior)
  - [Steps to Reproduce](#steps-to-reproduce)
  - [Possible Causes](#possible-causes)
  - [Possible Solution](#possible-solution)

## Actual Behavior
`Pipeline` and `Data` are reversed

![image.png](https://images.zenhubusercontent.com/61319c9f44ff4a6dab86ed92/fd868a2e-d422-48d3-862a-8203807610d3)

## Possible Causes
[here][cause code]

## Possible Solution
Just exchange them

**Comment by satu-n** [comment]
Now solved

![image](https://user-images.githubusercontent.com/49983831/131965102-05bf7482-589e-4d55-8812-f8b24945b56d.png)
