### ISSUE TITLE
why CreateAsset api don't have data parameter.

### ISSUE THREAD

**Issue by bohrqiu** [hyperledger/iroha#1399]
asset's entity model has `data JSON` field, but how can i set data? thx.

**Comment by laSinteZ** [comment]
@bohrqiu I guess you are referring to https://hyperledger.github.io/iroha-api/#entity-relationship-model However, this schema is a little bit dated. Currently there is no "Data" field in the Asset.

**Comment by bohrqiu** [comment]
and datebase has the colomn too 😄
![image](https://user-images.githubusercontent.com/1333657/40777423-64fbd78c-6500-11e8-8c92-66a5a888650e.png)

I am confused why no  "Data" to description asset?

**Comment by laSinteZ** [comment]
@bohrqiu I've investigated a little and you are right, there is a column in database.

Unfortunately, currently setter of this field is not implemented in Shared Model, so there is no way to set this column right now. (Unlike data in account field, for which there are "setAccountDetail"). 

I guess soon we will implement it. However, that this could be a good "good-first-issue" since code will be like setAccountDetail.

**Comment by bohrqiu** [comment]
Thank you for your explanation.

**Comment by laSinteZ** [comment]
@bohrqiu could you tell us more, why do you want this field to be active? Maybe your usecase will motivate to implement it faster :)

**Comment by bohrqiu** [comment]
@laSinteZ We want to write the description of the asset to the blockchain，and any peer can read the detail description information form blockchain.

**Comment by bohrqiu** [comment]
We want to write the description of the asset to the blockchain，and any peer can read the detail description information form blockchain without external system

**Comment by bohrqiu** [comment]
@laSinteZ We want to write the description of the asset to the blockchain，and any peer can read the detail description information form blockchain without external system

**Comment by laSinteZ** [comment]
@DblBee I will be frank with you: this feature is in backlog, but it is not the top priority for us (compared to, for example, new JS library we are working on, stability of system, performance). However, if you are willing to help us by implementing this feature – we can help you in this task and provide explanations/details.

**Comment by psaingtong** [comment]
+1.In Hospital management,Hospital has a daily activity (OPD=visit no,..etc).It should be use asset keep it for search patient (account).

**Comment by pulmark** [comment]
+1. Flea markets. Market has goods (assets) where registered customer (account) can sell or buy. It would be necessary to have a description of asset (manufacturer, model, size, color etc...). Complex asset, asset with properties or such.

**Comment by neewy** [comment]
We have this in our roadmap for Q2, right after the final 1.0 release
