### ISSUE TITLE
Support minting of assets with AssetValueType::BigQuantity

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha#1405]
Precondition:
Registered asset with type AssetValueType::BigQuantity

Expected:
When instruction to mint sent it is committed and asset minted

Current:
When instruction to mint sent then peer reject transaction and  error can be found in logs
```
Transaction 6b6066a7729de5c36cfb3956bbf46f3f6b3a439d7cf4623db424544fcfbd8411 was rejected by reason: `Failed: `Failed to assert type. Caused by: Failed to assert type of asset. Caused by: Asset type error: expected asset of type Quantity, but got BigQuantity` during execution of instruction: jp.co.soramitsu.iroha2.generated.datamodel.isi.Instruction.Mint
```

**Comment by takemiyamakoto** [comment]
u128 should be big enough?

**Comment by rkharisov** [comment]
For orillion use case it is certainly enough

**Comment by appetrosyan** [comment]
Was fixed in PR set mintability of asset at asset creation time.
