### ISSUE TITLE
CWE-807, CWE-20

### ISSUE THREAD

**Issue by teamwoot** [hyperledger/iroha#1409]
Hi Team, 

https://github.com/hyperledger/iroha/blob/master/test/framework/config_helper.cpp#L27

i.e

`auto pg_user = std::getenv("IROHA_POSTGRES_USER");`

Environment variables are untrustable input if they can be set by an attacker. They can have any content and length, and the same variable can be set more than once such as (CWE-807, CWE-20). Check environment variables  carefully before using them.

Request team to please have a look.

Thank you
Team w00t

**Comment by l4l** [comment]
These env variables are only used during irohad launching and only for some of the tests. I do not see any issue here

**Comment by l4l** [comment]
Since there's no additional comment I'm closing it
