### ISSUE TITLE
connection_with_grpc requires arguments, but test.sh runs tests without args

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#141]
Look at this build: https://circleci.com/gh/hyperledger/iroha/1083 at test phase: 
```
$ docker run -p 1204:1204 hyperledger/iroha-docker /test.sh
```
Tests exits with code 0 (success), but some tests failed.

It is because of presence of `exit 0` in `tests.sh`. I fixed this [in this commit](https://github.com/hyperledger/iroha/commit/959a14f1f049d05831f0ed0f67ef1920267cfae8#diff-1b531c5e405e0bc95890d52cf2f2f5b5L8) but tests started to fail even with SUCCESS code on each test.

Look at [this line](https://github.com/hyperledger/iroha/blob/master/test/connection/connection_with_grpc_test.cpp#L44). 
Test `connection_with_grpc` requires 2 arguments, otherwise it returns exit code 1.

[test.sh](https://github.com/hyperledger/iroha/blob/master/test.sh#L5) runs each test without arguments, this is why I temporarily commented test `connection_with_grpc` in this commit: 8823eba5a334c7650400c28a724323b32e621fa4.

Please, add default arguments to `connection_with_grpc` test or exclude it from `test_bin` folder.

**Comment by MizukiSonoko** [comment]
Sorry for my late reply.
convertor_test, and connection_with_grpc is old to convert to Flatbuffer.
Thank you for removing test.

**Comment by Warchant** [comment]
Solved by https://github.com/hyperledger/iroha/pull/144
