### ISSUE TITLE
error while running java sample

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/iroha#1420]
Log trace while running prepare.sh. Is there any maven project sample to test it out. Also please provide the path to download the jar directly, It will be really helpful for created a from scratch.

pradeep@pradeep-VirtualBox:~/iroha/example/java$ ./prepare.sh 
-- -DCMAKE_BUILD_TYPE=Debug
-- -DTESTING=ON
-- -DBENCHMARKING=OFF
-- -DFUZZING=OFF
-- -DCOVERAGE=OFF
-- -DPACKAGE_ZIP=OFF
-- -DPACKAGE_TGZ=OFF
-- -DPACKAGE_RPM=OFF
-- -DPACKAGE_DEB=OFF
-- -DENABLE_LIBS_PACKAGING=ON
-- -DSWIG_PYTHON=OFF
-- -DSWIG_JAVA=ON
-- -DSUPPORT_PYTHON2=OFF
-- -DSWIG_CSHARP=OFF
-- -DSWIG_NODE=OFF
-- Could NOT find gtest (missing:  gtest_INCLUDE_DIR gtest_LIBRARY gtest_MAIN_LIBRARY gmock_INCLUDE_DIR gmock_LIBRARY gmock_MAIN_LIBRARY) 
-- Could NOT find spdlog (missing:  spdlog_INCLUDE_DIR) 
-- Could NOT find protobuf (missing:  protobuf_INCLUDE_DIR protobuf_LIBRARY protoc_EXECUTABLE) 
-- Could NOT find grpc (missing:  grpc_LIBRARY grpc_INCLUDE_DIR gpr_LIBRARY grpc_CPP_PLUGIN) 
-- Could NOT find rapidjson (missing:  rapidjson_INCLUDE_DIR) 
-- Could NOT find pq (missing:  pq_INCLUDE_DIR postgres_INCLUDE_DIR pq_LIBRARY pg_config_EXECUTABLE) 
-- Could NOT find pqxx (missing:  pqxx_INCLUDE_DIR pqxx_LIBRARY) 
-- Could NOT find gflags (missing:  gflags_INCLUDE_DIR gflags_LIBRARY) 
-- Could NOT find rxcpp (missing:  rxcpp_INCLUDE_DIR) 
-- Could NOT find tbb (missing:  tbb_INCLUDE_DIR tbb_LIBRARY) 
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/dependencies.cmake:70 (find_package)
  CMakeLists.txt:113 (include)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/dependencies.cmake:70 (find_package)
  CMakeLists.txt:113 (include)

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/dependencies.cmake:70 (find_package)
  CMakeLists.txt:113 (include)

-- Could NOT find ed25519 (missing:  ed25519_INCLUDE_DIR ed25519_LIBRARY) 
-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE) 
-- Installed package SWIG not found. It will be pulled to /home/pradeep/iroha/external/src/swig_swig/share/swig/3.0.12 at compile time.
CMake Error at shared_model/bindings/CMakeLists.txt:49 (swig_add_library):
  Unknown CMake command "swig_add_library".
Call Stack (most recent call first):
  shared_model/bindings/CMakeLists.txt:91 (myswig_add_library)

-- Configuring incomplete, errors occurred!
See also "/home/pradeep/iroha/example/java/build/CMakeFiles/CMakeOutput.log".
See also "/home/pradeep/iroha/example/java/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'irohajava'.  Stop.

**Comment by laSinteZ** [comment]
@pradeeppadmarajaiah please install latest CMAKE (3.8 at least, 3.11 idealy). Also, AFAIK you need to have boost 1.65 installed.

**Comment by l4l** [comment]
Seems resolved
