### ISSUE TITLE
Iroha Execution Model

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1423]
# Iroha Execution Model

## Table of Contents

1. [Introduction](#intro)
2. [On Thread Management](#thread-management)
3. [MST Support](#mst)
4. [Transaction Pipeline](#tx-pipeline)
    1. [Transaction Diagram](#tx-diagram)
    2. [Detailed Description](#tx-detailed)
        * [Transaction Receiver](#tx-receiver)
        * [Transaction Collector](#tx-collector)
        * [Proposal Generator](#prop-generator)
        * [Proposal Timer](#prop-timer)
        * [Proposal Receiver](#prop-receiver)
        * [Proposal Validator](#prop-validator)
        * [Vote Timer](#vote-timer)
        * [Vote Receiver](#vote-receiver)
        * [Block Loader](#block-loader)
        * [Commit Receiver](#commit-receiver)
        * [Commit Application](#commit-application)
        * [Get Blocks](#get-blocks)
        * [GRPC Client](#grpc-client)
5. [Query Pipeline](#query-pipeline)

<a name="intro"></a>
## Introduction

This document describes threads and their interaction inside Iroha daemon. Overall configuration is presented and each thread's responsibilities are described in detail.

This is done to provide understanding in concurrency model of Iroha as well as to find any incorrect behavior in threading model.

<a name="thread-management"></a>
## On Thread Management

Iroha daemon avoids using raw threads provided by C++ standard library. Instead it relies on two distinct runtimes - grpc and rxcpp. They use threads internally to provide necessary functionality. In this document we treat these libraries as black boxes, meaning we are only stating the fact that the thread from a specific runtime is used, without going into details of where this thread came from.

The only place where a raw thread is used is AsyncGrpcClient implementation, which spawns a separate thread to listen to grpc replies.

<a name="mst"></a>
## Multisignature Transaction Support

Everything described below is done with MST support turned off.

<a name="tx-pipeline"></a>
## Transactions Pipeline

<a name="tx-diagram"></a>
### Transaction Diagram

The diagram below represents thread configuration when executing transactions on Iroha network.

![iroha-execution model-4](https://user-images.githubusercontent.com/14168731/41086289-3d1f64f8-6a42-11e8-8b8a-4a522599f25d.png)

Each block is a separate thread, and data flow is represented by arrows.

<a name="tx-detailed"></a>
### Detailed Description

<a name="tx-receiver"></a>
#### Transaction Receiver

Used components:

* Torii (tx processor)
* Peer Communication Service
* Ordering Gate

This is a grpc thread which handles transactions sent by users. Goal is to pass the transaction to the ordering service.

<a name="tx-collector"></a>
#### Transaction Collector

Used components:

* Ordering Service Transport
* Ordering Service

This grpc thread receives transactions from peers and puts them in a queue. Queue is processed by Proposal Generator

<a name="prop-generator"></a>
#### Proposal Generator

Used components:

* Ordering Service Transport
* Ordering Service

This is an rx thread which is triggered by two events: transactions added to the queue and proposal timeout. When queue is big enough or timeout event occurs, it starts proposal generation.

<a name="prop-timer"></a>
##### Proposal Timer

To prevent transactions from hanging indefinitely, special timer is started, which works in a separate thread. As soon as timer goes off, proposal is formed from all transactions currently in the queue.

<a name="prop-receiver"></a>
#### Proposal Receiver

Used components:

* Ordering Service Transport
* Ordering Gate

This thread receives proposals from ordering service and puts them in a proposal queue to be validated.

<a name="prop-validator"></a>
#### Proposal Validator

Used components:

* Ordering Gate
* Simulator
* Stateful Validator
* Yac (gate, order, network)

This thread takes proposal from the proposal queue and sends it for a validation. When proposal is validated we obtain verified proposal. Vote for this proposal is broadcasted to the other peers.

<a name="vote-timer"></a>
##### Vote Timer

To optimize vote propagation among peers, we need to wait before sending vote to the next peer in the list. This is done to allow first peer to collect necessary votes to issue a commit.

<a name="vote-receiver"></a>
#### Vote Receiver

Used components:

* Yac
* Yac Block Storage

Vote Receiver is a thread which listens for incoming votes. When enough votes were received, commit message is formed and broadcasted to all the peers.

<a name="block-loader"></a>
#### Block Loader

Used components:

* Block Loader Service
* Block Loader

This thread listens for requests to load blocks from the peer. It is called when we receive commit message and want to retrieve commited block.

<a name="commit-receiver"></a>
#### Commit Receiver

Used components:

* Yac

Commit receiver is a thread which listens for incoming commits, verifies them and passes to the pipeline to be applied.

<a name="commit-application"></a>
#### Commit Application

Used components:

* Synchronizer
* Chain Validator
* Ametsuchi

Commit is applied in a thread in which commit is obtained. If the peer creates commit, it is applied in Vote Receiver. If the peer receives commit, Commit Receiver applies it. Application of the commit begins with the retrieval of the block which is to be commited, then it is passed to the storage, which executes all transactions in the block.

<a name="get-blocks"></a>
##### Get Blocks

In a lot of cases GetTopBlocks function is called on a separate thread, it can be a different thread each time, and this is not really needed. Consider this a bug. List of components which call getTopBlocks in a separate thread:

* Simulator
* Storage
* Block Loader

<a name="grpc-client"></a>
##### GRPC Client

Only raw thread, it listens for replies from grpc calls. Each component which sends grpc calls uses this client, and thus occupies a thread. Transaction Receiver sends transactions to ordering service and owns its own client (ordering gate transport). Vote Receiver sends votes, and Proposal Validator sends commits. Both these actions are done via YacNetwork, so both threads share ownership of YacNetwork client.

<a name="query-pipeline"></a>
## Query Pipeline

Query execution in iroha is a lot simpler than transaction pipeline. When request arrives from the network it is handled by one of the grpc threads, which synchronously retrieves needed information from storage. Everything is done in a single thread.

**Comment by l4l** [comment]
> we treat these libraries as black boxes, meaning we are only stating the fact that the thread from a specific runtime is used, without going into details of where this thread came from

Actually that is not completely true. There's only one place where's the thread is used explicitly, that's [AsyncGrcpClient](https://github.com/hyperledger/iroha/blob/develop/irohad/network/impl/async_grpc_client.hpp#L62).
Moreover it is required to explicitly set the thread for rxcpp observables (e.g [here](https://github.com/hyperledger/iroha/blob/develop/irohad/main/impl/ordering_init.cpp#L34))

Comments for diagram:
- It may be also noticed that it applicable to irohad, and not for integration tests. The last one use synchronous (rx) OS
- I would consider one-way arrows for timers
- Although _gets block_ works on separate thread, in fact it's blocking. So it might be better not to put it here

Also could you open a PR for RTH page? I think it worth being published

**Comment by nickaleks** [comment]
Thank you for the feedback.

> Actually that is not completely true. There's only one place where's the thread is used explicitly, that's AsyncGrcpClient.

Yeah I overlooked that.

>Moreover it is required to explicitly set the thread for rxcpp observables

This is not completely true, we tell observable to execute on separate thread, but which thread will it be is manage by rx runtime.

> It may be also noticed that it applicable to irohad, and not for integration tests. The last one use synchronous (rx) OS

Yes, this is irohad only, tests are not covered by the diagram.

> Although gets block works on separate thread, in fact it's blocking. So it might be better not to put it here

This is diagram which represents threads, not concurrent execution. Since get blocks spawns additional thread for many cases, it is shown on the diagram.

**Comment by nickaleks** [comment]
Update: added grpc client

**Comment by nickaleks** [comment]
Added small description of query pipeline

**Comment by LiraLemur** [comment]
The reporter said it needs to be updated now. Jira created: https://jira.hyperledger.org/browse/IR-194
