### ISSUE TITLE
Integrate WASM Runtime into Iroha2

### ISSUE THREAD

**Issue by e-ivkov** [hyperledger/iroha#1425]

**Comment by eadventurous** [comment]
See https://wiki.hyperledger.org/display/iroha/Scripting+Languages+and+Runtimes+for+Iroha2+Smart+Contracts

**Comment by eadventurous** [comment]
Prototype - https://github.com/soramitsu/iroha2-wasm-prototype

**Comment by mversic** [comment]
Useful links:
https://www.w3.org/TR/wasm-core-1/#control-instructions%E2%91%A0
https://learnxinyminutes.com/docs/wasm/
https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility/
