### ISSUE TITLE
can't build android_build.sh

### ISSUE THREAD

**Issue by MikhailMe** [hyperledger/iroha#1430]
I just try build new bindings for Andorid
I run script android_build.sh
But it finished failure

I see at the logs and think that problem at line 97.
https://github.com/hyperledger/iroha/blob/0da37d4cd24833dd718b02fac143378c11f7e537/shared_model/packages/android/android-build.sh#L97

Probably problem in the iroha_ed25519, cause block block_variant.cpp cant' compiled. 

![image](https://user-images.githubusercontent.com/10109191/41100141-34585e7a-6a69-11e8-9055-7d9ac7789066.png)

**Comment by l4l** [comment]
Could you try it once again after pulling fixes from #1433?

**Comment by MikhailMe** [comment]
yeap, now a script works, thanks
i am closing issue
