### ISSUE TITLE
Remove memory leak in Iroha_ProtoSpecificQueryExecutorExecute

### ISSUE THREAD

**Issue by iceseer** [hyperledger/iroha#1431]
## Hello! 

It is great that you've decided to contribute to Hyperledger Iroha by telling us more about the issue you've encountered!

To report the issue here, please, try to **explain** it as thoroughly as possible and **include Iroha version and logs**, if you have any, as well as your **environment information**: OS, specifications etc.

**Comment by appetrosyan** [comment]
Incomplete description. Also Iroha v1 is to be deprecated soon.
