### ISSUE TITLE
Problem with quorum

### ISSUE THREAD

**Issue by MikhailMe** [hyperledger/iroha#1432]
I started android application and want send simple transaction to Iroha, but it failure on the Stateless validation.. because of quorum size

I use docker image of iroha x86_64-develop,  and develop version of android-sample repository 
android bildings from android-sample

![image](https://user-images.githubusercontent.com/10109191/41101364-9b2842d4-6a6c-11e8-8beb-85cde18c373d.png)

**Comment by l4l** [comment]
I guess the issue is fixed, since android bindings are updated now
Feel free to add smth here, if the issue is still persist
