### ISSUE TITLE
Return proper HTTP status code in case of signature verification error

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha#1436]
How to reproduce: send query  from behalf of some account with signature created with key do not associated with the account

Current behaviour:  peer responds with 500 status code

Expected behaviour: peer responds with proper status code (400 or 401)

`
12:38:33.389 [docker-java-stream-2067647305] INFO jp.co.soramitsu.iroha2.testcontainers.IrohaContainer - STDOUT: 2021-09-15T09:38:33.411855Z ERROR warp::reject: unhandled custom rejection, returning 500 response: ValidateQuery("Public key used for the signature does not correspond to the account.")
12:38:33.390 [ForkJoinPool-1-worker-3 @coroutine#39] INFO io.ktor.client.HttpClient - RESPONSE: 500 Internal Server Error
`

**Comment by s8sato** [comment]
API Specification also might have to be revised at the same time:
[Instructions](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md#:~:text=500%20Internal%20Server%20Error%20-%20Transaction%20Rejected%20(Malformed%20or%20improperly%20signed))
[Query](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md#:~:text=500%20Internal%20Server%20Error%20-%20Query%20Rejected%20(Failed%20to%20parse/execute%20or%20improperly%20signed))
These 500 ISEs are actually caused from the client side, if I'm right

**Comment by rkharisov** [comment]
That's correct. Error was caused due client signed query with wrong private key and do not related with server's logic
