### ISSUE TITLE
Change log level for events about block or transaction committing

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha#1439]
Current behaviour: when block or transaction committed the event about that logged with level `ERROR`

Expected behaviour: when block or transaction committed the event about that logged with level `TRACE`, `DEBUG` or `INFO`

`2021-09-16T07:18:18.889841Z ERROR start_genesis_round:commit_block: iroha::sumeragi: ev Pipeline(Event { entity_type: Block, status: Committed, hash: 125ef259857a80df9a98d88cf2d2f88d4d82a3ee2c41abe6532b3c4eb58e749d })`

`2021-09-16T07:28:27.246976Z ERROR start_genesis_round:commit_block: iroha::sumeragi: ev Pipeline(Event { entity_type: Transaction, status: Committed, hash: 756e24771b888d9f21b0c7802be044793cb2977eb7f30b06443d4e4bb20309fd })`

**Comment by eadventurous** [comment]
Fixed in https://github.com/hyperledger/iroha/pull/1461
