### ISSUE TITLE
membership_service

### ISSUE THREAD

**Issue by satellitex** [hyperledger/iroha#146]
Add initial peer.  modify save data method. ( 2016/02/14 20:16 )

# membership_service

## problem : どちらの peer class を使いますか？（現在どちらも使っている）
 - objects::Peer?
 - peer::Node?

## add<Peer>
1. ip と publicKey を指定して新しい peer を定義。
2. 現在稼働している他の peer からデータを正しいデータを持ってくる。(合意差分データ収集機構:後述)
3. peer を評価しTrustRateを定義。
4. peerList に 新しい peer を追加。
5. DB に新しい peer の情報を追加。

## remove<Peer>
1. 削除する ip と publicKey を定義。
2. peerList からそのpeerを削除。
3. DB を全削除

## update<Peer>
 - ip の変更
 - TrustRate の変更
 - update< 旧Peer, To< 新Peer > > execution() で実行 or
 - update< 旧peer >::execution( 新Peer ) で実行

## initial<Peer>
 - 新規ピアが最初に行う処理を記す

## question
 - peerList の中身は全ての peer が同じ順序で同じ peer を保持している？（その必要があるか？）
 - 合意差分データ収集機構とは？
 - peer_service_with_json.hpp にpeerListを保持していますが、sumeragi.jsonがなくなる予定であるならファイル名が不適切になりそうです。 
 - initial<peer> が必要では？

## 合意差分データ収集機構について
 - 最も優先度の高いピアからデータを受け取る。
 - 最も優先度の高いピアは add された node にデータをわたす

↓ English ver
## problem : Which does use peer class? ( now Iroha uses both class. )
 - objects::Peer?
 - peer::Node?

## add<Peer>
1. Define new peer from ip and publicKey ip.
2. Bring the correct data from other peers that are currently data running. ( 合意差分データ収集機構 [ recruitment cool name ] )
3. Evaluate peer that calc TrustRate.
4. Add peerList from new peer.
5. Add DB from new peer infomation.

## remove<Peer>
1. Define new peer from ip and publicKey.
2. Delete peerList to peer.
3. Delete DB.

## update<Peer>
 - Change ip.
 - Change TrustRate.
 - update< old Peer, To< new Peer > > execution()  or
 - update< old Peer >::execution( new Peer ) 

## initial<peer>
 - Write the process that the new peer first performs.

## question
 - Is peerList contents all peers holding the same peer in the same order?
 - What is "合意差分データ収集機構"？
 - peer_service_with_json.hpp has peerList. But sumeragi.json will be erase. So filename is inappropriate.
 - It need to initial<peer> method.

## About 合意差分データ収集機構( I recruitments cool name )
 1. new peer receive data from the highest priority peer.
 2. The highest priority peer send data to added peer.

**Comment by MizukiSonoko** [comment]
problem : どちらの peer class を使いますか？（現在どちらも使っている）
```
objects::Peer
```
Iroha has objects::Peer only.

And no problem thanks.

**Comment by satellitex** [comment]
sumeragi uses peer::Node.
It should replace peer::Node with objects::Peer?

**Comment by satellitex** [comment]
# peer service

### peer_service
 - addPeer
   -  specify `peer::Node`
 - removePeer  
   - specify `publicKey`
 - updatePeer
   - specify `publicKey`
   - specify `ip` and `trustScore` after updated.

## Sumeragi
 Sumeragi has `struct Context` which has validatingPeerList.

### Context has member names.
 - isSumeragi
 - maxFaulty
 - proxyTailNdx
 - panicCount
 - commitedCount
 - numValidatingPeers
 - myPublicKey
 - validatingPeers
 
### Context has method
 - update
   - This method update `validatingPeers` equal to `getPeerList` which in  PeerService has.
      and update the above member names. ( `panicCount` and `commitedCount` is another timing. )

**Comment by satellitex** [comment]
sorry, Japanese Only 
# This is memo
ピアが死亡した際に 新しいピアを自動的にチェンジする仕組み
→
削除について
合意形成後 全体で accept されたら、 reject したピアにマイナス評価を与える。（この時、rejectに理由を添える[嘘or死んでるor形成中]等 ）
全体が reject されたら、 accept したピアにマイナス評価を与える。 評価値がある一定値を下回ったらそのピアを削除するtransactionをブロードキャストする。

peer の削除の transaction が来たとき自分の持っているピアのリストを見て正誤判定をする。(?)
この流れで行くと、Remove<Peer> transaction は重複するがそれは特に構わない。

追加について
単体で iroha を起動
その後、何者かが起動したirohaの ip と publicKey を添えて 既に構成されているグループに add<Peer> 命令を送る。
合意形成をし終えたらリーダーピアが 追加するピアに対しデータを送る。
データを送り終えるまでこのピアは合意形成時にreject[理由：形成中]し続ける。

問題点として誰でもピアとして参加できてしまう。
許可するピアを予め設定しおくようにすると利便性が損なわれるが、どうしたらいいだろうか。

**Comment by MizukiSonoko** [comment]
Ok thanks!
I think transaction issuer is restricted, so no problem.
Andissuer should be restricted by permission.
What is your opinion?

**Comment by luckychess** [comment]
Hi all! I recently started to work on this task and I have several questions:

1. Am I correct that sumeragi.json is going to be removed? If yes, should we save peers inside Ametsuchi or store them only in memory and do a peer discovery procedure every time Iroha starts?
2. Should Ametsuchi be ready to store peers same time as assets and accounts? Are all of them a part of world state repository?
3. Commands like Add, Delete and so on defined for independent (in my opinion) entities like Peers, Accounts and Assets. Add<object::Account> and Add <object::Peer> (just for example) code fragments do absolutely different work but located inside one class which is (again in my opinion) a little bit confusing.
4. There are 2 branches about this task (featrure/membership-service and feature/membership-service). I think the first one should be removed :)

**Comment by satellitex** [comment]
Hi luckychees.
I can answer question 4.
feature/peer-service branch is used now.
featrure/membership-service and feature/membership-service is old branch, so we may remove these branch. ( "featrure" is misstype "feature"... sorry.. )

**Comment by satellitex** [comment]
# About  Auto Remove deaded Peer System.
## How to way
- Identify peer that timeout when do consensus. 
  - Need to get difference set of sent peer set and received peer set for each transaction.
- Give minus evaluation to timeout peer.
- When update Context in sumeragi, to issue transaction that remove peer whose trustScore is lower than base trustScore.
  ( Want to issue remove<Peer> transaction, but occur permission problem. 
    How do you to issue used iroha-root permission? ) 


## peer validator
- add Peer
  - Don't exist duplication IP in peerList after add Peer.
  - Don't exist duplication publicKey in peerList after add Peer.
- remove Peer
  - TrustScore of Removed peer must not be upper than base trust Rate and equal to one.
  - Exist removed peer in peerList before remove Peer.
- update Peer
  - Exist updated peer in peerList before update Peer.
  - Don't exist duplication IP in peerList after update Peer.
  - Don't exist duplication publicKey in peerList after update Peer.

## peer executor
- add Peer
  - do config::PeerService::getInstance().addPeer( peer );
- remove Peer
  - do config::PeerService::getInstance().removePeer( peer );
- update Peer
  - do config::PeerService::getInstance().updatePeer( peer );
- common 
  - store transaction to Ametsuchi.


# inJP ↓
 - 死んでる ピアを自動的に殺すシステム
- 合意形成時に timeOut した ピアを特定する必要がある
    - 各transaction について送信したピア集合と受信したピア集合の差集合を得る
- timeOutしたピアについてマイナス評価を与える。
- sumeragi が ピア順列 の update をかけるときに、基準値を下回る評価のピアを削除する transaction を peer service が発行する。(このとき remove<Peer> transaction を発行したいが permission の問題はどうするか root に肩代わりして発行してもらう方法)
 - peer validator ( ここにくるまでに permission filter にかかっているので発行元は信頼してよい )
	- add Peer
		- 追加後のピアリストのIPに重複があってはいけない
		- 追加後のピアリストのpublicKeyに重複があってはいけない
	-  remove Peer
		- 削除するピアの信頼度は基準値以上であってはいけない
		- 削除するピアが存在していなくてはいけない
	 - update Peer
		- 更新するピアが存在していなくてはいけない
		- 更新後のピアリストに重複があってはいけない
		- 更新後のピアリストのpublicKeyに重複があってはいけない 

 - peer executor ( ここにくるまでに 合意形成を行っているためこの transaction を信頼してよい )
	- add Peer
		- addPeer( peer ) する。
	- remove Peer
		- removePeer( peer ) する。
	- update Peer
		- updatePeer( peer ) する。
	- common
		- ametsuchi に transaction を保存する。

**Comment by satellitex** [comment]
# Problem and Question about peer service Design
## Question
### about check trustScore system
 - Is it better for a system in which peers try to trust each other from Sumeragi ?
   - Solution, Create an entrance for a new receive separate from Verify / Torii, which will do everything.
## Problem
### about AddPeer
 - when Execute, if you are a leader node, pass all the data to that peer.
   - Want about Transfer<Transaction>.
### about peerOrder
 - The order of peers changes when adding, deleting, or updating peers.
    It is dangerous to change peers agreed during consensus building.
 - Solution, Use the order of consensusEvent. This will manage the version of the peer list. 
   Use the same peer list for the same consensusEvent.

↓in JP
# 問題 / 質問
## 質問
### ピアが互いを評価するシステムについて
 - ピアが互いに信頼度を図るシステムは Sumeragi から乖離したほうが良い？
   - 上記の解決策として：Verify / Torii に次ぐ別の新たな receive の入り口を作り、それが全てをこなす。
## 問題
### Add Peer
 - Execute したとき、自身が リーダーノードであれば、そのピアにデータを全部渡す。
    - このとき、Transfer<Transaction>的なものがほしい。
### ピアの順序
 - ピアの追加、削除、更新した際にピアの順序が入れ替わる。
   合意形成中に合意を取るピアが変更されると危険です。
   解決策として、　consensusEvent の order を使う。 これでピアリストのバージョン管理を行う。
　同じ consensusEvent には同じピアリストを使うようにする。

**Comment by satellitex** [comment]
Monitor dead peers
If there is a peer not returning Response, ask peer-service to investigate that peer.
When Peer-service receives a request, it skips ping to that peer.
  When there was no response,
     When the reliability of peer has already fallen below the reference value
         Issue the peer deletion transaction.   other than that
         Issue transaction to lower the reliability of peer.
When there is a response,
     Restore the reliability of peer.

Monitor a lying peer
     Issue a transaction that reduces the reliability of nodes lying in consensus building

About addPeer
Each peer sends a sequence of transactions in block units (example) to the initial peer in order from the front.
When the initializing peer receives 2f + 1 of the same block, it accepts it and stores it in ametuchi.
- Block requires id for processing in order
- Block requires a unique hash
- The size of each block should be kept to be okay if it gets a memory of * 2f + 1 even if it dies

**Comment by satellitex** [comment]
## About initializePeer
A peer currently forming iroha by addPeer will send a history of large transactions to this peer.
Once received, it will sequentially execute them and build PeerList. After finishing all Transaction data, send update <Peer> (myself, trust-> isok = true); to the leader node and let them also participate in peerList.

### Create initializePeer as a mechanism different from PeerService
### It named "Izanami" ( purpose )

**Comment by satellitex** [comment]
# Perservice Revised Hijiri Docment ( but It haven't rename yet now. )

# # Hijiri is a mechanism to manage peers (nodes) building iroha.
- Hijiri
    - Constructor
    - Build a list of peers from sumeragi.json
- static Hijiri & getInstance ();
    - Return Hijiri's Instance.
    - Usually call this method by connecting to it.
    - Example) config :: Hijiri :: getInstance (). GetPeerList ();
- std :: string getMyPublicKey ();
    - Return my pier's piblicKey
- std :: string getMyPrivateKey ();
    - Return privateKey of your peer
- std :: string getMyIp ();
    - Return ip of your peer
- double getMaxTrustScore ();
    - Get maximum value of reliability.
    - Increasing this will relax the failure judgment, making it smaller will make the failure judgment more severe.
    - Suppose the number of normal nodes is the maximum value.
- std :: vector <std :: unique_ptr <peer :: Node >> getPeerList ();
    - Returns a list of current running peers sorted in descending order of confidence.
- std :: vector <std :: string> getIpList ();
    - Returns a list sorted by the reliability descending order of ip of the current running peer.
- void checkBrokenPeer (const std :: string & ip);
    - During communication, invoke when a peer who does not return Response met.
    - It examines whether a certain peer is not broken and issues the transaction of update <peer> according to the result.
- void finishedInitializePeer ();
    - Invoke itself when the DB initialization for participating in the ledger as a new peer is finished.
    - Issue update <peer> to keep itself running.
- void toIssue_addPeer (const peer :: Node &);
    - Issue a transaction to add a new peer.
    - The ip and publicKey are specified, the initial value of the reliability is max, and add <peer> is issued with an inactive setting.
- void toIssue_distructPeer (const std :: string & publicKey);
    - Issue a transaction that specifies publicKey and lowers the reliability of Peer.
- void toIssue_removePeer (const std :: string & publicKey);
    - Call a transaction that deletes Peer by specifying publicKey.
- void toIssue_creditPeer (const std :: string & publicKey);
    - Issue a transaction that restores the reliability of peer by specifying publicKey
- bool addPeer (const peer :: Node &);
    - Add peer to peerList.
    - Send history of all transactions to that peer after that.
- bool removePeer (const std :: string & publicKey);
    - Delete peer from peerList, specifying publicKey.
- bool updatePeer (const std :: string & publicKey, const
- peer :: Node & peer);
    - Specify publicKey and update peer information.
    - Ip is not defaultIP, change ip.
    - If publicKey is not defaultPublicKey, change publicKey.
    - Increase trustScore by peer.trustScore (). (Decrease if negative value)
    - Update if there is a change in whether it is running or not running.
- bool validate_addPeer (const peer :: Node &);
    - validate whether to do addPeer.
    - Duplicate IP in peer list after adding
    - There must be no duplication in the public key of the added peer list
- bool validate_removePeer (const std :: string & publicKey);
    - validate whether to do removePeer
    - The reliability of the peer to be deleted must not be higher than the reference value
    - Peers to be deleted must exist
- bool validate_updatePeer (const std :: string & publicKey,
- const peer :: Node & peer);
    - validate whether to do updatePeer
    - Peers to be updated must exist
    - Do not have duplicates in updated peer list
    - There must be no duplication in the public key of the updated peer list
- bool isLeaderMyPeer ();
    - Determine if yourself is a leader peer
- std :: unique_ptr <peer :: Node> leaderPeer ();
    - Return a leader peer.
- virtual std :: string getConfigName ();
    - Returns the path where Config is written.

in JP ↓
# Perservice 改め Hijiri のDocment ( まだリネームしていません。 )
## Hijiri は iroha を構築するピア(ノード)達を管理する機構である。
- Hijiri
    - コンストラクタ
    - sumeragi.json からピアのリストを構築する
- static Hijiri &getInstance();
    - Hijiri の Instance を返す。
    - 通常これにつなげてメソッドを呼び出す。
    - 例) config::Hijiri::getInstance().getPeerList();
- std::string getMyPublicKey();
    - 自分のピアの piblicKey を返す
- std::string getMyPrivateKey();
    - 自分のピアの privateKey を返す
- std::string getMyIp();
    - 自分のピアの ip を返す
- double getMaxTrustScore();
    - 信頼度の最大値を取得する。
    - これを大きくすると故障判定が緩くなり、小さくすると故障判定が厳しくなる。
    - 通常ノードの数を最大値にするとする。
- std::vector<std::unique_ptr<peer::Node>> getPeerList();
    - 現在の稼働している peer を信頼度の降順でソートしたリストを返す。
- std::vector<std::string> getIpList();
    - 現在の稼働している peer の ip を信頼度の降順でソートしたリストを返す。
- void checkBrokenPeer( const std::string& ip );
    - 通信中, Response の帰ってこない peer が会った際に invoke する。
    - ある peer が故障していないか調べて、その結果により update<peer> の transaction を発行する。
- void finishedInitializePeer();
    - 自身が新しい peer として ledger に参加するためのDBの初期化が終了した際に invoke する。
    - 自身を稼働中にする update<peer> を発行する。
- void toIssue_addPeer( const peer::Node& );
    - 新しい peer  を追加する transaction を発行する。
    - ip と publicKey を指定し信頼度の初期値は max で, 未稼働の設定で add<peer> 発行する。
- void toIssue_distructPeer( const std::string &publicKey );
    - publicKey  を指定して Peer の信頼度を下げる transaction を発行する。
- void toIssue_removePeer( const std::string &publicKey );
    - publicKey を指定して Peer を削除する transaction を発呼する。
- void toIssue_creditPeer( const std::string &publicKey );
    - publicKey を指定してpeer の信頼度を回復させる transaction を発行する
- bool addPeer( const peer::Node& );
    - peer を peerList に追加する。
    - その後、その peer に全ての transaction の履歴を送る。
- bool removePeer( const std::string &publicKey );
    - publicKey を指定して、peer を peerList から削除する。
- bool updatePeer( const std::string& publicKey, const
- peer::Node& peer );
    - publicKey を指定して、peer の情報を更新する。
    - Ip が defaultIP でなければ、ip を変更する。
    - publicKey がdefaultPublicKey でなければ、publicKeyを変更する。
    - trustScore を peer.trustScore() 分だけ増加させる。（負の値の場合は減る）
    - 稼働か未稼働かに変更があれば更新する。
- bool validate_addPeer( const peer::Node& );
    - addPeer をしてよいか validate する。
    - 追加後のピアリストのIPに重複があってはいけない
    - 追加後のピアリストのpublicKeyに重複があってはいけない
- bool validate_removePeer( const std::string &publicKey );
    - removePeer をしてよいか validate する
    - 削除するピアの信頼度は基準値以上であってはいけない
    - 削除するピアが存在していなくてはいけない
- bool validate_updatePeer( const std::string& publicKey,
- const peer::Node& peer );
    - updatePeer　をしてよいか validate する
    - 更新するピアが存在していなくてはいけない
    - 更新後のピアリストに重複があってはいけない
    - 更新後のピアリストのpublicKeyに重複があってはいけない 
- bool isLeaderMyPeer();
    - 自身がリーダーピアがどうかを判定する
- std::unique_ptr<peer::Node> leaderPeer();
    - リーダーピアを返す。
- virtual std::string getConfigName();
    - Config の書いてあるパスを返す。

**Comment by satellitex** [comment]
# Izanami
Izanami is a mechanism for constructing initial DB / peerList of peer participating on the way.
## # Izanami
- void receiveTransactionResponse (std :: unique_ptr <TransactionResponse>);
    - Invoke when receiving a transactionResponse for initial DB construction.

### class InitializeEvent
InitializeEvent is a class that manages transactionResponse sent from a peer that is already running for initial DB construction.
- InitializeEvent ();
    - Constructor of InitializeEvent class
    - Set the current progress block to 0
- void add_transactionResponse (std :: unique_ptr <TransactionResponse>);
    - Add transactionResponse
    - Generate a hash of transactionResponse and save the body in map with it as key.
- const std :: vector <std :: string> & getHashes (uint64_t);
    - Return a list of hashes of transactionResponse in a progress block. In the case of
- const std :: unique_ptr <TransactionResponse> getTransactionResponse (const std :: string &);
    - Specifying a hash returns the unique_ptr of the TransactionResponse pointed to by it.
- void next_progress ();
    - We will proceed with the progress block we are currently seeing.
- uint64_t now () const;
    - Return the progress block you are currently viewing.
- void storeTxResponse (const std :: string &);
    - Save the TransactionResponse that the hash points to the DB.
- void executeTxResponse (const std :: string &);
    - Perform all Transactions of TransactionResponse pointed to by hash.
- void clear ();
    - Discard all temporary data that was held. In the case of
### namespace detail
Functional function of ancillary functions.
- bool isFinishedReceiveAll (InitializeEvent & event);
    - Determine if all transactionResponse have been received.
    - [WIP: Currently unknown method]
- bool isFinishedReceive (InitializeEvent &);
    - Determine whether you have received the transactionResponse of the current progress block.
    Returns true if there is a transactionResponse of the same hash of the same progress block of 2f + 1.
- std :: string getCorrectHash (InitializeEvent &);
    - Return a hash of the transactionResponse of the current progress block.
- void storeTransactionResponse (InitializeEvent &);
    - Save the transaction of the specified progress block.

in JP ↓
# Izanami
Izanami は途中参加する peer の初期 DB / peerList 構築を行う機構です。
## Izanami
- void receiveTransactionResponse( std::unique_ptr<TransactionResponse> );
    - 初期 DB 構築のための transactionResponse を 受け取った時に invoke する。

###class InitializeEvent
InitializeEvent は初期 DB 構築のために既に稼働中の peer から送られてくる transactionResponse を管理する class です。
- InitializeEvent();
    - InitializeEvent class のコンスタラクタ
    - 現在の進捗ブロックを0にする
- void add_transactionResponse( std::unique_ptr<TransactionResponse> );
    - transactionResponse を追加する
    - transactionResponse のハッシュを生成しそれを key に map に本体を保存する。
- const std::vector<std::string>& getHashes( uint64_t );
    - ある 進捗ブロック における transactionResponse のハッシュのリストを返す。　
- const std::unique_ptr<TransactionResponse> getTransactionResponse( const std::string& );
    - ハッシュを指定するとそれが指す TransactionResponse のunique_ptr を返す。
- void next_progress();
    - 現在見ている進捗ブロックを次にすすめる。
- uint64_t now() const;
    - 現在見ていいる進捗ブロックを返す。
- void storeTxResponse( const std::string& );
    - DBに ハッシュが指す TransactionResponse を保存する。
- void executeTxResponse( const std::string& );
    - ハッシュが指す TransactionResponse が持つ Transaction を全て実行する。
- void clear();
    - 保持していた一時データを全て破棄する。 
###namespace detail
補助的な機能の関数郡。
- bool isFinishedReceiveAll(InitializeEvent &event);
    - 全ての transactionResponse を受け取り終えたかどうかを判定する。
    - [ WIP : 現在その方法が未定 ]
- bool isFinishedReceive(InitializeEvent &);
    - 現在の進捗ブロックの transactionResponse を受け取り終えたか判定する。
    - 2f+1 の同一進捗ブロックの同一ハッシュの transactionResponse があったとき true を返す。
- std::string getCorrectHash(InitializeEvent &);
    - 現在の進捗ブロックの transactionResponse のハッシュを返す。
- void storeTransactionResponse(InitializeEvent &);
    - 指定した進捗ブロックの transaction を保存する。

**Comment by l4l** [comment]
Is it still active?
