### ISSUE TITLE
Setup install step for C++ shared model

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#1465]
I want to use C++ Shared Model on client side. Proper way to do this from client prospective of view is to write:
```
cmake .. -DONLY_SHARED_MODEL=TRUE   # or -DONLY_CPP_CLIENT=ON
make install  
```
Look [how I did this for iroha-ed25519](https://github.com/hyperledger/iroha-ed25519/blob/master/CMakeLists.txt#L145-L182).
Proper way to exclude unrelated to shared_model targets from `make install` step is to exclude them from `all` target, it can be done with property [`EXCLUDE_FROM_ALL`](https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_ALL.html) ([example](https://github.com/hyperledger/iroha-ed25519/blob/08c58c9356a002e1f7c1a8f7f62f4084fc2861f3/cmake/ed25519_add_library.cmake#L57))

`make install` builds and installs iroha client library in the system:
```
/usr/local
├── include  # all include headers
├── lib      # libshared_model.{so,dylib}
├── share    # cmake config file with version, so find_package(iroha_shared_model) will find it
```

currently I need to do all of these manually (copy include headers, there is no single `shared_model` target, create cmake, which is hard to reproduce from version to version.

I request to add this feature in current release, as soon as possible.

**Comment by LiraLemur** [comment]
Moved to Jira: https://jira.hyperledger.org/browse/IR-193

**Comment by Warchant** [comment]
Outdated
