### ISSUE TITLE
iroha-lib is outdated in npm

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#1466]
This library still has `counter` in transaction, while it has been removed, as I know.

Please, setup continuous delivery for `npm`.

UPD: I used `yarn add iroha-lib` to install it and by default version 0.0.6 is installed. Please, change to latest version (0.1.4)

**Comment by stinger112** [comment]
Version for Iroha v1.0 beta-2 has been under testing because I tried to implement it using experimental Emscripten compilation.

Now we decide to make this experiment as default, so now you can install the version **iroha-lib** for the latest Iroha release by `yarn add iroha-lib` without tags.

**Comment by stinger112** [comment]
The new version of **iroha-lib** for _Iroha v1.0 beta-3_ has been released.
