### ISSUE TITLE
Potential bug in addPeer IP parsing

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#1467]
I am using latest develop java bindings. I am trying to create a transaction and for the following IP:
```
        .addPeer("192.168.1.2", keyPair.publicKey())
```

I get the following error:
```
java.lang.IllegalArgumentException: 1 AddPeer: [[Wrongly formed peer address, passed value: '192.168.1.2'. Field should have valid IPv4 format or be a valid hostname following RFC1123 specification ]]
```
which is apparently a bug.

Add a test case for this to check if it is bug.

**UPD**: in fact, any IPv4 is considered as wrong. I tried 1.1.1.1, 8.8.8.8, 78.12.6.12, which are valid IPv4 addresses

**UPD2**: this is logging error. Logs do not mention that first argument must be `{ip}:{port}`

**Comment by l4l** [comment]
Message description is wrong actually. Peer address must also contain port, e.g `"192.168.1.2:12345"`

**Comment by Warchant** [comment]
@l4l yes, this is logging bug.
