### ISSUE TITLE
Introduce a high load test

### ISSUE THREAD

**Issue by e-ivkov** [hyperledger/iroha#1479]
In most tests we wait before submitting another transaction for some time, though we need to check Iroha under more stressful conditions as we have seen that it might fail there.

**Comment by appetrosyan** [comment]
We could try to investigate this by varying the delay, and see what the optimum time is for request processing.

**Comment by SamHSmith** [comment]
The TPS benchmark serves this purpose now as it has no delay between transactions. When the benchmark is running parts of iroha such as the sumeragi thread have 100 % CPU usage while the node still works.

**Comment by appetrosyan** [comment]
Deploying this on an actual 4 machine network is something we should consider.
