### ISSUE TITLE
WIP: Iroha Shared Objects Description

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1498]
# Iroha Shared Objects Description

This document describes access to shared objects in a multithreaded scenario, whether or not is properly synchronized.

## Document Structure

Each component in this document has its own diagram describing all members, and whether or not access to them is synchronized or not. Following color scheme is used:

![legend](https://user-images.githubusercontent.com/14168731/41855929-858d18b2-789c-11e8-8f61-226e9c213362.png)

## Query Service

![query_service](https://user-images.githubusercontent.com/14168731/41851265-f9c36b9e-788f-11e8-837b-610911f0f547.png)

Query service is a grpc endpoint for queries from clients. It has cache, from which it receives responses. Access to the cache is protected by an internal mutex. Query processor actually fetches data from the storage. It is not synchronized here since all synchronization is internal.

## Query Processor

![shared_objects-3](https://user-images.githubusercontent.com/14168731/41851667-52801bd2-7891-11e8-9862-559f60bde143.png)

## Transaction Service

![transaction_service](https://user-images.githubusercontent.com/14168731/41851743-9079a7fa-7891-11e8-8bd7-3b31a04f6c2b.png)

Transaction Service uses response cache to send transaction statuses. Also, transaction processor is synchronized in status streaming.

## Transaction Processor

![tx-processor](https://user-images.githubusercontent.com/14168731/41852320-6859b1fa-7893-11e8-852d-cf9e18c0cf1e.png)

## Simulator

![simulator](https://user-images.githubusercontent.com/14168731/41853494-90f84326-7896-11e8-9197-cc839ea6ff93.png)

## Synchronizer

![synchronizer2](https://user-images.githubusercontent.com/14168731/41854748-ac12a27a-7899-11e8-93b2-824bd332d9cd.png)

## Yac Gate

![yac_gate](https://user-images.githubusercontent.com/14168731/41855251-d2ea4910-789a-11e8-8e46-f4a69c10b38b.png)

## Yac

![yac](https://user-images.githubusercontent.com/14168731/41855777-1938bf18-789c-11e8-832c-90db41c3220b.png)

**Comment by nickaleks** [comment]
Found an issue that query processor need read lock on the database in order to avoid data inconsistency

**Comment by LiraLemur** [comment]
moved to Jira: https://jira.hyperledger.org/browse/IR-194
