### ISSUE TITLE
Return full errors in response bodies in torii

### ISSUE THREAD

**Issue by eadventurous** [hyperledger/iroha#1502]
Currently probably due to migration to thiserror and eyre, our torii error return bodies stopped giving back full error chain.

Only specifying `#[source]` there does not seem to be enough as is demonstrated by [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=346bce4c5ddfe2278b227741bae5d85b). It seems we need to add where appropriate `{0}` or other formatting specifiers to error descriptions, to have full chain in bodies.

**Comment by appetrosyan** [comment]
Closing until an MWE is found to reproduce the issue.
