### ISSUE TITLE
Cmake and multiple Python versions

### ISSUE THREAD

**Issue by Stayer** [hyperledger/iroha#1516]
Iroha uses 2 and more python versions. CMake randomly selects this version. I think, we need to setup specific python version using additional parameters like `DPYTHON_EXECUTABLE`, `DPYTHON_LIBRARIES`, etc.

Detected builds: Linux x86_64, Windows

Example build log

```
15:02:11 [Linux bindings] -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.5", minimum required is "3.5") 
15:02:11 [Linux bindings] -- Found PythonInterp: /usr/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5")
```

Solution: https://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do

**Comment by LiraLemur** [comment]
Outdated since we are getting rid of bindings in favour of better solutions.
