### ISSUE TITLE
Incorrect CI build parameters

### ISSUE THREAD

**Issue by Stayer** [hyperledger/iroha#1519]
Reference PR: #1392 

Can't select architecture for bindings. In previous CI version, you can change platform and iroha/bindings builds, now you can pick only "bindings" without platform selection

**Comment by tyvision** [comment]
@Stayer @bakhtin My concern is that we need to exclude `params.iroha` due to new pipeline generation and repair the logic of `params.bindings` + `params.{Java,Python,Android}Bindings` and `params.x86_64_win`

**Comment by tyvision** [comment]
Thus, it will look like that:
```groovy
stage('bindings') {
  when {
     expression { return params.bindings }
  ...
  }
...
}
stage('windows_bindings') {
  when {
    allOf {
      expression { return params.bindings }
      expression { return params.x86_64_win }
    }
  }
...
}
```

**Comment by tyvision** [comment]
Proposed solution is at the https://jenkins.soramitsu.co.jp/job/iroha/job/iroha-hyperledger/job/fix%252Fci-pipeline-logic/1/console
or `fix/ci-pipeline-logic` branch.

**Comment by LiraLemur** [comment]
Outdated since we are getting rid of bindings in favour of better solutions.
