### ISSUE TITLE
CI improvement recommendations meta-issue

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1525]
## About

This is a blanket issue for collecting proposals on how to make the CI for `iroha2-dev` faster and more reliable. 

@i1i1 @GaroRobe @s8sato @KalitaAlexey  your input is welcome.

**Comment by i1i1** [comment]
## Make docker image for check workflow in ci

It would remove installing cargo lints and nightly toolchain for formatting.

**Comment by i1i1** [comment]
> I'm a little iffy of automatically applying clippy suggestions. They often require manual intervention.

Most of them (like remove `clone`) don't though :)

It wont hurt anyway to add `clippy --fix`

**Comment by appetrosyan** [comment]
# Consider using smaller Docker images

Most of our unrealiable tests run out of memory. Due to the way docker containers work, it might be improved by using a more minimal customised docker image that contains our dependencies and does not contain any extraneous packages/systems.

**Comment by appetrosyan** [comment]
# Consider granular dependency based-testing. 

- If only `md` files changed, the only things that need to run are `add_label` and `DCO`. 

- If only the `json` files changed, we don't need to re-run the source based unit tests (which we don't differentiate from other tests, even though I think that we should). 

- If a crate changed, only its, its dependencies' and the integration tests need to be re-run. This saves on running many unit tests for crates like `client_cli`.

**Comment by appetrosyan** [comment]
Use the cranelift compiler 
https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/docs/usage.md

**Comment by appetrosyan** [comment]
Use smarter cache. 
https://github.com/Swatinem/rust-cache
