### ISSUE TITLE
AddAssetQuantity has incorrect params

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [hyperledger/iroha#1559]
https://github.com/hyperledger/iroha/blob/91bbb0f5a53929f2be017f3b2f00281b080b74bb/iroha-cli/interactive/impl/interactive_transaction_cli.cpp#L91

`iroha-cli` asks to enter account id that has been removed recently for the command. It seems that we forgot to fix it in CLI.
```
15. Add Asset Quantity (add_ast_qty)
...
0. Back (b)
> : 15
Account Id: iroha
Asset Id: coin
Amount to add (integer part): 1
Amount to add (precision): 0
```

**Comment by LiraLemur** [comment]
Outdated
