### ISSUE TITLE
my_test_bin/sumeragi_test linking failed

### ISSUE THREAD

**Issue by boully** [hyperledger/iroha#157]
build environment:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

build iroha by https://github.com/hyperledger/iroha/blob/master/docs/how_to_build.rst step by step.

and make failed because of a test unit linking failure, failed info as following:

> [ 91%] Linking CXX executable ../../my_test_bin/sumeragi_test
> /usr/bin/ld: cannot find -lleveldb
> collect2: error: ld returned 1 exit status
> test/consensus/CMakeFiles/sumeragi_test.dir/build.make:115: recipe for target 'my_test_bin/sumeragi_test' failed
> make[2]: *** [my_test_bin/sumeragi_test] Error 1
> CMakeFiles/Makefile2:1698: recipe for target 'test/consensus/CMakeFiles/sumeragi_test.dir/all' failed
> make[1]: *** [test/consensus/CMakeFiles/sumeragi_test.dir/all] Error 2
> Makefile:94: recipe for target 'all' failed
> make: *** [all] Error 2]

I tried to add link_directry of leveldb for sumeragi_test, it doesn't working since another linking lib named snappy is missing, which is specified by the CMakeLists.txt

did you guys meet this problem before? How can I fix it?

**Comment by MizukiSonoko** [comment]
Ok
Maybe reason for it is libleveldb is not built.
Could you try it
```
cd $IROHA_HOME/core/vendor/leveldb
make 
```

**Comment by boully** [comment]
> cd $IROHA_HOME/core/vendor/leveldb
> make 
the build for leveldb is done. As I can get two output library folds: out-shared, out-static

I have tried to add this out-static path into sumeragi_test's CMakeLists.txt for link_directory, it introduce another link problem.

**Comment by MizukiSonoko** [comment]
Ok what is problem?

**Comment by boully** [comment]
Problem solved, as I made such modification:
```
diff --git a/test/consensus/CMakeLists.txt b/test/consensus/CMakeLists.txt
```
<pre>
index 8eb6240..e6272f7 100644
--- a/test/consensus/CMakeLists.txt
+++ b/test/consensus/CMakeLists.txt
@@ -4,6 +4,7 @@ SET(CMAKE_CXX_FLAGS_DEBUG "-g")

 SET(KECCAK_PATH  "${PROJECT_SOURCE_DIR}/core/vendor/KeccakCodePackage")
 SET(ED25519_PATH "${PROJECT_SOURCE_DIR}/core/vendor/ed25519")
+SET(LEVELDB_PATH "${PROJECT_SOURCE_DIR}/core/vendor/leveldb")

 include_directories(
     ${PROJECT_SOURCE_DIR}/core
@@ -15,6 +16,7 @@ link_directories(
     ${KECCAK_PATH}/bin/generic64
     ${PROJECT_SOURCE_DIR}/core/infra/crypto
     ${AERON_PATH}/cppbuild/Release/lib
+   ${LEVELDB_PATH}/out-static
 )

 add_executable(sumeragi_test
@@ -23,6 +25,7 @@ add_executable(sumeragi_test


 target_link_libraries(sumeragi_test
+   leveldb
     snappy
     objects
     base64
</pre>

**Comment by MizukiSonoko** [comment]
I'm sorry that it is confusing...

**Comment by boully** [comment]
sorry for confusing...

I did some modification for file: test/consensus/CMakeLists.txt
next figure shows the diff that I made:
![2017-02-14 7 17 52](https://cloud.githubusercontent.com/assets/19681098/22927071/51de5d8e-f2ea-11e6-835a-b72cf7410976.png)
