### ISSUE TITLE
BUG: AddAssetQuantity is taking incorrect params

### ISSUE THREAD

**Issue by ayushpalak** [hyperledger/iroha#1578]
hi team, 
I was using AddAssetQuantity but it seems that on passing account id, the value is getting allocated to asset id. please fix it. Without this command we can't do a lot with it.

Thanks

**Comment by l4l** [comment]
Account identifier was removed from the command (#1511), since it doesn't introduce additional information (the account can add assets only to him/her-self).
I hope the problem is solved, so closing the issue. Feel free to bump it, if the issue is remaining

**Comment by neewy** [comment]
Please transfer assets which were added to the account

**Comment by ayushpalak** [comment]
How can I add asset then, the info in doc is old and giving error. help plz

**Comment by l4l** [comment]
@AmitKalita it was already discussed that it's not an issue. AddAssetQty is intended to be performed only and only toward account creator
