### ISSUE TITLE
Inter-ledger transactions between Fabric and Iroha

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#159]
We would like to realize inter-ledger transactions between Fabric and Iroha. To do this we need to:

① Define a protocol for inter-ledger transactions

and then

② implement the protocol in Fabric and Iroha.

Related to ①, we should probably consider the following:

 - 2 phase commit
 - multi-signature transaction

I have a feeling that multi-signature transactions might be a good way to realize this protocol, but I need to think more about this. Does anyone have any ideas?

**Comment by adrianhopebailie** [comment]
@takemiyamakoto you should look at the Interledger Protocol (https://interledger.org) it uses 2 phase commit to perform synchronised transfers on 2 (or more) ledgers to effect a multi-ledger transfer through a counter-party (connector) that has accounts on both ledgers.
