### ISSUE TITLE
New Account Structure

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1594]
We need to refactor accounts for public blockchain use cases, where pre-registration is not needed. For example, like ethereum or polkadot accounts, where you can generate a key offline and get an address people can send assets to.

Account names can be registered as an "alias" or public identity.

**Comment by appetrosyan** [comment]
Another point that was raised during status, was that Substrate accounts have a primary key-pair and secondary keys used for multi-signature transactions.

**Comment by s8sato** [comment]
This issue has to do with how a new peer join the network #1375
With the current design, a new peer cannot take any action spontaneously in public chains
