### ISSUE TITLE
Bug in version 1.3.0 which was not in version 1.3rc1 - blocks are being created only with max_proposal_size commands

### ISSUE THREAD

**Issue by baziorek** [hyperledger/iroha#1651]
I've been using iroha for more than year and I have two networks. After completing internship projects I've migrated iroha from version 1.2 into 1.3.0rc. After 1.3.0 was released I've upgraded my networks into versions:
```
$ docker pull hyperledger/iroha-burrow:1.3.0
$ docker images
REPOSITORY                 TAG          IMAGE ID       CREATED         SIZE
hyperledger/iroha-burrow   1.3.0        379586614dad   2 weeks ago     195MB
```
and suddenly I've noticed that transactions are being committed after they reach: `max_proposal_size`, despite the fact that we have few transactions per hour.
_____________
My `config.docker` file (it was working before version 1.3.0, but since 1.3 version it is not working as before):
```
$ cat config.docker 
{
    "block_store_path" : "/home/blockchain_blocks/",
    "torii_port" : 50051,
    "internal_port" : 10001,
    "pg_opt" : "host=localhost port=5432 user=postgres password=mysecretpassword",
    "max_proposal_size" : 100,
    "proposal_delay" : 1000,
    "vote_delay" : 1000,
    "mst_enable" : true,
    "mst_expiration_time" : 60,
    "max_rounds_delay": 1000,
    "stale_stream_max_rounds": 2
}
```
__________
Transactions in sample block after migration:
```
$ jq < 0000000000141070 | grep commands | wc -l
100
```
but in contrast before migration:
```
$ jq < 0000000000141062 | grep commands | wc -l
1
```
____________________
I've compared its locally in temporary single-node network and I see that there is problem with params: `proposal_delay` and `max_rounds_delay`. To be more specific:
1. Everything is working fine with config:
```
{
    "block_store_path" : "/home/blockchain_blocks/",
    "torii_port" : 50051,
    "internal_port" : 10001,
    "pg_opt" : "host=localhost port=5432 user=postgres password=mysecretpassword",
    "max_proposal_size" : 100,
    "proposal_delay" : 5000,
    "vote_delay" : 1000,
    "max_rounds_delay": 3000,
    "mst_enable" : true,
    "mst_expiration_time" : 60,
    "stale_stream_max_rounds": 100
}
```
2. on the other hand it is not working with the config:
```
{
    "block_store_path" : "/home/blockchain_blocks/",
    "torii_port" : 50051,
    "internal_port" : 10001,
    "pg_opt" : "host=localhost port=5432 user=postgres password=mysecretpassword",
    "max_proposal_size" : 100,
    "proposal_delay" : 3000,
    "vote_delay" : 1000,
    "max_rounds_delay": 3000,
    "mst_enable" : true,
    "mst_expiration_time" : 60,
    "stale_stream_max_rounds": 100
}
```
3. this is also not working (even despite 2 seconds difference between those params):
```
{
    "block_store_path" : "/home/blockchain_blocks/",
    "torii_port" : 50051,
    "internal_port" : 10001,
    "pg_opt" : "host=localhost port=5432 user=postgres password=mysecretpassword",
    "max_proposal_size" : 100,
    "proposal_delay" : 3000,
    "vote_delay" : 1000,
    "max_rounds_delay": 1000,
    "mst_enable" : true,
    "mst_expiration_time" : 60,
    "stale_stream_max_rounds": 100
}
```

**Comment by LiraLemur** [comment]
Hi @baziorek !

So, here's what happens. 1) max_round_delay is deprecated. It was replaced some time ago by proposal_creation_timeout

2) there is this thing with these 2 parameters: proposal_delay must be bigger than proposal_creation_timeout. Not following this rule will lead to unstable system -- we recently found this out. These parameters are connected and I mentioned it in the docs (still in review though (you can take a look and review it :) ) : https://github.com/hyperledger/iroha/pull/1654

**Comment by baziorek** [comment]
Hi @LiraLemur, thanks for the explanation and for documentation changes (I've added approve here https://github.com/hyperledger/iroha/pull/1654). I think I can close my issue.
