### ISSUE TITLE
Void

### ISSUE THREAD

**Issue by lazaridiscom** [hyperledger/iroha#1659]

**Comment by lazaridiscom** [comment]
https://iroha.readthedocs.io/en/main/build/index.html#id7

it looks like parameters are reversed:

```sh
powershell -ExecutionPolicy ByPass -File .\.packer\win\scripts\vcpkg.ps1 .\vcpkg .\iroha\vcpkg

should be

powershell -ExecutionPolicy ByPass -File .\.packer\win\scripts\vcpkg.ps1 .\iroha\vcpkg .\vcpkg 
```

installation continues now on my side.

**Comment by lazaridiscom** [comment]
@LiraLemur

**Comment by kuvaldini** [comment]
We dropped support of Windows in summer 2021.

@LiraLemur Please add note to documentation that 

#### Windows (outdated)

**Comment by kuvaldini** [comment]
@lazaridiscom Could you please try Linux way through Git Bash?

**Comment by kuvaldini** [comment]
@lazaridiscom, and there are still 3 options for you. 
 
 1. Run ready prepared hyperledger/iroha in docker.
 1. Build Iroha in docker image hyperledger/iroha-builder, than copy executable irohad to fresh ubuntu. irohad is standalone, linked statically.
 1. Use WSL. I heard it is pretty stable.

**Comment by lazaridiscom** [comment]
All good, I processed the native Win build just as a quality test. Using usually ubuntu1804 docker instance for main build.
