### ISSUE TITLE
Sort out cargo dependencies

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1661]
There are unused dependencies in `Cargo.toml`s around and some should be listed as `dev-dependencies`. Make use of `cargo udeps` which can also be added to our CI to guard against unused dependencies. It's very easy to use and we don't have to run it on every PR?

**Comment by appetrosyan** [comment]
We should probably check for vulnerabilities.

**Comment by mversic** [comment]
That too, there is a tool `cargo audit` I think

**Comment by mversic** [comment]
https://github.com/rustsec/rustsec
