### ISSUE TITLE
[IROHA2] Consider Moving Iroha2 to own Repository

### ISSUE THREAD

**Issue by lazaridiscom** [hyperledger/iroha#1664]
I came to iroha mainly because its in C++

>  Hyperledger Iroha features a simple construction, modular, domain-driven C++ design,

> Iroha is a distributed ledger project, that aims to provide a development environment where C++ and mobile application developers could contribute to Hyperledger. 

https://wiki.hyperledger.org/display/iroha/Hyperledger+Iroha

Due to build problems on a windows machine (#1659) i looked around and noticed `iroha2-dev`, and of course many issues re "iroha2".

After reading a bit, I got excited about Iroha2, but then noticed that its implemented in Rust.

This feels a bit confusing and irritating, iroha is for a long time as "C++" in my mind, and iroha2 seems anyways like something different.

Possibly the team should consider to rebrand "iroha2" away from "iroha", meaning an own repo, ideally with an own name:

* iroha => C++, focuses strictly on C++, and iroha2 would be again in C++
* maroha => Rust (just picked some random name)

**Comment by kuvaldini** [comment]
Hello. Thank you for your interest to Iroha.  
This idea has been already considered more than one time. There are some organizational things and agreements whose makes us keep both irohas in same repo.  What I can say – Iroha2 is considered to be successor of iroha1. Let them be.

**Comment by lazaridiscom** [comment]
> There are some organizational things and agreements whose makes us keep both irohas in same repo.

The essence is:

I (and possibly other potential users/contributors) cannot focus on Iroha-C++ development/maintenance, because the project-resources are full of Iroha2-Rust traffic.

Just take this into account.

**Comment by kuvaldini** [comment]
Never mind. Just  checkout to branch `main` and iroha-rust never worries. Nobody comlained earlier. Just a little inconvenience. Closing.

**Comment by lazaridiscom** [comment]
Oh my, what a disaster. Closing issues does not fix an obvious problem.

**Comment by kuvaldini** [comment]
Please collect votes from contributors. You are first and along person who claims.

**Comment by lazaridiscom** [comment]
> Please collect votes from contributors. You are first and along person who claims.

This issue was closed (you) and voided (me).

Alll good, keep the project as is.
