### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1671]
Current Versioning has a lot of code duplication and unnecessary fluff.

**Comment by mversic** [comment]
The ability to manage dependencies for all workspace crates is not yet available in `cargo`. However, here is [a tracking issue](https://github.com/rust-lang/cargo/issues/8415) for this feature. Once available we can make good use of it to manage dependency versions for all of our crates

**Comment by mversic** [comment]
Duplicate of #1675
