### ISSUE TITLE
Make use of `AsRef`, `AsMut` and `From` for versioned containers

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1673]
Our versioned containers implement `into_v1`, `as_v1`, `as_mut_v1` separately. To make this look more rusty I propose:

* find all instances of `into_v1` in the code and replace them with implementation of `From` trait
* find all instances of `as_v1` in the code and replace them with implementation of `AsRef` trait
* find all instances of `as_mut_v1` in the code and replace them with implementation of `AsMut` trait

**Comment by lazaridiscom** [comment]
> look more rusty

@mversic , is this iroha2 related?

**Comment by mversic** [comment]
@lazaridiscom yes. I've added label

**Comment by SamHSmith** [comment]
I was not able to make progress on this without making changes to a derive macro.
core/src/sumeragi/message.rs:108 causes issues. `declare_versioned_with_scale!(VersionedMessage 1..2, Debug, Clone, iroha_macro::FromVariant, iroha_actor::Message);`

With the included From implementation things don't work and without they break in other ways. Someone with better macro abilities should work on this.

**Comment by ilchu** [comment]
Closing it as non-relevant. These concerns could resurface when we have an actual versioning system in place.
