### ISSUE TITLE
Simplify macro generation of versioned containers

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1675]
Our current macro implementation of versioned containers creates wrapper structure for each versioned item. Instead of using wrapper structure we should use private type alias. This will reduce the amount of code generated by the macro and will make our API look much nicer

**Comment by kuvaldini** [comment]
could you please mark iroha2 issues with corresponding label

**Comment by mversic** [comment]
@kuvaldini yes, I forgot. I'll try to be more careful
