### ISSUE TITLE
Unnecessary Protobuf backend usage in irohad

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1678]
Shared model design introduces a separation between model objects and their implementation. This reduces coupling to specific backends, such as protobuf. Unfortunately, during migration to shared model, it was not possible to implement all the functionality needed by Irohad using only interfaces.

This Issue describes cmake targets of Irohad which should not rely on the protobuf backend, but still do. For each target, necessary changes are proposed, so that it may be decoupled from the protobuf.

- ordering_service: uses protobuf because it includes ordering_service_transport. Since ordering service is going to be replaced in the future, it is not necessary to change it at the moment.

- raw_block_loader: uses protobuf to deserialize JSON objects. #1662 introduces interface for serialization of blocks, and it can be used instead of raw protobuf.

- yac: big target which includes transport and storage. Can be split into several targets

- common_execution - permissions' toString() function uses protobuf. We need to introduce an interface for that

- synchronizer - not needed. Need to remove extra includes, and the target.

-  block_loader - can be replace with schema

**Comment by LiraLemur** [comment]
Moved to Jira: https://jira.hyperledger.org/browse/IR-197
