### ISSUE TITLE
Update `contributing.md`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1685]
We need to update the `contributing.md`.

**Comment by lazaridiscom** [comment]
@appetrosyan you mean `iroha2-dev/contributing.md`?

Possibly the topmost important change would be to add a note to `main/contributing.rst` in order to clarify that development focuses now on iroha2 within the iroha2-dev branch. 

(even better to add such a note within the README, right on top)

**Comment by appetrosyan** [comment]
Good idea.
