### ISSUE TITLE
Super user permissions

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#1711]
For private blockchains it's crucial to have global permissions for a privileged account. Those permission relate to both queries and instructions and may be applicable to most of existing ones.
- Abilities to query any account's data of type X
- Abilities to write/modify (meta)data of any account/asset etc

Such permissions will allow to have a privileged user not caring about any potential account/asset etc created after such a permission being issued.

**Comment by appetrosyan** [comment]
Fixed at the genesis block level. Alternative requires too much long-term maintenance.
