### ISSUE TITLE
Revive `docker_test`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1726]
Currently, the `test_docker` is non-functional and has been since we upgraded to `rust 1.56`. 

As we plan to move to test on physically distributed peers, this is not a priority, but reviving this test (and figuring out how to do such tests in the future) might come in handy.

**Comment by Mingela** [comment]
@appetrosyan could you provide a bit more context on what exactly is wrong with the test? Actually, a containerized application/node should be considered as a target deployment too.

**Comment by appetrosyan** [comment]
When we first introduced `rust-1.56` the docker test in our CI stopped working. Since then, we've stopped running the docker-test on any of our pull requests, either before or after merge. We wanted to get to it, and fix the thing, but RC1 stuff got in the way and so we shelved it for the time being. 

Now that the Iroha 2 tutorial is almost done, and the first release candidate is up, we have the means and the time to focus on making a docker test that checks a bit more of what we need.
