### ISSUE TITLE
Return references to blocks from WSV instead of cloning

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1737]
When interfacing WSV it is a good idea to return references to the blocks in the blockchain as the cloning can be quite expensive. At the moment we have `blocks_from_height` and `blocks_after_hash` which can/should both be replaced with something akin to the following:
```
    /// Returns iterator over blockchain blocks
    ///
    /// **Locking behaviour**: Holding references to blocks stored in the blockchain can induce
    /// deadlock. This limitation is imposed by the fact that blockchain is backed by [`Dashmap`]
    pub fn blocks(
        &self,
    ) -> impl Iterator<Item = impl Deref<Target = VersionedCommittedBlock> + '_> + '_ {
        self.blocks.iter()
    }
```

However, users of this function should be very careful not to store references(release them as soon as possible) to the blocks since blockchain is backed by the `dashmap` which can deadlock on insert in this case.

There may also be other methods on WSV which also return cloned blocks instead of references. Those should be modified as well to return references

**Comment by appetrosyan** [comment]
COW?

**Comment by mversic** [comment]
I don't think COW is necessary. Either all have to be cloned or none. If it is, I would consider it in another issue

**Comment by Arjentix** [comment]
See also #1974

**Comment by SamHSmith** [comment]
Sumeragi Simplification changes so much of this that it will have to be re-evaluated afterwards.

**Comment by SamHSmith** [comment]
The blocks on kura has made this change.
