### ISSUE TITLE
BlockLoaderImpl Block: [[Transaction list: [[Transaction sequence can not be empty ]]

### ISSUE THREAD

**Issue by truongnmt** [hyperledger/iroha#1747]
After I testing Iroha on a heavily test scenario (300 user concurrently send request), now one of my peer constantly print out:
```
...
[2018-10-01 07:36:13.737135991][th:676][error] BlockLoaderImpl Block: [[Transaction list: [[Transaction sequence can not be empty ]]
...
```
Although the is no imcomming request, Iroha still seem to process something.

![peek 2018-09-26 08-31](https://user-images.githubusercontent.com/11817656/46275652-e3542700-c587-11e8-9e36-a642170482d2.gif)

Here is a full [4 peers log](https://gist.github.com/truongnmt/e8e57fcc1767ad5393269de448d314b6).

**Comment by lebdron** [comment]
Fixed in https://github.com/hyperledger/iroha/pull/1792
