### ISSUE TITLE
Iroha performance

### ISSUE THREAD

**Issue by truongnmt** [hyperledger/iroha#1748]
I setup an scenario to test Iroha performance. This is my environment spec:
- AWS t3.small instance: 2 vCPUs, 2.5 GHz, Intel Skylake P-8175, 2 GiB memory
- Iroha docker develop tag
- 1 host with 4 peers (nodes)
- Python SDK with Flask server API to hander user request

I setup a scenario using JMeter. 300 threads (user) will send 1 create user request. And the result is very bad, error rate 95%.

Here is my 4 peers logs:
https://gist.github.com/truongnmt/83a179c3cb83f5830f9ac709238eaf13

Also I see a framework to test for blockchain is [Caliper](https://github.com/hyperledger/caliper), install everything but on the part [running benchmark](https://github.com/hyperledger/caliper#run-benchmark) is so confusing.

**Comment by truongnmt** [comment]
I just tuning some parameter here is what I got.
```
max_proposal_size: 50
proposal_delay: 7000
vote_delay: 100
```
300 threads, ramp-up 5 seconds (meaning that it take 5 seconds for all thread to send request. So roughly ~60 tx/s)
![screenshot from 2018-10-03 11-22-24](https://user-images.githubusercontent.com/11817656/46394097-33f78b80-c712-11e8-980c-81e47f3433cd.png)

```
max_proposal_size: 200
proposal_delay: 7000
vote_delay: 100
300 threads, ramp-up 5 seconds
```
![screenshot from 2018-10-03 12-58-23](https://user-images.githubusercontent.com/11817656/46394113-4376d480-c712-11e8-9f59-84d78d976924.png)

```
max_proposal_size: 300
proposal_delay: 10000
vote_delay: 100
300 threads, ramp-up 5 seconds
```
![screenshot from 2018-10-03 13-29-03](https://user-images.githubusercontent.com/11817656/46394148-6608ed80-c712-11e8-9716-948e3922b34b.png)

**Comment by truongnmt** [comment]
Notice that on No. 6 attempt, I got error:
```
[2018-10-03 07:06:12.498330740][th:1261][warning] BlockLoaderImpl Block not found
[2018-10-03 07:06:12.499745529][th:1261][error] YacGate Could not get block from block loader
```

**Comment by l4l** [comment]
That amazing research you've done, thank you!
But still there's some lack of information to conclude and understand the core of the issues.

> 1 host with 4 peers (nodes)

Am I correct that you've launched one aws instance and 4 iroha peers on it? That may cause thread scheduling, memory exhausting and numerous of other issues.
Also where was the client launched? (on the same aws instance or outside)

> I setup a scenario using JMeter ... error rate 95%

I'm not familiar with that tool. Could you explain what does "error rate" means in this particular context? Dropped network packets, cancels on OSI application level or smth else?

Any other additional info might be really helpful, so feel free anything other info (even if you consider is barely useful)!

**Comment by truongnmt** [comment]
Sorry for my late response. 
> 1 host with 4 peers (nodes)
Yes one aws instance and 4 iroha peers. I setup JMeter (client) on my localhost. In AWS instance I setup Iroha and Iroha Python SDK with Flask server API to hander user request.

I did a test with 4 AWS instances, each has 1 peer. But I didn't notice any different in comparison with 1 instance 4 peers.

I think the reason is this. During a heavy load, due to the waiting time too long (either because of max_proposal_size or proposal_delay), most of the request go timeout. While the time to process transactions is very fast. With the default config: 
```
"max_proposal_size" : 10,
"proposal_delay" : 5000,
"vote_delay" : 5000,
"load_delay" : 5000
```
I using Postman to send request to server, it takes 10s to complete. With 100 concurrent user, timeout is inevitable. So with this config:
```
max_proposal_size: 300
proposal_delay: 500
vote_delay: 100,
load_delay: 5000
```
The request only take 600-800ms @@. That's nut! 

About the JMeter, that is a tool to test web performance. So I setup an scenario that 300 user will create account. Just provide params, host web server IP and it will run it for you. Success request will return status 200. The rest (501, 502 ...) is fail. So the error rate is the percent of failure request in total.

**Comment by nickaleks** [comment]
Hi, regarding any performance numbers, we are currently in the process of optimization transactions.
Currently, we do not have a precise number to show. Latest dev branch can have about 300 tx/sec of throughput.

Regarding your benchmark, could you please specify how many transactions/sec did you send to iroha? Did you send them to a single peer or a whole network?

Regarding the bug you encountered, we are currently looking into it, please expect fixes to be in the dev branch soon.

**Comment by TranBaVinhSon** [comment]
@nickaleks Could you send me a configuration for `300 tx/sec`?
how many peers, hosts, `config.docker` file...etc

**Comment by nickaleks** [comment]
Unfortunately, this number is not confirmed right now. As soon as we have a benchmark to show, It will be published.

**Comment by truongnmt** [comment]
Again, reading about the [configuration tips](https://iroha.readthedocs.io/en/latest/guides/configuration.html#environment-specific-parameters) and try to implement as suggested: raise `max_proposal_size` and `proposal_delay` on handle a lot of transactions.

Here is my setting: 
max_proposal_size: 400
proposal_delay: 5000
vote_delay: 400

Here is the result with an individual request using Postman: **6-9s**.

Using jmeter tool, I sent **400 transactions** in 1 second and here is the result:
<img width="870" alt="screen shot 2018-10-25 at 17 20 10" src="https://user-images.githubusercontent.com/11817656/47494538-1d110880-d87c-11e8-8a17-5b734acc1161.png">

**95%** of the transactions failed. If I understand correctly, `max_proposal_size: 400` and
`proposal_delay: 5000` means that on receiving >400 transactions *or* after 5s, all transactions will be processed at once. I wonder why first 268 transactions failed already? It should have wait  🤔

![image](https://user-images.githubusercontent.com/11817656/47493844-7841fb80-d87a-11e8-9671-d6eea4c92cb3.png)

**Comment by nickaleks** [comment]
Are you sure your transactions are correct? What is the response status of those transactions?

**Comment by truongnmt** [comment]
Yes I'm sure all transactions are correct. I create random user name so no one has the same name. Here is a sample response:

```
Thread Name: Create user 1-157
Sample Start: 2018-10-25 17:18:54 ICT
Load time: 384
Connect Time: 192
Latency: 384
Size in bytes: 348
Sent bytes:163
Headers size in bytes: 166
Body size in bytes: 182
Sample Count: 1
Error Count: 1
Data type ("text"|"bin"|""): text
Response code: 502
Response message: Bad Gateway


HTTPSampleResult fields:
ContentType: text/html
DataEncoding: null
```

All failed transactions has the same response, 502 Bad gateway.

**Comment by truongnmt** [comment]
Oh I think I figured it out, wait me a second @@

**Comment by truongnmt** [comment]
I think I could solve half of the problem.

> I wonder why first 268 transactions failed already? It should have wait 🤔
![image](https://user-images.githubusercontent.com/11817656/47601251-08f21600-d9f8-11e8-8463-93ee49418d0b.png)

So I inscrease the value of `somaxconn`. Simply put, the `somaxconn` is the maximum number of queued connections we want on a socket. This `somaxconn` specifies how long we want this line to be. If more clients attempt to connect to our server, more than the backlog, those connections will be dropped. 

So I `$ sudo nano /proc/sys/net/core/somaxconn` and increase from 128 to 20000.

**Comment by LiraLemur** [comment]
This is being worked on :) https://jira.hyperledger.org/browse/IR-17 - here's the link

**Comment by truongnmt** [comment]
Appriciated! Keep up the hard work! 💪💪💪
