### ISSUE TITLE
Store and validate events in the block

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#1771]
> The next step would be to add events to the block on leader and for validator peers to validate that events are there (This is needed for Triggers to react to events, as described in the Trigger RFC).

_Originally posted by @eadventurous in https://github.com/hyperledger/iroha/pull/1764#pullrequestreview-841319562_

**Comment by s8sato** [comment]
Speaking only about events emitted __by transaction execution__,
what is the difference between:
- Events are stored to the block and in the next round pull event-based-triggers
- Event-based-triggers are pulled by events converted from transactions in the previous block

I mean, can we store only events emitted __by triggers__?

**Comment by eadventurous** [comment]
For the start I think we can just store the events emitted from the previous block in WSV. And replace this list with each new block. This will let us handle event based Triggers.

**Comment by eadventurous** [comment]
Later optionally we might want to store all events by block in WSV, for example to answer queries like `GetEventsForBlock { height: u32 }`

**Comment by eadventurous** [comment]
I agree that this approach will introduce too much complexity now:
> The next step would be to add events to the block on leader and for validator peers to validate that events are there

**Comment by s8sato** [comment]
I illustrated it as I was a bit confused myself.

![image](https://user-images.githubusercontent.com/49983831/147682722-56b88f6c-a5d8-4cea-9baa-c63d0a5c55ce.png)

The idea of not storing instruction-events is based on the fact that
they can be uniquely derived from a committed block.

Without being stored, instruction-events can pull triggers
by having the execution order switched
and being wired to the following event-based-triggers.

But I wonder if I've overlooked some downsides

**Comment by s8sato** [comment]
If I close this issue, it will be after finding out what to do next

**Comment by s8sato** [comment]
Under cooperating with Event Based Trigger reconsideration #1619

**Comment by s8sato** [comment]
Closed as being addressed in #1874 and its deriving issues
