### ISSUE TITLE
Peers crashed after several hours on longevity stand

### ISSUE THREAD

**Issue by e-ivkov** [hyperledger/iroha#1777]
See #1714 for longevity stand description.
Load: 2 TPS

Peers crashed after approximately 9 hours on longevity stand. The stand script tried to bring them back online after that for a while unsuccessfully - as their block stores were corrupted.

Reason for a crash needs investigation. Logs need to be checked.

**Comment by e-ivkov** [comment]
Crash log for peer 4 - https://drive.google.com/file/d/1Vd_RKeMsBVac2lawfOj8fDKd05pW1mCT/view?usp=sharing

**Comment by e-ivkov** [comment]
It seems that at first something forcefully restarted the peer - making it corrupt the Kura store.

Then after that peer always failed because it could not load the Kura storage.

So the issue that needs investigation is why a peer was restarted, when it has not crashed.

**Comment by e-ivkov** [comment]
Node started at: `2022-01-19T21:47:40.827656Z`
First restart at: `2022-01-20T09:51:13.582132Z`

**Comment by e-ivkov** [comment]
After some investigation and discussion with DevOps we came to conclusion that the first time the peer was restarted due to reaching its memory limit, which was set to 500 MB.

**Comment by e-ivkov** [comment]
![photo_2022-01-21_15-03-27](https://user-images.githubusercontent.com/17401538/150524234-f59a819a-0faa-4278-96f2-78811f3641b0.jpg)

**Comment by e-ivkov** [comment]
The longevity stand was restarted with peers having more memory. But it is worrying that 500MB were used in just 10 hours.

Also as can be seen from the charts, the CPU usage is increasing. This also needs investigation. Probably also needs a separate issue.

**Comment by appetrosyan** [comment]
Unfortunately, the RAM usage is in line with what I measured in the first week of January. The CPU usage increase needs investigation.
