### ISSUE TITLE
Strong typing for socket addresses

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1786]
Currently all socket addresses are stored as strings. This is not ideal, because we don't know if the configuration files should contain the protocol specifier or not. For example, there are many instances in the code, where a string check for presence of `http://` is done, and a format pre-pend. 

We should probably either use one of the `std::net` types, or (better), a custom type that can be converted into the types that we need.

**Comment by appetrosyan** [comment]
Could benefit from https://github.com/rust-lang/rust/issues/82485

**Comment by s8sato** [comment]
I remember I reverted use of `std::net::SocketAddr::V4` because it was not SCALE compatible

**Comment by appetrosyan** [comment]
> I remember I reverted use of std::net::SocketAddr::V4 because it was not SCALE compatible

True. There's also the question of `#[no_std]`. 

The current best solution is to replace the OS-specific implementations of `std::net::SocketAddr` which remain binary-compatible with standard OS-specific networking libraries, with easily convertible replacements, which also reflect the use inside Iroha.
