### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1788]
The test introduced in #1784 demonstrated that creating a million accounts results in average memory usage of 5kiB per account. This is far in excess of what is acceptable for even modest performance requirements, 

We should consider reducing the memory footprint significantly. 

The proposed solution is to use Trait objects in lieu of statically-typed `enum` objects.

**Comment by e-ivkov** [comment]
This issue is especially given https://github.com/hyperledger/iroha/issues/1777

**Comment by mversic** [comment]
might be worth considering: https://github.com/upx/upx
