### ISSUE TITLE
Add CORS support for rest API

### ISSUE THREAD

**Issue by yves-pkstd** [hyperledger/iroha#181]
This issue is related to https://github.com/soramitsu/iroha-demo-javascript/issues/2

Currently http_server_with_cappuccino.cpp does not offer any CORS support.  This means that access from a browser fails because of the CORS preflight check. 

![prelight 1](https://cloud.githubusercontent.com/assets/25895088/23453232/dff58702-feaa-11e6-9d16-1659440e8037.png)

The necessary HTTP header flow:
client:OPTIONS --> Origin --> server
server --> Access-Control-Allow-origin --> client
client:POST -> Origin --> server
server --> Access-Control-Allow-origin --> client

Now I thought I could easily fix this by  adding the following:

```
Cappuccino::route<Cappuccino::Method::OPTIONS>("/account/register", [](std::shared_ptr<Request> request) -> Response {
            auto res = Response(request);
            res.header("Access-Control-Allow-Methods","POST");
            res.header("Access-Control-Allow-Headers","Content-Type");
            res.header("Access-Control-Allow-origin","*");
            res.header("Access-Control-Max-Age","86400");
            res.status(200);
            return res;
        });
```

and add this to the POST handler

`res.header("Access-Control-Allow-origin","*");`

The problem is that there is a bug in the cappuccino web server code:

```
if(context.routes.find(*request->path) != context.routes.end()){
			auto f = context.routes[*request->path].first;
			if(
				context.routes[*request->path].second.find(method_of(*request->method)) !=
				context.routes[*request->path].second.end()
				||
				method_of(*request->method) == Method::HEAD
			){
				return f(move(request));
			}else{
				return Response( 405, "Method Not Allowed", *request->protocol, *request->method, "<h1>Method Not Allowed!</h1>", *request->path);
			}
		}
```

The following code assumes there is only one Method  assigned per path thus making it impossible to fix it.  Either OPTIONS passes or POST passes depending on the order you assigned them.

Now I can fix this as well but if the rest api is going to be canned, then I guess it is not really worth fixing anymore.

**Comment by MizukiSonoko** [comment]
thanks!
please do not worry. 
I will not erase REST (but it will be optional, sorry).
I am truly appreciate your contribution!

**Comment by takemiyamakoto** [comment]
Will you add CORS support?
