### ISSUE TITLE
Add warnings when `iroha` is given unrecognised command-line flags.

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1812]
Currently, the Iroha peer binary ignores the command line flags that are incorrect. Since the number of flags is limited, it should be possible to provide an efficient sanity check for the end user, warning of any unrecognised flags.

**Comment by Lavesh-Saluja** [comment]
can you please tell me how to find this issue in the code

**Comment by appetrosyan** [comment]
Easy. 

The problem is contained inside [`cli/src/main.rs`](https://github.com/hyperledger/iroha/blob/86862ed8937e49bcacc0cce9fd0c878b59021b55/cli/src/main.rs#L11), where the main function sees if the command line arguments match any of the known. 

What you should do is simply check if there are any command line arguments that don't match `--help`, `--submit`, or `--submit-genesis`. We don't use `structopt`, `argh` and/or `clap` for performance reasons, so the code should be contained to that function.
