### ISSUE TITLE
Implement configuration of Log pattern

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#1813]
To ease logs gathering and processing across a set services within a project using Iroha it'd be great to have an opportunity to specify the desired log entry format, including time format, order of parts, custom separators and spaces etc

**Comment by appetrosyan** [comment]
Quick question, do you want this to be specified at compile time, or be a run-time configuration? `tracing` is designed with a very different use-case in mind and is very rigid in terms of what can be done at run-time.
