### ISSUE TITLE
Prevent validated transactions and blocks from being sent between peers

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1868]
Transactions and blocks have lifecycles like:
`Transaction` -> `AcceptedTransaction` -> `ValidTransaction`
`PendingBlock` -> `ChainedBlock` -> `ValidBlock`

only `Transaction` and `PendingBlock` should be allowed to be sent between peers because invariants that are expected to hold true in later parts of the lifecycle cannot be guaranteed (there can be malicious nodes pretending to have performed validation). This means that transaction/block should traverse it's lifecycle only in the context of one peer

Currently, we do this by developers diligence but it would be better if we were to disable these programs from compiling. If there is a proposal or an idea on how to do this it should be discussed before implementation

**Comment by Arjentix** [comment]
So for developer side we can have strongly typed functions.
For security we can allow to deserialize (decode) only `PendingBlock`s.
I can't see a big problem here
