### ISSUE TITLE
Potential network partitioning causes WSV collapse

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#1875]
The scenario was like that:
- Create a network of 4 peers with the single (same) block supplied (genesis). The block includes 'admin' domain and a user in the domain creation. 
- 1 of the peers couldn't start
When submitting a query from the user created within the genesis Iroha returns an error 'domain not found: admin'. Considering there might be a mess with WSV it's even more strange the query is not failed with smth related to the signature failure (assuming the block could be applied entirely only).

**Comment by appetrosyan** [comment]
Need more details.

**Comment by appetrosyan** [comment]
Fixed in DM
