### ISSUE TITLE
Iroha slowed down

### ISSUE THREAD

**Issue by hira000** [hyperledger/iroha#1878]
We executed Create Asset using iroha-Cli and created about 2.88 million assets.
Then, the memory usage sharply increased, the operation of iroha slowed down, making it impossible to continue operation.
At this time, the memory usage seen by ps aux and free was about 90%.
Restarting iroha daemon and Docker did not change the situation, memory was used when daemon was started up, and slow down was reproduced.
If 2.88 million assets are created, is it reasonable that the system will slow down with approximately 8 GB of memory used?

**Comment by hira000** [comment]
The size of the block store is about 2 GB. Even if this is all put in memory, it does not reach 8 GB, so I'd like to know quickly why 8 GB of memory is used and how to avoid using memory.

**Comment by hira000** [comment]
Looking at Valgrind's output, most seems to be a memory reference by google:protobuf.
It may be a problem of protobuf.
I'd like to check the version of protobuf, but I do not know how. How can I check the version?
It seems to be reproduced in many environments if the protobuf in Docker is due to the old, but has anyone recreated similar events?

[valgrind_memcheck_02_has_0100_account_data.log](https://github.com/hyperledger/iroha/files/2622626/valgrind_memcheck_02_has_0100_account_data.log)

**Comment by LiraLemur** [comment]
Moved the issue to Jira: https://jira.hyperledger.org/browse/IR-200
