### ISSUE TITLE
Remove sample configs from the Docker container

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#1883]
> Aleksandr Petrosyan, [2022/02/08 15:19]
> Another point that Bogdan raised is that we should stop including default configuration files inside containers. People boot up the container, see no error messages, assume everything is fine, when it isn't.
> 
> S Sato, [2022/02/08 16:30]
> [In reply to Aleksandr Petrosyan]
> The following would be one of the solutions:
> - Convert config.json to sample.env
> - Specify env_file: peer0.env .. for each peer in docker-compose.yml
> - Direct users to edit and rename sample.env and use docker compose
> https://docs.docker.com/compose/environment-variables/
> 
> S Sato, [2022/02/08 16:42]
> [In reply to S Sato]
> Not so much difference from directly writing environment section as current though
> 
> Aleksandr Petrosyan, [2022/02/08 16:42]
> [In reply to S Sato]
> This is a simplification, however.
> 
> Aleksandr Petrosyan, [2022/02/08 16:43]
> If we can reduce the number of places where Iroha can be configured to just one, I don’t see an issue.
> 
> S Sato, [2022/02/08 16:57]
> [In reply to Aleksandr Petrosyan]
> Yes, at least we can merge peer/config.json into environment variables,
> but instead, iroha_config will have to have dotenv

**Comment by dmitrivenger** [comment]
@appetrosyan please change the title

**Comment by appetrosyan** [comment]
Done
