### ISSUE TITLE
Add complete IPFS path validation

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#1885]
Complete validation requires checking if path is composed only from valid hashes

[ipfs](https://docs.rs/ipfs/latest/ipfs/) crate source code can be helpfull

##  Alternative implementations

https://github.com/hyperledger/iroha/issues/1606

**Comment by appetrosyan** [comment]
I think we should re-visit this in the Blockchain explorer context. I'll add the relevant issue to the board, and re-assign work.

**Comment by appetrosyan** [comment]
Closed in favour of https://github.com/soramitsu/iroha2-block-explorer-backend/issues/20
