### ISSUE TITLE
Wasm smartcontract execution time

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1888]
It seems that wasm smartcontract takes about 30sec to execute. This should be investigated as it's absurdly too large. It's possible this is related to block wait time as defined in configuration

**Comment by mversic** [comment]
When executed through integration tests it takes 10sec which is the amount of time we wait for execution to finish. This indicates that most of the execution was due to some configuration limit (maybe `block_wait_time`). More measurement is required

**Comment by mversic** [comment]
To precompile module [precompile_module](https://docs.rs/wasmtime/latest/wasmtime/struct.Engine.html#method.precompile_module) can be used and deserialized afterwards with [Module::deserialize](https://docs.rs/wasmtime/latest/wasmtime/struct.Module.html#method.deserialize)

**Comment by mversic** [comment]
Iroha is built with LTO which produces a more optimized build of wasmtime which is then able to compile wasm binaries faster

**Comment by appetrosyan** [comment]
During discussion we found that execution time is acceptable after merging PRs TODO.
