### ISSUE TITLE
Introduce integration tests for Event-triggers based on Orillion use-cases

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1890]

**Comment by Arjentix** [comment]
Use-cases provided by Orillion devs:

1. Mint asset after transaction commmit with new (other) asset with metadata
2. Creating NFT (Store asset) with metadata for every user based on queries every set period of time
3. Precommit trigger meaning quantitative restriction for operation
4. Trigger that should change token metadata once after some time passed

**Comment by appetrosyan** [comment]
2 is blocked by #1984 .

**Comment by Arjentix** [comment]
3 is blocked by #2037

**Comment by Arjentix** [comment]
2 will  be done in #2099
