### ISSUE TITLE
Refactor event emission

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1892]
Currently events are emitted in multiple places, and not properly controlled by the WSV. This means that if multiple sources of events could exist, (e.g. internal execution of WASM blob using a customised version of ISI, it's possible to not emit any events at all. 

We should both scope events to domains, and propagate them to the WSV, such that they can be handled by both scoped and global triggers, before being sent to their external listeners.

**Comment by mversic** [comment]
@Arjentix [here](https://github.com/mversic/iroha/tree/execute_associated_type) is some work I've been doing on this. Maybe it helps you
