### ISSUE TITLE
Error: Transaction should contain at least one command Wrongly formed creator_account_id, passed value: ''

### ISSUE THREAD

**Issue by samanshahmohamadi** [hyperledger/iroha#1906]
Hi
I am trying to write a web application interface for iroha network. I used java example code to implement a java service. The problem is every transaction fails with `STATELESS_VALIDATION_FAILED` status.    
In response I get an error message, but could not find the problem behind it.
This is the error:
```
Transaction: [[Transaction should contain at least one command Wrongly formed creator_account_id, passed value: ''. Field should match regex '[a-z_0-9]{1,32}\@([a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?' bad timestamp: too old, timestamp: 0, now: 1543929881030 Quorum should be within range (0, 128] ]]
```
You can find the controller and service code [here](https://gist.github.com/samanshahmohamadi/256f40b618b77f2d5a89dbcf27ef8585).

**Comment by LiraLemur** [comment]
Please try to use a new version of Iroha from master branch (we've had some pretty great changes there!) 
If the issue remains, please contact us here: https://chat.hyperledger.org/channel/iroha
