### ISSUE TITLE
Processing queries depends on the number of assets present

### ISSUE THREAD

**Issue by hira000** [hyperledger/iroha#1918]
If the number of assets created is large, the execution time of the query is delayed and the CPU usage rate is rising as follows.
Is this reasonable? Does Iroha's ability to process queries depend on the number of assets?

What I did:
1. As a result of issuing queries (get_acc_ast) with 10 multiplexes in an environment where few assets were created, processing was completed in 7 seconds. The CPU usage rate was about 50%.
2. As a result of executing the same processing as 1 in an environment where about 14,400 assets were created, the processing was completed in 43 seconds. The CPU utilization was about 90%.

**Comment by LiraLemur** [comment]
Moved the issue to Jira: https://jira.hyperledger.org/browse/IR-201

It would also be great if you could contact us in our chatroom and tell us more about your research and experience: https://chat.hyperledger.org/channel/iroha
