### ISSUE TITLE
Replace SCALE codec for wasm serialization

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1929]
Remove the statically linked SCALE codec from inside the WASM binary. 

Relates to the [following](https://github.com/hyperledger/iroha/issues/1887#issuecomment-1043606262) part of #1887

**Comment by mversic** [comment]
While this is an interesting idea, it's not without some inherent problems. What I wanted initially was to have `Instruction` and `QueryBox` laid out in memory in a deterministic way that would be portable between rust compiler versions but across different languages so as to avoid the need for serialization (we could say that memory layout of the structures coincides with their serialization format - essentially ABI). There are ways to achieve [stable ABI](https://docs.rs/abi_stable/latest/abi_stable/) when doing Rust to Rust FFI. 

1. For stable ABI across different programming languages 1st there is an option to use C ABI. This sounds like a tempting solution, but the issue are structures like `Vec`, `String` and `BTreeMap` which are not controlled by us and don't have `repr(C)` representation. Also, there is an issue that we sometimes use `smallvec` and `smallstr` which also don't have `repr(C)`. This indicates that some form of serialization is due. Some serialization possibilities:
1. force memory layout of `Instruction`/`QueryBox` to adhere to C ABI. This means to make our own `repr(C)` versions of `BTreeMap` and alike([safer-ffi](https://docs.rs/safer-ffi/0.0.6/safer_ffi/)). I don't consider this a viable solution
2. using opaque pointers - client can never access elements of structures directly, only through functions receiving opaque pointers to structures. Layout of structures is irrelevant in this case. Also, we can make some sort of facade around exported functions. This is often the approach taken when doing FFI
3. separate FFI structs - every structure that will participate in FFI, even though it doesn't have stable ABI, should be able to transform itself into C ABI representation

2. Another possibility for stable ABI across languages is using [flatbuffers](https://google.github.io/flatbuffers/) which should have a very small code size footprint and may be even more portable than C ABI.

**Comment by appetrosyan** [comment]
As of #1826, `smallvec` and `smallstr` are encoded and decoded as `Vec` and `String`. So we only need to worry about the standard library types.

**Comment by mversic** [comment]
I'm closing this issue in favor of #2062
