### ISSUE TITLE
`FindAllParameters` unusable

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1966]
Since `ValidQuery` is not implemented for `FindAllParameters` it's not possible to execute this query. Either this query should be removed entirely or it should be enlisted in the `QueryBox` enum

**Comment by abhijeetjejurkar** [comment]
Hey, I am from Openforce 2022, I would like to work on this issue.

**Comment by mversic** [comment]
@appetrosyan I guess we should support this query? not remove it

**Comment by appetrosyan** [comment]
If neither Unkai nor Orillion use it, I would vote for removal. @Mingela do you think that such a query might be useful in the future?

**Comment by appetrosyan** [comment]
@abhijeetjejurkar while you're free to choose what issue you work on, issues that are particularly easy to fix by people outside the core development team (and often higher priority are unassigned and marked with the "good first issue" tag. 

If you like, we could arrange a small introduction and give you an overview of the issues that would be higher priority for Iroha, and more self-contained.

**Comment by abhijeetjejurkar** [comment]
Yes please give me overview of issues which can be solved by me, I would like to work with your community 😊. I will search and work for such high priority issues.

**Comment by appetrosyan** [comment]
Thank you, it's much appreciated.

To get started, you should look at good first issues and on our board, issues in the Chores categories that aren't assigned to anyone. These are small self-contained modifications that do not interfere with our roadmap. 

Be sure to read our contributing guide, particularly to use the rebase workflow, and follow our commit conventions: square brackets, category, #issue number: description  

https://app.zenhub.com/workspaces/iroha-v2-60ddb820813b9100181fc060/board?repos=181739240

**Comment by abhijeetjejurkar** [comment]
Sure👍, Thankyou 😊

**Comment by mversic** [comment]
@Mingela any thoughts on this?

**Comment by appetrosyan** [comment]
The `FindAllParameters` query is messed up. Instead of being tied to the configuration struct and returning a structure based off of configuration, it instead returns something known as `Parameter`. Instead of being a struct containing all of the publicly available fields, it instead is an enum. 

There needs to be more work done on this query before it can be made available publicly.

**Comment by dmitrivenger** [comment]
Closing the issue now. The feature is relevant now. 
@appetrosyan and @astrokov7
