### ISSUE TITLE
Improve `core/docs`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1968]
This is a meta-issue tracking the potential improvements to `iroha_core/docs` and the possibility of removing the explicit binary.

**Comment by appetrosyan** [comment]
@mversic @s8sato @Arjentix , I'd be interested to hear what you have to say.

**Comment by Arjentix** [comment]
I've noticed, that `client` configuration parameters (fields in `config.json`) isn't described anywhere outside code. By looking at `core/docs` code I can see, that any `Configurable` thing can generate documentation. Can we adopt `core/docs` to generate such docs as well?

**Comment by s8sato** [comment]
I don't think we can remove it unless we have an alternative
