### ISSUE TITLE
Replace `blocks()` with `visit_blocks()` in WSV

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#1974]
Right now `WorldStateView::blocks()` has locking behaviour if user stores somewhere an iterator from this function. This can be fixed by replacing it with `visit_blocks()` function, which looks something like this:

```rust
/// Visit and apply `f` for every block
///
/// # Errors
/// Throws up first `f` error
pub fn visit_blocks<F>(&self, f: F) -> Result<(), Error>
where
    F: Fn(&VersionedCommittedBlock) -> Result<(), Error>,
```

In this way user can't store reference to a block, cause it is passed as a function parameter and **Rust** won't allow to save references like that

**Comment by Arjentix** [comment]
Now I think, that returning generic `R` instead of `Result<(), Error>` is better, cause we don't know the way user will use it

**Comment by SamHSmith** [comment]
When implementing pr #2140 I didn't find that there was a particular need for something like this. If we do at a later point find that we do want this kind of api it can be implemented on the spot. If we do so in many places we can move it into the `LockedChainViewer`.
