### ISSUE TITLE
Make automatic doc generator note optional features inside the documentation. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1975]
When generated with `iroha_docs`, `config.md` can contain information about optional features. We want to make the addition of those features optional too, so that distribution packagers can remove the flags that they don't need, but by default if you just cloned the repository, you should be shown all of the optional features, explained how to use them and all of that be included in the docs.

**Comment by s8sato** [comment]
If we had some [Build Scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to generate the doc with the build, the features would be synchronized between the doc and the distribution

**Comment by appetrosyan** [comment]
We have decided that configuration options should never be feature gated.
