### ISSUE TITLE
Improve the EventFilter API

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1981]
Currently any user of the `EventFilter` API needs to retain in their head the entire hierarchy of events and their relationships. This is extremely cumbersome, especially given that we have the `FilterOpt` structure, which is not the same as `Option`.

**Comment by mversic** [comment]
likely related to #3068. @DCNick3 please consider it

**Comment by mversic** [comment]
likely related to #3068. @DCNick3 please consider it
