### ISSUE TITLE
CMake Design for Faster Build Times 

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha#1985]
# CMake usage

## Introduction

CMake is the build system used in Hyperledger Iroha. It is a complex system, with no single way to achieve the desired result. Some ways are newer and more preferable, however a lot of options that CMake provides have different trade offs and it is not clear which one to use.

The aim of this document is to analyze what methods of organizing the project exist, and which one achieves our goals, which are: fast build and separation of components from each other.

## Build performance measurement

Any discussion of build time without measurement is meaningless. In this case we are interested in build time of the whole project. Simple measurement can be obtained with time utility like this:

```gtime -f "%S\t%U" cmake --build build --target -- -j6 > /dev/null```

This will output system and user time of the build.
Notice that gtime is OS X specific. For Linux use /usr/bin/time (not builtin time!)

Of course, ccache must be disabled for the measurement since we are interested in compilation from scratch.

How precise is this measurement? Running this script 10 times and then counting average build time on a Macbook yields standard deviation of the measurement around 1%. This means that this method is precise enough to be used. We should consider incorporating it into our CI.

## Project Structure

Projects are organized in subdirectories with source files separated into physical components. The question is how to organize CMake to build these components

### Single Library

This approach consists of adding all source files of the project, into a single library, and then linking that library to an executable or tests.

This has several advantages:
* Less linking required
* No dependencies between libraries, which means more parallelism

However there are severe disadvantages to this method:
* CMake file gets big
* Every executable must be linked with the whole library
* Every time change occurs, whole library must be relinked
* Configuration cannot be different for different modules

This approach is used by a lot of projects, one of the examples is RocksDB database.

https://github.com/facebook/rocksdb/blob/da1c64b6e75048068bf8599f198b8fe0e54eedfc/CMakeLists.txt#L462 - RocksDB CMakelists.txt where sources are defined.

### Multiple Libraries

This approach constructs each module as a separate library, which are then linked together for the final executable.

Advantages:
* Libraries can be defined in their own directories CMakeLists.
* Tests only need to link with required libraries.
* Each library can have its own configuration (defines, compile options)

Disadvantages:
* More linking required
* More space for build directory

https://github.com/ethereum/aleth/blob/master/CMakeLists.txt - Ethereum C++ Client

### Difference in build time

In both cases, you must compile all object files for the resulting executable. So there is no difference in compilation time. However single library requires only linking a single library and then linking it to each executable. The multiple libraries option requires a lot more linking.

The total build time depends on how slow is the linking of the libraries. Usually linking is a just a fraction of compilation time.

### What to use in Iroha

Currently iroha is built as a set of libraries which are then linked into irohad executable and various tests. The impact of this on a performance is not very clear, and we have to measure link and compile time to get the picture of where most of the build time is spent.

If we want to reduce link time, it could be more beneficial to create a single target for all source files, and then add all executables to it. This however may be problematic since now we cannot separately configure concrete parts of the system.

## Test Organization

How to organize tests is an important question, since usually test code is bigger than application code. The general question is how granular test executables must be. We might have a single binary with all the tests from the whole project, executable for one module or one executable for each test file.

When we have single binary for a test, we must build everything in order to run a single test. However this compilation must only be done once, and all subsequent recompiles are as cheap as the other options.

On the other hand, having many executables increases total size of the build files, and as in the case with multiple libraries, more linking needs to be done.

At the moment, almost each test file is compiled into a separate executable. This leads to about 100+ executables being generated, all of which statically link necessary components. This leads to a huge code duplication, and a large amount of linking required.

To mitigate that, we can reorganize tests to have a single executable per module. This would lead to faster build time, less space wasted. However this might make it harder to profile tests execution time, since they will be joined together and hard to separate.

To do that reorganization, some code changes must be done in addition to CMake rewrite. One of the issues that I have encountered trying to do that, is the fact that a lot of functions in header files used in tests are not declared inline, which leads to link errors because of duplicate symbols. This is easily solvable, but may slow down the refactoring.

## Possible Build Optimizations

Now that we've seen basic information about project structure, we need to examine CMake and C++ specific options which can improve build time of the project.

### Unity build

Unity build is a C++ "technique" to improve compile times. It involves combining all .cpp files into a single big file, which is then compiled only once.

This has a huge impact on the performance of the compilation for several reasons:
* file IO is drastically reduced single every header is included only once.
* Every template is instantiated only once.

However unity build has major drawbacks, which prevent it from being just a drop-in solution:
* Every symbol must be unique, since they will all end up in the same file.
* Memory usage during compilation may increase significantly, since the whole combined file is compiled at once.

Effect of compilation speed varies, depending on the project and has to be tested.

Unity build can break correct code, for example when the same symbol is declared in separate files. This means that if we want to implement this thing for iroha, some substantial refactoring might be required.

Cotire plugin for cmake can create unity build targets by itself, and we should try that and see the benefit.

https://buffered.io/posts/the-magic-of-unity-builds/ - about unity builds

Also as an example of Unity build we can check out Ripple project:

https://github.com/ripple/rippled/blob/96c949a99791fdd077b091f682139a050cd1034b/CMakeLists.txt#L1331

### Precompiled Headers

Precompiled headers does not solve problem of the clean build (for example for CI), however for development, they can significantly speed up the build. The idea is to precompile headers that rarely change (such as third party or standard library), and then use these precompiled headers when compiling targets. This significantly improves compilation time. However it has some limitations, such as only one header for a source file can be precompiled.

Both unity build and precompiled headers techniques are supported in cmake by cotire plugin.

https://github.com/sakra/cotire

Precompiled headers require us to carefully separate rarely changed header files into a separate header, which then gets included everywhere. Cotire seems to be able to extract 3rd party headers into a precompiled header, which needs to be checked for iroha project.

https://clang.llvm.org/docs/UsersManual.html#usersmanual-precompiled-headers - CLang user manual precompiled headers

### Modules Isolation

Even though performance is an important factor, we must consider also correctness of build configuration. To ensure that, modules must be as isolated as possible, to prevent unwanted dependencies. One of the big issues in this regardis isolation of header files. Currently, I can include every header from irohad into every file. This means that dependencies are not transparent, since we do not state in CMake, that this module depends on other module, even though I can include header file from that module.

This happens because we define global include_directories() for the whole irohad directory. This issue can be mitigated, if each library defines its own include directories. The drawback of that, with current directory layout we would have to change include paths, for example "ametsuchi/storage.hpp" will become "storage.hpp" etc. Whether or not that is a good thing, is a subject of discussion.

## Conclusion

As a main thing, I would like to get total build time statistics into CI as soon as possible.

As it stands, the easiest thing we can do to improve build times, is to reduce number of test executables. All other changes need to be investigated, since they may require some substantial refactoring.

As for the project structure, combining all components into a single library seems to present more issues than benefits, considering that the link time is not substantial part of the build.

**Comment by Warchant** [comment]
>If we want to reduce link time, it could be more beneficial to create a single target for all source files, and then add all executables to it. This however may be problematic since now we cannot separately configure concrete parts of the system.

if you do this, you will slow down average compilation time, because single change will lead to the full recompilation

**Comment by nickaleks** [comment]
> if you do this, you will slow down average compilation time, because single change will lead to the full recompilation
Not really, since only the changed file will be recompiled.

**Comment by LiraLemur** [comment]
Moved to Jira: https://jira.hyperledger.org/browse/IR-202
