### ISSUE TITLE
Reduce size of `Name` struct

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1985]
`Name` is a `repr(transparent)` struct wrapping `std::string::String`, which has a pointer, a length and a capacity. 

However, in most cases a name isn't modified, but instead, a new name is created. So in theory we could get rid of `capacity`, as we don't intend for the `Name` struct to be mutable (there isn't a single mutable borrow or mutable `Name` in the code-base). 

So we should investigate either using `std::str::str` or creating a custom structure for storing `Name`s

**Comment by Arjentix** [comment]
I think we can do something like `ConstantString` and implement `impl From<ConstantString> for String` to give possibility to act with it as basic a `String`.

Also right now `Name::new()` accepts `&str` but allocates memory for `String` inside it. AFAIK Rust convention is to let user decide when to allocate memory. So I think a new constructor should be: `pub fn new(name: ConstantString)`.
If we really want to create `Name` from `&str`, then we can use `FromStr::from_str()` or create `Name::from()` as it is done for `std::str::String`

**Comment by appetrosyan** [comment]
I largely agree, but I have a few comments: 

> I think we can do something like `ConstantString` and implement `impl From<ConstantString> for String` to give possibility to act with it as basic a String.

Only if necessary. The way I see it, a `ConstantString` should only implement `Deref` to a string slice. Most functions we're interested in take a slice anyway. 

> Also right now Name::new() accepts &str but allocates memory for String inside it…

We could try that. IMO it should really be `FromStr::parse`, because we raise a `ParseError`.

**Comment by mversic** [comment]
`Name::new` is out the window with #1984 

If we'll consider interning of common immutable objects as in #2008, which would save us a lot more memory space compared to removing capacity `usize`, this should become a much more low priority issue

**Comment by mversic** [comment]
[This](https://github.com/nu11ptr/flexstr) seems like an interesting and highly maintained crate
