### ISSUE TITLE
`PartialEq` and `PartialOrd` of `Identifiable` structures 

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1988]
Identifiable structures, such as `Domain`, derive their implementation of `PartialEq`, but have the following implementation of `PartialOrd`:
```rs
impl PartialOrd for Domain {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.id().cmp(&other.id))
    }
}
```

Would it make sense to have equivalent implementation of `PartialEq` instead of deriving it?
Other `Identifiable` structures should be considered as well

**Comment by appetrosyan** [comment]
What do you think about a blanket implementation for all identifiables?

**Comment by appetrosyan** [comment]
Blanket `impl` would not work as well as I hoped. `PartialOrd` is a foreign trait, meaning that in order for `impl <T:Identifiable> PartialOrd for T` to work the `Identifiable` trait should be made private. This in and of itself wouldn't be a problem, but for the `data_model` restructuring to work, we'd also need to make every implementer of `Identifiable` foreign, so the orphan rule prevents a blanket impl from working as intended. 

Kind of a workaround would be to make `Identifiable` object-safe, and implement for `dyn Identifiable`, but that is sub-optimal.

**Comment by mversic** [comment]
> What do you think about a custom proc-macro, that derives Identifiable, Ord, Eq, Hash and enforces that all implementations are compliant?

sure, but why not a declarative macro? I find them way easier to both implement and read and this should be a very simple macro

actually, our current implementation could be buggy as per [PartialEq documentation](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html):
>If [PartialOrd](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) or [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) are also implemented for Self and Rhs, their methods must also be consistent with PartialEq (see the documentation of those traits for the exact requirements). It’s easy to accidentally make them disagree by deriving some of the traits and manually implementing others.

**Comment by appetrosyan** [comment]
> sure, but why not a declarative macro? I find them way easier to both implement and read and this should be a very simple macro

We don't have to choose. 

https://crates.io/crates/macro_rules_attribute
