### ISSUE TITLE
Add proper IPFS logo mutator

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1994]

**Comment by mversic** [comment]
Should logo be allowed to be constructed with `NewDomain` if it can be mutated with instructions?

**Comment by appetrosyan** [comment]
I think we should be able to mutate the logo with an instruction, I'm just not too keen on adding an instruction just to edit the logo.

**Comment by mversic** [comment]
would be irrelevant if we make `logo` as metadata value

**Comment by mversic** [comment]
let's change the scope of this ticket to make `logo` a metadata value, not a field in the `Domain` struct

**Comment by mversic** [comment]
closed in favor of #4230
