### ISSUE TITLE
Move `GenesisDomain` and `GenesisAccount` to `iroha_core`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#1996]
Currently, genesis domain and account are in `iroha_data_model`. It is my understanding that they are only used in `iroha_core` and should in fact not be presented to the user through data model API. Therefore, they should be moved into `iroha_core`

**Comment by appetrosyan** [comment]
A discussion we had, meant that the overwhelming majority of the Iroha 2 team would prefer to move to a domain-first approach, where there would be a separate crate for `genesis`-related work.
