### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by LiraLemur** [hyperledger/iroha#2]
Does the bot works correctly?

**Comment by igor-egorov** [comment]
What are the test results?

**Comment by LiraLemur** [comment]
As you can see, it is still there. I've created a ticket, hopefully webhooks will be fixed. 
If this issue is bothering you in any way, please close it

**Comment by igor-egorov** [comment]
Thanks. It is fine. I don't know where to look for bot's processing results. :(

**Comment by LiraLemur** [comment]
It would say something like "your issue is transferred to Jira" etc
