### ISSUE TITLE
Example fails with Failed to parse genesis block

### ISSUE THREAD

**Issue by martin-lizner** [hyperledger/iroha#2000]
Hi, I have followed example scenario as described here https://iroha.readthedocs.io/en/latest/getting_started/index.html

but got error at this command:

root@139e1e28c6d2:/opt/iroha_data# irohad --config config.docker --genesis_block genesis.block --keypair_name node0
NOTICE:  relation "role" already exists, skipping
NOTICE:  relation "domain" already exists, skipping
NOTICE:  relation "signatory" already exists, skipping
NOTICE:  relation "account" already exists, skipping
NOTICE:  relation "account_has_signatory" already exists, skipping
NOTICE:  relation "peer" already exists, skipping
NOTICE:  relation "asset" already exists, skipping
NOTICE:  relation "account_has_asset" already exists, skipping
NOTICE:  relation "role_has_permissions" already exists, skipping
NOTICE:  relation "account_has_roles" already exists, skipping
NOTICE:  relation "account_has_grantable_permissions" already exists, skipping
NOTICE:  relation "position_by_hash" already exists, skipping
NOTICE:  relation "tx_status_by_hash" already exists, skipping
NOTICE:  relation "height_by_account_set" already exists, skipping
NOTICE:  relation "index_by_creator_height" already exists, skipping
NOTICE:  relation "position_by_account_asset" already exists, skipping
[2018-12-28 13:28:26.670812900][th:265][error] MAIN Failed to parse genesis block.

The genesis file is from git develop branch and docker image is hyperledger/iroha:develop.

Thank you for helping me.

**Comment by richhildyard** [comment]
Same issue here. Martin, did you find a solution?

**Comment by laSinteZ** [comment]
@martin-lizner @richhildyard try using genesis block from [dev](https://github.com/hyperledger/iroha/tree/dev) branch, not develop.

I guess guys still didn't fix problems with develop/dev branch and we should update our docs :)

**Comment by richhildyard** [comment]
Thank you.
I had a problem with the private keys not matching just using the dev genesis block, but if I changed the existing block to match the dev branch at the bottom of the file to:   "prevBlockHash": 00000000000000000000000000000000000000000000000000000000000000000"
then removed the existing containers and volume and rebuilt, everything came together.

**Comment by LiraLemur** [comment]
I changed develop to master in docs, so should not be an issue now. 
Happy to hear everything worked out fine!

If you still have any questions, please contact us here: https://chat.hyperledger.org/channel/iroha
