### ISSUE TITLE
Parity Scale decoder tool

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2003]
We need a tool that given a binary string and a type, attempts to decode the binary string according to the type. This should be used as a reference for SDKs as well as in debugging incompatibility issues.

**Comment by mversic** [comment]
if it's an external tool maybe it would make sense to have both `--scale` and `--json` flags? Though json format is human readable

**Comment by Arjentix** [comment]
Not sure if we should have a flag for this, cause this tool can guess is it scale format or json. Anyway let's move json feature into another issue? This one already has a lot of code
