### ISSUE TITLE
Compile time checking for architecture dependent types on serialized structures

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#2004]
It would be useful to have compile time checks that ensure our serialized and deserialized types are identical across architectures so that we don't reintroduce fields containing eg usize/isize in future.

**Comment by mversic** [comment]
We should also add a runtime test which would traverse the schema map and make that no pointer sized type is encountered. This is necessary to guard against faulty manual implementations. Compile test can be added to make sure that there is no pointer sized types in derived implementation
