### ISSUE TITLE
Grant and revoke role emit `PermissionAdded`/`PermissionRemoved` events

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2007]
take a look at `smartcontracts/isi/account.rs` implementation of `Execute` for grant/revoke of `Role` and you will see that permission events are returned for granting and revoking both roles and permission tokens. Is this fine?

Also `PermissionRemoved` event is emitted in `Unregister<Role>` in `smartcontracts/isi/domain.rs`

**Comment by omkar-mohanty** [comment]
Hi can I take this issue?

**Comment by omkar-mohanty** [comment]
Roles are a collection of permissions so when we `Grant/Revoke` a role it's okay to emit `Permission` events although it is a bit misleading. It would be better to emit `RoleGranted/RoleRemoved` imo as it would give more accurate information to the user.

**Comment by appetrosyan** [comment]
Closed as discussion is complete.
