### ISSUE TITLE
Interning of common immutable objects

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2008]
[Intering](https://en.m.wikipedia.org/wiki/Interning_(computer_science)) is a technique to reuse objects which are created often. This reduces memory footprint while the expected effect on performance should remain negligible.

In Iroha it would make sense to intern `Identifiable::Id`s like `DomainId`, `AccountId`, `Assetaid`, etc. If you know of other examples that would benefit from interning please name them in this issue.

There could be a library offering this functionality, if not, it can be implemented

**Comment by appetrosyan** [comment]
https://dev.to/cad97/string-interners-in-rust-797

There's a bit more research that needs to be done. Since most of our operations are hash-table related unless we have many collisions, interning might hurt us more than help.

**Comment by mversic** [comment]
just to be clear, I'm not proposing interning of all strings, just interning of object Ids.

**Comment by mversic** [comment]
as far as the library is concerned [internment](https://github.com/droundy/internment) seems to be the best choice. There is also a fork of `internment` [arc-interner](https://github.com/ryzhyk/arc-interner) which doesn't seem to have the same momentum

**Comment by s8sato** [comment]
The followings might have something to do with not having duplicate ids between layers:
https://wiki.hyperledger.org/display/iroha/Merkle-zation+World+State
https://docs.substrate.io/v3/advanced/storage/

**Comment by appetrosyan** [comment]
During a discussion with @ilchu we concluded that after merging of #1985 interning of objects alone might not provide us with memory savings. 

For 95% of all strings we went from 24 bytes + actual string to 15 bytes + 1 byte in RAM usage. 

Interning can save us on allocation overhead (which we should benchmark), but that isn't much in the grand scheme of things. 

We should consider restricting the numbers of objects that we can have nested withing `Domain`, `Account`, etc. For example, if we require that there can only be 4bn accounts in a domain and 4bn domains, we can reduce the size of `<account as Identifiable>::Id` from `2*2*usize` to `usize`, plus the actual storage of the associated strings. As you can probably see, this only makes sense for things that are likely to be repeated.

**Comment by ilchu** [comment]
Closing this and the related draft PR due to reasons stated above by @appetrosyan.
