### ISSUE TITLE
Excessive Platform Resource Consumption within a Loop in Kubernetes

### ISSUE THREAD

**Issue by bhaskarvilles** [hyperledger/iroha#2010]
Package ```(gopkg.in/yaml.v2)```  (Go) ```< 2.2.8```

The Kubernetes API Server component in versions ```1.1-1.14```, and versions prior to ```1.15.10, 1.16.7 and 1.17.3``` allows an authorized user who sends malicious YAML payloads to cause the kube-apiserver to consume excessive CPU cycles while parsing YAML.

**Comment by appetrosyan** [comment]
Hi, can you please provide more details? For example, does this relate to Iroha 1, or the (in-development) version of Iroha 2? Steps to reproduce?

**Comment by appetrosyan** [comment]
No details provided, likely Iroha 1, therefore closing
