### ISSUE TITLE
Design implementation-agnostic data model schema

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2021]
## Problems

Current data-model problems:

- Has a lot of duplications of the same types, e.g. `EvaluatesTo<xxx>` that is always, from the codec side, always contains just an `Expression`.
 
- Has non-normalized type names, including noise such as module paths.

  Why normalization matters?

  For example, there are a plenty of `Id` types, but in different scopes:

  - `iroha_data_model::peer::Id`
  - `iroha_data_model::asset::Id`
  - `iroha_data_model::trigger::Id`
  
  It produces questions for SDK developer: how should I keep this format, and should I? Or should I try to use the same module-based approach to structure generated code? But it's not really possible due to specifics of my language in particular... If not keep same names, then normalize them, but in which way exactly? `PeerId`, `DataModelPeerId`, `ModelPeerId`?.. How should it be documented for the end user that, e.g., came from other SDK and familiar to some other format? How to synchronize SDKs in terms of type names?

  **upd**: even in Iroha itself names are normalized under `iroha_data_model::prelude` scope!

- Fragile. There are too many implementation specific details.

## Wishes

- **Make implementation-agnostic schema that is a source of truth for both Iroha and SDKs**. Make it just a pure SCALE namespace schema as much as possible.
- Remove duplicated types
- Simplify type names and **fit them into a single namespace** (i.e. normalize names)

**Comment by 0x009922** [comment]
May be also related here: https://github.com/hyperledger/iroha/issues/2020

**Comment by 0x009922** [comment]
Related: #3535

**Comment by 0x009922** [comment]
BTW: https://github.com/stepchowfun/typical

It is an example of schema-first design with versioning support. Supports Rust and TypeScript atm.

**Comment by mversic** [comment]
this has been taken care of in #3268
