### ISSUE TITLE
StorageImpl prepared block are not enabled

### ISSUE THREAD

**Issue by aleksandrovych** [hyperledger/iroha#2059]
What should I do to fix this warning, also what does this warning mean?

**Comment by l4l** [comment]
Most of the postgresql queries to the WSV are prepared statement. And afaik postgresql by default doesn't enable it support. You need to specify postgres parameter `max_prepared_transactions=100`, or if you're using docker: `docker run -d postgres:9.5 -c 'max_prepared_transactions=100'`.
You may check, that it was properly set by executing `SHOW max_prepared_transactions;` sql query.
