### ISSUE TITLE
Debug register peer failing

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2060]
### MWE: 
1. Start a fresh BFT network

```bash
./scripts/test_env.sh setup
```

2. Create a new peer 
```bash
TORII_P2P_ADDR="127.0.0.1:1341" TORII_API_URL="127.0.0.1:8084" TORII_TELEMETRY_URL="127.0.0.1:8184" IROHA_PUBLIC_KEY="ed01206a7b60c110099ad641488ae9c4b3175ce93173d4e2b8ea9dc154314e0d33a637" IROHA_PRIVATE_KEY="{ \"digest_function\": \"ed25519\", \"payload\": \"e4cd89f6b8a59a973d1d65df19a4d154de9e7cffdadc39e1dc09777ac56734876a7b60c110099ad641488ae9c4b3175ce93173d4e2b8ea9dc154314e0d33a637\" }" SUMERAGI_TRUSTED_PEERS='[{ "address": "127.0.0.1:1341", "public_key": "ed01206a7b60c110099ad641488ae9c4b3175ce93173d4e2b8ea9dc154314e0d33a637"}]' ./iroha
```

3. Register peer 
```bash
./iroha_client_cli peer register --address 127.0.0.1:1341 --key ed01206a7b60c110099ad641488ae9c4b3175ce93173d4e2b8ea9dc154314e0d33a637
```

### Expected behaviour

Peer is added to the network and everything works. 

### Actual behaviour
Peer is listed as a trusted peer, however the actor system raises multiple errors, and the peer is neither function nor can be unregistered

![image.png](https://images.zenhubusercontent.com/615ecfcf34e89aca674dc2ac/b2c3cc63-d860-40a8-976c-d46e3605c05a)

**Comment by QuentinI** [comment]
Invalid as described [here](https://github.com/hyperledger/iroha/issues/2043#issuecomment-1156795576) and [here](https://github.com/hyperledger/iroha/issues/2385#issuecomment-1166997002) .
