### ISSUE TITLE
Synchronize Ledger

### ISSUE THREAD

**Issue by satellitex** [hyperledger/iroha#207]
# TODO: Synchronize Ledger

All peers must have the same Transactions in the same order.

**Comment by satellitex** [comment]
# Synchronize Blocks Flow ( WIP )
https://docs.google.com/a/soramitsu.co.jp/presentation/d/1Yz5_CZ8osPLY6NpGE6SrlXFXQLv6vWIeEjqjjDb21e8/edit?usp=sharing

Please review it.

**Comment by satellitex** [comment]
# Synchoronize Blocks FlowChart ( Preliminary version )
https://drive.google.com/file/d/0BzrYBcd0oxJOT0VNZVNRS1pJVmc/view?usp=sharing

## Description
- Synchornize peer main
  - main method.
  - Start synchornize start ledger
- Check broken root
  - Check root-hash is different another peer.
- Search broken point
  - Search where hash to broken.
- fetch transaction
  - This is called by each fetch transaction ( streaming ).
- Finish Fetch
  - This is called by finish fetch or error fetch.
  - It checked valid root-hash. If invalid restart sync-operation.
- Call Fetch Transaction ( id )
  - This call streaming fetch all transaction after transaction's identify >= `id`

**Comment by Warchant** [comment]
What if there is a difference in a leftmost leaf?

**Comment by satellitex** [comment]
I think node of merkle has accumulation hash. ( e.g, i-th hash has [0..i] hash )
So, Can do alike binary search.

**Comment by neewy** [comment]
Peer synchronisation is implemented now
