### ISSUE TITLE
Replace immutable strings with `ConstString`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2073]
In some places, namely `data_model` and `crypto` library there are immutable structures which store `String`s that can never be modified. Examples include `PublicKey`, `PrivateKey`, `IpfsPath`, ...

Grep the codebase for `String`s and make use of the newly added `ConstString` instead of `std::String` where applicable to reduce the memory footprint. #1985

**Comment by ales-tsurko** [comment]
It's impossible to make it for `crypto` (because of the cyclic dependencies) untill either #2386 or #2392 is done

**Comment by ales-tsurko** [comment]
> > It's impossible to make it for `crypto` (because of the cyclic dependencies) untill either #2386 or #2392 is done. Will open a PR for `iroha_data` and its dependencies though.
> 
> would it be possible to extract `data_model/primitives` into a separate lib as part of this PR? This will also be useful for the upcoming refactor.

Yeah, I can do that.
