### ISSUE TITLE
Transactions becomes Rejected under high load conditions

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#2078]
## Expected Behavior
Ideally, transaction results are not affected by transaction load or other network status

## Actual Behavior
As the transaction interval narrows, the number of rejected transactions increases (and eventually the program crashes).

## Steps to Reproduce

> commit dbe8a901c330454ed44446923ea462a29763879e
> 
> [feature] #1952: Add a TPS benchmark as a standard for optimizations (#1963)

1. Configure `interval_us_per_tx` in `client/benches/tps/config.json`

2. Simulate frequent transactions:

    ```bash
    cd client
    cargo run --example tps-oneshot
    ```

3. See the `txs_rejected` log appear at INFO level
    - After several local trials @s8sato can see `(80000, 0)` and `(50000, 8)` of `(interval_us_per_tx, txs_rejected)`

### Hint?
- All the rejection reason seem to be `FindError`
- One of sample instructions contains a query request
- It seems always `txs_rejected=0` when one of the two instructions in `tps_oneshot::lib::MeasurerUnit::instructions` is disabled

**Comment by appetrosyan** [comment]
Related to #1753

**Comment by SamHSmith** [comment]
This is fixed by new-sumeragi. Make sure to run the tps-oneshot in release though, otherwise the nodes can never get round to reporting new blocks because they are so overwhelmed with transactions.
