### ISSUE TITLE
Add ways of targetting an account by its public key, as well as alias

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2086]
All ISI which can target an account need to have separate implementations that can target an account both by their address (public key, then ss58) and an alias.

**Comment by s8sato** [comment]
As long as `transaction.payload.authority` is `AccountId`, aliases should be resolved before the transaction building.
Otherwise the transaction signature will be affected by aliases, which means validators should consider alias history of the transaction authority

**Comment by mversic** [comment]
closed in favor of #4372
