### ISSUE TITLE
Add query for block header

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2098]

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue??

**Comment by appetrosyan** [comment]
@ritikBhandari, please, be my guest. Let me know if you'd like a guided tour of the code-base to help you with your task.

**Comment by ritikBhandari** [comment]
@appetrosyan I'll appreciate that.

**Comment by QuentinI** [comment]
Closed in #2453
