### ISSUE TITLE
Handle `QueryError`s in client

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2105]
## The Problem

If you go to [api_spec.md#query](https://github.com/hyperledger/iroha/blob/iroha2/docs/source/references/api_spec.md#query), you may found the following table:

> **Responses**:
> 
> | Response        | Status | Body [*](#iroha-structures) |
> | --------------- | ------ | ---- |
> | Decode err.     |    400 | `QueryError::Decode(Box<iroha_version::error::Error>)` |
> | Version err.    |    400 | `QueryError::Version(UnsupportedVersionError)` |
> | Signature err.  |    401 | `QueryError::Signature(String)` |
> | Permission err. |    403 | `QueryError::Permission(String)` |
> | Evaluate err.   |    400 | `QueryError::Evaluate(String)` |
> | Find err.       |    404 | `QueryError::Find(Box<FindError>)` |
> | Conversion err. |    400 | `QueryError::Conversion(String)` |
> | Success         |    200 | `VersionedQueryResult` |

Currently, `iroha_client` does handle only 200 response, and just throws an untyped error in case when status code is not 200.

## The Request

Handle 400-404 status codes too and return result with `QueryError` when it is possible:

```rust
enum RequestError {
  BadRequest(QueryError),
  Undefined(Whatever)
}

fn request(/* ... */) -> Result<R::Output, RequestError> {}
```

**Comment by s8sato** [comment]
The followings should be resolved together:
- [ ] https://github.com/hyperledger/iroha/pull/1965#discussion_r823362373
- [ ] https://github.com/hyperledger/iroha/pull/1965#discussion_r823825724
- [ ] https://github.com/hyperledger/iroha/pull/2107#discussion_r853915178
