### ISSUE TITLE
Create short guide explaining how to hot-reload the Iroha binary in the docker container

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2119]

**Comment by mversic** [comment]
I made the following write-up

# Procedure
1. Build Iroha with `cargo build --release` or similar on your host OS
2. Enter docker container with `docker exec -it iroha-iroha0-1 bash`
3. Execute `cp root/soramitsu/iroha/target/x86_64-unknown-linux-musl/release/iroha .`
4. Exit docker container and restart it - your custom Iroha should be up and running

# Static linking
Sometimes an issue can arise with dynamically linking against `glibc`
if your host OS has a newer version of `glibc` than what is offered in the docker container.
If this happens you should add `--target x86_64-unknown-linux-musl` to your build command to
force static linking against `musl` libc implementation. You should also enable "vendored"
feature in the `iroha_crypto` library to facilitate static linking of `openssl` library

# Recommit genesis block (fresh start)
Previously explained procedure will keep the state of the blockchain as it was at the time
of restarting the docker container. If it is required to also recommit a custom genesis block
this will be done automatically if you remove the block information stored on the disk with
`rm blocks/*` before restarting the container

# Using custom configuration files (e.g. `config.json`/`genesis.json`)
Just copy them to `/` before restarting docker container. Changes will take effect automatically upon container restart

# Custom env variables (e.g. `IROHA_PUBLIC_KEY`)
Just modify them before restarting container. Changes will take effect automatically upon container restart

# Container restart VS. container down + container up
If you use `container down + container up` any modifications you made to the container will be lost, use restart instead

Where would you like to place this information?
