### ISSUE TITLE
Use enum for `PublicKey`/`PrivateKey` digest function

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2123]
Both `PublicKey` and `PrivateKey` store their respective digest functions as a string. They should store it as an `Algorithm` enum provided in the `iroha_crypto` crate.

**Comment by Tezas-6174** [comment]
Can I please work on this issue?

**Comment by Retssaze** [comment]
Thanks, very good one. It looks like I got what it is needed to do

**Comment by appetrosyan** [comment]
Good. Let me know if you want to set up a meeting and discuss the work in more detail.

**Comment by Retssaze** [comment]
Thank you for your kidness

**Comment by Retssaze** [comment]
Hi Alex,

How are you doing? What about our Meeting?

K.S.

**Comment by Retssaze** [comment]
It looks like I did something
