### ISSUE TITLE
Add `FindAssetDefinitionById` query

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2125]
Make it possible to find an `AssetDefinition` by its `AssetDefinitionId`.

**Comment by ritikBhandari** [comment]
hi,
Can I take up this issue if possible?

**Comment by appetrosyan** [comment]
I thought you wanted to work on another issue?

**Comment by ritikBhandari** [comment]
yeah I did but I couldn't get any response for my next message. So I thought you must have other plans for that issue.

**Comment by appetrosyan** [comment]
Yeah, I thought your previous message was a statement, rather than a question, regardless, if you kindly pick a slot in my calendar I could do some onboarding, and we'd be happy to receive your code contributions. 

https://calendar.google.com/calendar/u/0?cid=cGV0cm9zeWFuQHNvcmFtaXRzdS5jby5qcA

**Comment by ritikBhandari** [comment]
Sure.
But just to be clear, which issue should I work on? Though both are related to adding queries and I'm comfortable taking both of them.

**Comment by ritikBhandari** [comment]
Also, can I know what is your time zone? Actually I'm comfortable either at morning or night but I dont know if it would be okay for you.

**Comment by appetrosyan** [comment]
Re: issues, take whichever you like, but take one. 

Re: time zone, UTC+4, but I can work around your schedule if you like.

**Comment by ritikBhandari** [comment]
I have selected 6-7pm (UTC+5:30) on 26th April. Let me know if you are fine with it or we can figure another time frame suitable for both of us.

**Comment by appetrosyan** [comment]
Good! Please use my personal meeting Zoom link.

**Comment by appetrosyan** [comment]
https://zoom.us/j/2144517702?pwd=d25oMUFKVG5Kamh2Z1NMTVEwb0JzZz09

**Comment by appetrosyan** [comment]
CFT #2126

**Comment by appetrosyan** [comment]
We discussed the main bits of information. If you need any extra help, please find me on the Hyperledger Discord #iroha.

**Comment by appetrosyan** [comment]
@ritikBhandari When do you expect to start working on this issue?

**Comment by ritikBhandari** [comment]
I'm sorry my router is not working.

**Comment by ritikBhandari** [comment]
I'll start it today only

**Comment by 0x009922** [comment]
It is not tested in the explorer yet. Maybe it will be reopened again.
