### ISSUE TITLE
Representation of key pair in configuration files

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2135]
It has been [mentioned](https://github.com/hyperledger/iroha/pull/2130#discussion_r855210627) recently that in `client::Configuration`/`cli::Configuration`/`genesis::Configuration` we store `public_key` and `private_key` as separate variables as in:

```rs
pub struct Configuration {
    pub public_key: PublicKey,
    pub private_key: PrivateKey,
}
```
when they could be stored as a key pair as in:
```rs
pub struct Configuration {
    pub key_pair: KeyPair,
}
```

This is probably related to the deserialization either from config files or env variables. It should be investigated whether this switch can be made and will there be any tolerable consequences for the API of config files or env variables.

**Comment by s8sato** [comment]
One possibility is to stop deserializing to keys from config files or environment variables altogether
and configure it only when sign-up (keys generation) or login

**Comment by dmitrivenger** [comment]
#3240

**Comment by mversic** [comment]
@0x009922 is this still actual?

**Comment by 0x009922** [comment]
On the user layer (reading from a file/env), it is still represented by separate `public_key` and `private_key` fields. However, when the user layer is parsed further, a we construct a `KeyPair` and then put it into the type-strong view of the config.

As for what format is good for the config file, I am not sure if nesting these two fields into a `key_pair` will make much difference:

```toml
public_key = "..."
private_key = { algorithm = "...", payload = "..." }
```

```toml
[key_pair]
public_key = "..."
private_key = { algorithm = "...", payload = "..." }
```

I'd vote for making things flat if possible (i.e. don't introduce `key_pair` nesting).
