### ISSUE TITLE
Detailed logging of Error conditions

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2163]
Every time any function inside Iroha returns an error, we should be able to find that failure in the logs (probably with a backtrace). 

As such it may be a good idea to enable a custom trait that logs all/some error conditions but only in Debug builds and is otherwise a no-op.

**Comment by mversic** [comment]
especially this is relevant to logging errors comming from `wasm::Error`. For some reason only the top level error is displayed in the log and it's impossible to figure out what was the cause
