### ISSUE TITLE
Created assets aren't returned with `FindAllAssets`

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2167]
## Problem

I have:

- 4 Iroha peers, upped with `docker-compose up`
- Iroha client

I am doing:

- Creating some random assets with client cli

I see:

- A lot of committed blocks in Iroha logs
- None of created assets when I request them with `FindAllAssets`

## MWE

https://github.com/0x009922/iroha-issue-listing-assets

**Comment by s8sato** [comment]
Closed because the issue does not appear as of now (efa9a35692a949707ae0752119e4c4a1a08342a1).
See [the update to the MWE](https://github.com/0x009922/iroha-issue-listing-assets/pull/1)
