### ISSUE TITLE
Hook installation fail in `color-eyre`

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#2212]
When instantiating a peer through `iroha` cli, `color_eyre` fails to install its hooks in the `with_genesis` [function](https://github.com/hyperledger/iroha/blob/iroha2-dev/cli/src/lib.rs#L149). This is weird as this should be the first initialization. As mentioned by @appetrosyan, this could be caused by some tokio task trying to do the same thing separately, and needs further investigation, as for now we're just logging and ignoring it.

**Comment by QuentinI** [comment]
Couldn't reproduce neither on current HEAD nor on commits from around issue creation date.
