### ISSUE TITLE
Huge memory and CPU leak in iroha-main

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#223]
Branch: https://github.com/hyperledger/iroha/pull/209

Steps to reproduce:
1. run single node with default config
    ```
    docker run -it --name iroha hyperledger/iroha-docker
    ```
2. get IP of running node:
   ```
   docker inspect iroha | grep IPAddress
   ```
   (assume 172.17.0.2)
   
2. send 4 or 5 **different** queries on registration (different public key and alias)
```
curl -X POST http://172.17.0.2:1204/account/register -d '{"publicKey":"53IrRuiebs78YDdxrve6ZSp3rFbGvJB5fnGcRdVKTrw=","alias":"bogdan1","timestamp":1485182435}'
curl -X POST http://172.17.0.2:1204/account/register -d '{"publicKey":"43IrRuiebs78YDdxrve6ZSp3rFbGvJB5fnGcRdVKTrw=","alias":"bogdan2","timestamp":1485182435}'
curl -X POST http://172.17.0.2:1204/account/register -d '{"publicKey":"33IrRuiebs78YDdxrve6ZSp3rFbGvJB5fnGcRdVKTrw=","alias":"bogdan3","timestamp":1485182435}'
curl -X POST http://172.17.0.2:1204/account/register -d '{"publicKey":"23IrRuiebs78YDdxrve6ZSp3rFbGvJB5fnGcRdVKTrw=","alias":"bogdan4","timestamp":1485182435}'
curl -X POST http://172.17.0.2:1204/account/register -d '{"publicKey":"13IrRuiebs78YDdxrve6ZSp3rFbGvJB5fnGcRdVKTrw=","alias":"bogdan5","timestamp":1485182435}'
```

iroha will consume 100% CPU and 100% RAM in few seconds.

**UPD**: you can limit memory for docker by passing `-m 2G` to `docker run`, if you want to

**Comment by Warchant** [comment]
UPD: This is for develop branch also.

**Comment by l4l** [comment]
[This](https://github.com/hyperledger/iroha/blob/master/core/repository/consensus/merkle_transaction_repository.cpp#L94) loop is endless, that is the problem
ping @takemiyamakoto

**Comment by takemiyamakoto** [comment]
@l4l That code shouldn't even be used right now because we are moving all the Merkle root code to ametsuchi.

**Comment by l4l** [comment]
Leak is still here
working on this

**Comment by l4l** [comment]
look fine now
