### ISSUE TITLE
Replace simple-ish implementations of debug and display with derive

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2233]
Cases where an `impl Debug` is needed just to skip a field can be greatly simplified.

**Comment by mversic** [comment]
`Display` can only be derived with `derive_more`. Is there an example of what you mean by `Debug` implementation skipping just one field?

**Comment by appetrosyan** [comment]
Turns out that `derive_more::DebugCustom` allows the exact same API.
