### ISSUE TITLE
Multistage testing

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#2242]
Currently `I2::Dev::Tests` workflow has 2 different testing jobs (`tests_with_coverage` and `integration_tests`) and has some duplicated compilation cost

**Comment by astrokov7** [comment]
I see that both jobs still have the following duplicated steps:
Checking out the repository with actions/checkout@v3.
Using the Rust cache with Swatinem/rust-cache@v2.

But we need to clarify compilation cost of it. @BAStos525 Could you help us?

**Comment by BAStos525** [comment]
> I see that both jobs still have the following duplicated steps: Checking out the repository with actions/checkout@v3. Using the Rust cache with Swatinem/rust-cache@v2.
> 
> But we need to clarify compilation cost of it. @BAStos525 Could you help us?

Compilation cost is free for us now. As for tests organization and design, it's better to discuss with i2 team.
