### ISSUE TITLE
WebSocket communication noise

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2247]
For data streaming we use websocket communication protocol over which we overly our own. Our communication protocol over an **already established** websocket for both **events** and **block** streaming (the only two we currently have) looks like this:
1. client sends an event stream subscription request with all the details
2. server responds with _subscription accepted_ message
3. server starts streaming events:
3.1 server sends an event
3.2 client responds with the _event received_ message

Both the _subscription accepted_ message and the _event received_ message are redundant because they don't influence the control flow in any way and the fact that the message was received is guaranteed in the lower layers of abstraction as in TCP. While _subscription accepted_ message is sent only once _event received_ incurs a useless communication latency and should be removed.

**Comment by appetrosyan** [comment]
I suppose the answer lies in what can be sent as a receipt, and if we can encode the lower-level receipt as a higher-level control flow primitive.
