### ISSUE TITLE
"nocheckin" detection in CI

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#2249]
While developing it is often needed to insert code into the codebase that you only use for debugging or understand what the code is doing. Being able to flag these pieces of code with a nocheckin comment that stops the CI from passing would ensure none of this code
actually gets commited to iroha2.

This code for example would not pass CI.
```
println!("got here"); // nocheckin
```

I suggest we simply grep all the rust source files for the string `nocheckin` and fail if we find anything.

**Comment by appetrosyan** [comment]
Sounds easy to do.

**Comment by Arjentix** [comment]
Or maybe we can use some procedural macro? It's implementation can be empty but this should look more ideomatic

**Comment by appetrosyan** [comment]
re: proc macro. there actually is one, called todo!, and it doesnt get past clippy (which should fail CI). I use it all the time, and in my emacs config (relevant to @SamHSmith it's bound to T<Tab>).
