### ISSUE TITLE
Grant and Revoke roles should emit `RoleGranted`/`RoleRevoked` events. 

### ISSUE THREAD

**Issue by omkar-mohanty** [hyperledger/iroha#2257]
Following from #2007 as of now `Revoke` role (in `smartcontracts/isi/account.rs`) emits `PermissionRemoved` event which is misleading since roles are a collection of permissions. Refactor the code so that `Revoke` role emits `RoleRemoved` and `PermissionRemoved` events.

**Comment by Arjentix** [comment]
Closed as duplicate of #2280
