### ISSUE TITLE
Include current Block hash into `BlockHeaderValue`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2276]
Currently, when we query for block headers we cannot reliably compute the hash of the block, since it's computed from the byte representation of the block and can be representation dependent. 

To simplify our work, I suggest including the block hash in the query result

**Comment by omkar-mohanty** [comment]
Can I take this issue?

**Comment by appetrosyan** [comment]
Thank you! Your help would be much appreciated.

**Comment by appetrosyan** [comment]
@0x009922 Would you like to weigh in on the discussion.
