### ISSUE TITLE
Return `view_change_proofs` back to `BlockHeaderValue`

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2277]
The block header value intentionally omits the `view_change_proofs` from the `BlockHeader` defined in `iroha_core::block`. We should add that information back in.

**Comment by appetrosyan** [comment]
Return subset of the information to prevent brute-forcing of the proof.

**Comment by ales-tsurko** [comment]
It's blocked by #2392, because of cyclic dependencies. I suggest adding a dependency.

**Comment by SamHSmith** [comment]
We don't use view_change_proofs in the same way any more. So now there isn't any information to return.
