### ISSUE TITLE
Notify event listners when a role is Revoked

### ISSUE THREAD

**Issue by omkar-mohanty** [hyperledger/iroha#2280]
## Problem
As noted in [PR #2264](https://github.com/hyperledger/iroha/pull/2264) an account can lose a permission that's included in a role and event listeners that look for the permission being removed will not be notified.
## Solution
 It would be nice if  event listeners that look for `PermissionAdded` / `PermissionRemoved` to also be notified if a role that contains this permission is being revoked.

**Comment by omkar-mohanty** [comment]
Hi I would like to continue my work on this. Can I get assigned to this issue?

**Comment by 6r1d** [comment]
@omkar-mohanty hello, are there any updates regarding this issue?

**Comment by omkar-mohanty** [comment]
Hi @6r1d  I tried solving this issue for a long  time and could not come up with anything. I think it"s best if it's reassigned to someone else.

**Comment by Erigara** [comment]
IMO there is no point in this change currently. Our `AccountEvent::PermissionAdded/Removed` doesn't have any additional info only `AccountId`, so we would just spam with bunch of meaningless events.

We should firstly extend our events to contain more data.
