### ISSUE TITLE
fatal error: infra/protobuf/api.pb.h: No such file or directory

### ISSUE THREAD

**Issue by viettienbk** [hyperledger/iroha#230]
I build iroha in local environment, but have a issue:
`[ 48%] Building CXX object core/validation/CMakeFiles/validator.dir/transaction_validator.cpp.o
/home/ubuntu/iroha/core/validation/transaction_validator.cpp:20:35: fatal error: infra/protobuf/api.pb.h: No such file or directory
compilation terminated.
core/validation/CMakeFiles/validator.dir/build.make:62: recipe for target 'core/validation/CMakeFiles/validator.dir/transaction_validator.cpp.o' failed
make[2]: *** [core/validation/CMakeFiles/validator.dir/transaction_validator.cpp.o] Error 1
CMakeFiles/Makefile2:1821: recipe for target 'core/validation/CMakeFiles/validator.dir/all' failed
make[1]: *** [core/validation/CMakeFiles/validator.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by MizukiSonoko** [comment]
Could you try to it?
```
cd $IROHA_HOME; mkdir build; cd build; cmake ..
```

In this command, generates api.pb.h.
```
cmake ..
```

**Comment by viettienbk** [comment]
I have installed it on ubuntu 16.04, branch: master.
When I post: `curl -X POST http://172.31.28.237:1204/account/register -d '{"publicKey":"WdvM/DPabapmtA7ISbTYPywbHxk8gWu2221LzmcmAgw=","alias":"yonezu","timestamp":1482053586}'`
Iroha log:
`1489759618[sumeragi] 0--------------------------0
1489759618[sumeragi] +~~~~~~~~~~~~~~~~~~~~~~~~~~+
1489759618[sumeragi] |Would you agree with this?|
1489759618[sumeragi] +~~~~~~~~~~~~~~~~~~~~~~~~~~+
1489759618[sumeragi] 0================================================================0
1489759618[sumeragi] 0958857657e077431b5914f3d4b9ebf55d5233161ddc4d3a9bd5e815fb64443ad0
1489759618[sumeragi] 0================================================================0
1489759618[sumeragi] +-ー-++-ー-++-ー-+
1489759618[sumeragi] | 　 || 　 || 　 |
1489759618[sumeragi] |-承-|| 否 || 否 |
1489759618[sumeragi] | 　 || 　 || 　 |
1489759618[sumeragi] +-＝-++-＝-++-＝-+
1489759618[sumeragi] ==＝====＝====＝==
1489759618[sumeragi] numValidSignatures:1 faulty:1
1489759618[sumeragi] +==ーー==+
1489759618[sumeragi] |+-ーー-+|
1489759618[sumeragi] || 承認 ||
1489759618[sumeragi] |+-ーー-+|
1489759618[sumeragi] +==ーー==+
1489759618[sumeragi] commit
1489759618[sumeragi] commit count:1
1489759618 INFO [WorldStateRepositoryWithLeveldb] LoadDB
1489759618 INFO [WorldStateRepositoryWithLeveldb] NotFound: 
Killed
`

**Comment by MizukiSonoko** [comment]
Ok, I understand reason.
Maybe config is not setted.

**Comment by viettienbk** [comment]
Yepp.
When will you finish it?

**Comment by MizukiSonoko** [comment]
In first, 
Could you tell me result of
```
echo $IROHA_HOME
```
and 
Is there config.json in $IROHA_HOME/config/ ?
config.json is 
https://github.com/hyperledger/iroha/blob/master/config/config.json

**Comment by viettienbk** [comment]
`echo $IROHA_HOME`
`/home/ubuntu/iroha`

`nano $IROHA_HOME/config/config.json`
`{
  "database_path":"/tmp/iroha_ledger",
  "java_class_path":"java_tests",
  "java_class_path_local":"smart_contract/java_tests",
  "java_library_path":"lib",
  "java_library_path_local":"build/lib",
  "java_policy_path":"jvm/java.policy.txt",
  "concurrency": 0,
  "max_faulty_peers" : 1,
  "pool_worker_queue_size": 1024,
  "http_port": 1204,
  "grpc_port": 50051
}`
