### ISSUE TITLE
Querying: get domain triggers

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2302]
## The Problem

In the Iroha Explorer, we need to show domain triggers in the frontend. Only its count for now.

Backend fetches domain(s) with `FindAllDomains` and `FindDomainById`, but there is no any triggers data.

## Possible solutions

- Add domain triggers data to `FindAllDomains` and `FindDomainById`. Actually... it is more relevant to `FindDomainById` and may be omitted for `FindAllDomains`
- Add another query like `FindDomainTriggersByDomainId`

**Comment by appetrosyan** [comment]
Since we don't actually support domain-scoped triggers (#1889 which is blocked by #2062 which is going to take us at least a month to stabilise), I propose introducing a stop-gap solution where the query returns an empty struct, or a struct with a length identically equal to `0`.

**Comment by pesterev** [comment]
@0x009922 hey, we've implemented and merged domain-scoped triggers. Now the `FindTriggersByDomainId` query should return an actual list of triggers.
