### ISSUE TITLE
Refactor produce events

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2307]
As of now `produce_events` in `core/src/wsv.rs`has a few worrying branches. While the confusing return statement was fixed, we still have the problem of checking for whether an event sender is present outside of a loop. 

Because of `impl Into<Event>` it's possible that the inlined implementation of the function could elide the repeated check, but it is far from guaranteed. It is preferable to use the borrow checker to precisely always have an `event_sender` and to not have to check an option; @Erigara referred to this as a state-machine. 

Another point is that the return statement contains an explicit `drop`, which is usually a code smell for something being better expressed as a scope. The function needs to be investigated further and possibly extended.

**Comment by mversic** [comment]
also, check for other explicit `drop` statements around the codebase. There may be a few more

**Comment by appetrosyan** [comment]
Sounds like an easy fix. In general Options as functiin parameters are not a good idea.

**Comment by Erigara** [comment]
> Another point is that the return statement contains an explicit drop, which is usually a code smell for something being better expressed as a scope.

> also, check for other explicit drop statements around the codebase. There may be a few more

Actually we have quite a few explicit `drop`s around the codebase, so i am going to create separate issue for that to keep PR scope narrow.
