### ISSUE TITLE
Collect general profiling data on longevity test net

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#2350]
CPU time and memory cost money, the more we use per user the smaller networks we can support. It is therefore important that we have good knowledge of where in iroha2 we are slow and where we are fast. Same goes for memory but investigating that is a different matter and will be done as a different issue. I will be adding instrumentation to the various parts of iroha2 so that during a test net profile we can gather data on what needs improving.

**Comment by mversic** [comment]
related [RFC](https://wiki.hyperledger.org/display/iroha/General+Profiling+for+improving+Iroha2+TPS)

**Comment by Erigara** [comment]
We now have integrated profiler which we can use to collect necessary data.
