### ISSUE TITLE
Add a way to use custom client configuration in test `PeerBuilder`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2368]
Right now we have no possibility to use custom client in tests. I.e. it always uses `alice@wonderland` as a signer which is not very useful for some tests.
I think, it could be fixed by providing a way to pass custom `Client` object to `PeerBuilder`

**Comment by s8sato** [comment]
> always uses `alice@wonderland`

Yes. The combination of the fixed `alice@wonderland` and the generated key pair might have introduced extra inconsistencies.
After switching to the key-centric accounts, this would be resolved by removing the account names from payloads of queries and transactions
