### ISSUE TITLE
Fix unreadable `Grant instruction validator` error message

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2369]
# Problem

Take a look at `default_permissions()` at `permissions_validators/src/public_blockchain/mod.rs`. This configuration is used for checking instrucitons in Iroha 2 by default right now.

The first part of validators configuration is called `grant_instruction_validator`. If this part fails then it produces error message that says pretty nothing:

```
Error: Transaction was rejected

Caused by:
   0: Transaction rejected due to insufficient authorisation
   1: Action not permitted: None of the instructions succeeded in Any permission check block with name: Grant instruction validator.
```

All we can retrieve from this message is that something is wrong with some `Grant` instruction. We don't know which instruction and what is exactly wrong.
That was a problem while debugging #2081

# Suggested solution

I, personally, think that using `Result` doesn't fit well for validators, because we can't tell what (`Err` or `Ok`) should be returned from validator if it gets unexpected instruction. Right now `Grant` validators return `Err`, but `Instruction` validators return `Ok`. We need a unified way to do it. We need 3 variants: `Ok`, `Err` and `Skip`. We could use `Option<Result<...>>` but it looks ugly in my opinion.

So my suggestions is to introduce another return type for validators and refactor complex validators construction. This will allow us to tell which validators have failed in `any_should_succeed()` and etc. Altough I think that `any_should_succeed()` and `all_should_succeed()` will be less usable then and we can introduce `noone_should_fail()` which would meen *"All should return `Skip` or `Ok`"*. And maybe `at_least_one_success()`

**Comment by appetrosyan** [comment]
Custom return result?

**Comment by Arjentix** [comment]
Yes, something like:

```rust
enum ValidatorVerdict<T> {
    Ok(T),
    Err(DenialReason),
    Skip,
}
```

**Comment by Arjentix** [comment]
Our validation scheme reminds me about [chain-of-responsibility pattern](https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern)
