### ISSUE TITLE
Add query filtering client test

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2380]
Create a client test that demonstrates the usage of the new filtering infrastructure. It should be a scenario in which 
- [ ] assets are exchanged, 
- [ ] multiple blocks are created, 
- [ ] assets are filtered as identifiable using `contains`. 
- [ ] blocks are filtered by the creation timestamp,

**Comment by Erigara** [comment]
Closed as duplicate of #2398.
