### ISSUE TITLE
Deprecate `decode()` for  `decode_all()` 

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2384]
* Blocked by #2378 

As mentioned in [this comment] we temporary allow users to send extra bytes, but we print warning message. This was done to help SDK-developers.

After everything is stabilized we have to remove this and return an error every time something with extra bytes was sent

**Comment by appetrosyan** [comment]
@arndey @0x009922 , this is an important change, included in RC6.

**Comment by appetrosyan** [comment]
You should test this against the RC.6 peer, and verify. The interpretations can silently diverge.
