### ISSUE TITLE
Remove `MerkleTree` from Kura

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#2388]
Explore the possibility.

> S. Sato, [2022/06/20 21:45]
> [In reply to Sam H. Smith]
> It seems to be to handle GetBlockHash messages, but I'm not sure why sumeragi ask this for not wsv but kura

**Comment by s8sato** [comment]
[Currently](), `KuraWithIO::store` holds the only use case of `MerkleTree::add`.
Since `store()` is async while `add()` just inserts an hash to the tail of the tree without any sorting, there could be inconsistency between the block height and the index in the leaves of the block hash tree.
This inconsistency is problematic in `Handler<GetBlockHash>::handle` where the index in the leaves is interpreted to the block height

**Comment by SamHSmith** [comment]
I went ahead and did this during the Kura Simplification issue and PR. So in the current iroha2-dev source, this issue has already been done. https://github.com/hyperledger/iroha/blob/04205299c89fa0b028b50beacb7663674f8f2201/core/src/kura.rs
