### ISSUE TITLE
Panic if genesis cannot be applied. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2395]
If the `genesis.json` block cannot pass consensus (because the transactions contain valid types, but in invalid contexts, e.g. `Register<Account>` instead of `Register<NewAccount>`), the iroha startup should be terminated with a panic, showing the instruction that caused the failure.

**Comment by SamHSmith** [comment]
I think this is related to #1915. A strict init in kura should involve perfectly validating every block in the chain. This issue would be included in that. Kura might as well panic if it has no blocks to work with because the provided genesis is faulty.

**Comment by Erigara** [comment]
@appetrosyan, if peer can't submit genesis and panics, other peers should continue working as is, what do you think?
