### ISSUE TITLE
Consider transfer/burn *all* of an asset ISI

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2400]
## Use case
- For Cactus interoperability, we may need to open wallets for many accounts. These wallets should ideally be cleaned completely after all transfers have finished. Currently this can be implemented via a smartcontract, but it probably could be done more simply with a single instruction. 
- Internal blockchain exchanges can lead to a situation where the end user doesn't know how much money is to be transferred, but wants the money to be transferred. 

## Implementation

E.g. `Mint<…, u32>` becomes a `Mint<…, Amount(u32)>`, where schematically
```rust 
pub enum Amount<u32> {
    Exactly(NonZeroU32), 
    All
}
```

## Advantages: 
- Simpler.
- Explicit

## Drawbacks: 
- Can be emulated without an ISI, 
- In some way conflicts with `RISC + Vector extensions` architectural mantra. 
- Can be emulated with more complex logic (i.e. withdraw if and only if the quantity is above a certain threshold). 
- Probably better emulated by fixing the Expression API

**Comment by appetrosyan** [comment]
Best solution is to plug into the `Expression` API and have an `EvaluatesTo` variant that means all of an asset.

**Comment by mversic** [comment]
not needed anymore
