### ISSUE TITLE
Migrate to fbs

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#243]
[Structure so far](https://gist.github.com/Warchant/b7049e2f0653bd30c78f06b283c30bf0)

@Warchant @MizukiSonoko @takemiyamakoto

**Comment by l4l** [comment]
as continuation of #222

**Comment by MizukiSonoko** [comment]
Ok

**Comment by l4l** [comment]
Firstly let's finalize (more or less) the structure of fb, I have a few proposals before

**Comment by MizukiSonoko** [comment]
I think https://gist.github.com/Warchant/b7049e2f0653bd30c78f06b283c30bf0 is good.
And is there other proposals?
