### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2446]
When submitting bug reports we have a few common patterns. 

- [x] We only support `LTS` and `stable` versions (in the `iroha2-lts` and `iroha2` branches respectively)
- [x] We need an Minimum Working Example preferably in Rust (if it's an SDK problem, point them to the proper issue location in them). 
- [x] We need expected and actual behaviour. 
- [x] OS? 
- [x] Compiled or pulled from Docker/Nix
- [x] LIBC type and version (distro)? 
- [x] Logs in JSON format (+ instructions how to collect them).

**Comment by 6r1d** [comment]
I'm going to solve that issue.

**Comment by 6r1d** [comment]
There's no default spoiler for JSON logs, so I want to add one.
