### ISSUE TITLE
Flaky tests on M1

### ISSUE THREAD

**Issue by ales-tsurko** [hyperledger/iroha#2462]
Integration tests are flaky on M1. Ignoring `integration::events::pipeline::transaction_with_no_instructions_should_be_committed` and `integration::events::pipeline::transaction_with_fail_instruction_should_be_rejected` fixes it.

**Comment by ales-tsurko** [comment]
The fix is setting the maximum number of file descriptors to a higher value using `ulimit -n` (thanks @QuentinI).

**Comment by appetrosyan** [comment]
Another fix is to redistribute the tests across several binaries, or use `nextest` as a standard. 

The two solutions can be combined, since `nextest` creates more processes anyway.
