### ISSUE TITLE
[suggestion] Consider using struct variants internally

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2480]
### Feature request

We might consider expanding the scope of `IntoSchema` to parse `Struct`-like  variants, instead of referring the users to a non-existent style guide. 

### Motivation

In most cases a structure-like variant can make the code much more concise, and enforce a few invariants in the process. As we have significant duplication of responsibilities, it might make sense to add an extra processing step that auto-generates the information as needed, rather than defaulting to an error message.

**Comment by mversic** [comment]
regarding the `data_model`, this issue might be in conflict with #2491 . However, this enhancement will most likely be used only in `data_model`. I've added it as a blocking dependency so we can evaluate after #2491 is implemented

**Comment by appetrosyan** [comment]
Indeed, this is likely no longer required. Closing as not planned.
