### ISSUE TITLE
support `ffi_export` on freestanding functions

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2490]
currently `ffi_export` supports only inherent impl blocks. Expanding the support to include freestanding functions should be very easy.

This function:
```rs
#[ffi_export]
fn some_fn(arg1: String, arg: &[u32]) {
    // ... do something ...
}
```

should produce, once macro is expanded, something like the following `extern fn` declaration:

```rs
extern fn __some_fn(arg1: <String as TryFromReprC>::Source, arg2: <&[u32] as TryFromReprC>::Source) {
    // ... generated code ...
}
```

**Comment by ales-tsurko** [comment]
Should it support functions with return types either then `()`? And if so, what kind of type should be returned? `<T as TryFromReprC>::Source`?

**Comment by mversic** [comment]
> Should it support functions with return types either then `()`? And if so, what kind of type should be returned? `<T as TryFromReprC>::Source`?

Yes, the type returned is `<<T as IntoFfi>::Target as Output>::OutPtr`. You can see this in the `impl_visitor` I believe
