### ISSUE TITLE
[documentation] Incorrect error text in client_cli

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2499]
There are two incorrect values for error text I'd prefer to fix, copying the account-related error.

This value should be "`Failed to get all assets`":

https://github.com/hyperledger/iroha/blob/5ff6b67d392a0f8238d483918ea36e82d9a22937/client_cli/src/main.rs#L674-L675

And this one should be "`Failed to get all domains`":

https://github.com/hyperledger/iroha/blob/5ff6b67d392a0f8238d483918ea36e82d9a22937/client_cli/src/main.rs#L288-L289

**Comment by mversic** [comment]
@6r1d we can close this issue now?
