### ISSUE TITLE
🦟 [BUG] Iroha 1.5 build with Ursa leads to command rejection

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2519]
### GIT commit hash

https://github.com/hyperledger/iroha/commit/0d22d117

### Minimum working example

Irohad (v1.5) was built with `-DUSE_LIBURSA` flag with no issues.

### Expected behaviour

Iroha 1.5 is expected to run normally with Ursa.

### Actual behaviour

Network and peers run normally, but an attempt to run the commands leads to rejection:

> **[2022-07-22 12:22:51.209490937][th:40023][info]**
> **Irohad/CommandService/Processor Stateful validation error**:
>
> transaction 105b3595081547f208eaf4a74f1494f25674037e6961b54633aeb1d8781aa9a1 did not pass initial verification: 
> checking 'signatures validation', error code '1', query arguments:
>
> wD/sos/a/admin/S/9e317d98e23a3f955a80e691b0c2ff8935d9483e9384d2926f63caf6e33841fb/.
> Was not found.

### Operating system

Debian 5.10.113-1, kernel 5.10.0-14-amd64

### LibC type and version

ldd (Debian GLIBC 2.31-13+deb11u3) 2.31

### Current environment

Source code build

**Comment by appetrosyan** [comment]
`Ursa` is EOL, and Iroha v1 is going to be deprecated soon.
