### ISSUE TITLE
[SUGGESTION] Derive `Identifiable`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2527]
Often `impl Identifiable for T` is very simple code repeated throughout the code base: we need to replace 

```rust
impl Identifiable for T {
       type Id = Self;
       
       fn id(&self) -> &Self::Id { 
           self
       }
}
```

with 

```rust
derive(Identifiable)
```

and 

```rust
impl Identifiable for PermissionToken {
    type Id = some::Id;

    fn id(&self) -> &Self::Id {
        &self.id_field
    }
}
```

with 

```rust
#[derive(Identifiable)]
#[Id = some::Id, field = id_field]
```

### Optional nice to have

In some cases an `Identifiable` is also `Registered`. Often it's obvious that it has to be registered with `Self`, so another derive macro in the same crate could be useful.

**Comment by Erigara** [comment]
@appetrosyan i think we already have such macro, introduced in #2476.

**Comment by appetrosyan** [comment]
Indeed.
