### ISSUE TITLE
[BUG] Query results are not synchronised across peers

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2528]
### GIT commit hash

7ed7b4c8000db5505b445a61c03c3bc08c572b56

### Minimum working example

Taken from Orillion deployment.

Given: An asset (with 10 metadata entries) is not seen at the peer X but present on peer Y
When: Modifying the asset metadata attribute A to value V using peer X explicitly

### Expected behaviour

Then: Commit success, peer X sees the asset, 

### Actual behaviour

but in metadata there is only A->V, no other attributes, peer Y sees the whole updated picture (10 entries, including A->V)

### Operating system

Docker

### LibC type and version

None

### Current environment

Docker Hub

### Logs in JSON format

None

### Who can help?

@appetrosyan

**Comment by Tohanich** [comment]
Cannot reproduce

**Comment by Mingela** [comment]
Another potentially valuable addition, an asset minting happens via a smart contract, if possible please try reproducing considering that too
