### ISSUE TITLE
Add Trusted networks in config.json

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#254]
To bootstrap the network I need to receive the list of ips and public keys of all peers on some single node (master).

I propose the following solution:
1. add this to `config.json`:
   ```
   trusted_hosts: [
       "192.168.0.0/24", // can be a network
       "192.168.1.1"     // can be a host
   ]
   ```
   default is `trusted_hosts: []`
2. write separate tool (put in folder `$IROHA_HOME/tools`), (let's call it `hostdiscover`) which reads this parameter from config and polls all hosts and receives as an answer 
    - `IP`
    - `public key`
3. to communicate with hosts use grpc

It will be used as following:
1. I run docker-compose with 100 nodes. As a result I have bootstrapped 100 networks, each consists of single peer with correct sumeragi.json and config.json.
2. I pick single node (master) and run `hostdiscover`, it prints to stdout only this (and returns code 0 in case of success, even if no hosts found; and code !0 in case of any error):
   ```
   ip1 pubkey1
   ip2 pubkey2
   ip3 pubkey3
   ```
3. then I run script, which runs `issue_transaction add peer ipX pubkeyX` for each line, thus merging all networks from `trusted_hosts`

this task is assigned to @luckychess 
after completion I will be able to finish https://github.com/hyperledger/iroha/issues/250

**Comment by takemiyamakoto** [comment]
Shouldn't there be public keys associated with IPs in the config.json?

**Comment by luckychess** [comment]
@takemiyamakoto I think IPs are enough. We can get public keys from the nodes which are actually alive at the time of request. And it can work in case of node IP can be changed.

**Comment by Warchant** [comment]
@luckychess correct. At the startup we know only a range of IPs where **probably** peers can be running. But we don't know their public key and exact IPs.

**Comment by luckychess** [comment]
First version. Does not work with network masks at the moment.

**Comment by techiecircle** [comment]
Would you consider additional layer of trust using Digital Certificates.

**Comment by neewy** [comment]
Check solution in https://soramitsu.atlassian.net/wiki/spaces/IS/pages/12517377/Create+swarm+network+of+Iroha+nodes

If needed, reopen issue or create JIRA task
