### ISSUE TITLE
Add logs to `smartcontracts/wasm.rs`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2542]
As @appetrosyan mentioned [here](https://github.com/hyperledger/iroha/pull/2523#discussion_r929069912) we should consider adding some logs in this file

**Comment by Erigara** [comment]
@appetrosyan, what kind of behavior we want to log with `debug`? 

If we are talking about errors during smartcontract execution, then we already log them inside functions that uses this module.

**Comment by mversic** [comment]
already fixed by @appetrosyan
