### ISSUE TITLE
[suggestion] Expand `Multiply` expression to more types

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2543]
### Feature request

@appetrosyan suggested [here](https://github.com/hyperledger/iroha/pull/2523#discussion_r929083075) to impl `Multiply` expression for more than just `U32`

### Motivation

More types `Multiply` supports -- the more flexible this instruction is

### Who can help?

@appetrosyan

**Comment by appetrosyan** [comment]
Research how Ethereum does it.

**Comment by Arjentix** [comment]
That's what the [Solidty docs](https://docs.soliditylang.org/en/v0.8.17/control-structures.html#checked-or-unchecked-arithmetic) say:

> Prior to Solidity 0.8.0, arithmetic operations would always wrap in case of under- or overflow leading to widespread use of libraries that introduce additional checks.

> Since Solidity 0.8.0, all arithmetic operations revert on over- and underflow by default, thus making the use of these libraries unnecessary.

Although modern *Solidity* has a way to bring back unchecked operations we aren't interested in that.

And some [docs](https://docs.soliditylang.org/en/v0.8.17/contracts.html?highlight=revert#errors-and-the-revert-statement) about `revert` which was mentioned above:

> ... They (errors) have to be used together with the [revert statement](https://docs.soliditylang.org/en/v0.8.17/control-structures.html#revert-statement) which causes all changes in the current call to be reverted and passes the error data back to the caller

So this is like *panicking* in our case

**Comment by Arjentix** [comment]
Options we have:

1. Copy `Solidity` behaviour
2. Copy `Rust` behaviour
3. Remove `Multiply` at all

**Comment by appetrosyan** [comment]
What's the use case for leaving multiply @Arjentix? To me it seems that we are guaranteed both precision loss and overcomplicate expressions.

**Comment by Arjentix** [comment]
@appetrosyan , in my opinion, we should remove not only `Multiply` then. We should find a way to diferentiate between things we want to keep and things we want to remove. I don't see such a sign now.

**Comment by appetrosyan** [comment]
Expand functionality of expression to handle complex arithmetic. Need conversion methods. Must create epic

**Comment by Erigara** [comment]
Closed in favor of #2905.
