### ISSUE TITLE
Doctests and CI to add them directly to docs repo as examples

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2544]
We want to keep a set of tests which specifically showcase basic operations and types. 

We want to include them as examples in the in the docs repo and whenever there are changes to these examples, we want to automatically create a PR into the docs repo. 

### Benefits

Automagical maintenance of docs in an up-to-date state. 

We will know that the code snippets in docs are up to date, because they have been tested in our repo when they were introduced and passed CI checks. 

### Drawbacks 

Time consuming and needs to be done for all major supported SDKs. 
- [x] Rust
- [x] Java
- [x] Kotlin
- [x] JavaScript
- [x] Python

**Comment by s8sato** [comment]
As for Rust, #2309 needs to be resolved

**Comment by appetrosyan** [comment]
@timofeevmd Please verify that the tests are all running in the docs repo and if not, create relevant issues, before closing this one.

**Comment by appetrosyan** [comment]
@timofeevmd asked to clarify:

We need to point to the documentation files. We need to ensure that every example that **can** be moved into a working piece of checked code in the repos is extracted into a separate test, even a doctest. 

This ticket is not about updating the docs, it's about starting issues for when tests need to be written and the docs need to be updated.

**Comment by timofeevmd** [comment]
I checked the documentation for our SDKs, below is a list of tasks

 Rust https://github.com/hyperledger/iroha-2-docs/issues/361
 Java/Kotlin   https://github.com/hyperledger/iroha-2-docs/issues/364
 JavaScript https://github.com/hyperledger/iroha-2-docs/issues/363
 Python https://github.com/hyperledger/iroha-2-docs/issues/362
