### ISSUE TITLE
how to use the hyperledger/iroha-dev to build iroha-docker in centos ?

### ISSUE THREAD

**Issue by shangmacun** [hyperledger/iroha#256]
How to use the hyperledger/iroha-dev to build iroha-docker in centos ?

when I use this script:
docker run -i --rm \
    -v ${IROHA_HOME}/docker/build:/build \
    -v ${IROHA_HOME}:/opt/iroha \
    hyperledger/iroha-dev \
    sh << COMMANDS
    cd /opt/iroha
    /build-iroha.sh || (echo "[-] Can't build iroha" && exit 1)
    /mktar-iroha.sh || (echo "[-] Can't make tarball" && exit 1)
    (cp /tmp/iroha.tar /build/iroha.tar || \
        (echo "[-] FAILED! Mount /build folder from your host or use iroha/docker/build.sh script!" && exit 1))
COMMANDS

the result is : 
sh: 2: /build-iroha.sh: not found
[-] Can't build iroha
[-] Can't make tarball
sh: 3: /mktar-iroha.sh: not found

**Comment by cimadai** [comment]
@shangmacun
I solved this problem.
https://github.com/hyperledger/iroha/pull/268

I think you can build iroha inside iroha-dev container using above pr's script.

This script is for current develop branch.

**Comment by neewy** [comment]
Fixed. Check `sh scripts/run-iroha-dev.sh` in develop branch
