### ISSUE TITLE
[BUG] compose V3.8 not supported in ubuntu 20 LTS

### ISSUE THREAD

**Issue by outSH** [hyperledger/iroha#2566]
### GIT commit hash

91da336a

### Minimum working example

`docker-compose up`

### Expected behaviour

Should start

### Actual behaviour

Not sure if this is a bug or a feature request. Official ubuntu 20 LTS repository ships `docker-compose 1.25.0-1` which doesn't support compose V3.8 that is currently used by Iroha2 test ledger. In order to run the network, user has to obtain docker-compose from other sources. Ubuntu 20 is fairly popular and will be supported for a while so I think entry-level convenience for new users would be nice.

From what I've checked the only change needed in `docker-compose.yml` is to change `version: "3.8"` to `version: "3.7"`, everything else works fine.

### Operating system

Ubuntu 20.04.4 LTS

### Current environment

Source code build

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

**Comment by s8sato** [comment]
Hi, could you tell me the reason why you withhold updating `docker-compose` from the version `1.25.0-1` @outSH ?

**Comment by outSH** [comment]
@s8sato Hi, what I've meant was that main ubuntu repo ships old docker and docker-compose (see: https://packages.ubuntu.com/focal/docker and https://packages.ubuntu.com/focal/docker-compose), and if someone doesn't install docker from docker repo, the test ledger will not start :(

As for me, I do have updated docker-compose but I was initially confused because my environment linked `docker-compose` to old one from ubuntu repo and not the new one from docker-repo for some reason :)

In summary, I don't think this is critical because installing docker from docker-repo is recommended AFAIK, but still would be nice to be able to run this from plain ubuntu installation with ubuntu-repo docker-compose.

**Comment by s8sato** [comment]
We'd rather encourage everyone to upgrade to the latest versions than downgrade to support an older, potentially vulnerable version of software @outSH

**Comment by outSH** [comment]
@s8sato This is a matter of API usage, not specific package usage.. You can, for instance, use openssl 1.0 in RHEL 7 as long as it's supported and it still receives security updates (from redhat), even though the current upstream supported version is 1.1. Enterprises might be unwilling to use something not covered by OS vendor support they pay for, but this is a enteprise linux sidetrack - it's your call :)
