### ISSUE TITLE
Small revisions list

### ISSUE THREAD

**Issue by MizukiSonoko** [hyperledger/iroha#257]
I think we should do it. I want many people to revisions, Would you contribute? 🙇🙇🙇
**Of course, people who are not Hyperledger Iroha members are welcome too!!**

- [x]  Re write logger
https://github.com/hyperledger/iroha/blob/master/core/util/logger.cpp
Currently, iroha uses std::cout/cerr. but we should replace it with https://github.com/gabime/spdlog likes ametsuchi.  
- [x] Transition [this function](https://github.com/hyperledger/iroha/blob/master/core/consensus/sumeragi.cpp#L430) to `utils`
  `void setAwkTimer` is used by `izanami.cpp` too.
  ( reference : https://github.com/hyperledger/iroha/blob/master/core/service/izanami.cpp#L33 )
- [x] Improve exception
  - [x] Create base exception class like:
https://github.com/hyperledger/iroha-ametsuchi/blob/master/include/ametsuchi/exception.h
It is bad for all exceptions to derive `domain_error` or `invalid_argument`.
  - [x] Prepare more exception cases / Remove redundant exceptions.
https://github.com/hyperledger/iroha/blob/master/core/util/exception.hpp
Currently, there is exceprion likes FileOpenException, NotImplementedException, 
It is really good? I think need more exception cases
For example,
```c++
namespace crypto {
    class InvalidKeyException: public std::invalid_argument{};
    class InvalidMessageLengthException: public std::invalid_argument{}; // new 
}
```

- [ ] Refactoring(code)
    - [ ] Remove unused include
    - [ ] Apply `clang-format`
    - [ ] more clearly value name
    - [ ] Correct my wrong English 🏯 
    - [ ] Remove magic numbers and hard coded values.
    - [x] Gather `if (getenv("IROHA_HOME") == nullptr) {...}` into config.
    - [x] Remove unused util/service files.
    - [x] Mark *Deprecated* to JVM and smart contracts.
    - [ ] Replace assertions with exceptions except in test codes.
    - [ ] merge sumeragi.json to config.json
    - [ ] assert config.json when setup iroha.

- [ ] Add Test
    - Is there memory leak?
    - Is there segmentation fault case?
- [ ] Does iroha run on macOS (optional)
- [x] Load hierarchical configuration, or configuration should not be hierarchical.
  - It depends on whether loading `sumeragi.json` should be done by deriving `abstract_config_manager.hpp` or not. https://github.com/hyperledger/iroha/blob/master/core/infra/config/peer_service_with_json.cpp#L39

UPD (@warchant):
- [ ] Add some interface to peers. It can be a separate management tool.
   - [ ] Connect to peer by ip
   - [ ] Users want to be able to see a list of peers in a network. 
   - [ ] a list of "alive" peers and "dead" peers
   - [ ] a list of transaction they processed (?)
   - [ ] statistics
      - [ ] number of processed transactions
      - [ ] min, average, median, maximum transaction size

**Comment by motxx** [comment]
It is bad for all exceptions to derive domain_error or invalid_argument.
It is better to prepare base exception class like:
https://github.com/hyperledger/iroha-ametsuchi/blob/master/include/ametsuchi/exception.h

**Comment by grimadas** [comment]
I have just tested on macOS Sierra. Having trouble with openssl 

`
/Users/bulat/iroha/core/infra/service/http_client.cpp:26:10: fatal error:
      'openssl/ssl.h' file not found
#include <openssl/ssl.h>
`

It seems that Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

**Comment by lebdron** [comment]
spdlog integration in progress https://github.com/hyperledger/iroha/tree/feature/spdlog

**Comment by luckychess** [comment]
Started for on abstract_config_manager

**Comment by luckychess** [comment]
I decided to make abstract_config_manager hierarchical. Implementation was a bit tricky so please somebody review before merging.

**Comment by luckychess** [comment]
Just started utils refactoring.

**Comment by luckychess** [comment]
Done with utils. Merged without a review since all changed are pretty simple.

Anybody wants to review https://github.com/hyperledger/iroha/pull/258? )

**Comment by kamilsa** [comment]
Could you check out pull request? https://github.com/hyperledger/iroha/pull/265
