### ISSUE TITLE
[BUG] iroha_client_cli does not work inside docker with default config

### ISSUE THREAD

**Issue by wpi86** [hyperledger/iroha#2572]
### Current environment

**Docker Hub**;
**OS:** Ubuntu;
**GIT commit hash:** 90eb5e69 or any later.

### Description of actions

- `docker-compose up`
- `docker exec -it iroha_iroha1_1 sh`
- `iroha_client_cli domain list all`
- `curl http://localhost:8180/status`

Deploy iroha2 network with docker-compose file inside the repository, get into any iroha container and try iroha_client_cli any_command with configs/client_cli/config.json.
Also try curl http://localhost:8180/status

### Actual behaviour

![image](https://user-images.githubusercontent.com/86880521/181919718-cdfc73eb-cfda-4484-b5ec-663ecf9c19c4.png)

But i think i found the reason. It happens because iroha only listen for connections for local container address, but not for localhost or 127.0.0.1
![image](https://user-images.githubusercontent.com/86880521/181919916-c35ef4eb-fe11-48cf-8bfd-f6aeb7d01732.png)
![image](https://user-images.githubusercontent.com/86880521/181921112-6d846ee9-3857-48fa-a60d-088b76731914.png)

### Expected behaviour

iroha_client_cli works
curl http://localhost:8180/status works

### Note

For curl i can use default $HOSTNAME, but for config not, it takes this variable in lowercase and doesn't work
![image](https://user-images.githubusercontent.com/86880521/181920319-1c2a0076-a5ce-4cb1-99f1-8cb17391cc91.png)

### Who can help to reproduce?

@astrokov7

**Comment by astrokov7** [comment]
It's no longer reproduce on later committee [908f09f](https://github.com/hyperledger/iroha/commit/908f09f)
![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/471355c8-1b35-4ed0-b63f-42e4fb90190b)

**Comment by s8sato** [comment]
Not reproducible to me with the following modified steps.
Also, I need some clarifications:

- What is the intention of `docker exec` @wpi86  ? Are you trying to run a client from inside a peer?
- Why did you focus on 90eb5e6 ?

<details>
<summary>Terminal 1</summary>

```bash
git checkout 90eb5e6
```
```bash
sudo docker-compose -f docker-compose-local.yml up --build
```
</details>
<details>
<summary>Terminal 2</summary>

```bash
cargo build -p iroha_client_cli
```
```bash
cd configs/client_cli
```
```bash
curl http://localhost:8180/status
```
```bash
../../target/debug/iroha_client_cli domain list all
```
</details>

**Comment by astrokov7** [comment]
Actually, commit doesn’t matter. Last commit doesn't work too. I’ve edited this string.

**Comment by wpi86** [comment]
> 

Hi, yes, I'm trying to run a client from inside a peer.

**Comment by AlexStroke** [comment]
Resolved here 
https://github.com/hyperledger/iroha-2-docs/pull/396
