### ISSUE TITLE
We should have a way of pushing the iroha2-ci:dev image before merging into iroha2-dev.

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2577]
We should have a way of pushing the iroha2-ci:dev image before merging into iroha2-dev. 

__Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/2576#discussion_r935188901__

**Comment by BAStos525** [comment]
I guess that this task is not relevant more.

**Comment by BAStos525** [comment]
Another way to push this ci-image manually is to provide the updated `Dockerfile.build` and ask DevOps team to upload it to `hyperledger` DockerHub account since DevOps team has credentials to do it whenever it's required.
