### ISSUE TITLE
📖 [documentation] Connecting Iroha 1 and Iroha 2 documentation

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2579]
### Documentation URL(s)

Applies to both [Iroha 1](https://iroha.readthedocs.io/en/develop/) doc and [Iroha 2](https://hyperledger.github.io/iroha-2-docs/guide/iroha-2.html)

### Description

An advice from @Mingela during the meeting: connect two Iroha documentation pages, so Sphinx doc is able to link to Iroha 2 tutorial.

**Comment by outoftardis** [comment]
https://github.com/hyperledger/iroha-2-docs/pull/235 and https://github.com/hyperledger/iroha/issues/3034 address this issues

**Comment by 6r1d** [comment]
Thank you, I approve https://github.com/hyperledger/iroha/pull/3034 and I am closing this issue.
