### ISSUE TITLE
Tracking Issue for Configuration Overhaul

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#2585]
## What is it

This issue serves as the central point for monitoring the ongoing overhaul of the configuration system.

## RFC

[Rendered](https://github.com/hyperledger/iroha-rfcs/blob/main/text/001-config-overhaul.md)

RFC document related work:

- https://github.com/hyperledger/iroha-rfcs/pull/3
- https://github.com/hyperledger/iroha-rfcs/pull/8

## Tasks

Issues opened before the merging of the RFC:

- #2615 
- #2801 
- #2824 
- #3367
- #3470
- #3499
- #3500 
- #3501 
- #3502 
- #3503
- #3504 
- #3505 
- #3507 
- #3107
- #3327

New subtasks/discussions/PRs:

- #4028 
- #4029 
- #4030 
- #4059 
- #4063 
  - #4076
  - #4100
- #4064 
- #4079
- #4127
- #4136
  - #4153
- #4161
  - #4239
- #4194
- #4287
- #4288
- #4291
- #4292
- #4293
- #4294
- #4295
- #4296
- #4297
- #4299
- #4300
- #4301
- #4320
- #4323
- #4278
- #4383

Tracking of the configuration reference update:

- hyperledger/iroha-2-docs#392

**Comment by 0x009922** [comment]
I consider this epic to be mostly done. Some issues and questions are still open; some are going to be closed by some PRs soon; but in its core the overhaul is complete.
