### ISSUE TITLE
Reconsider the actor model

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2609]
Currently we use actors for everything. It's used both for inter-peer communication, inside Kura, and with work done by @SamHSmith still significantly prevalent in Sumeragi. 

However, actors need to be used with care. `actin_web` is a notorious example of a library moving away from actors. 

We should consider the following three options: 
1. Remove the actor system entirely. Prefer explicit interactions. This may save us a lot of overhead, not just because we don't use actors, but also, because the API will no longer require `async` in many places (especially places where a simple synchronous function would have been more effective). 
2. Remove parts of the actor system. This approach can be adopted as an intermediate step to option 1. Given that we have profiling, we can see if the actor system really benefits us in any case. 
3. Retain the actor system, but adjust its API. This is a conservative option. 
4. Retain the current actor system as is, with minor optimisations. 

@mversic @s8sato @SamHSmith @Erigara @ilchu your input would be welcome.

**Comment by Erigara** [comment]
I would prefer 2 approach (without removing actors entirely), because actor system help us with decouple parts of system or in cases when we want to provide same information for multiple modules.

**Comment by SamHSmith** [comment]
I'm for approach 1 but I think approach 2 works as well as an intermediate. I think the obvious gains are in understandability of the code.

**Comment by appetrosyan** [comment]
Consensus is, that some simplification is necessary. 

However, the removal is not a high priority task and isn't always going to improve performance/readaiblity/reusability. 

So each person decides if they want to remove the actor system for their task.
