### ISSUE TITLE
Remove all unneede parent attributes on `_Proxy` structs

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#2617]

**Comment by appetrosyan** [comment]
Should we open the discussion here?

**Comment by ilchu** [comment]
> Imagine that the struct has an attr from derive_more, which defines some behaviour. Would they not lead to a compile error given that the derive_more::From isn't part of the derive() directives?

It definitely would, and in the case of `derive_more` we wouldn't need most of this functionality on the proxy struct (such as display formatting etc.), as it's only an intermediary that gets thrown away after bootstrapping.

My doubts initially concerned attributes such as `#[config(inner)]`, as I figured they would be needed for trait impls, but upon further look it's perfectly sufficient to only have them on parent struct as we do now.

So I guess if everyone agrees, and I don't stumble against unforeseen roadblocks, the attributes can actually be ditched.

**Comment by ilchu** [comment]
Currently the only present attributes, `#[view]` and `#[serde]` are being deleted, but a small change might be required to make sure to delete *all* irrelevant attributes to make it future proof.

**Comment by Erigara** [comment]
IMO we should keep scope of `Proxy` structs narrow, so remove unnecessary attributes.
