### ISSUE TITLE
Arrangement naming convention for sumeragi and connection

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#263]
This issue is about [migrating-flatbuf](https://github.com/hyperledger/iroha/tree/migrating-flatbuf) branch, which is being hard restructured.

I think some names of methods and namespaces are obscure, therefore reading/writing codes are not easy. I'd like to propose some changes. If there are my misunderstandings, feel free to point out.

- [ ] namespaces are obscure.
    - e.g.
        - ::connection::iroha::SumeragiImpl
        - ::sumeragi
        - ::iroha::[FlatbuffersSchema]
    - Identifier `iroha` should be **top most level** namespace of program.
    - Namespace named as **proper noun** (e.g. sumeragi, izanami, ...) may be better **at one place**.
        - Giving namespaces proper noun is expected that they are unique. e.g. It's bad that there are `connection::iroha` and `iroha::[FlatbuffersSchema]`.
    - Make names readable such as **`B in A`** if **`A::B`**.
        - `::connection::iroha::SumeragiImpl` needs to be read such as `in case that iroha's sumeragi wants to use connection`.
    - Follow ordinary naming convention. `[Something]Impl` is implementation of `[Something]` itself.
    - namespace should be noun. (namespace `Verify` is bad)

- [ ] method names' are obscure.
    - `SumeragiConnectionClient::Verify()`
        - `verify` recalls just confirming data integrity, for example, validating data format, password, etc. `SumeragiConnectionClient::Verify()` calls other peer's `Verify()` method, which is not simply integrity checking.
    - `connection::iroha::SumeragiImpl::Torii::receive()`
        - `receive` might recall getting transaction from other peer or client, but this method set callback function that receives transaction.

**Comment by takemiyamakoto** [comment]
For verify: there is stateless validation and stateful validation, so that distinction should be made.
