### ISSUE TITLE
[BUG] Docker fails to pull image with `build` tag

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#2640]
### GIT commit hash

05eae34d

### Minimum working example

Either:
```bash
docker build . -t hyperledger/iroha2:dev      
```
or:
```bash
docker-compose -f docker-compose-single.yml up
```
from the root of the repo on `iroha2-dev` with the above commit hash.

### Expected behaviour

Iroha should pull the image from DockerHub and build it locally in both cases.

### Actual behaviour

Trying the above in both cases meets the user with:
```
[+] Building 2.0s (6/6) FINISHED
=> [internal] load build definition from Dockerfile
 => => transferring dockerfile: 37B
 => [internal] load .dockerignore
 => => transferring context: 34B
 => CANCELED [internal] load metadata for docker.io/library/alpine:3.16
 => ERROR [internal] load metadata for docker.io/library/iroha2:build
 => [auth] library/iroha2:pull token for registry-1.docker.io
 => [auth] library/alpine:pull token for registry-1.docker.io
------
 > [internal] load metadata for docker.io/library/iroha2:build:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
Thus it seems that the image tries to pull a tag `build`, which doesn't allow public access or doesn't exist.

### Operating system

MacOS 12.5.1

### Current environment

Source code build

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

**Comment by s8sato** [comment]
Will be resolved by the 4th feature of #2427. Workaround is:

> You need to build prior images, or docker will try to pull them @Erigara @I_am_6r1d 
> docker build -t iroha2:base -f Dockerfile.base .
> docker build -t iroha2:build -f Dockerfile.build .

**Comment by s8sato** [comment]
Correction. After ce9b21e0 (#2576), workaround is
```bash
sudo docker build -f Dockerfile.build --build-arg TAG=dev -t iroha2:build .
sudo docker-compose -f docker-compose-local.yml up
```
until #2427 is merged

**Comment by s8sato** [comment]
Correction. After f26263ad (#2427), workaround is

modify this line
https://github.com/hyperledger/iroha/blob/f26263ad5bda8f3910c8c7f64af6e84e1ba54d4e/Dockerfile#L3
to
```dockerfile
FROM hyperledger/iroha2-ci:$TAG AS builder

```
and
```bash
sudo docker-compose -f docker-compose-local.yml up
```
until the next CI PR is merged

**Comment by s8sato** [comment]
Resolved https://hub.docker.com/r/hyperledger/iroha2-base/tags
