### ISSUE TITLE
New-WSV

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#2664]

**Comment by appetrosyan** [comment]
Data-orientation is a bit broad. Could you provide us with a few more specifics?

**Comment by SamHSmith** [comment]
The number one reason why code runs slowly is cache misses. So in order to *be fast* we have to be very conscious about how data is stored and accessed. Right now we don't do this.

We also want to apply patch theory to this problem. Something that I think also requires this kind of approach. It's *Data in, Data out*. What transformations are we actually doing?

**Comment by nxsaken** [comment]
@Erigara should we close this?
