### ISSUE TITLE
Add split generics in macro impls

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#2665]

**Comment by appetrosyan** [comment]
Description please

**Comment by ilchu** [comment]
What I meant here is that maybe using [`split_for_impl()`](https://docs.rs/syn/latest/syn/struct.Generics.html#method.split_for_impl) here would be prudent. But on second thought, `Configuration` structs are unlikely to become generic even in future, so that would be redundant, and this issue can be closed.

Still might need a bit of cleanup in `iroha_config::base::derive` as `generics` field on `StructWithFields` or its tokenization is unneeded due to absence.
