### ISSUE TITLE
Validate item names/ids without allocating `Vec`

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#2675]
We have a few places where we allocate a vector within the `FromStr` implementation for an element name/id when we don't really need to. 

Approach without allocation: data_model/src/trigger/mod.rs impl FromStr for Id.

**Comment by appetrosyan** [comment]
https://docs.rs/zerocopy/latest/zerocopy/ Might be useful

**Comment by Retssaze** [comment]
Where this data_model/src/trigger/mod.rs  is located?

**Comment by appetrosyan** [comment]
Hi! This is an iroha version 2 issue, so you need to switch to the iroha2-dev branch.

**Comment by Retssaze** [comment]
Let's cath up

**Comment by suiwenfeng** [comment]
@appetrosyan `zerocopy` make sense on packat deserialization from network bytes, but how can it do validation on invalid input? for example, no `@` in account_id(which should have format like `name@domain_name`).

after look at `data_model/src/trigger/mod.rs`, just replace

``` rust
let vector: Vec<&str> = string.split('@').collect();
```

with 
``` rust
let mut split = s.split('$');
match (split.next(), split.next(), split.next()) {
```

That`s right?

**Comment by suiwenfeng** [comment]
Ok, i will refactor such code. Method execution time did improved in my local benchmark.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/106252855/206404485-fc0d2bcb-116e-45c1-849f-a17886e70b03.png">

**Comment by Erigara** [comment]
Great to hear! Will be waiting for the PR.

**Comment by suiwenfeng** [comment]
#3003

**Comment by Retssaze** [comment]
> #3003

You took my task, what a shame!

**Comment by 6r1d** [comment]
While I am not sure it helps, there's a [list](https://github.com/hyperledger/iroha/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) of several issues that may be interesting for the new contributors.

**Comment by Erigara** [comment]
For example you can take a look at #2123.

**Comment by Retssaze** [comment]
To [suiwenfeng](https://github.com/suiwenfeng): Sir, For sure you are very strong and quick, and a message above by [6r1d](https://github.com/6r1d) is definitely not only for you!
