### ISSUE TITLE
Fix tests on staging branch

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#2678]

**Comment by Tohanich** [comment]
Description required:
What the tests
What the branch
Steps to reproduce

**Comment by SamHSmith** [comment]
```
branch: iroha2-staging
steps to reproduce: cargo test
```

**Comment by SamHSmith** [comment]
I have a partial fix.

**Comment by SamHSmith** [comment]
Here is the partial fix: https://github.com/hyperledger/iroha/pull/2682
But this issue isn't really closed. The PR only makes it easier to debug because the tests don't abort.
