### ISSUE TITLE
Iroha-CPP: choosing a proper JSON library

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2681]
Currently, two separate JSON libraries are used in the codebase:

* [RapidJSON](https://github.com/Tencent/rapidjson) by [Tencent](https://github.com/Tencent?type=source): [MIT / JSON / BSD license](https://github.com/Tencent/rapidjson), with 29 [code mentions](https://github.com/hyperledger/iroha/search?q=rapidjson). [Last release](https://github.com/Tencent/rapidjson/releases) in 2016, last commit [9 days ago](https://github.com/Tencent/rapidjson/commit/06d58b9e848c650114556a23294d0b6440078c61).
* [Niels Lohmann's JSON library](https://github.com/nlohmann/json), [MIT license](https://github.com/nlohmann/json/blob/develop/LICENSE.MIT). 2 [mentions with full name](https://github.com/hyperledger/iroha/search?q=nlohmann_json), 5 [mentions with short name](https://github.com/hyperledger/iroha/search?q=nlohmann). Last release [5 days ago](https://github.com/nlohmann/json/releases), last commit [yesterday](https://github.com/nlohmann/json/commit/307c053b9b250abc6e6d478a4336fd98592ae173).

While rapidjson is used much more, we should choose one of the libraries for `iroha-cpp`. Which one would you prefer, @iceseer, @appetrosyan? Why?

**Comment by appetrosyan** [comment]
Isn't it obvious? Last release yesterday sounds much better than 2016.

**Comment by iceseer** [comment]
Nlohman was erroneously added as it is easy to use and was planned to be removed in the future.. It uses only in tools. RapidJSON is very stable and much faster comparing with nlohamn. 

https://github.com/miloyip/nativejson-benchmark
Benchmark relative results are very similar to the results of our tests.

So given the above, it does not matter when and how often the updates were, if the results are better. Rapidjson it is the main json library used in Iroha-1.

**Comment by 6r1d** [comment]
Thanks, I believe we can close the issue now.

**Comment by baziorek** [comment]
Thanks a lot! So RapidJSON is better to be used in iroha-cpp library:).
