### ISSUE TITLE
Add the cargo installation to the build guide for Ubuntu before cargo build

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#2684]
`sudo apt install cargo`

**Comment by outoftardis** [comment]
we mention `cargo` as a prerequisite though, do you think we need to provide this line of instruction?

<img width="416" alt="image" src="https://user-images.githubusercontent.com/17865025/187905677-5899e331-0924-40ee-b6eb-c9cd218c9ae3.png">

**Comment by astrokov7** [comment]
@outoftardis Ok, I think this enough. Sorry.
