### ISSUE TITLE
[BUG] scripts/test_env.sh wasn't backported to iroha2-lts branch

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#2709]
### Current environment
**OS:** MacOS M1 (run on metal)
**Branch:** iroha2-lts
**Running docker containers:** neither one running

### Description of actions

```bash
 $ git clone https://github.com/hyperledger/iroha.git --branch iroha2-lts
 $ cd iroha
 $ cargo build -p iroha_client_cli
 $ scripts/test_env.sh setup
```

### Actual behaviour

<details>
  <summary>Log contents</summary>
  
```
alexstrokelive@Aleksandrs-MacBook-Pro iroha % scripts/test_env.sh setup
+ TEST=./test
+ HOST=127.0.0.1
+ IROHA2_CONFIG_PATH=./test/peers/config.json
+ IROHA2_GENESIS_PATH=./test/peers/genesis.json
+ declare -A public_keys
scripts/test_env.sh: line 12: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] …]
```
</details>

### Expected behaviour
Successfully runs

### Note
I should change first string of the script `#!/usr/bin/env bash` instead `#!/bin/bash`

### Who can help to reproduce?
@astrokov7

**Comment by 6r1d** [comment]
It seems to be a `bash` version being outdated: I think that `-A` option should declare a new associative array.
