### ISSUE TITLE
[BUG] Trigger (un) registering leads to Iroha looped panic

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#2741]
### GIT commit hash

docker.io/hyperledger/iroha2:lts@sha256:4072d09bee376c8fcbc586d35ea25624738694ce2c37aa0db60c9998c613048b

### Minimum working example

https://github.com/soramitsu/orillion-core-middleware/tree/develop/smart-contracts/reward-mint-with-cap-smart-contract source code
https://github.com/soramitsu/orillion-core-middleware/tree/develop/services/admin/src/main/resources mint_with_cap is the compiled wasm

### Expected behaviour

Iroha went panicing
After container death it is restarted and seems to behave okay for some time but then it's started again

### Actual behaviour

Correct unregister+register of the trigger (for the same id though)

### Operating system

k8s, dev env

### Current environment

Docker Hub

### Logs in JSON format

2022-09-13T14:52:53.506685Z  INFO iroha: Hyperledgerいろは2にようこそ！
2022-09-13T14:52:53.506736Z  INFO iroha: (translation) Welcome to Hyperledger Iroha 2!
2022-09-13T14:52:53.506822Z  INFO iroha: Starting peer listen_addr=0.0.0.0:1337
2022-09-13T14:52:53.506844Z  INFO iroha_p2p::network: Binding listener listen_addr=0.0.0.0:1337
2022-09-13T14:52:53.506927Z  INFO iroha_p2p::network: Starting network actor listen_addr=0.0.0.0:1337
2022-09-13T14:52:58.756188Z  WARN apply: iroha_core::wsv: The following errors have occurred during trigger execution errors=[
   0: Failed to find. Failed to find domain: `dn`
   1: Failed to find domain: `dn`

Location:
   core/src/wsv.rs:151

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible]

other ton of logs https://drive.google.com/file/d/1jgEDovjgKAnzKE-GTHjLS-9Ozh_lFxO-/view?usp=sharing

**Comment by adaagava** [comment]
Registering and unregistering trigger works fine with Iroha2-lts brunch.

**Comment by adaagava** [comment]
Checked in one and in 2 separate transactions.

**Comment by Mingela** [comment]
> Checked in one and in 2 separate transactions.

have you checked that running 4 peers?
