### ISSUE TITLE
Revise Transaction state that is accepted by Wasm Validators

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2744]
After the merge of #2641 we should revise how we pass transactions to *Wasm Validators*. 

@Erigara [has mentioned](https://github.com/hyperledger/iroha/pull/2641#discussion_r970634627) that it's against our rules to construct `Transaction` from `AcceptedTransaction` and pass it to validators. Something is wrong with states here.

**Comment by Arjentix** [comment]
ATM it looks fine to me.

Executor should now nothing about `core` transaction states. Currently in `core/src/tx.rs` `AcceptedTransaction` is being converted into `SignedTransaction` and passed to the `Executor`.

I suggest closing this issue. @Erigara , @mversic , what do you think?

**Comment by Erigara** [comment]
@Arjentix i agree
