### ISSUE TITLE
Iroha 1 build breaks when Abseil lib is built on Ubuntu 20 LTS

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2768]
Yesterday, bzealous007 [reported](https://discord.com/channels/905194001349627914/905205848547155968/1021873677828104303) an issue with Iroha builds in Hyperledger Iroha Community Discord.

### Context

* Ubuntu 20 LTS, 64 bit
* Build stops on [Abseil](https://abseil.io/): `absl/debugging/failure_signal_handler.cc` on line 139 with mismatched types, `std::initializer_list<_Tp>` and `long int`
* Git commit: [`a544eb269e`](https://github.com/hyperledger/iroha/commit/a544eb269e02593bbb9d8394f79c1b6aeac73026)
* [Log file](https://github.com/hyperledger/iroha/files/9614421/install-x64-linux-dbg-out.log)

**Comment by 6r1d** [comment]
I am trying to check if I can suggest the [Iroha Builder](https://github.com/hyperledger/iroha/blob/main/docs/source/build/index.rst#iroha-builder) as a solution.

First attempt is a failure (log is attached below), but since the network disappeared globally on my machine, I am re-trying it.

[ibuilder_Sep_22.log](https://github.com/hyperledger/iroha/files/9623517/ibuilder_Sep_22.log)

**Comment by baziorek** [comment]
@6r1d @appetrosyan I think it was fixed here: https://github.com/hyperledger/iroha/pull/2902 so the issue can be closed

**Comment by 6r1d** [comment]
Thank you, @baziorek.
