### ISSUE TITLE
Implement transfers in addition to mints in `kagami --synthetic`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2776]
These aren't strictly necessary, but since we have them, we should consider adding `Transfer`s in a separate issue.

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/2771#discussion_r977239857_

**Comment by Erigara** [comment]
As i understand `Genesis` represents initial state of blockchain, does it make sense to transfer assets on initial state?
