### ISSUE TITLE
Compile error with jvm and smart contract folder location

### ISSUE THREAD

**Issue by rupc** [hyperledger/iroha#278]
Hi. When I build hyperledger/iroha following this [how to build](https://github.com/hyperledger/iroha/blob/master/docs/how_to_build.rst#iroha本体のbuild--build-iroha), I encountered two error messages.
One thing is that it cannot found "jni_md.h" when it compiles jvm related sources. So I put "jni_md.h" from "java-8-openjdk-amd64/include/" to "/usr/lib/jvm/default-java/include".

The other one is that "javac: file not found: /smart_contract/*". I think Makefile seeks smart contract folder at root location. So, when I put the entire iroha/smart_comtract folder to /root/, It works without any error.

I think these should be mentioned in advanced or fixed.
(My environment is Ubuntu 16.04.2 LTS)
Thanks

**Comment by nothingcosmos** [comment]
JAVA_HOME setting required

ex)
$ echo $JAVA_HOPME
/usr/lib/jvm/default-java

**Comment by motxx** [comment]
Thank you for this issue. It might be something wrong with configure setting program, but I still haven't check enough yet. By the way, current master branch will be replaced with develop branch, which is new architecture, and java smart contracts will be completely removed.

**Comment by takemiyamakoto** [comment]
We don't use Java any more, so this should be fixed.
