### ISSUE TITLE
Get rid of `Option` inside `sumeragi::main_loop`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2791]
So in this function looks like you want to say, that there will be no `None` elements in `transaction_cache`. Like you have introduced `Option` just for this function.

Maybe we can do something with it? I.e. add assertion (at least in `debug` mod)? Or completely remove `Option` and use another approach storing just transactions and replacing one vec with another?

_Originally posted by @Arjentix in https://github.com/hyperledger/iroha/pull/2762#discussion_r979024279_

**Comment by Erigara** [comment]
`transaction_cache` doesn't have `Option` any more
