### ISSUE TITLE
FFI niche counting

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2793]
So only case when enum does't have niche is when it has number of variants equal to `ffi_type::MAX - ffi_type::MIN`, we could check this condition during macro expansion.

Then we could do [the following](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b1fcf019c2454cff92e41b63f9d659fc) to find niche value, we can't find niche during expansion because discriminant is expression.

_Originally posted by @Erigara in https://github.com/hyperledger/iroha/pull/2625#discussion_r967125234_

**Comment by mversic** [comment]
Closed in favor of #2794
