### ISSUE TITLE
Reject Fieldless enums with explicit discriminants in FFI

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2794]
Currently, determining discriminant values of fieldless enums in FFI is done by incrementally counting the number of variants. This works for the common case, but is not entirely accurate. There can be holes in the sequentially increasing number for the discriminant, in the case that user defines a discriminant value by hand. Additionally, related to this, is finding a niche value for the fieldless enum if the enum doesn't take the whole range of the discriminant. This can be any value in the range. 

Example:

```rs
#[repr(u8)]
enum FieldlessEnum {
    A,       // discriminant = 0
    B = 43 - 1,
    C,        // discriminant = 43
    D = 255
}
```

This will most likely fail to compile or will result in an incorrect implementation. 
In this case niche value can be any value in the range `[1, 41]` or `[44, 254]`. I would recommend choosing a value that is most unlikely to be used by the enum in the future (assuming that additional variants will be added at some point). Largest available discriminant value might be a good candidate?

**Comment by appetrosyan** [comment]
Better to reject this pattern. We don't need it to cross the FFI boundary necessarily.
