### ISSUE TITLE
String representation in FFI

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2795]
#2625 makes an assumption that `String` can be transmuted into `Vec<u8>`. Usually `repr(Rust)` structures don't offer any guarantees on the representation of the object in memory. However, [this](https://users.rust-lang.org/t/soundness-about-transmute-vec-vec-u8-to-vec-string/63854/3) comment made some points in favor of making this assumption. 

We should consider special handling `String` conversion in FFI instead of transmuting it into `Vec<u8>`

**Comment by Erigara** [comment]
After some investigation it was found that `repr(rust)` single-field structs is guaranteed to have the same memory layout as it's single field ([Unsafe Code Guidelines Reference](https://github.com/hyperledger/iroha/issues/2795)).

Currently `String` is implemented as single-field struct ([source](https://doc.rust-lang.org/src/alloc/string.rs.html#367)) so it's transmutable into `Vec<u8>`.
There is still chance that `String` layout will be changed in the future, but this seems unlikely and could be fixed later.
