### ISSUE TITLE
Formally verify `Expression` and `ISI` strict typing

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2826]
Strict typing := no implicit conversions and operations without any overloads. 

### Example: 

StandardML is a strictly-typed language, meaning no implicit conversions. 

```ml
> 1 + 2 
3
> 1.0 + 2 
Elaboration failed: Type clash. Functions of type "int * int → int" cannot take an argument of type "real * int": Cannot merge "real" and "int".
```

### Corollary

```rust 
Add<u64, u128> 
``` 
Is not implemented, the `u64` needs to be manually converted into `u128`. While this can cause some inconvenience for the developers, given that what we're dealing with are financial calculations, this is actually a benefit. 

What this leads to is also a simplification of some of the underlying code. All binary operations have strictly two branches, which are reduced to one thanks to `EvaluatesTo<u64>`. 

### Relation to #1568 

Code that resolves this issue also resolves #1568, but not the other way around.

**Comment by appetrosyan** [comment]
Added benefit, this is how rust does things.

**Comment by mversic** [comment]
we don't have expressions in the core anymore
