### ISSUE TITLE
Fix `Id` deserialization/decoding in `data_model`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2840]
For any `Id` in `data_model` (e.g. `Trigger`) for which `FromStr` can fail a manual implementation of both `serde::Deserialize` and `parity_scale_codec::Decode` has to be given in the same manner as it's done for `Name`. This happened with the addition of the short-hand syntax in #2772.

**Comment by mversic** [comment]
related to #1995

**Comment by Erigara** [comment]
Not confirmed.
