### ISSUE TITLE
[BUG] Running single instanced iroha network is signaling `RPC failed` and not committing any commands

### ISSUE THREAD

**Issue by baziorek** [hyperledger/iroha#2857]
### GIT commit hash

f39d22db63d6e88e45c4c7205e9fff27057726a2

### Minimum working example

1. build iroha, according to instructions. Config from [example](https://github.com/hyperledger/iroha/tree/develop/example) with only database host changed into `localhost` in `config.docker`
2. Run database:
```
docker run --rm --name iroha_postgres \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_PASSWORD=mysecretpassword \
    --network=host \
    -d postgres \
    -c 'max_prepared_transactions=100' \
    -c 'port=5432'
```
3. Run iroha from repository main path:
```
cd $(IROHA_REPOSITORY_ROOT)
/home/student/Desktop/iroha_code/baziorek/build-iroha-Desktop_Qt_6_3_2_GCC_64bit-Debug/bin/irohad \
   -config example/config.sample \
   -genesis_block example/genesis.block \
   -keypair_name example/node0 \
   -drop_state -overwrite_ledger
```
4. After few seconds message like:
```
[2022-10-12 06:28:47.016924727][W][Irohad/Consensus/Network]: RPC failed: bddd58404d1315e0eb27902c5d7c8eb0602c16238f005773df406bc191308929
```
is appearing every few seconds.
______________________
I've checked with `iroha:docker` official image and result was the same:
```
cd $(IROHA_REPOSITORY_ROOT)

docker run --name irohad_develop \
    --network=host \
    -v "$(pwd)/example/:/opt/iroha_data" \
    -e KEY=node0 \
    hyperledger/iroha:develop -drop_state -overwrite_ledger
...
[2022-10-12 06:27:30.793802052][I][Init]: Irohad version: 1.6.0-rc.1-34-ge82726d2
...
[2022-10-12 06:28:47.016924727][W][Irohad/Consensus/Network]: RPC failed: bddd58404d1315e0eb27902c5d7c8eb0602c16238f005773df406bc191308929
```
_____________________
But when I use `iroha:1.5.0` docker image everything works:
```
docker run --name irohad_1.5.0 \
    --network=host \
    -v "$(pwd)/example/:/opt/iroha_data" \
    -e KEY=node0 \
    hyperledger/iroha:1.5.0 -drop_state -overwrite_ledger
```

### Expected behaviour

No warnings like that, committing commands

### Actual behaviour

Warnings like:
```
[2022-10-12 06:28:47.016924727][W][Irohad/Consensus/Network]: RPC failed: bddd58404d1315e0eb27902c5d7c8eb0602c16238f005773df406bc191308929
```
And commands hanging until timeout

### Operating system

Ubuntu 22.04 and docker

### LibC type and version

ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35

### Current environment

Source code build

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

### Who can help?

@iceseer

**Comment by 6r1d** [comment]
@baziorek let's discuss it and try to replicate. If it doesn't repeat anymore, I think we can close this issue.

**Comment by baziorek** [comment]
> @baziorek let's discuss it and try to replicate. If it doesn't repeat anymore, I think we can close this issue.

Yes, it was fixed: https://github.com/hyperledger/iroha/pull/2749 so I think it can be closed
