### ISSUE TITLE
Use `mut* u8` in`BoxedString` vs `NonNull<u8>`. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2859]
`ReprC` structs are required to be `Copy` currently. The choice is either to remove the `Copy` supertrait and apply the suggestion or leave it as is. after discussion with @Erigara it was decided to leave it as is for the moment at least and possibly revisit in the future.

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/2837#discussion_r993656876_

**Comment by mversic** [comment]
not relevant anymore

**Comment by mversic** [comment]
not relevant anymore
