### ISSUE TITLE
Add `ipfspath` metadata type

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2869]
Idea: 

Get rid of special `ipfspath` handling. Instead of it being a data member in e.g. `AssetDefinition` as it is today, it should be a special metadata key that is interpreted by the front-end. 

For that to happen, it should be possible to add a `Value::IpFsPath` and `Value::Url` variants, which have special handling.

**Comment by Arjentix** [comment]
I'm not sure what does this issue mean
