### ISSUE TITLE
[BUG] `LOG_FILE_PATH` env var doesn't work as expected

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2894]
### GIT commit hash

b783f10fa7de26ed1fdd4c526bd162f8636f1a65

### Minimum working example

Build Iroha and run it in terminal:

```bash
LOG_FILE_PATH=/dev/stdout ./iroha
```

### Expected behaviour

Expected to see JSON logs in STDOUT.

### Actual behaviour

I get an error:

```
Error: Failed to (de)serialize the field: log_file_path

Caused by:
   0: Name of the field: log_file_path
   1: expected value at line 1 column 1
```

### Operating system

macOS 12.2.1

### LibC type and version

_Undefined_

### Current environment

Source code build

### Additional context

**Known workaround** is to escape the variable contents:

```bash
LOG_FILE_PATH="\"/dev/stderr\"" ./iroha
```

Also, it would nice if this variable is included into `docker-compose.yml` files located in the repo - thus it will be covered with tests, I guess.

**Comment by adaagava** [comment]
Actual. 
Works correctly with 
`    "LOG_FILE_PATH": "/dev/stdout",` in config file,
but failed from command prompt.
