### ISSUE TITLE
Expression enhancement

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2904]
The original intention behind introducing ISI was to allow encoding arbitrary logic using a fixed set of blockchain-specific instructions. These should be suitable for blockchain applications, and as such tailored to financial calculations. We must, as such implement the missing functionality, such that it is possible to both optimise the instruction pipelining, as well as replace some simple use cases for WASM using ISI.

**Comment by appetrosyan** [comment]
Potentially superseded

**Comment by mversic** [comment]
closed in favor of #3937
