### ISSUE TITLE
[suggestion] Iroha Genesis migration tool

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2920]
### Feature request

Iroha 2 needs a migration tool that can convert between the several versions of the `genesis.json` file.

### Motivation

The Genesis format can periodically change. As a result, we may see errors like this one:

```
iroha0_1  | Error: Failed to deserialize raw genesis block from "config/genesis.json"
iroha0_1  | 
iroha0_1  | Caused by:
iroha0_1  |     missing field `object` at line 18 column 11
iroha0_1  | 
iroha0_1  | Location:
iroha0_1  |     …/iroha/core/src/genesis.rs:266:41
```

### Who can help?

@mversic @appetrosyan

**Comment by QuentinI** [comment]
Done in [iroha-squash](https://github.com/QuentinI/iroha-squash)
