### ISSUE TITLE
[suggestion] Simplify JSON deserialization further

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2922]
### Feature request

Consider extending the shorthand syntax to include the following case: 
```json
"Register": {
	"Identifiable": {
		"NewAssetDefinition": {
			"id": "sapporo#neverland",
			"value_type": "Quantity",
			"mintable": "Infinitely",
			"metadata": {}
		}
	}
}
```

where the Identifiable is obvious from internal representations. We can't (at this point in time), register anything that isn't part of the `IdentifiableBox` `enum`. So we could extend the idea due to @Arjentix to shorten the syntax: 

```json
"Register": {
	"NewAssetDefinition": {
		"id": "sapporo#neverland",
		"value_type": "Quantity",
		"mintable": "Infinitely"
	}
}
```

### Motivation

Shorter syntax ⇒ less space for large genesis blocks ⇒ less work. 

### Who can help?

@appetrosyan

**Comment by pesterev** [comment]
I think it would also be convenient to use a single writing style - `snake_case` or `PascalCase`. Currently uses both styles.

**Comment by appetrosyan** [comment]
I think it's actually good to use different styles for different entities.
