### ISSUE TITLE
[suggestion] Error message improvement for the configuration parser

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2926]
### Feature request

`iroha_client` crate that is used by Iroha Blockchain Explorer [backend](https://github.com/soramitsu/iroha2-block-explorer-backend) can throw an error error that may be extended with hints on how to fix it.

```
Error: failed to parse client config file: ./config.json

Caused by:
    Algorithm not supported at line 6 column 4

Location:
    src/main.rs:72:18
```

I believe it to be related to the private key config, specifically, either the `digest_function` or `payload`.

This issue is related to [BCE-backend#33](https://github.com/soramitsu/iroha2-block-explorer-backend/issues/33) I have added before.

### Motivation

Giving hints on configuring the public and private key may be helpful, because current error doesn't tell the user how to proceed.

**Comment by appetrosyan** [comment]
Duplicate
