### ISSUE TITLE
Migration tool

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2932]
For smooth upgrades, one needs to be able to migrate the versioned transactions from the old standard to the new preferably ensuring that the operations are handled automatically when it is safe to do so, but with human intervention requested when that is necessary.

**Comment by mversic** [comment]
related #2920

**Comment by pesterev** [comment]
As you know, the Client CLI accepts and executes JSON instructions. I guess we should also add versions to them to avoid problems that can appear for our users.
