### ISSUE TITLE
[BUG] Events are emitted even if transaction fails

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2937]
### OS and Environment

MacOs

### GIT commit hash

52dc18cd81bdc1d1906ffeecb666dd9b2eb27955

### Minimum working example / Steps to reproduce

create a transaction of multiple instructions where last one fails to execute.

### Actual result

Events are emitted for all instructions up until the first one that fails

### Expected result

No events are emitted

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

### Notes

Events should be aggregated and only emitted upon transaction successful completion otherwise they should be discarded

**Comment by Erigara** [comment]
Steps to reproduce.

1. Start Iroha peers;
2. Start listening for data events (`./iroha_client_cli events data`);
3. Put following into `instructions.json`:
```json
[
    {
        "Register": {
        "Identifiable": {
            "NewAccount": {
            "id": "anton@wonderland",
            "signatories": [
                "ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
            ]
            }
        }
        }
    },
    {
        "Fail": {
            "message": "Failed"
        }
    }
]
```
4. Run `cat instructions.json | ./iroha_client_cli json`.
5. See if events are produced.

**Comment by Erigara** [comment]
Not reproducible on `iroha2-dev` branch, fixed by this [commit](https://github.com/hyperledger/iroha/commit/d5342a33398d7efd04bf10360abd42b97147ae84).
