### ISSUE TITLE
Fix the numbers in `test_network` based on feedback-driven analysis

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2972]
These numbers seem arbitrary. We need to have a clear idea on how to set them, and how to measure the timeouts for the types of deployment. Perhaps they should even be extracted into configuration files.

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/2969#discussion_r1032066730_

**Comment by mversic** [comment]
not so relevant
