### ISSUE TITLE
[suggestion]: Enforce that `SignaturesOf` contaings signatures for the same payload

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#2976]
### Feature request

Enforce that `SignaturesOf` contaings signatures for the same payload.

### Motivation

It would help us to find places where we might use `SignaturesOf` inconsistently.

Currently we have 2 guarantees about `SiganturesOf`:

1. This container always contains at least 1 signature
2. Each signature corresponds to a different public key 

Proposed change would essentially add 3rd grantee: 

3. Each signature corresponds to the same payload

### Who can help?

@Erigara @SamHSmith

**Comment by samsmith** [comment]
not me. perhaps @samhsmith

**Comment by Erigara** [comment]
Yeah, sorry.

**Comment by SamHSmith** [comment]
If we only used Ed25519 with sha512 hashing then we could implement this. But since we support BLS this would require modifications to URSA. Not something worth doing for a simple safety guarantee.
