### ISSUE TITLE
[BUG] When one of four peers wiped and restarted, Then it can't embed back into the network.

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#2977]
### OS and Environment

MacOS, DockerHub

### GIT commit hash

52dc18cd

### Minimum working example / Steps to reproduce

1. 
2.

### Actual result
```json
{
    "peers": 3,
    "blocks": 6,
    "txs_accepted": 14,
    "txs_rejected": 0,
    "uptime": {
        "secs": 505373,
        "nanos": 71000000
    },
    "view_changes": 0
}
```
```json
{
    "peers": 3,
    "blocks": 7,
    "txs_accepted": 15,
    "txs_rejected": 0,
    "uptime": {
        "secs": 506044,
        "nanos": 552000000
    },
    "view_changes": 0
}
```
Peer can't embed back into the network

### Expected result

Peer successfully embed back into the network.

### Logs 

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

### Who can help to reproduce?

@astrokov7

**Comment by Erigara** [comment]
This bug is not reproducible on `dev` branch due to the changes in how `sumeragi` count required number of votes to commit block ([795d91a](https://github.com/hyperledger/iroha/commit/795d91ad9602395b001f2322478180de561e64c4)).
