### ISSUE TITLE
Add Merkle Signature option

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#3]
https://en.wikipedia.org/wiki/Merkle_signature_scheme

Merkle signatures can be quantum resistant, so adding these to Iroha would be beneficial.

**Comment by amitkumarj441** [comment]
@takemiyamakoto I'm willing to take up this task.
Could you please tell me more about this issue( like where to add MSS)?

**Comment by takemiyamakoto** [comment]
Great! It should be implemented here: https://github.com/hyperledger/iroha/tree/develop/libs/crypto

**Comment by Warchant** [comment]
Is this still relevant issue?

**Comment by amitkumarj441** [comment]
Thanks @Warchant for the reminder.
I think this feature is still pending, I'll start a PR for this as suggested by @takemiyamakoto

**Comment by l4l** [comment]
Outdated, merkle tree is removed for now
New enhancement proposed in #774
