### ISSUE TITLE
Wanted create Iroha Test Connecrtion-Network 

### ISSUE THREAD

**Issue by satellitex** [hyperledger/iroha#300]
We want to test connection-network.
Connection-network means peer belong to network before setup iroha.

## additonal config.json
```
{
.
.
"leader" : leader_ip,
"isLeader" : true or false,
.
.
}
```

We should implement docker-network or docker-compose or whatever.
And add Circle-Ci test.

If above mension is can't understand, Please ask me.

**Comment by neewy** [comment]
As part of this user story https://soramitsu.atlassian.net/browse/IR-358 we plan to check the state of network.
