### ISSUE TITLE
Iroha Postgres Installation failed

### ISSUE THREAD

**Issue by kapsali29** [hyperledger/iroha#304]
Hello all,

I am trying to deploy single instance Iroha using the following docker compose script

`version: '3.4'

services:

services:

  postgres:
    image: postgres:10
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - iroha-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: mysecretpassword
    command: -c 'max_prepared_transactions=100'
    networks:
      - iroha-network

  iroha:
    image: hyperledger/iroha:latest
    hostname: iroha
    restart: always
    ports:
      - 50051:50051
    volumes:
      - blockstore2:/tmp/block_store
      - C:\Users\user\Desktop\iroha\example:/opt/iroha_data
    environment:
      IROHA_POSTGRES_HOST: postgres
      IROHA_POSTGRES_PORT: 5432
      IROHA_POSTGRES_USER: iroha
      IROHA_POSTGRES_PASSWORD: mysecretpassword
      KEY: node0
    command: -c 'max_prepared_transactions=100'
    depends_on:
      - postgres
    networks:
      - iroha-network
  

networks:
  iroha-network:
    driver: bridge

volumes:
  blockstore2:
  iroha-db:`

Postgres container was initialized correctly but Iroha container failed and the logs are the following:

`NOTE: IROHA_POSTGRES_HOST should match 'host' option in config file
wait-for-it.sh: waiting 30 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
[2019-11-07 21:31:21.320422700][I][Init]: Irohad version: 1.0.1
[2019-11-07 21:31:21.320478000][I][Init]: config initialized
[2019-11-07 21:31:21.327511700][I][Irohad]: created
[2019-11-07 21:31:21.327586300][I][Irohad/Storage]: Start storage creation
[2019-11-07 21:31:21.327644900][I][Irohad/Storage]: block store created
[2019-11-07 21:31:23.010715500][E][Init]: Failed to initialize storage`

Any thoughts and ideas would be helpful. Thanks in Advance

**Comment by junaidgirkar** [comment]
Is this issue resolved? Unable to find the solution even on Jira. Would be really grateful if someone could post a working solution here.

**Comment by 64anushka** [comment]
Is this issue resolved?
