### ISSUE TITLE
[feature]: Introduce enum for signature check

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3040]
Currently iroha2 returns only `true/false` for signature check and so there is no way to distinguish when transaction does not yet has enough signatures, or when transaction signature check is just wrong. 

In case of not yet enough signatures we want to put transaction into the waiting buffer and reject transaction in the second case.

So enum would look something like this `Accept/Deny/Pending`.

**Comment by mversic** [comment]
superseeded by #3526
