### ISSUE TITLE
[BUG] The default `genesis.json` doesn't work on the last `dev` branch.

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#3051]
### OS and Environment

MacOS, Docker Hub

### GIT commit hash

fbc7d346

### Minimum working example / Steps to reproduce

```bash
docker compose up
```

### Actual result

`genesis.json` did not apply. Peers did not rise.

### Expected result

`genesis.json` applied. 

### Logs

<details>
  <summary>Log contents</summary>
  
  ```json
iroha-iroha0-1  | Error: Failed to deserialize raw genesis block from "/config/genesis.json"
iroha-iroha0-1  | 
iroha-iroha0-1  | Caused by:
iroha-iroha0-1  |     data did not match any variant of untagged enum ExpressionDeserializeWrapper at line 246 column 9
iroha-iroha0-1  | 
iroha-iroha0-1  | Location:
iroha-iroha0-1  |     /iroha/core/src/genesis.rs:254:41
  ```
</details>

### Who can help to reproduce?

@astrokov7

### Notes

Problem is reproducible. [This](https://github.com/hyperledger/iroha/blob/iroha2-dev/configs/peer/genesis.json) genesis doesn’t work.

**Comment by ronaldaraujo** [comment]
Hi, @astrokov7. Do you have a solution for this?

**Comment by mversic** [comment]
> Hi, @astrokov7. Do you have a solution for this?

yes, you can re-generate the default genesis with 
`cargo run --bin kagami -- genesis > configs/peer/genesis.json`

**Comment by astrokov7** [comment]
> Hi, @astrokov7. Do you have a solution for this?

Just update docker image `docker pull hyperledger/iroha2:dev`
