### ISSUE TITLE
Map transaction hash to block hash in `wsv`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3063]
I've noticed that we're storing hashes of all transactions in `wsv` as a `DashSet<HashOf<VersionedSignedTransaction>>`. Since we're doing that, I would recommend that we store a mapping `DashMap<HashOf<VersionedSignedTransaction>, HashOf<VersionedCommittedBlock>>` which would greatly seed up the search for a transaction in the blockchain. Currently we're searching the entire blockchain for the transaction based on the hash

**Comment by appetrosyan** [comment]
Excellent point. Don't think it's a Question though.
