### ISSUE TITLE
[documentation] Changing the dev activity note in Iroha 1 documentation to a warning

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3070]
### Documentation URL(s)

https://github.com/hyperledger/iroha/blob/main/docs/source/index.rst

### Description

Currently, the documentation claims that I1 and I2 development happens in parallel, while the core team is focused on Iroha 2. This needs an update, so the users are not misdirected towards using I1 in new projects.

### Your suggestions

I have an updated text in mind. First of all, it should be a `warning`, not an `info` block, secondly, it has to be on the top.
Finally, I believe it should look like this to reflect the current state of development:

    Please note that support for Hyperledger Iroha v1 is limited because it's no longer actively developed.

    The core team focuses on Hyperledger Iroha v2, a complete rewrite of Iroha in Rust.

    These versions are incompatible, so you will have to use Iroha 2 instead of Iroha 1 for the new projects.
    You can read about the differences in the Iroha 2 documentation.

### Who can help?

@outoftardis

**Comment by outoftardis** [comment]
Addressed in #3071
