### ISSUE TITLE
[suggestion]: Disallow invalid transactions in genesis block

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3075]
Let me rephrase. If a transaction in a genesis fails we seem to just skip it and log error. Why don't we fail blockchain initialization if there is even one invalid transaction?

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/3074#discussion_r1084054877_

**Comment by mversic** [comment]
The point here is, why do we tolerate invalid transactions in the genesis block? IMHO genesis block should be rejected entirely if it contains even one invalid transaction.

I would like to hear others opinion on this matter. Can you come up with a reason where it's expected to find invalid transaction in the genesis block?

**Comment by Erigara** [comment]
I can't find reason for such behavior especially when in almost all cases our genesis block has exactly 1 transaction.

**Comment by timofeevmd** [comment]
Done

![image.png](https://images.zenhubusercontent.com/6454ddfaa513c57f8883fb16/861dbb70-ac45-4fa1-bdca-c27bbe4d2bef)

**Comment by Erigara** [comment]
I think we can close this since it was verified by @timofeevmd.
