### ISSUE TITLE
[suggestion] `DoAs` instruction

### ISSUE THREAD

**Issue by QuentinI** [hyperledger/iroha#3085]
### Feature request

Introduce an instruction combinator that would execute underlying ISIs on behalf of another account.

### Motivation

Primarily comes from my needs for squash tool: there is no way to preserve information about account registering an asset when squashing blockchain state to a genesis block, since all transactions in genesis block are executed as if submitted by genesis account - and this information is frequently relied on by validators.

**Comment by Arjentix** [comment]
While I understand the motivation, I wonder if this can be avoided by registering asset from genesis and then giving a permission token with full access to the original owner?

This is not quite equal to being an asset creator, but should work

**Comment by QuentinI** [comment]
@Arjentix it would work with our predefined validators and tokens, yes, but in general case we don't know anything about validators or permission tokens defined in the blockchain.

**Comment by Arjentix** [comment]
@QuentinI , makes sense. Then what about introducing `TransferOwnership` instruction? Could be useful not just in genesis.

**Comment by QuentinI** [comment]
@Arjentix `DoAs` could also be useful in some contexts I suppose, but I really like your idea. We could do it by just implementing `Transfer` for `AssetDefinition` and basically avoid introducing a new ISI at all.

**Comment by Arjentix** [comment]
@QuentinI , yeah, `Transfer` for `AssetDefinition` sounds good. But may be we are missing another good point of `DoAs` which can't be implemented like this? Are there any other pros of `DoAs`?

**Comment by QuentinI** [comment]
@Arjentix I imagine in a private blockchain you could have an administrator/support account that would be permitted to execute `DoAs` to do stuff on behalf of users, although I don't know enough to say if it makes sense in any potential real-world applications.

**Comment by Arjentix** [comment]
@QuentinI , in that case Blockchain owners can just allow admin account to execute any instruction.
`DoAs` still will show, who submitted this transaction, so everybody will know, that in fact it was the admin who did this. That's the same as allowing all admin instructuons

**Comment by QuentinI** [comment]
@Arjentix duh, that's right. In that case the only usecase for `DoAs` I can imagine is temporarily giving someone else permissions to do stuff with user's account without giving up the keys. Don't know if it's at all useful.

**Comment by QuentinI** [comment]
Anyways, I'm in favor of implementing `Transfer` for `AssetDefinition`

**Comment by Arjentix** [comment]
@QuentinI that's possible with permission tokens and runtime validators, which I'm working on right now.

So, I believe, if @appetrosyan agrees, we can close this issue and open a new one with `Transfer<AssetDefinition>` implementation

**Comment by appetrosyan** [comment]
This can solve the problem that @Mingela had. He would still need to squash the blockstore, and update the schema, but having this instruction means that it's not possible to end up in that situation in the future.

**Comment by appetrosyan** [comment]
Closing this issue.

**Comment by QuentinI** [comment]
@appetrosyan you mean in favor of `Transfer<AssetDefinition>`? Should I create that one?
