### ISSUE TITLE
[suggestion] Report predicates that attempt to filter blocks by height

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3095]
### Feature request

And/xor: 
1) Make `Predicate::SemiInterval<u64>` accept `Value::Block` or 
2) Make `Predicate::SemiInterval<u64>` issue a warning and redirect to documentation on how to use the Block Streaming API. 

### Motivation

Currently, the `FindAllBlocks` query can only return the full block store. Combined with pagination and the ability to discard it's possible to retrieve a specific range of blocks. We also have the `data_model::predicate` system, which suggests that it is possible to retrieve blocks with a specific height, by applying `predicate::SemiInterval<u64>` to `Value::Block`. 

The best option is to not encourage a misuse of the API too much with clear and immediate feedback (Option 2 only). 

Option 1 is an expected use of the API, and it falls intuitively into what people expect to be possible (@Mingela ), but it will lead to a performance degradation because of how the predicate API works (it's not lazy, it does instantiate the entire return value in memory before sending it via pagination (which is lazy)), so I'd recommend adding Option 2 to the full implementation. 

### Who can help?

@appetrosyan

**Comment by mversic** [comment]
not relevant anymore
