### ISSUE TITLE
View changes in idle conditions

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3103]
The whitepaper states that once a valid set `A` is found it should be kept, i.e. not mixed with set `B` until there is a consensus failure. From a performance perspective this makes sense, we don't want to waste time on determining non-faulty peers that comprise set `A` on every `sumeragi` round

The question is whether we want to do view changes when there are no transactions. Current situation is such that we do view changes every time a block isn't produced in due time. A block may not be produced because of faulty peers in set `A` or because there are no transactions.

#### Benefits
* mitigates censorship - otherwise the same set of nodes (namely the set `A`) will always be validating peers unless one of the nodes becomes faulty. Low contention is the perfect time to bring in observing nodes to consensus and, consequently, recreate sets `A` and `B`. Mitigating censorship is the reason why we change set `A`peer roles as per the whitepaper
* negligible performance impact

#### Downsides
* to be discussed

[This](https://github.com/hyperledger/iroha/pull/3097#discussion_r1092428102) discussion is relevant

**Comment by Erigara** [comment]
One downside i observed so far is that if idle state continues for large amount of time view change proofs we send with every message became bigger and bigger slowing down message processing. 
Situation will be better after #3110 where i use more efficient way to merge view changes, but problem still there.
Maybe we should reconsider how we transfer proofs.

**Comment by mversic** [comment]
Since the #3166 bug we're not doing view changes on idle. Should we or should we not can still be discussed in this ticket

**Comment by mversic** [comment]
not relevant anymore
