### ISSUE TITLE
Retrieving the user in Iroha smart contracts

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3137]
Yesterday, `dhawkmoon` in the Hyperledger Iroha community [requested](https://t.me/hyperledgeriroha/25929) information on Iroha 1 smart contract support while working on a legacy Iroha 1 Burrow integration for smart contracts using [Solidity](https://soliditylang.org/).

`dhawkmoon` asked if there is a way to get the login of smart contract caller (`foo@bar`) inside a smart contract to check permissions based on the caller's role (to make a delegation call to the service contract).

There's an alternative question in case that does not work: is it possible to retrieve the caller's account using the `msg.sender` property?

------

@baziorek replied that Iroha 1 has an API that [wraps](https://iroha.readthedocs.io/en/develop/develop/api.html) Iroha commands and queries.

He said that when a programmer uses multiple commands wrapped that way, they will be unable to find out which command failed and why. He had also recommended [this page](https://github.com/hyperledger/iroha/tree/main/example/burrow_integration) to `dhawkmoon`.

----

If you have time to comment, please do, @iceseer. Thanks in advance for your comments on this request.

**Comment by appetrosyan** [comment]
Unfortunately Iroha v1 is in maintenance mode, unlikely to be addressed, given lack of interest, the issue is closed.
