### ISSUE TITLE
[suggestion] Sorting numeric values

### ISSUE THREAD

**Issue by pesterev** [hyperledger/iroha#3139]
### Feature request

I'd like Iroha2 to sort numeric values.

### Motivation

After merging #3118, we can sort any values that contain metadata because Iroha sorts by a metadata key. But numeric values don't have metadata. There is a suggestion to sort numeric values always regardless sorting key (but if this key is specified in query parameters).

### Who can help?

@appetrosyan @pesterev

**Comment by appetrosyan** [comment]
Context: 
#3118 assumes that values are either `Asset` s (not `AssetDefinition` s) **xor** `HasMetadata`. This assumption might be violated in the future. I propose relaxing this condition to is `Asset` **or** `HasMetadata`, such that further asset types, e.g. specialised NFTs can be sorted by metadata key. 

Sorting of numerical values by their value was not exactly my suggestion. But if it is easier to implement I have no principal issue with it. Sorting of enums is going to access all values regardless, and most of the overhead is in the hash function for strings, so adding sub-sorting by numerical values is unlikely to affect performance. 

While this is not likely to come up with our current implemetation of the queries API, when GraphQL #1455  is introduced, we might have vectors of heterogeneous data returned as query results.
