### ISSUE TITLE
Visualization tools for iroha2 behavior and data flow before each release

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#3150]
we should use it as a QA process

**Comment by mversic** [comment]
it's a flow chart describing a process of releasing Iroha version

**Comment by AlexStroke** [comment]
found existing
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazFYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2c707912eca4bf8f5ad32a634aa84aaa47724c30/image.png)

**Comment by AlexStroke** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1prIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f3302f855eccdaa2e2bbda4616de99b5daa3fa26/image.png)
