### ISSUE TITLE
[feature] Limit name lengths and characters for `account`, `domain` and `asset` instances

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3154]
### Feature request

If Iroha 2 limits the name lengths for `domain`, `account` and `asset` instances to 256 UTF-8 characters, it'd be possible to avoid blockchain desync behaviours caused by longer names. Said length should be useful enough, for example:

`cbbcddbce_dcecde_dec_ecbb_ddddaedabcdded_da_dd___e_bbd_debcabebdbeaebcaabdca_eeeba_a_ddceeaedeb_ecad_cbceebddd_b_ebdecb_d_aa_a_bbc_eaceece_eae_edb__ecadacae_cdaeace_ede_aeadad__cbbc_ac_ee_ae_cdbbe_e__cbedc__ebdaed__abaaed_ebbba_ccebbceaa_ed_abedeeacddeaeae`

Later, we'll also restrict the symbols being used in the names:

- `@` character is reserved for `account@domain` constructs
- `#` character is reserved for `asset#domain` constructs
- `$` character is reserved for `trigger$domain` constructs
- `%` — for `validator%account`
- **Do we use anything else or mix some of those?**
- Whitespaces will be excluded because most people can't visually distinguish a non-breaking space from a space or four spaces from a tab.
- `;` and the greek question mark (`;`) have to go
- we need to have all the special characters that we use also enumerated
- `::` will probably be reserved for subdomains, while a single `:` is forbidden for the safety reasons

**These rules should be formalized at a later point**. A formal model will allow us to have a well-understood solution that remains the same.

**Comment by mversic** [comment]
this can be done via custom parameters now
