### ISSUE TITLE
[BUG] Block Stream doesn't emit blocks when requested height is 0

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3162]
### OS and Environment

macOS 13.1 (22C65)

### GIT commit hash

fe826be8

### Minimum working example / Steps to reproduce

- Save the JS file into `bundle.js` - https://pastebin.com/NZ0a8wFV
  It is a dependency-free JavaScript bundle with rolled up `iroha-javascript` code responsible for handling Block Stream API and a simple workflow to reproduce the bug at the very end of the bundle.
- Run Iroha in any way you like it.
- Run `bundle.js` with Node.js 16/18:
  ```shell
  DEBUG=@iroha2* node bundle.js \
    // optionally pass Torii API URL
    http://localhost:8080
  ```
- See "Block stream is ready" message in console
- Commit some block into Iroha and see what is printed from the script

### Actual result

Nothing is printed - Iroha doesn't send any messages via WebSocket.

### Expected result

I expected Iroha to send committed blocks.

### Logs in JSON format

I can't provide you with any useful logs.

**Comment by 0x009922** [comment]
New context: it works if requested `height` is greater than 0.

**Comment by Erigara** [comment]
Problem is following `kura` try to get block with height `0`, see nothing and return `None`. 

@0x009922 suggested to change height from `u64` to `NonZeroU64` since valid range starts from 0.
