### ISSUE TITLE
Runtime Validators CI check

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3224]
Right now we check our *default* Runtime Permission Validators (stored in `permission_validators` folder) by running `cargo check` in `cli/build.rs`.

This is not the best way to do it. We should replace this check with CI check.

If some developers wants to know if they break permission validators in developement stage and not in CI stage, then they can just modify their *pre-commit hook*.

**Comment by mversic** [comment]
@Arjentix this seems irrelevant by now? if so, can you close it?
