### ISSUE TITLE
Consider a way to ensure that every ISI has a Validator

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3239]
I'm not sure if this is even possible, but it's very desirable. Right now we can not be sure that existing validators covers all functionallity. We should try to figure out how we can automatically check this.

I like the way I did it in traits system for permission tokens in validators. When developer derives `Token` they should also implement `Validate` which requires `validate_grant()` and `validate_revoke()`. This way we can be sure, that every token has a validation for `Grant` and `Revoke` (which was a big problem before, because we often didn't check `Revoke`).

Maybe it will be not possible to do that in type or traits system. But there can be another way. Maybe with some tool which we can run in CI or something like that.

**Comment by mversic** [comment]
@Arjentix is this still relevant?
