### ISSUE TITLE
Add a way to get owner of `AssetDefinition`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3252]
Originally discussed [here](https://github.com/hyperledger/iroha/pull/3106#discussion_r1104082014).

In #3106 I've introduced a new query just to get bool if an account is an asset defintiion creator, because current `FindAssetDefinitionById` does not provide information about creator. Creator is stored in `AssetDefinitionEntry` inside `WSV`

@mversic  suggests to  replace `FindAssetDefinitionById` return type to `AssetDefinitionEntry`.
@Erigara suggests to add creator information into `AssetDefinition`.

Let's discuss it here and then implement.

**Comment by Arjentix** [comment]
If we implement new way after perming #3106, then we need to remove `IsAssetOwner` query

**Comment by Erigara** [comment]
Already implemented. `AssetDefinition` contains it's owner.

**Comment by mversic** [comment]
implemented in #3442
