### ISSUE TITLE
`kagami` library

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3253]
Turn's out we need a way to get kagami output inside other crates.

We can do it by implementing `kagami` as not just binary but also a library.

**Comment by mversic** [comment]
the other crate being `core/test_network`. Are we planning to get rid of this crate when restructuring integration tests?

**Comment by mversic** [comment]
specifically, it looks like we need the generated `genesis.json`

**Comment by Arjentix** [comment]
After dicsuccion with @appetrosyan , we decided that it does't worth it. Better to wait for Python tests
