### ISSUE TITLE
Type inference for triggers and validators

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3260]
Originally suggested by @mversic [here](https://github.com/hyperledger/iroha/pull/3106#discussion_r1115262135).

We can infere the type of input parameters by looking at function parameter type names. It won't work in 100% cases because user can name his type the same way or do something else. So we need to keep the old system as well, but make it optional.

## Example

Old:

```rust
#[entrypoint(params = "[query]")]
pub fn validate(_: QueryBox) -> Verdict {
    Verdict::Deny("No queries are allowed".to_owned())
}
```

New:

```rust
#[entrypoint]
pub fn validate(_: QueryBox) -> Verdict {
    Verdict::Deny("No queries are allowed".to_owned())
}
```

**Comment by mversic** [comment]
Another option is to not pass them as arguments to an `entrypoint` function but to give the user methods such as `get_authority`/`get_event`/`get_operation`/... to query directly. In this case we should cache results from these function calls as static variables. I think this is inferior solution and not worth further consideration

**Comment by mversic** [comment]
this is no longer applicable
