### ISSUE TITLE
Rename `_iroha_wasm_main()` for triggers and validators

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3263]
Originally suggested by @mversic [here](https://github.com/hyperledger/iroha/pull/3106#discussion_r1119633398).

The idea is to rename `_iroha_wasm_main()` to:

1. `_iroha_trigger_main()` -- for triggers;
2. `_iroha_validator_main()` -- for validators.

This will require changes on both Iroha side and procedural macros side.

**Comment by mversic** [comment]
no, my suggestion was to have only one name `_iroha_wasm_main` instead of multiple different
