### ISSUE TITLE
[refactor]: Replace `thiserror` with `derive_more`

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3267]
We could consider replacing `thiserror` with `derive_more`, given that this pattern would be covered with `derive_more::From`, and we can derive `Display` independently from `error`.

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3138#discussion_r1113756103_

`thiserror::Error` could be replaced with combination of `derive_mode::Error/Display/From`.
This will give us more convenient way to derive `From` impls.

**Comment by mversic** [comment]
@DCNick3 addressed the main concern
