### ISSUE TITLE
[suggestion]: Unambiguous schema names

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3268]
## Motivation

This PR is largely an under-the-hood improvement, yet the SDKs must do extra work to account for the change of the locations of `Block` structures. No semantic changes took place, yet work must be done manually. 

If all schema types have unambiguous names, we can drop the qualified path, and never have to worry about it.

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3138#discussion_r1113743083_

**Comment by arndey** [comment]
From the point of view of the kotlin/java SDK deleting paths will not add convenience to us

**Comment by mversic** [comment]
In the generated `schema.json` structure names are always fully qualified
