### ISSUE TITLE
Generate a JSON file with the last structures of all ISI

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#3274]
### Feature request

Generate a JSON file containing the last examples structures of all existing ISI instructions from the code located at core/src/smartcontracts/isi/ for testing purposes, similar to the genesis.json? 

### Motivation

I require this to construct user's instructions that have not yet been added to the client_cli.

### Who can help?

@astrokov7

**Comment by pesterev** [comment]
@astrokov7 
#3398 adds a new subcommand to kagami that you can pipe to `iroha_client_cli`.

```bash
./kagami examples create-account --account-id "test123@wonderland" | ./iroha_client_cli json
```

This feature should help you to reproduce use cases from [these tests](https://github.com/hyperledger/iroha-java/blob/iroha2-dev/modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt#L476)
