### ISSUE TITLE
`kagami new` command

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3283]
It was originally suggested by @QuentinI [here](https://github.com/hyperledger/iroha/pull/3106#pullrequestreview-1318899224) and reworked by me [here](https://github.com/hyperledger/iroha/pull/3106#issuecomment-1451757314).

We need some new sub-commands for `kagami`:

- `kagami new --smartcontract`
- `kagami new --trigger`
- `kagami new --validator`

They will create appropriate **Rust** projects, just like `cargo new` does.

This will help us and users. However it will require addinitional energy to properly support this instrument.

**Comment by appetrosyan** [comment]
@ilchu Create an issue with the results of the discussion and close this.

**Comment by ilchu** [comment]
Closing in favor of #3773.
