### ISSUE TITLE
Investigate if `RawGenesisBlock` is needed in schema

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3284]
this might be the only struct that is not part of the data model which derives `IntoSchema`. As far as I remember there was some reason why sdk devs need it

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/3138#discussion_r1127464124_

**Comment by appetrosyan** [comment]
@0x009922 @arndey ?

**Comment by 0x009922** [comment]
AFAIK `RawGenesisBlock` was used in the genesis tool GUI, which builds genesis JSON. Since JavaScript SDK only uses schema for SCALE coding, not JSON, I don't see a need for this structure to be in the schema.

**Comment by QuentinI** [comment]
Not used in iroha-python as far as I can see.
