### ISSUE TITLE
[bug] Make `iroha_wasm` dependent crates testable

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3292]
## Problem

Current implementation of `iroha_wasm` crate makes it impossible to test crates which use `iroha_wasm` as a dependency.

The problem is in `panic_hadler` and `error_alloc_handler`. They are not usable with `cfg(test)` and we have this conditional compilation in `iroha_wasm` it-self. However dependent crates always gets this handlers from `iroha_wasm` so that `cargo test` or `cargo check --tests` will always fail.

## Proposed solution

After a discussion with @appetrosyan we decided to remove these handlers from `iroha_wasm` and provide them inside macro which will be called on user-side.
Users won't be able to compile their crates for `wasm32-unknown-unknown` without these handlers, so they will probably don't forget about our macro. Also in #3283 we will insert this macro invokation in the default template.

**Comment by mversic** [comment]
there is [this](https://docs.rust-embedded.org/book/start/panicking.html) option to rely on external crates
