### ISSUE TITLE
Move "atleast one signature" validation out of `SignaturesOf`

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#3295]
I am retiring the invariant of SignaturesOf which states that the structure must contain at least one signature. I'm doing this because the new topology needed a way to clear the signatures. Since `tx.rs` is the only place this invariant is used the code that is enforcing the invariant should be moved out of SignatureOf and into `tx.rs`.

**Comment by mversic** [comment]
The invariant was removed [here](https://github.com/hyperledger/iroha/pull/3250/files#diff-fd0293ea1784f925a76c6cd0f336b9d20d05a451b6c228dc221d4a15b14c070d) following [this](https://github.com/hyperledger/iroha/pull/3250#discussion_r1131099891) discussion.

Removing this invariant might have adverse effect on other parts of the codebase. As far as I can see this invariant is relied upon during deserialization of `SignaturesOf`. Considering recent changes made by @Erigara that enforce validity invariants more strictly during consensus this might not be relied on anymore

Changes such as these that potentially have non-local effects can introduce logical errors or even worse UB. A more strict auditing process should be mandatory in cases such as this
