### ISSUE TITLE
[client_cli] Update MST commands

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3305]
### Feature request

Update `iroha_client_cli` to be able to mint public keys to an account. 

### Motivation

The currently accepted way of creating a multisignature transaction does not explain enough about how to use MST. We need to update the info, and ensure that community members know how to use Multisignature transactions. 

### Who can help?

@erigara

**Comment by appetrosyan** [comment]
Check we can do this with `iroha_client_cli -j`

**Comment by mversic** [comment]
we're going to go with using json file for input of `iroha_client_cli` instead of flags
