### ISSUE TITLE
Update or remove `docs/source/guides/develop-iroha-module.md`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3308]
This doc is heavily outdated

# Who can help
@6r1d @outoftardis

**Comment by outoftardis** [comment]
There was a [comment from Aleksandr](https://github.com/hyperledger/iroha/pull/2872/files#r998384802) a few months back:

> This guide should be revised. Preferably once we have decided the shape in which modules will be implemented.

Was such a decision made?
