### ISSUE TITLE
[suggestion] Check for `TODO` items in CI

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3312]
### Feature request

Identify all `TODO` items in CI and produce them as comments, so we can use `reference in new issue` to quickly associate a ticket to every TODO item intrdocued after fixing this issue. 

### Motivation

We often introduce `TODO` items in PRs, and sometimes forget to resolve them, or stall a PR until a TODO item is resolved. We can decouple these processes. 

### Who can help?

@appetrosyan

**Comment by mversic** [comment]
close in favor of manual review
