### ISSUE TITLE
[client_cli] Add flag to wait for consensus and transaction to be committed to block

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3313]
### Feature request

Add an extra command-line flag to wait for consensus and confirm that the transaction passed 
e.g. 
```bash
./iroha_client_cli 
--wait-consensus -w 
```

### Motivation

During the discussion of the internal testing framework, we found that instead of using the event system, we often just used polling to identify if a transaction was genuinely accepted and passed consensus. 

This would not be necessary if `iroha_client_cli` could block until it received the response from the Iroha node, as it would if it were a separate process. 

### Who can help?

@appetrosyan

**Comment by Erigara** [comment]
@appetrosyan currently `iroha_client_cli` uses `submit_blocking` which wait (through events) for transaction to be committed.

**Comment by mversic** [comment]
might be relevant for python client tests. Closing in favor of #1233
