### ISSUE TITLE
[documentation] Update the Dockerhub doc and tags

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3314]
### Documentation URL(s)

Dockerhub repositories for [`Iroha 1`](https://hub.docker.com/r/hyperledger/iroha) and [`Iroha 2`](https://hub.docker.com/r/hyperledger/iroha2).

### Description

Our Dockerhub documentation needs to be updated.

* Doc for V2 repo [is empty](https://hub.docker.com/r/hyperledger/iroha2)
* It's hard to distinguish between Iroha 1 and Iroha 2, as both are pretty different. No disclaimers say anything like "this repo is for V1, and this is for V2". No links tell something akin to "you need to go here for this version".
* "Images description" part does not point to versions of Iroha
* A link to the documentation for v1 repo, "https://iroha.readthedocs.io/en/latest/", is dead.
* "Maintained by" line seems unnecessary.
* Nobody's using Gitter, and it's first in the contacts list.
* I do not know if Rocketchat is alive, but it is also in the contacts list.

My reason here is that people will build their configurations. That's one of the first things I did when I started working on Iroha 2.

### Your suggestions

After agreeing on the text and replacing it, I'd like to completely rewrite both and discuss the results with @WRRicht3r and @outoftardis.

**Comment by 6r1d** [comment]
I want to change [Iroha 1 page](https://hub.docker.com/r/hyperledger/iroha) as written below.

-------------

The purpose of this repository is to store Hyperledger Iroha version 1.

### Quick reference

To get help, visit the official [Telegram](https://github.com/hyperledger/iroha
) and the `iroha` channel on [Hyperledger Discord](https://discord.gg/hyperledger)

To file issues, visit the ["reporting bugs"](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) page.

Supported Architectures: amd64.

Supported OS: Linux.

### Image description

| Image | Description |
| -------- | --------------- |
| `latest` | the last stable release, contains the stable version of Iroha 1 |
| `master` | image that contains cutting edge version of Iroha 1 built from the `master` branch |
| `develop-build` | image that contains dependencies for building Iroha built from the `master` branch |
| `1.*.*` | See Iroha releases. An image that is built from the release tag. |

### Supported tags and respective Dockerfile links

| Tag | Description |
| -------- | --------------- |
| `latest` | `docker/release/Dockerfile` |
| `master` | `docker/release/Dockerfile` |
| `develop-build` | `docker/develop/Dockerfile` |
| `1.*.*` | `docker/release/Dockerfile` |

**Comment by 6r1d** [comment]
I want to change [Iroha 2 page](https://hub.docker.com/r/hyperledger/iroha2) as written below.

--------

The purpose of this repository is to store Hyperledger Iroha version 2.

### Quick reference

The documentation is available on a dedicated [GitHub page](https://hyperledger.github.io/iroha-2-docs/).

To get help, visit the official [Telegram](https://github.com/hyperledger/iroha) and the `Iroha` channel on [Hyperledger Discord](https://discord.gg/hyperledger)

To file issues, visit the ["reporting bugs"](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) page.

Supported Architectures: amd64.

Supported OS: Linux.

### Image description

| Image | Description |
| -------- | --------------- |
| [`lts`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=lts) | image that contains the long-term support build of Iroha 2 |
| [`stable`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=stable) | image that contains cutting edge version of Iroha 2 built from the `stable` branch |
| [`dev`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=dev) | image that contains the most recent, unstable build from the `dev` branch |

(Should we mention tags like `dev-nightly`, `kagami-dev-nightly`, `kagami-lts`, `kagami-stable`, `client-cli-lts`, `client-cli-stable`?)

### Supported tags and respective Dockerfile links

| Tag | Description |
| -------- | --------------- |
| `latest` | `docker/release/Dockerfile` |
| `master` | `docker/release/Dockerfile` |
| `develop-build` | `docker/develop/Dockerfile` |
| `1.*.*` | `docker/release/Dockerfile` |

**Comment by 6r1d** [comment]
I want to change [bug report guide](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) as written below.

-----------------

Reporting Bugs
~~~~~~~~~~~~~~

*Bug* is an error, design flaw, failure or fault in Iroha that causes it to produce an incorrect or unexpected result or to behave in unintended ways.

Bugs are tracked as [GitHub issues](https://github.com/hyperledger/iroha/issues). Please follow the instructions in the template, fill in the fields you requested, and mark the correct version of Iroha that maintainers should check in the tags!

**Comment by WRRicht3r** [comment]
> I want to change [Iroha 1 page](https://hub.docker.com/r/hyperledger/iroha) as written below.
> 
> The purpose of this repository is to store Hyperledger Iroha version 1.
> 
> ### Quick reference
> Due to maintenance, fresh builds are available in the temporary [Read the Docs](https://iroha-1-fork.readthedocs.io/en/latest/) page. Generally, documentation is available on [Read the Docs](https://iroha.readthedocs.io/en/develop/).
> 
> To get help, visit the official [Iroha Telegram channel](https://github.com/hyperledger/iroha) and the `Iroha` channel on the [Hyperledger Discord](https://discord.gg/hyperledger)
> 
> To file issues, visit the ["reporting bugs"](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) page.
> 
> Supported Architectures: `amd64`.
> 
> Supported OS: `Linux`. (**What Linux distributions should we mention, if any?**)
> 
> ### Image description
> Image	Description
> `latest`	the last stable release, contains the stable version of Iroha 1
> `master`	an image that contains the cutting-edge version of Iroha 1 built from the `master` branch
> `develop-build`	an image that contains dependencies to build Iroha from the `master` branch
> `1.*.*`	See Iroha releases. An image that is built from the release tag.
> ### Supported tags and respective Dockerfile links
> Tag	Description
> `latest`	[`docker/release/Dockerfile`](https://github.com/hyperledger/iroha/blob/main/docker/release/Dockerfile)
> `master`	[`docker/release/Dockerfile`](https://github.com/hyperledger/iroha/blob/main/docker/release/Dockerfile)
> `develop-build`	[`docker/develop/Dockerfile`](https://github.com/hyperledger/iroha/tree/main/docker/develop)
> `1.*.*`	[`docker/release/Dockerfile`](https://github.com/hyperledger/iroha/blob/main/docker/release/Dockerfile)

**Comment by WRRicht3r** [comment]
> I want to change [Iroha 2 page](https://hub.docker.com/r/hyperledger/iroha2) as written below.
> 
> The purpose of this repository is to store Hyperledger Iroha version 2.
> 
> ### Quick reference
> The documentation is available on a dedicated [GitHub page](https://hyperledger.github.io/iroha-2-docs/).
> 
> To get help, visit the official [Iroha Telegram channel](https://github.com/hyperledger/iroha) and the `Iroha` channel on the [Hyperledger Discord](https://discord.gg/hyperledger)
> 
> To file issues, visit the ["reporting bugs"](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) page.
> 
> Supported Architectures: amd64.
> 
> Supported OS: Linux.
> 
> ### Image description
> I want to change [Iroha 2 page](https://hub.docker.com/r/hyperledger/iroha2) as written below.
> 
> The purpose of this repository is to store Hyperledger Iroha version 2.
> 
> ### Quick reference
> The documentation is available on a dedicated [GitHub page](https://hyperledger.github.io/iroha-2-docs/).
> 
> To get help, visit the official [Iroha Telegram channel](https://github.com/hyperledger/iroha) and the `Iroha` channel on the [Hyperledger Discord](https://discord.gg/hyperledger)
> 
> To file issues, visit the ["reporting bugs"](https://github.com/hyperledger/iroha/blob/main/CONTRIBUTING.rst#reporting-bugs) page.
> 
> Supported Architectures: `amd64`.
> 
> Supported OS: `Linux`.
> 
> ### Image description
> Image	Description
> [`lts`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=lts)	An image that contains the long-term support build of Iroha 2
> [`client-cli-lts`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=client-cli-lts)	A separate container for [`iroha_client_cli`](https://hyperledger.github.io/iroha-2-docs/guide/bash.html) tool
> [`kagami-lts`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=kagami-lts)	A separate container for the [`kagami`](https://hyperledger.github.io/iroha-2-docs/guide/glossary.html#kagami-teacher-and-exemplar-and-or-looking-glass) tool
> [`stable`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=stable)	An image that contains the cutting edge version of Iroha 2 built from the `stable` branch
> [`client-cli-stable`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=client-cli-stable)	A separate container for the [`iroha_client_cli`](https://hyperledger.github.io/iroha-2-docs/guide/bash.html) tool
> [`kagami-stable`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=kagami-stable)	A separate container for the [`kagami`](https://hyperledger.github.io/iroha-2-docs/guide/glossary.html#kagami-teacher-and-exemplar-and-or-looking-glass) tool
> [`dev`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=dev)	An image that contains the unstable build from the `dev` branch
> [`client-cli-dev`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=client-cli-dev)	A separate container for the [`iroha_client_cli`](https://hyperledger.github.io/iroha-2-docs/guide/bash.html) tool
> [`kagami-dev`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=kagami-dev)	A separate container for the [`kagami`](https://hyperledger.github.io/iroha-2-docs/guide/glossary.html#kagami-teacher-and-exemplar-and-or-looking-glass) tool
> [`dev-nightly`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=dev)	An image that contains the nightly unstable build from the `dev` branch
> [`client-cli-dev-nightly`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=client-cli-dev-nightly)	A separate container for the [`iroha_client_cli`](https://hyperledger.github.io/iroha-2-docs/guide/bash.html) tool
> [`kagami-dev-nightly`](https://hub.docker.com/r/hyperledger/iroha2/tags?page=1&name=kagami-dev-nightly)	A separate container for the [`kagami`](https://hyperledger.github.io/iroha-2-docs/guide/glossary.html#kagami-teacher-and-exemplar-and-or-looking-glass) tool
> ### Supported tags and respective Dockerfile links
> Tag	Description
> `dev`	[`iroha2-dev/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-dev/Dockerfile)
> `stable`	[`iroha2-stable/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-stable/Dockerfile)
> `lts`	[`iroha2-lts/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-lts/Dockerfile)
> ### Supported tags and respective Dockerfile links
> Tag	Description
> `dev`	[`iroha2-dev/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-dev/Dockerfile)
> `stable`	[`iroha2-stable/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-stable/Dockerfile)
> `lts`	[`iroha2-lts/Dockerfile`](https://github.com/hyperledger/iroha/blob/iroha2-lts/Dockerfile)

**Comment by WRRicht3r** [comment]
Hi Victor, added some minor fixes to the texts proposed. 
Otherwise LGTM

**Comment by petermetz** [comment]
> * I do not know if Rocketchat is alive, but it is also in the contacts list.

@6r1d FYI: The foundation has migrated from RocketChat to Discord but https://chat.hyperledger.org still works it just redirects to a wiki page with the discord info.

**Comment by 6r1d** [comment]
> > * I do not know if Rocketchat is alive, but it is also in the contacts list.
> 
> @6r1d FYI: The foundation has migrated from RocketChat to Discord but https://chat.hyperledger.org still works it just redirects to a wiki page with the discord info.

Thanks, I will update the text.
