### ISSUE TITLE
Or maybe generating a link such as `iroha/docs/source/references/config.md#queuetransaction_time_to_live_ms` would be easier?

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3326]
Or maybe generating a link such as `iroha/docs/source/references/config.md#queuetransaction_time_to_live_ms` would be easier?

_Originally posted by @ilchu in https://github.com/hyperledger/iroha/pull/3321#discussion_r1146026361_

**Comment by 0x009922** [comment]
Might be considered a part of the RFC:

- #3795
