### ISSUE TITLE
Case insensitive config parameters

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3358]
@arndey mentioned that we have WSV_WASM_RUNTIME_CONFIG in upper case, but WSV_ACCOUNT_METADATA_LIMITS in lower case:
https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/config.md.
Let's make them case insensitive.

**Comment by mihir1739** [comment]
Can I work on this ? If I could be assigned this issue it would be even better.

**Comment by appetrosyan** [comment]
if you know what you're doing, go ahead. 

Before you start, make sure you have 
```bash 
rustup toolchain add nightlly-2022-12-22
```
and read `Contributing.md`. Make sure your commits are signed-off (`git commit -s`) and that you don't use more commits than necessary (one per issue is fine, just amend the previous one, or squash before or during rebase). Try to avoid updating from upstream via merge, use rebase `git pull --rebase`). 

I'm assigning the issue to you. Let's keep in touch.

**Comment by mversic** [comment]
@mihir1739 any progress on this one?

**Comment by mversic** [comment]
this should not be an issue anymore after #2585
