### ISSUE TITLE
ZST representation in schema

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3359]
My point is to ask the question from the perspective of schema, without knowing about Rust impl: does it make sense to have `FindAllAccounts`, or in general, `QueryBox::FindAllAccounts(())`, instead of having just `QueryBox::FindAllAccounts`? I would answer "No, it doesn't, it's just a noise and the second variant is clearer."

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/3317#discussion_r1159510445_

Please read entire discussion in the link above

**Comment by QuentinI** [comment]
My 2 cents: IMHO schema should track how stuff is actually serialized/deserialized. Having it be less verbose is an added bonus, but I don't think making one-size-fits-all schema is an achievable goal, SDKs will inevitably need to do some wrapping to expose more idiomatic API for their respective language. Thus my stance as SDK developer is "would be nice, but I care more about current limitations of the schema (e.g. no way to know what has `#[serde(transparent)]`, etc)".

**Comment by 0x009922** [comment]
IMO, the goal of schema is not only communicating to SDKs how to serde data types in SCALE, but also to expose it as a readable reference of what Iroha DSL consists of. The documentation has mentions of the data model, and the consumer might need to explore it. In sense of exploration, the more the schema is clear and well-organised - the better.

Therefore, having ZST new-type structs in the schema is redundant and is just a Rust impl detail. Actually, I think I might find other points like this, but I don't have them in mind right now.

**Comment by appetrosyan** [comment]
We decided to keep info in `schema`.
