### ISSUE TITLE
[feature]: Consider adding configuration parameters for actor channels

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3364]
These (actor channel capacities) should be config params at some point. 
              
              Consider adding them (with defaults) to the `p2p` config proxy. 
_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3346#discussion_r1162608850_

 
 Currently all bounded channels of iroha have capacity of `1`, without observed performance penalties. Additional benefit of smallest possible capacity is that we will find out about any communication problems sooner than later. 
 We should discus and consider addition of configuration params to change capacity of actor channels.

**Comment by mversic** [comment]
not relevant anymore
