### ISSUE TITLE
[suggestion] `debug_assertions` aware logging. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3365]
### Feature request

Add shorthand macros for `iroha_logger` which expand to 
```rust
#[cfg(debug_assertions)]
::iroha_logger::trace!(thing, "message that occurs frequently and ruins performance");
#[cfg(not(debug_assertions)]
// no-operation
```

and similarly for `debug`. 

### Motivation

In some situations, an event should not be logged unless in a debug build. 

### Who can help?

@appetrosyan

**Comment by mversic** [comment]
related to #3126
