### ISSUE TITLE
Implement instruction/expression validator

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3369]
While we have implemented instruction verification, we don't have any instruction validation. Since our data model is mostly strongly typed this, as far as I can see, applies only to expression evaluation.

This would be beneficial for the following reasons:
* transactions can be rejected more early in the process
* reduces amount of work done in the runtime validator or trigger making it smaller and faster to execute

Interestingly, `Expression::Query` is the only expression that requires `wsv`. If we wanted to pre-evaluate instructions we could do so by reducing every expression either to a value or to a `f(query)`. We can even consider client side evaluation

Since I have already started some work on this, I'm assigning it to myself

**Comment by Arjentix** [comment]
> While we have implemented instruction verification(incorrectly named runtime validator atm), we don't have any instruction validation. 

I don't get it. Currently we have permission checking for instructions and in #3329 I made it even better.

Queries inside expressions are also checked for permissions.

I don't understand what does this task stand for

**Comment by appetrosyan** [comment]
Potentially superseded by an ISA restructuring.

**Comment by mversic** [comment]
> I don't get it. Currently we have permission checking for instructions and in https://github.com/hyperledger/iroha/pull/3329 I made it even better.

this ticket is about eagerly evaluating expression as much as possible. This `Less` expression:
```rs
let is_running_out = Less::new(50_u32, 100_u32);
```
doesn't have to reach host for it to be evaluated to `true`. Even client can do this evaluation. 

However, no parts of this expression can be evaluated further. We say this expression form is minimized 
```rs
let is_running_out = Less::new(
    EvaluatesTo::new_unchecked(Expression::Query(
        FindAssetQuantityById::new(asset_id(self.name)).into(),
    )),
    100_u32,
);
```

More generally, every expression that doesn't involve queries can be minimized
