### ISSUE TITLE
Reduce repetition in `derive(Error)` docstring and error message

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3374]
If the docstring is just text and the format of the error is too, just use the doc-string in both places. If the error `Display` impl has a format string,  the doc-string could be concatenated to the doc-string. E.g. 
```rust
/// Too many inputs 
#[error("{inputs}, maximum: {maximum}")]
TooManyInputs
```
which displays as  `Too many inputs. 3 maximum: 2`

**Comment by DCNick3** [comment]
Related: https://github.com/dtolnay/thiserror/issues/104

**Comment by DCNick3** [comment]
There is a possibility to rely on [`displaydoc`](https://docs.rs/displaydoc/latest/displaydoc/) to produce the `Display` implementation, without integrating it into the custom derive. 

It, however, will require putting all the format-string to the doc-comment:

```
rust
/// Too many inputs. {inputs}, maximum: {maximum}
TooManyInputs
```

Displaying as `Too many inputs. 3, maximum: 2`.

The rustdoc will look not as good though
