### ISSUE TITLE
Consider introducing limit for long queries

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3379]
@arndey suggested to intorduce the limit feature, so that there will be a way to limit execution of long queries (i.e. `FindAllAssets` requires 3 nested loops).

@appetrosyan , suggested to use lazy evaluation, wsv clonning and paggination to implement this.

**Comment by mversic** [comment]
possible duplicate of #3347

**Comment by appetrosyan** [comment]
One potential solution is to introduce re-entrant pagination and default to returning a reasonably paginated lazily evaluated result.

**Comment by Mingela** [comment]
Agree to solve that implementing a pagination and close this one in favor of that one
