### ISSUE TITLE
Transmuting hash into array

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3386]
Do you think there could be any issue with treating Hash as transmutable into `[u8; Hash::LENGTH]` considering it's a `repr(C)` struct with two fields?

I'm slightly concerned about the effects on the calling convention, though probably that's not an issue

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/3336#discussion_r1152903861_

**Comment by mversic** [comment]
[relevant discussion](https://github.com/eqrion/cbindgen/issues/777)

**Comment by appetrosyan** [comment]
AFAICT, this is an upstream issue. `cbindgen` is relatively young and IMO this will remain an open question for a while.
