### ISSUE TITLE
Security implications of equivalent peer addresses

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3387]
The essence of the problem is as follows. Multiple Ip addresses can resolve to the same machine (e.g. `0.0.0.0` and `127.0.0.1` and `localhost` and `loopback`) and potentially the same peer program instance. 

If a malicious peer was disconnected based off of their public key, they can simply generate a new one. As such it makes more sense to block based off of a resolved IP addresses. But this does not preclude a denial of service attack based off of equivalent IP addresses, spoofed IP addresses, a DNS attack with different peers and so on.

**Comment by QuentinI** [comment]
Isn't it basically just DoS, since they can't re-register themselves?

**Comment by Arjentix** [comment]
Maybe we need to check what other blockchains do for that

**Comment by Erigara** [comment]
At the moment we use topology to decide what peers are allowed to be connected. 
If peer change it's private key it won't be present in topology and it won't be able to connect to the network.
However such peers still can DoS by initiating handshake over and over again.

**Comment by Erigara** [comment]
Another thing that bothers me is that during handshake peers just send their public keys (without any proof that they indeed have corresponding private key).
So maybe we want to send signature of something instead of just pub key?

**Comment by appetrosyan** [comment]
There's not much of a difference. 

I would recommend exchanging information that would be difficult to spoof all at once; MAC addresses, CPU vendors, local time and many other things can all be faked individually. However, requesting one of those at random forces the DoS to do more work, and thus less likely to cause a massive performance regression.

**Comment by appetrosyan** [comment]
Discussion reached consensus that any attempt can be easily mitigated and as such no significant fix can be achieved.
