### ISSUE TITLE
Make `model!` be a module attribute macro

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3388]
After a discussion with @mversic we decided to re-implement `model!` macro as a module attribute macro.
New usage will look like so:

```rust
#[model]
pub mod model {
    // Struct goes here...
}
```

Pros:

1. Better IDEs support. They can't always analyze what's going on inside `model!` macro, but can work with module like that
2. Less noise in the codebase
3. You don't skip some struct accidentally

**Comment by appetrosyan** [comment]
From experience with Sbustrate’s macros, attribute macros are better, but not necessarily much better.
