### ISSUE TITLE
Replace `RwLock` with `AtomicPtr` in `WorldStateView::validator` field

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3390]
@appetrosyan [suggested](https://github.com/hyperledger/iroha/pull/3329#discussion_r1165160906) to replace `RwLock` to `AtomicPtr`.

This will gain some performence, primary because we don't need to sync read access, which is used most of the time. When updating validator it will be enough to just use `swap()` operation

**Comment by Arjentix** [comment]
Blocked by #3329

**Comment by Arjentix** [comment]
@appetrosyan , do I understand right that it will look something like this:

```rust
let new_validator = Box::new(Validator::new(...));
let new_validator_ptr = Box::leak(new_validator);
let old_validator_ptr = wsv.validator.swap(new_validator_ptr, Ordering::SomeOrdering);
    
// Old validator clean-up
unsafe { Box::from_raw(old_validator_ptr) }
```
?

**Comment by Arjentix** [comment]
Ok, looks like we can't clean-up old value just then we upload a new one. Because another thread could already accure the raw pointer from it and using it right now. We should deallocate that old Box when all threads using old value will finish

**Comment by appetrosyan** [comment]
Also, keep in mind that if we have parallel instruction execution the validators must be running as separate instances

**Comment by Erigara** [comment]
I believe this issue could be closed since we don't use `RwLock` for `validator` anymore.
