### ISSUE TITLE
Deserialize/Decode of structs with invariants is dubious

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3424]
Having a default implementation of `Deserialize`/`Decode` for transactions and blocks that carry certain invariants should be frowned upon. Almost all of blocks and transactions (maybe all?) should not derive implementation of `Deserialize`/`Decode` as this allows creating types with invalidated invariants. 

Examples include `AcceptedTransaction`/`RejectedTransaction`/`ValidTransaction`/`CommittedBlock`, etc. Even `SignedBlock` should not have `Deserialize` on it, i.e. `Deserialize` should be provided only on `Candidate<SignedBlock>`. Approach with wrapping such structs in `Candidate` might be generalized for this purpose

**Comment by mversic** [comment]
related to #3343

**Comment by appetrosyan** [comment]
Worked on

**Comment by mversic** [comment]
consider adding a trait `Unverified` that offers a constructor to construct a type with enforced invariants

**Comment by mversic** [comment]
finished
