### ISSUE TITLE
[BUG] Iroha fails to deserialize raw default genesis block when running `docker-compose up`

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#3427]
### OS and Environment

MacOS, Docker Hub

### GIT commit hash

b1855454

### Minimum working example / Steps to reproduce

1. Checkout Iroha 2 commit b1855454
2. Run docker-compose up
3. Observe the error in the console output

### Actual result

Iroha 2 fails to start, displaying an error related to deserializing the raw genesis block and a warning regarding the creation of a peer.
```
iroha-iroha2-1  | 2023-04-26T05:44:07.014632Z  INFO iroha: Starting Iroha
iroha-iroha0-1  | Error: Failed to deserialize raw genesis block from "/config/genesis.json"
iroha-iroha0-1  | 
iroha-iroha0-1  | Caused by:
iroha-iroha0-1  |     invalid type: map, expected a sequence at line 1 column 1
iroha-iroha0-1  | 
iroha-iroha0-1  | Location:
iroha-iroha0-1  |     /iroha/genesis/src/lib.rs:122:41
iroha-iroha3-1  | 2023-04-26T05:44:07.033073Z  WARN iroha_p2p::network: Unable to create peer error=Failed IO operation.
```

### Expected result

Iroha 2 should start without any errors or warnings related to deserializing the raw genesis block or creating a peer.

### Who can help to reproduce?

@astrokov7

**Comment by Arjentix** [comment]
It can be fixed by `docker pull`. Looks like you used outdated `iroha2:dev` image and tried to run them with new configs
