### ISSUE TITLE
[suggestion] Restore old coverage behaviour

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3431]
### Feature request

During the retro for RC14, it was decided that the old approach to code coverage reporting, with the coverage computed relative to the previous latest state of `iroha2-dev` was preferred by most. 

### Motivation

Relative coverage reporting is better if the previous HEAD was considered the target. 

### Who can help?

@BAStos525

**Comment by BAStos525** [comment]
It was switched to Coveralls instead of Codecov in [PR #3513](https://github.com/hyperledger/iroha/pull/3513).
