### ISSUE TITLE
[BUG] Versioned structures in the schema miss discriminant info

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3444]
### GIT commit hash

b1855454

### Description

After the merge of #3317, the schema doesn't contain info about enum discriminants anymore. It was discussed in a topic (https://github.com/hyperledger/iroha/pull/3317#discussion_r1159516469). I thought that if discriminants aren't explicitly specified anymore, then the default sequential discriminants computation should be used. It turned out not to be the case: `VersionedSignedTransaction` and `VersionedSignedQuery` still have custom discriminants (`1` for `V1`) while it is not specified in the schema:

https://github.com/hyperledger/iroha/blob/b1855454ac03603fb62a3a6491b5492ab26f9777/docs/source/references/schema.json#L3978-L3993

### What is expected

It is expected that the schema should not have such implitic details at all. If there are custom discriminants for enum variants, they should be specified.

### Desired solution

I think that it is not necessary to specify discriminants for all enums, it would be too verbose. However, optional `discriminant` field should exist for such a case. The approach of discriminants computation should be the same as it works in Rust ([Enumerations > Discriminants - The Rust Reference](https://doc.rust-lang.org/reference/items/enumerations.html#discriminants)). For example:

```rust
enum Foo {
    Bar,            // 0
    Baz = 123,      // 123
    Quux,           // 124
}
```

```json5
{
  Foo: {
    Enum: [
      { name: 'Bar' },                     // 0
      { name: 'Baz', discriminant: 123 },  // 123
      { name: 'Quuz' }                     // 124
    ]
  }
}
```

**Comment by mversic** [comment]
Your example isn't entirely correct because the enums in question are not fieldless. Here is a better example of how it actually looks in Iroha:

```rs
enum VersionedEnum {
    #[codec(index = 1)]
    V1(V1Enum),
}
```

The actual discriminant is:
1. 0 in Rust (although this might not be stable). Whatever it is, this value cannot be changed for data-carrying enums
2. 1 when serialized to a binary format with `parity_scale_codec`
3. not used when serialized with `json`

What should be done about this?

**Comment by 0x009922** [comment]
The example I put is to show the approach of discriminants computation for the schema. I don't understand what do you mean by "incorrect". And this is not the main point.

Now schema doesn't have discriminants info. I, as a codegen develop, need to compute actual discriminants to generate codecs properly. I don't see discriminants in the schema, so I expect them always to start from 0 and ascend then. This logic doesn't work for versioned structs - their discriminants don't start from 0.

Thus, I think that discriminants should be specified for versioned enums (and for any other enums that have custom discriminants). In order to avoid specifying ALL discriminants for ALL enums and variants, I propose to specify them only when needed. The approach of discriminants resolution is what I have put as the example in the issue description.

What should be done? Discriminants should be specified explicitly when default logic of their computation is not applicable.

**Comment by mversic** [comment]
> The example I put is to show the approach of discriminants computation for the schema. I don't understand what do you mean by "incorrect". And this is not the main point.

I mean that we guard against the use of explicit discriminants so the given example:
```rs
#[derive(IntoSchema)]
enum Foo {
    Bar,            // 0
    Baz = 123,      // 123
    Quux,           // 124
}
```

would not compile. We never use explicit discriminants in Rust codebase, but we use `codec[index = 'X']` to define how they are serialized into binary format.

When I ask what should be done, there are two approaches:
1. show discriminant info in the schema - this was the previous approach that is now broken
2. don't allow custom discriminants when serializing - let them always start from 0

If you think of Rust's `[repr(C)]` as a serialization format( will be used in FFI), then there seems to be no way to specify a discriminant value for FFI serialization in Rust codebase. You can read about it [here](https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html).

I prefer the 2nd approach because I don't want the binary serialization formats diverging. Like, in the schema it would say the discriminant is `1`, but when you serialize to `repr(C)` the discriminant is `0`. Additionally, if we just don't allow custom discriminants ever, schema and to code to generate it would be simpler

Would you be ok with me removing custom discriminants altogether?

**Comment by 0x009922** [comment]
> Would you be ok with me removing custom discriminants altogether?

I think it is not a good way, because having a custom discriminant for versioned enums has some purpose. As far as I remember, it will help to route different API versions (when there will be other ones) by simply looking at the first byte of the payload.

**Comment by mversic** [comment]
> I think it is not a good way, because having a custom discriminant for versioned enums has some purpose. As far as I remember, it will help to route different API versions (when there will be other ones) by simply looking at the first byte of the payload.

you can still do the same. It's just that version would be `version - 1`, i.e. version counting starts from `0`. For example, here discriminant `0` would mean `V1` and `1` would mean `V2`
```rs
enum VersionedEnum {
    V1(V1Enum),
    V2(V2Enum),
}
```

`json` serialization will remain unaffected, only `scale` serialization will change the first byte to `byte - 1`

**Comment by 0x009922** [comment]
I still think that I am not understood.

Anyway, okay, it would be just fine if versioned structs don't have custom discriminants (in SCALE) at all. But I think it requires a wider discussion, because this was made with some reason.

**Comment by appetrosyan** [comment]
Not a huge fan of the design we have right now. I don't like the idea of going with verbose `discriminant` fields everywhere, but it's less costly than mistakes from the side of the SDK designers. 

> I'm saying this because for binary formats we don't have a unified framework like serde

Yes, but it is commonly accepted that the schema is used for inter-peer communication, which goes through SCALE. If we go with what @0x009922 suggested (and I strongly recommend we consider it), we still have options. 

We know that all frameworks would be working relative to the Rust discriminant, so we can just specify that. Document that SDK devs need to be mindful that the discriminants are offset for SCALE and how to work them out. 

I would still recommend specifying the discriminant values. This is less error prone and offloads the issue from the SDK designers. This will also signal changes to the discriminants to us at Pull Request time; if something changes the discriminants, it will be reflected in the schema. This in turn allows a degree of automation: if there are changes to the schema, we can automatically add them to a batch of changes.

**Comment by 0x009922** [comment]
My quotations:

> I think that it is not necessary to specify discriminants for all enums, it would be too verbose. However, optional discriminant field should exist for such a case.

> I think that discriminants should be specified for versioned enums (and for any other enums that have custom discriminants).

> I propose the 3rd way, the middle between the two: don't show discriminants for all enums, but only when it is needed. In the way how Rust does it.

Please note that **I don't mean to add discriminants to all enum variants**. I only ask to add them in those places where the default disciminants inferrence model is not applicable, i.e. for versioned structs.

**Comment by mversic** [comment]
SCALE codec is not behaving as you assume it does. For example:
```rs
enum VersionedEnum {
    V1,
    #[codec(index = 8)]
    V2,
    V3,
}
```

will have the following discriminants: `[0, 8, 2]`. This is different from Rust's default behavior. Unless you place `#[codec(index = x)]` attribute on every variant in the enum, SCALE will just overlay custom variants over the Rust default

**Comment by 0x009922** [comment]
I didn't assume `parity-scale-codec` works this way. It was my proposal how it might (ideally) work in schema.

However, now I think it is a little bit overcomplicated to implement on the schema gen side. Can we just say, that either enum **(in schema)** should not have discriminants at all, or should explicit discriminants for each variant?

**Comment by appetrosyan** [comment]
> We have never noticed this because we only have one version in our API atm

Technically we had this problem, but this was  before you joined the team. And we can keep it that way, by enforcing some invariants. 

If we can commit to discriminants being identical in Rust and when encoded, or if we can commit to them being trivially computable, then it's enough to specify some discriminants and some discriminant variants. 

I personally don't mind giving each enum a field like so. 
```
  "discriminants" {
    "rust": [0, 123, 124], 
    "SCALE": [0, 8, 2], 
    "extern C": [1, 2, 3],
  }
```
