### ISSUE TITLE
[BUG] remove the Burning assets item from the documentation

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#3458]
### OS and Environment

any

### GIT commit hash

any

### Minimum working example / Steps to reproduce

Remove item **#7Burning assets** from https://hyperledger.github.io/iroha-2-docs/guide/bash.html#_5-registering-and-minting-assets because this command is **not** supported by irona_client_cli

`./iroha_client_cli asset --help                                                                               
iroha_client_cli-asset 
The subcommand related to assets

USAGE:
    iroha_client_cli asset <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    get         Get info of asset
    help        Print this message or the help of the given subcommand(s)
    list        List assets
    mint        Command for minting asset in existing Iroha account
    register    Register subcommand of asset
    transfer    Transfer asset between accounts
`

### Actual result

information is in the documentation

### Expected result

information missing from documentation

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
nothing to do
  ```
</details>

### Who can help to reproduce?

@timofeevmd

**Comment by ayush4345** [comment]
hey, i would like to contribute to this issue

**Comment by ayush4345** [comment]
![image](https://user-images.githubusercontent.com/99096397/236463768-69111ac3-a37d-4e7a-89e9-8a8a097d8ebb.png)
should I remove this 7th section from the documentation,, or do I have to replace it something else

**Comment by timofeevmd** [comment]
after discussion, decision  was made to implement 
https://github.com/hyperledger/iroha/issues/3462
