### ISSUE TITLE
iroha blockchain explorer ?

### ISSUE THREAD

**Issue by freedomtrain** [hyperledger/iroha#3466]
### Feature request

Is there a iroha blockchain explorer ?

### Motivation

We are going to be deploying an iroha instance and we would like to have way that non technical team members can have the opportunity to interact with iroha

**Comment by appetrosyan** [comment]
Yes there is

**Comment by freedomtrain** [comment]
Thanks so much for your help.
Can you please point me to a link for this ?

**Comment by 6r1d** [comment]
Hello.
First, I must explain that it is not a complete project, but there will be updates during the upcoming mentorship project, so it is expected to be more functional than now in one or two months.
Please review the video to see if our [Blockchain explorer](https://www.youtube.com/watch?v=aze3jwW6d-U) covers your needs.
You can use the code in [this repository](https://github.com/0x009922/explorer-deploy-dev-tool/) to deploy it, although it may be unstable right now.

**Comment by freedomtrain** [comment]
Thank you so much for your help !
