### ISSUE TITLE
[BUG] Asset transfer failure with iroha_client_cli

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3471]
This issue covers and quotes today's community question from Harini Ravikumar.

### GIT commit hash

9273a912

### Minimum working example

* `docker-compose up`
* `mkdir test-docker` (under the Iroha root directory).
* `iroha_client_cli` and `config.json` permission files for asset transfer permissions are placed there.
* minting: `./iroha_client_cli asset mint --account="mad_hatter@bash-network" --asset="tea#bash-network" --quantity="70"`
* I created a permission file and gave the below command to transfer five assets from the `mad_hatter` account to the `white_rabbit` account to transfer the assets
* `./iroha_client_cli asset transfer --from mad_hatter@bash-network --to white_rabbit@bash-network --asset-id tea#bash-network --quantity 5`
* I gave the below command to list the assets based on account.
`./iroha_client_cli asset list all` to check whether the asset transfer is successful

### Expected behaviour

The assets should've been transferred.

### Actual behaviour

> I gave the command `./iroha_client_cli asset list all` to list the account with their assets.

> The asset is not getting transferred.

> I've generated 70 assets under the account name `mad_hatter`. After doing the transfers, all those assets are still under the `mad_hatter` account.

```
Asset {
        id: Id {
            definition_id: DefinitionId {
                name: "tea",
                domain_id: Id {
                    name: "bash-network",
                },
            },
            account_id: Id {
                name: "mad_hatter",
                domain_id: Id {
                    name: "bash-network",
                },
            },
        },
        value: Quantity(
            70,
        ),
    }
```

### Operating system

Ubuntu Linux, kernel 5.15.0-71

### LibC type and version

ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

### Current environment

Docker Hub

**Comment by mversic** [comment]
Needs `QA-confirmed`

**Comment by mversic** [comment]
this is most likely an issue with documentation in [this](https://hyperledger.github.io/iroha-2-docs/guide/bash.html#_6-transferring-assets) step. `alice` user doesn't have the permission to execute this transfer

**Comment by 6r1d** [comment]
@astrokov7, could you check this one, please?

**Comment by astrokov7** [comment]
This documentation's issue is already fixed.
