### ISSUE TITLE
[refactor]: Persistent WSV

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3472]
Get rid of interior mutability inside WSV and use persistent data structures for cheep cloning.

**Comment by appetrosyan** [comment]
Usage of persistent structures resulted in 500% performance regression. 
![apply_blocks_persistent_wsv_flamegraph](https://github.com/hyperledger/iroha/assets/15856657/c6d2b1d1-babf-4513-8aad-924c69bd265b)

Flamechart (attached) shows that the allocator pressure is not the dominant issue, indicating that a different form of persistent structure can still yield the required performance benefits.
