### ISSUE TITLE
[suggestion] Make most of the configuration parameters optional

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3501]
### Feature request

Currently, you have to provide ALL of the configuration fields, even the maximum log level.

Instead, most of the configuration parameters should be optional and have default values.

### Motivation

Simplify configuration process.

**Comment by 0x009922** [comment]
Related:
- #3461

**Comment by appetrosyan** [comment]
#3551 Addressed this somewhat. 

QA should confirm that most parameters are now optional, except for `Key_Pair*`, `trusted_peers` and `*_URL`s.

**Comment by 0x009922** [comment]
It was probably solved by #3541, but needs verification.

**Comment by 0x009922** [comment]
Closed by #4239
