### ISSUE TITLE
[suggestion] Remove the requirement to set `sumeragi.key_pair` and `sumeragi.peer_id` to `null` in the configuration

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3504]
### Feature request

The configuration reference says:

> **Sumeragi: default `null` values**
>
> A special note about sumeragi fields with `null` as default: only the [`trusted_peers`](#sumeragi.trusted_peers) field out of the three can be initialized via a provided file or an environment variable.
>
> The other two fields, namely [`key_pair`](#sumeragi.key_pair) and [`peer_id`](#sumeragi.peer_id), go through a process of finalization where their values are derived from the corresponding ones in the uppermost Iroha config (using its [`public_key`](#public_key) and [`private_key`](#private_key) fields) or the Torii config (via its [`p2p_addr`](#torii.p2p_addr)). This ensures that these linked fields stay in sync, and prevents the programmer error when different values are provided to these field pairs. Providing either `sumeragi.key_pair` or `sumeragi.peer_id` by hand will result in an error, as it should never be done directly.

It is an internal detail that should be never exposed to the end user. These fields simply should not exist in the user configuration.

Speaking in terms of "resolved and user configuration" (#3500), sumeragi key pair is definitely a part of the `ResolvedConfig`.

**Comment by mversic** [comment]
why do we even have `sumeragi.key_pair`? Because we have top level `public_key` and `private_key`

**Comment by 0x009922** [comment]
Closed by #4239

----

> why do we even have `sumeragi.key_pair`? Because we have top level `public_key` and `private_key`

It was an implementation detail leaked to the user-space.
