### ISSUE TITLE
[suggestion] Get rid of "rustisms" in the configuration reference

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3505]
### Feature request

For the end user, it doesn't make sense:

- to mention things like `Option<..>`, `Option<Option<..>>` and explaining "what does it mean to them"
- to say that some field is of type `std::path::PathBuf` when it simply means that it is a string
- to mention structs like `PublicKey`, `PrivateKey`, `PeerId` without explaining their structure

Configuration parameters types and values examples should be explained in respect of the configuration format itself, i.e. JSON (or TOML #3499). In other words, use `null`, `number`, `string` and other format-related types.

### Motivation

Make clear to user what they should put into the configuration.

**Comment by appetrosyan** [comment]
I'd suggest expanding the tutorial section with these structures and explaining what those mean and what to do about them. Rust-isms aren't a problem in and of themselves, Iroha has many Rust sensibilities anyway. The problem is that they're all undocumented.

**Comment by 0x009922** [comment]
> I'd suggest expanding the tutorial section with these structures and explaining what those mean and what to do about them.

Yes, I am talking about that. The point is to explain such structures not in terms of Rust, but in terms of the config format (e.g. as JSON schema).

**Comment by appetrosyan** [comment]
Being more precise with our language helps the potential implementor.

**Comment by 0x009922** [comment]
Auto-generated configuration reference was removed. New reference:

- https://github.com/hyperledger/iroha-2-docs/issues/392
