### ISSUE TITLE
[suggestion] Offer only predefined set of signature check conditions

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3526]
Related to #3088

The issue is described in the previous ticket. We have to make sure that our signature check conditions are valid and don't suffer from halting problem

**Comment by DCNick3** [comment]
AFAIU, it would be enough to support two options:

- require all the signatures from the account's signatory (corresponding to the default `SignatureCheckCondition`)
- require all the signatures from the user-provided set (corresponding to the `multisignature_transactions_should_wait_for_all_signatures` test)

**Comment by mversic** [comment]
> require all the signatures from the account's signatory (corresponding to the default SignatureCheckCondition)

or a subset of all account's signatories
