### ISSUE TITLE
[BUG]: Define topology for 3 or less peers

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3529]
Atm we have inconsistencies for topology of size 3 or less which can cause bugs. 
We need to properly define topology and make `Topology` methods be consistent with each other.

**Comment by appetrosyan** [comment]
We have to remember that such a topology can be the result of network partitioning. As such, preventing non-BFT topologies from the API standpoint doesn't prevent non-BFT topologies from occurring.

**Comment by SamHSmith** [comment]
1 peer: Leader
2 peer: Leader, Proxytail
3 peer: Leader, Validating Peer, Proxytail
