### ISSUE TITLE
Instructions of tag names for docker images don't match

### ISSUE THREAD

**Issue by oimou** [hyperledger/iroha#353]
It seems there are some different tag names used for docker images when running `docker build`. I wonder whether it is intentional.

### hyperledger/iroha-dev
* https://github.com/hyperledger/iroha/blob/master/docker/README.md
* https://github.com/hyperledger/iroha/blob/master/docker/dev/Dockerfile

### warchant/iroha-dev
* https://github.com/hyperledger/iroha/blob/master/docker/build_in_docker.sh

### warchantua/iroha-dev
* https://github.com/hyperledger/iroha/blob/master/docker/dev/README.md

**Comment by Warchant** [comment]
Correct is `warchantua/iroha-dev`, thanks.

**Comment by oimou** [comment]
Thanks for your quick reply! Should I close this issue after the image is pushed, or leave it open until these are fixed?

**Comment by neewy** [comment]
Fixed. Check `sh scripts/run-iroha-dev.sh` in develop branch
