### ISSUE TITLE
[ci] Post coverage report link to PR as comment

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3542]
### Feature request

Post coveralls coverage report in GitHub PR page. 

### Motivation

When moving away from codecov and towards coveralls, we have lost the ability to see the coverage reports on the PR page. We want to restore that functionality. 

### Who can help?

@appetrosyan

**Comment by ryjones** [comment]
@BAStos525 I think I over-wrote your coveralls install. Please try again

**Comment by BAStos525** [comment]
We with @ryjones  tried all things described in the official documentation. Probably it could be [the reason](https://github.com/coverallsapp/github-action/issues/7).
