### ISSUE TITLE
[bug]: `metric_tx_amounts` add total asset value and not increment

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3543]
If we look at `tx_amounts` metrics definition: "average amount involved in a transaction on this peer"

In implementation of `Asset`-related instructions (`Mint`, `Burn`, `Transfer`) we always add `total` quantity value for `metrics_tx_amounts`. When it seems like should add only actual value being transferred, minted or burnt. 

For example:
- if user A had 10 apples and then mint 1 apple we should add 1 to `metrics_tx_amounts` (and currently we add 11);
- if user A had 10 apples and then burn 1 apple we should add 1 to `metrics_tx_amounts` (and currently we add 9);
- if user A had 10 apples and then transferred 1 apple to user B who already had 6 apples then we should add 1 to `metrics_tx_amounts` (an currently we add 7).

**Comment by timofeevmd** [comment]
testing blocked https://github.com/hyperledger/iroha/issues/3709
