### ISSUE TITLE
[suggestion] Deprecate `u128` literals in JSON

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3574]
### Feature request

Deprecate unquoted `u128` instead using syntax
```json
  "value": "123456787989898",
```

### Motivation

`serde_json` uses the `arbitrary_precision` arithmetic which is slow. Given that genesis reading performance is a vital performance characteristic, simplifying the deserialisation process will pay off. 

### Who can help?

@appetrosyan

**Comment by DCNick3** [comment]
Potentially deprecate all numbers outside of string literals and make them tagged (like `"32_u32"`)
