### ISSUE TITLE
Resolve licensing issues discovered by Fossology scan

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/iroha#361]
Iroha source was scanned using Fossology to determine license for files contained in the following repositories

-   https://github.com/hyperledger/iroha.git
-   https://github.com/hyperledger/iroha-javascript.git
-   https://github.com/hyperledger/iroha-ametsuchi.git
-   https://github.com/hyperledger/iroha-scala.git
-   https://github.com/hyperledger/iroha-ios.git
-   https://github.com/hyperledger/iroha-android.git
-   https://github.com/hyperledger/iroha-network-tools.git
-   https://github.com/hyperledger/iroha-docker-develop.git
-   https://github.com/hyperledger/iroha-python.git

From the Hyperledger Charter (https://www.hyperledger.org/about/charter) Section 13, all files that are included in Hyperledger projects should either be licensed with the Apache License, Version 2.0 for source code or Creative Commons Attribution 4.0 International License for documentation.  

There are files in the Iroha source base that do not meet these requirements.  See the attached file for results. [iroha-2017-06-05.xlsx](https://github.com/hyperledger/iroha/files/1056143/iroha-2017-06-05.xlsx)

The files listed under Attribution, Other, and No License Found need to be resolved. For the Attribution and Other tab, these files should be replaced with code meeting the Apache 2.0 license.

For the files listed as No License Found, first check with the original contributors to make sure that they can contain an Apache 2.0 license (for source code) or a Creative Commons with Attribution 4.0 license (for documentation). Once this has been verified, the editable files must be annotated with the correct license text and/or the SPDX short identifiers (see  https://spdx.org/sites/cpstandard/files/pages/files/using_spdx_license_list_short_identifiers.pdf).
For binary files, a license.txt file should be included in the directory calling out the file types and the associated license.

Any files that are not covered by Apache 2.0 or CC by 4.0 that need to remain with the project will need to go through an exception process with the governing board.

**Comment by MizukiSonoko** [comment]
Ok thanks 
In now, WIP in  this pull request. 
https://github.com/hyperledger/iroha/pull/349

**Comment by takemiyamakoto** [comment]
This scan should probably be run again on the develop branch, as a lot has changed.

**Comment by tkuhrt** [comment]
@takemiyamakoto : is this true for all Iroha repositories or just this one? Meaning, if I pulled the develop branch for all Iroha repositories listed above would that be the right scan to do?

**Comment by takemiyamakoto** [comment]
Just this repository.

**Comment by neewy** [comment]
Tracy, can you please help us and run this scan once again? Thanks

**Comment by neewy** [comment]
Tracy, if this problem remains, please reopen this issue. I will close it since there was no answer for a month 😃
