### ISSUE TITLE
[suggestion] Don't tolerate invalid signatures in a transaction

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3613]
ATM we tolerate invalid transaction with invalid signatures, we just remove the invalid signature from signature set. What happens then is that transaction is accepted and lingers in the queue until it expires or until it's added more signatures (like a MST). @arndey encountered this issue where his transaction submit would timeout instead of being straight rejected. Check [here](https://github.com/hyperledger/iroha/blob/iroha2-dev/data_model/src/transaction.rs#L433)

**Comment by appetrosyan** [comment]
At discussion we agreed to remove txn with even a single invalid signature.

**Comment by DCNick3** [comment]
Assign me
