### ISSUE TITLE
[suggestion] Deprecate `cargo lints`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3622]
### Feature request

Inline all of the general `deny` lints into the top levels of each affected crate. 

### Motivation

`cargo lints` is a package that is effecitvely a thin wrapper around `clippy`. The issue with building our CI around it is as follows
1. It applies to the entire workspace. Some lints are enforced as a matter of policy, e.g. groups like `pedantic` and `restriction`. However, most are specific to the crates in which they exist. For example, `arithmetic_side_effects` is only sensible in crates where we do arithmetic. This rules out `logger` and `telemetry`. 
2. It applies to tests and benchmarks, even though the standards for those crates are different. Sometimes expressive tests take shortcuts for the sake of readability and coverage. 
3. It requires more tools to be installed on the potential contributor's system. 
4. `cargo lints` hasn't been updated since May 2021. Likely won't be. 
5. It doesn't properly use `clippy-driver` which can potentially break Rust in the future. 

### Who can help?

@appetrosyan

**Comment by DCNick3** [comment]
With the merge of #3904, `cargo-lints` is no longer being used and points 3, 4 and 5 no longer apply. We might still want to have the lints be more granular

**Comment by mversic** [comment]
closed in favor of #3927
