### ISSUE TITLE
Transition to using `std::cell::OnceCell`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3656]
This got stabilized recently in the `std` but we're still using `once_cell` external crate. Remove `once_cell` dependency and use the one from `std` instead

**Comment by DCNick3** [comment]
It's only the `OnceCell` that got stabilized. `iroha` currently uses `Lazy` (which exists in std [under `LazyCell` name](https://doc.rust-lang.org/std/cell/struct.LazyCell.html)), which is not yet stabilized
