### ISSUE TITLE
Could we remove view change proof from every message?

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3657]
Since we now separate queue for service messages could we use remove view change proof from every message?

_Originally posted by @Erigara in https://github.com/hyperledger/iroha/issues/3652#issuecomment-1609659814_

**Comment by Erigara** [comment]
If we do so, we also might consider combine `ViewChangeSuggested` messages into one while it's stay in the queue.

**Comment by SamHSmith** [comment]
This issue has been fixed long ago.
