### ISSUE TITLE
The exact same piece of code is also changed here:

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3673]
The exact same piece of code is also changed here:

https://github.com/hyperledger/iroha/pull/3661/files#r1251267503

Not sure which option is better. Just pointing out to the work duplication.

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/3666#discussion_r1251408055_

**Comment by ilchu** [comment]
Closing it as not planned due to the two options being equivalent and not bearing any benefit beside stylistic concerns.
