### ISSUE TITLE
[BUG] No way to get tx_amount metric

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#3709]
### OS and Environment

MacOS ventura 13.3, DockerHub

### GIT commit hash

128df48

### Minimum working example / Steps to reproduce

The description of the tx_amount metric is missing from the documentation https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md

It is also not possible to get the metric curl -X GET http://0.0.0.0:8180/metrics

The metric is not uploaded to prometheus

### Actual result

It is possible to get the metrics via curl -X GET http://0.0.0.0:8180/metrics

The metric is uploaded to prometheus

### Expected result

There is no way to get the metrics via curl -X GET http://0.0.0.0:8180/metrics

The metric is not uploaded to prometheus

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  ```bash
 docker-compose: ✗ curl -X GET http://0.0.0.0:8180/metrics
# HELP accounts User accounts registered at this time
# TYPE accounts gauge
accounts{domain="garden_of_live_flowers"} 1
accounts{domain="genesis"} 1
accounts{domain="looking_glass_3026bda2-4b53-4b2f-b1bd-8c34939cb600_209dbebf-764e-4b10-acd0-48ca391bc69b"} 0
accounts{domain="looking_glass_bc883052-4ce6-462e-91f9-bd7a2528b0d6_8c584d01-ec2b-4188-a188-68b2a46990c8"} 0
accounts{domain="wonderland"} 2
# HELP block_height Current block height
# TYPE block_height counter
block_height 3
# HELP connected_peers Total number of currently connected peers
# TYPE connected_peers gauge
connected_peers 3
# HELP domains Total number of domains
# TYPE domains gauge
domains 5
# HELP dropped_messages Sumeragi dropped messages
# TYPE dropped_messages counter
dropped_messages 0
# HELP queue_size Number of the transactions in the queue
# TYPE queue_size gauge
queue_size 0
# HELP tx_amount average amount involved in a transaction on this peer
# TYPE tx_amount histogram
tx_amount_bucket{le="0.005"} 0
tx_amount_bucket{le="0.01"} 0
tx_amount_bucket{le="0.025"} 0
tx_amount_bucket{le="0.05"} 0
tx_amount_bucket{le="0.1"} 0
tx_amount_bucket{le="0.25"} 0
tx_amount_bucket{le="0.5"} 0
tx_amount_bucket{le="1"} 0
tx_amount_bucket{le="2.5"} 0
tx_amount_bucket{le="5"} 0
tx_amount_bucket{le="10"} 0
tx_amount_bucket{le="+Inf"} 0
tx_amount_sum 0
tx_amount_count 0
# HELP txs Transactions committed
# TYPE txs counter
txs{type="accepted"} 4
txs{type="rejected"} 0
txs{type="total"} 4
# HELP uptime_since_genesis_ms Network up-time, from creation of the genesis block
# TYPE uptime_since_genesis_ms gauge
uptime_since_genesis_ms 66288356
# HELP view_changes Number of view changes in the current round
# TYPE view_changes gauge
view_changes 1

```

</details>

### Who can help to reproduce?

@timofeevmd

**Comment by timofeevmd** [comment]
problem is not solve

➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli domain register --id="looking_glass"
"99698DC566BA84623356FD3A5E42B451E2EE463F4760685EE3B46F58D9E52609"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli account register \
    --id="mad_hatter@looking_glass" \
    --key="ed01204595da8957c5598d4de20fe5f3eb4c14820678e1a1957a535db1fd4b3d1607c5"
"C6E66DD9BCC02898BEE127FF6BE2D7D18372BD865CFB64FE26A94C8D406AF169"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli account register \
    --id="white_rabbit@looking_glass" \
    --key="ed0120a4c4dadd9f18b0f63d6a420151fe0748d785475dec63034a15fcf999ceda1e65"
"9D425DB32C3A1316A7DDB86F3540DA63735A62EF746DAF9C60B7D2CFB0887D09"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset register \
    --id="tea#looking_glass" \
    --value-type=Quantity
"FECA904FFEB3BB9B655D661DC3996AB5BA54E4CB99A9533951D1CB596D16A9BD"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset mint \
    --account="mad_hatter@looking_glass" \
    --asset="tea#looking_glass" \
    --quantity="100"
"3D93A8DC7344F744425ABA2E2D133700B78D778D5170214E549871B53350643B"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset transfer --from mad_hatter@looking_glass --to white_rabbit@looking_glass --asset-id tea#looking_glass --quantity 5
"BE5B2AE52400E8C68CAD9571BB4039F2338FC707F41A984D71BB45AF8D3F285B"
➜  test_docker git:(iroha2-dev) ✗ curl -X GET http://127.0.0.1:8180/metrics                                                                                                  
# HELP accounts User accounts registered at this time
# TYPE accounts gauge
accounts{domain="garden_of_live_flowers"} 1
accounts{domain="genesis"} 1
accounts{domain="looking_glass"} 2
accounts{domain="wonderland"} 2
# HELP block_height Current block height
# TYPE block_height counter
block_height 7
# HELP connected_peers Total number of currently connected peers
# TYPE connected_peers gauge
connected_peers 3
# HELP domains Total number of domains
# TYPE domains gauge
domains 4
# HELP dropped_messages Sumeragi dropped messages
# TYPE dropped_messages counter
dropped_messages 0
# HELP queue_size Number of the transactions in the queue
# TYPE queue_size gauge
queue_size 0
# HELP tx_amount average amount involved in a transaction on this peer
# TYPE tx_amount histogram
tx_amount_bucket{le="0.005"} 0
tx_amount_bucket{le="0.01"} 0
tx_amount_bucket{le="0.025"} 0
tx_amount_bucket{le="0.05"} 0
tx_amount_bucket{le="0.1"} 0
tx_amount_bucket{le="0.25"} 0
tx_amount_bucket{le="0.5"} 0
tx_amount_bucket{le="1"} 0
tx_amount_bucket{le="2.5"} 0
tx_amount_bucket{le="5"} 1
tx_amount_bucket{le="10"} 1
tx_amount_bucket{le="+Inf"} 4
tx_amount_sum 162
tx_amount_count 4
# HELP txs Transactions committed
# TYPE txs counter
txs{type="accepted"} 8
txs{type="rejected"} 0
txs{type="total"} 8
# HELP uptime_since_genesis_ms Network up-time, from creation of the genesis block
# TYPE uptime_since_genesis_ms gauge
uptime_since_genesis_ms 614620
# HELP view_changes Number of view changes in the current round
# TYPE view_changes gauge
view_changes 1

**Comment by timofeevmd** [comment]
problem is not solve

➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli domain register --id="looking_glass"
"99698DC566BA84623356FD3A5E42B451E2EE463F4760685EE3B46F58D9E52609"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli account register \
    --id="mad_hatter@looking_glass" \
    --key="ed01204595da8957c5598d4de20fe5f3eb4c14820678e1a1957a535db1fd4b3d1607c5"
"C6E66DD9BCC02898BEE127FF6BE2D7D18372BD865CFB64FE26A94C8D406AF169"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli account register \
    --id="white_rabbit@looking_glass" \
    --key="ed0120a4c4dadd9f18b0f63d6a420151fe0748d785475dec63034a15fcf999ceda1e65"
"9D425DB32C3A1316A7DDB86F3540DA63735A62EF746DAF9C60B7D2CFB0887D09"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset register \
    --id="tea#looking_glass" \
    --value-type=Quantity
"FECA904FFEB3BB9B655D661DC3996AB5BA54E4CB99A9533951D1CB596D16A9BD"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset mint \
    --account="mad_hatter@looking_glass" \
    --asset="tea#looking_glass" \
    --quantity="100"
"3D93A8DC7344F744425ABA2E2D133700B78D778D5170214E549871B53350643B"
➜  test_docker git:(iroha2-dev) ✗ ./iroha_client_cli asset transfer --from mad_hatter@looking_glass --to white_rabbit@looking_glass --asset-id tea#looking_glass --quantity 5
"BE5B2AE52400E8C68CAD9571BB4039F2338FC707F41A984D71BB45AF8D3F285B"
➜  test_docker git:(iroha2-dev) ✗ curl -X GET http://127.0.0.1:8180/metrics                                                                                                  
# HELP accounts User accounts registered at this time
# TYPE accounts gauge
accounts{domain="garden_of_live_flowers"} 1
accounts{domain="genesis"} 1
accounts{domain="looking_glass"} 2
accounts{domain="wonderland"} 2
# HELP block_height Current block height
# TYPE block_height counter
block_height 7
# HELP connected_peers Total number of currently connected peers
# TYPE connected_peers gauge
connected_peers 3
# HELP domains Total number of domains
# TYPE domains gauge
domains 4
# HELP dropped_messages Sumeragi dropped messages
# TYPE dropped_messages counter
dropped_messages 0
# HELP queue_size Number of the transactions in the queue
# TYPE queue_size gauge
queue_size 0
# HELP tx_amount average amount involved in a transaction on this peer
# TYPE tx_amount histogram
tx_amount_bucket{le="0.005"} 0
tx_amount_bucket{le="0.01"} 0
tx_amount_bucket{le="0.025"} 0
tx_amount_bucket{le="0.05"} 0
tx_amount_bucket{le="0.1"} 0
tx_amount_bucket{le="0.25"} 0
tx_amount_bucket{le="0.5"} 0
tx_amount_bucket{le="1"} 0
tx_amount_bucket{le="2.5"} 0
tx_amount_bucket{le="5"} 1
tx_amount_bucket{le="10"} 1
tx_amount_bucket{le="+Inf"} 4
tx_amount_sum 162
tx_amount_count 4
# HELP txs Transactions committed
# TYPE txs counter
txs{type="accepted"} 8
txs{type="rejected"} 0
txs{type="total"} 8
# HELP uptime_since_genesis_ms Network up-time, from creation of the genesis block
# TYPE uptime_since_genesis_ms gauge
uptime_since_genesis_ms 614620
# HELP view_changes Number of view changes in the current round
# TYPE view_changes gauge
view_changes 1

**Comment by SamHSmith** [comment]
The tx_amount_bucket, tx_amount_sum and tx_amount_count is the tx_amount histogram. It is solved.
