### ISSUE TITLE
[suggestion] Side-effect-free Queries

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3717]
### Feature request

All queries should be free of any side effects. This means that all queries are idempotent, unless the underlying `wsv` was modified after the query execution. 

This means specifically that the queries should not request `&mut wsv`, and no persistent data should be stored anywhere including the executor about which queries were executed. 

### Motivation

Queries are naturally assumed to be _read-only_ operations. However, by request of @Mingela we added some capability to track execution of queries and limit them. 

Instead we believe that the execution method of queries should be separated from regular execution of queries. 

### Who can help?

@Arjentix @appetrosyan

**Comment by Mingela** [comment]
With this, will it be still possible to consider executing some custom logic around queries (ideally atomically) via an executor or a permission validator?
