### ISSUE TITLE
[refactor] Replace `FindAccountsWithPermissionTokenDefinition` with filtered `FindAllAccounts`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3720]
- Originally suggested by @appetrosyan: https://github.com/hyperledger/iroha/pull/3707#discussion_r1266314964

Should be done after the merge of #3707 as a part of #3671 or in a separate PR.

### Who can help?
@appetrosyan , @DCNick3

**Comment by mversic** [comment]
while we're at it, we should remove `FindAccountsByName` and `FindAssetsByName(FindAssetsByName)`

**Comment by DCNick3** [comment]
I believe this is done as of the merge #4833
