### ISSUE TITLE
Check for unused dependencies in CI

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3725]
Would be nice to have a check for unused dependencies in CI. I'm sure there is some tool in Rust ecosystem

_Originally posted by @Arjentix in https://github.com/hyperledger/iroha/pull/3625#discussion_r1268011168_

**Comment by appetrosyan** [comment]
Too expensive to do in CI. 

I periodically prune dependencies with `cargo undepend`. This is a long process, and it requires human intervention.
