### ISSUE TITLE
[ci] Manual trigger workflow to start Load testing

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3734]
### Feature request

- [ ] Need a trigger with manual dispatch that takes the current `iroha2-dev` and `iroha2-stable` and deploys it on a k8s cluster with 4 peers. The peers are physically separated. 

- [ ] **Important** Not all builds of the `java` SDK are compatible with all builds of `iroha2-dev` and sometimes not all builds of `iroha2-stable`. 

- [ ] Then we deploy `gatling` as tuned by @timofeevmd, with the `iroha-java` SDK, and Grafana + Graphite. 

Gatling should be pointed at the peers in the k8s cluster, the cluster must pass initial consensus and monitoring for all machines should be done to at least gather the 
- [ ] RAM + CPU + 
- [ ] optional `prometheus` metrics. 

- [ ] Gatling also needs RAM + CPU monitoring. 

- [ ] The Graphite needs to be ran on a separate machine to prevent a cascading failure. 

### Motivation

Need load testing to know about Iroha's performance metrics and behaviour under a stress load.

**Comment by BAStos525** [comment]
We have:
- five iroha2 pods in k8s cluster
- outside instance for longevity service run
- Ansible playbook + Jenkins job for longevity service deployment
