### ISSUE TITLE
[BUG] Kagami cannot access the cloned repo in the tmp dir

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3741]
### OS and Environment

macOS 13.4 (22F66)

### GIT commit hash

2ebc38e0

### Minimum working example / Steps to reproduce

Run the following in the repo root:

1. `cargo build --release --bin kagami`
2. `./target/release/kagami validator`

### Actual result

Kagami fails with the following output:

```
Initialized empty Git repository in /private/var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ/iroha-cloned/.git/
remote: Enumerating objects: 734, done.
remote: Counting objects: 100% (734/734), done.
remote: Compressing objects: 100% (655/655), done.
remote: Total 734 (delta 83), reused 311 (delta 33), pack-reused 0
Receiving objects: 100% (734/734), 975.72 KiB | 294.00 KiB/s, done.
Resolving deltas: 100% (83/83), done.
From https://github.com/hyperledger/iroha
 * branch            2ebc38e051b90b8190b3795c7576094a9299982e -> FETCH_HEAD
HEAD is now at 2ebc38e [fix] #3445: make `POST configuration` work again
Error: 
   0: Failed to canonicalize path: /var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ/iroha-cloned/default_validator
   1: No such file or directory (os error 2)

Location:
   wasm_builder/src/lib.rs:113
```

As you can see, initially it clones the repo into `/var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ` temporary directory. It comes from here: 

https://github.com/hyperledger/iroha/blob/2ebc38e051b90b8190b3795c7576094a9299982e/tools/kagami/src/validator.rs#L25

Then, _for some reason_, this directory disappears before it is actually used by Kagami. 

### Expected result

Expected to build the validator successfully.

### Notes

I think that the cause might be an incorrect usage of `tempfile` crate.

**Comment by 0x009922** [comment]
### Reproducible on Linux

**System:** Linux `6.1.29-1-MANJARO` (`x86_64`)

**Output:**

```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /tmp/.tmpuFjnRa/iroha-cloned/.git/
remote: Enumerating objects: 734, done.
remote: Counting objects: 100% (734/734), done.
remote: Compressing objects: 100% (655/655), done.
remote: Total 734 (delta 85), reused 308 (delta 33), pack-reused 0
Receiving objects: 100% (734/734), 974.70 KiB | 1.27 MiB/s, done.
Resolving deltas: 100% (85/85), done.
From https://github.com/hyperledger/iroha
 * branch            2ebc38e051b90b8190b3795c7576094a9299982e -> FETCH_HEAD
HEAD is now at 2ebc38e [fix] #3445: make `POST configuration` work again
Error: 
   0: Failed to canonicalize path: /tmp/.tmpuFjnRa/iroha-cloned/default_validator
   1: No such file or directory (os error 2)

Location:
   wasm_builder/src/lib.rs:113
```

**Comment by timofeevmd** [comment]
after run a comand ./target/release/kagami validator
below you can see the output of the validator

[validator_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTRoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19f852aff9a2a58a36225d1fb80f9a8a5ab57b25/validator_output.txt)

**Comment by ilchu** [comment]
> commit [ee60fc8](https://github.com/hyperledger/iroha/commit/ee60fc828aa50cdcf5bd8cd270868597656df8a6)
> 
> Environment macOs Ventura 13.3 m1
> 
> after run a comand ./target/release/kagami validator below you can see the output of the validator
> 
> [validator_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTRoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19f852aff9a2a58a36225d1fb80f9a8a5ab57b25/validator_output.txt)

Answered in the corresponding PR: [comment](https://github.com/hyperledger/iroha/pull/3748#issuecomment-1687454611)
