### ISSUE TITLE
[refactor]: Type check by injection

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3764]
One trick that you could do here is to insert the actual type with the fully qualified path. What this will do is also type check the output of the function.

So you could for example replace the return type with `::iroha_validator::validator::ValidatorResult`, and allow `rustc` to also type check the output, not just be a passive observer. 

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3723#discussion_r1278086983_

**Comment by Arjentix** [comment]
Was done initially in #3723 as I pointed [here](https://github.com/hyperledger/iroha/pull/3723#discussion_r1278935635)
