### ISSUE TITLE
[suggestion] publish 2.0.0-RC* images to container registry

### ISSUE THREAD

**Issue by petermetz** [hyperledger/iroha#3771]
### Chore request

The Hyperledger Cacti contributors are hard at working adding support[1] for Iroha 2 and we could use some of the RC images published on the container registry of your choice.

[1] https://github.com/hyperledger/cacti/pull/2252

We do have a workaround of just using the digests but the digest encodes much less information and makes mistakes easier to make.

If the issue is that the automated publishing is not set up and it would take a long time, then I'm happy to volunteer to manually publish an image or two to the official hyperledger org on the GitHub Container Registry (where we also publish Cacti images). I believe I can do this without any help from the Iroha maintainers but I wouldn't want to do it without explicit permission of course, so please let me know what you think!

### Motivation

Please see my specific comment here:
https://github.com/hyperledger/cacti/pull/2252#issuecomment-1658840143

### Who can help?

@appetrosyan

**Comment by appetrosyan** [comment]
Our convention is that anything other than `-stable` and `-lts` is an unsupported version. However, we are conscious of the fact that a rolling release might not be in everyone's interest so we added the digest to pin dependencies. 

As an intermediate measure, we could add the crate major-minor-patch-rc triplet into the digest as a prefix, turning: 
```
iroha-{hash} 
```
into 
```
iroha-v2.0.0-pre-rc.18-{hash}
```

does that sound good for you @petermetz ?

**Comment by appetrosyan** [comment]
Keep in mind that this only a temporary solution, when Iroha v2.0.0 is released, it will follow proper independent semantic versioning of all of its components.

**Comment by petermetz** [comment]
> Our convention is that anything other than `-stable` and `-lts` is an unsupported version. However, we are conscious of the fact that a rolling release might not be in everyone's interest so we added the digest to pin dependencies.
> 
> As an intermediate measure, we could add the crate major-minor-patch-rc triplet into the digest as a prefix, turning:
> 
> ```
> iroha-{hash} 
> ```
> 
> into
> 
> ```
> iroha-v2.0.0-pre-rc.18-{hash}
> ```
> 
> does that sound good for you @petermetz ?

@appetrosyan Yes, that would work just fine (anything will work that allows us to refer to a specific image version that is not changing over time the way `latest` or `lts` does) Thank you very much!
