### ISSUE TITLE
[suggestion] Restructure the Iroha repository

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#3773]
### Feature request

Based on the discussion we've had previously with @appetrosyan, there are several points regarding Iroha structure that could use some enhancement. The structure could be recategorized into:
* Functionality pertaining to peer creation should be grouped together. That would include crates such as `cli` or `logger`, as they are not related to core logic, but are rather an implementation detail. This category could also include `test_network` as it constitutes a peer implementation of sorts. Anything pertaining to `core` should remain monolithic and put into peer category as well.
* WASM-related crates' position is somewhat dubious. They're mostly a realization detail, and instead smartcontracts should be at the forefront, as that's the thing that most interests a developer who's an outside user of Iroha. Overall smartcontracts should be separate from core and grouped with WASM crates in a single category.
* Smartcontract tests that are currently kept in `client/tests/integration` are also an important detail that could serve as an example of implementation for the consumer, but it's currently hidden away deep in the nested structure. They should be part of a top-level smartcontract folder, and that's where we could start building the functionality mentioned in #3283.
* Client functionality, including Torii, web glue and so on.
* Executor and friends.
* Some miscellaneous items like tools, docs and such.

Coming back to the smartcontracts, we need to be thinking more about the workflow imposed by the folder structure, targeting ease of use for our consumers. This would also be helped by detailed documentation, guiding anyone not familiar with the repo which particular crates s/he would need to use to implement some desired functionality.

### Motivation

More intuitive repo navigation, semantically sane structuring of crates in the workspace, easier onboarding. Ease of use for people besides core maintainers.

### Who can help?

@ilchu @appetrosyan

**Comment by mversic** [comment]
let's do this right after RC20 release so as not to conflict with other work

**Comment by 0x009922** [comment]
I would also suggest renaming the directories so that they are directly mapped to the library/binary name. E.g., instead of `cli` name it just `iroha`, `client_cli` -> `iroha_client_cli`, `tools/kagami` -> `kagami` etc. It will make life of users and possible newcomer contributors a little simpler.

**Comment by mversic** [comment]
of questionable value. Should be reconsidered

**Comment by mversic** [comment]
not something we will consider atm
