### ISSUE TITLE
[refactor] Migrate from warp to axum/actix

### ISSUE THREAD

**Issue by ilchu** [hyperledger/iroha#3776]
### Feature request

Replace `warp` crate to a more batteries included kind of web framework, main candidates being `axum` or `actix`. Do some researching/benchmark to determine what's better, if possible.

### Motivation

Currently the `warp` crate is used throughout the `cli` and `version` parts of the codebase, but it's been known as a pain point for a while with unwieldy filter type signatures occupying the whole screen and awkward proc macro metaprogramming to reach our goals.

### Who can help?

@appetrosyan

**Comment by 0x009922** [comment]
I guess it will automatically close #2430

**Comment by DCNick3** [comment]
In https://github.com/hyperledger/iroha/pull/3983#discussion_r1365171284 it was suggested to postpone more proper content type negotiation until we move to actix/axum. Don't forget to handle it
