### ISSUE TITLE
Validate genesis transactions

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3781]
Currently we do not validate transactions in genesis for historical reasons.

There are a couple of problems with that:

1. We cannot validate permission tokens usage in genesis
2. Validator may want to have all transactions to be passed through it so that it can store some information inside

The solution is to validate genesis transaction but with some additional info, so that Validator could know that it's from genesis.
@mversic proposed to pass block number to the validator. Seems a good solution to me, because with that users can also implement some interesting logic like "Let users do X after the block N" (like a permission delayed in time).

**Comment by appetrosyan** [comment]
Postponed to ISA RFC
