### ISSUE TITLE
[BUG] Lockfile is present after Iroha is stopped in Kubernetes as PID1 

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3792]
### Minimum working example / Steps to reproduce

Signal propagation in Kubernetes doesn't let Iroha finish correctly as `PID 1`. Lockfile remains.
Issue repeats with dev builds on a single container (`docker-compose.dev.single.yml`) with the fresh (`e208f8ca470`) code.
Thanks to @BAStos525 for isolating the issue.

### Who can help to reproduce?

@astrokov7

**Comment by astrokov7** [comment]
https://github.com/hyperledger/iroha/issues/3793 Created the bug report

**Comment by nxsaken** [comment]
Superseded by #3793
