### ISSUE TITLE
[BUG] Signal Propagation Issue Prevents Correct Termination of Iroha as PID 1 in Kubernetes with Docker Compose

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#3793]
### OS and Environment

MacOS, Docker Hub

### GIT commit hash

7e7c120e

### Minimum working example / Steps to reproduce

```bash
docker compose -f docker-compose.dev.single.yml up -d
docker compose -f docker-compose.dev.single.yml stop 
docker compose -f docker-compose.dev.single.yml up   
```

### Actual result

Iroha does not terminate correctly, leaving a lockfile at /storage. When attempting to start Iroha again, the presence of this lockfile results in an error and prevents the service from starting.
```
Error: Tried to lock block store by creating a lockfile at /storage, but it already exists
Location:
    /iroha/cli/src/lib.rs:240:20
```

### Expected result

Iroha should terminate gracefully without leaving a lockfile behind, allowing for a subsequent successful restart.

### Logs 

<details>
  <summary>Log contents</summary>
  
  ```bash
alexstrokelive@Aleksandrs-MacBook-Pro-169 iroha % docker compose -f docker-compose.dev.single.yml up -d
[+] Running 1/1
 ⠿ Container iroha-iroha0-1  Started                                                                                                                                         0.5s
alexstrokelive@Aleksandrs-MacBook-Pro-169 iroha % docker compose -f docker-compose.dev.single.yml stop 
[+] Running 1/0
 ⠿ Container iroha-iroha0-1  Stopped                                                                                                                                         0.0s
alexstrokelive@Aleksandrs-MacBook-Pro-169 iroha % docker compose -f docker-compose.dev.single.yml up   
[+] Running 1/0
 ⠿ Container iroha-iroha0-1  Created                                                                                                                                         0.0s
Attaching to iroha-iroha0-1
iroha-iroha0-1  | 2023-08-09T09:36:24.725882Z  WARN iroha: The configuration parameter `DISABLE_PANIC_TERMINAL_COLORS` is deprecated. Set `TERMINAL_COLORS=false` instead. 
iroha-iroha0-1  | 2023-08-09T09:36:24.727523Z  INFO iroha: Hyperledgerいろは2にようこそ！(translation) Welcome to Hyperledger Iroha! version=2.0.0-pre-rc.18 git_commit_sha="7e7c120e"
iroha-iroha0-1  | 2023-08-09T09:36:24.771617Z  INFO init:start{listen_addr=Host(SocketAddrHost { host: "iroha0", port: 1337 })}: iroha_p2p::network: Network bound to listener
iroha-iroha0-1  | 2023-08-09T09:36:24.786477Z  INFO run{listen_addr=iroha0:1337 public_key=ed01208BA62848CF767D72E7F7F4B9D2D7BA07FEE33760F79ABE5597A51520E292A0CB}: iroha_p2p::network: All handles to network actor are dropped. Shutting down...
iroha-iroha0-1  | Error: Tried to lock block store by creating a lockfile at /storage, but it already exists
iroha-iroha0-1  | 
iroha-iroha0-1  | Location:
iroha-iroha0-1  |     /iroha/cli/src/lib.rs:240:20
iroha-iroha0-1 exited with code 1
alexstrokelive@Aleksandrs-MacBook-Pro-169 iroha % 
  ```
</details>

### Who can help to reproduce?

@astrokov7

### Notes

When running Iroha as PID 1 in a Kubernetes environment, an issue is observed where the signal propagation doesn't allow the application to terminate correctly. This leads to a remaining lockfile, preventing subsequent instances of Iroha from starting correctly. The issue has been isolated to the development builds using docker-compose.dev.single.yml

Furthermore, this behavior is observed during any non-standard termination of Iroha. Even in expected termination scenarios, such as updating the version where containers are recreated, Iroha does not send the SIGTERM signal to its process nor does it delete the lockfile.

Attempts to handle signal propagation with tini as PID 1 were unsuccessful, as evidenced by the processes' output:
```sql
PID   USER     TIME  COMMAND
1 iroha     0:00 /sbin/tini -- /usr/local/bin/iroha
7 iroha     0:17 /usr/local/bin/iroha
113 iroha     0:00 ps
```

**Comment by mversic** [comment]
I think we should make sure that we exit gracefully as possible at least in the sense that we remove the `.lock` file on exit

**Comment by VAmuzing** [comment]
Both #3831 and #3806 improved cleanup code and removed the necessity of manual deletion of `kura.lock` file.
Currently the bug is not reproducible.
If after some changes in the future the bug returns we might consider manual deletion of `kura.lock` file.
