### ISSUE TITLE
[BUG] kagami unable to deploy docker containers from generated docker compose

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#3828]
### OS and Environment

Dockerhub, linux Ubuntu 22.04.2 LTS

### GIT commit hash

ee60fc82

### Minimum working example / Steps to reproduce

docker image dfe6dead90b5

```bush
cargo install --git https://github.com/hyperledger/iroha.git \
   --all-features \
   --rev 7e7c120e \
   --root ./cargo-install-root \
   kagami
   
./kagami  swarm  --peers 5 dir ./kagami_config_image --image hyperledger/iroha2:dev
```

Same result 
```bash
./kagami swarm  --peers 5 dir ./kagami_config_github --build-from-github
```

```bash
./kagami swarm  --peers 5 dir ./kagami_config --build /home/mtimofeev/project/iroha
```

### Actual result

 * branch            7e7c120e0dc4e5c786f0c421fc25205621cff31a -> FETCH_HEAD
HEAD is now at 7e7c120 [refactor] #2398: Add integration tests for query filters
Error: 
   0: Failed to prepare configuration
   1: Failed to canonicalize path: /home/mtimofeev/project/iroha/kagami_config/cargo-install-root/bin/default_validator
   2: No such file or directory (os error 2)

Location:
   wasm_builder/src/lib.rs:113

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

### Expected result

iroha working, 4 peers working

### Logs in JSON format

<details>
 unfortunately no logs
</details>

### Who can help to reproduce?

@timofeevmd

**Comment by 0x009922** [comment]
This issue is no longer relevant:

- #3841

`kagami swarm` is now a separate `iroha_swarm` binary. It doesn't have `dir` mode anymore.
