### ISSUE TITLE
Fix stable/lts config update job

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3849]
As you can see [here](https://github.com/hyperledger/iroha/actions/runs/6008950057/job/16297459509) this job fails because it doesn't have the permission to merge anything into protected branch `iroha2-dev`. The same job fails when executed from `iroha2-stable` and `iroha2-lts` branches

We should find a way to allow config update to be merged

**Comment by BAStos525** [comment]
Fix: https://github.com/hyperledger/iroha/pull/3894
