### ISSUE TITLE
Replace `null` with `{}` in token payload

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3861]
currently we're using `json!(null)` to create permission token without payload. I think it would be more appropriate to use `json!({})`

**Comment by farhan61023h** [comment]
I think you must prefer json!({}).

**Comment by pratik-31** [comment]
Can I work on this issue?

**Comment by farhan61023h** [comment]
@pratik-31 I am having a question that is this issue workable or he is just asking a question?

**Comment by pratik-31** [comment]
@farhan61023h I was also confused but if is this an issue I can contribute. @mversic Please clarify

**Comment by farhan61023h** [comment]
@mversic Same goes here :)

**Comment by mversic** [comment]
this is still and open question. Considering how serde serializes ZST and how we serialize ZST into schema `null` might be appropriate here
