### ISSUE TITLE
[suggestion] Add `this file is autogenerated` into `iroha_swarm` output

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3868]
Before #3864 I had no idea that our `docker-compose.dev.*` files are generated with `iroha_swarm`.

I suggest to add a comment like:

```yml
# This file is autogenerated with `iroha_swarm <used options>`
```

@0x009922 , what do you think?

**Comment by 0x009922** [comment]
I think it is a good idea!

Not sure about adding the exact options used, but why not. Seeing an exact seed might help.

Also I think it might be not always intended. What about enabling/disabling it with a flag like `--disclaimer-header`?

**Comment by Arjentix** [comment]
`--disclaimer-header` sounds fine
