### ISSUE TITLE
Remove `IsAssetDefinitionOwner` query

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3874]
This query was introduced only for the purposes of validator. Since #3442 we can use `FindAssetDefinitionById` to do the exact same thing.

**Comment by benhhack** [comment]
Hey there, I'm a fairly experienced Python programmer with some experience in C++ and Solidity. I'd love to pick up this issue to contribute to your DL. Besides for the docs and YouTube vids, would you recommend anything to help me get up to speed?

**Comment by mversic** [comment]
I will assign you. I expect you will find this issue to be easy enough. You can look at Iroha2 [documentation](https://hyperledger.github.io/iroha-2-docs/)

**Comment by benhhack** [comment]
> I will assign you. I expect you will find this issue to be easy enough. You can look at Iroha2 [documentation](https://hyperledger.github.io/iroha-2-docs/)
I've been looking through the docs and am understanding better whats going on, however, I can't find this query anywhere. Could you please help with a little more direction?

**Comment by mversic** [comment]
look at `iroha2-dev` branch in the module `data_model/query/mod.rs`

**Comment by benhhack** [comment]
@mversic I'm having some problems understanding Cargo, Rust, and where everything is in the repository. When running cargo build I get the error

```
error[E0412]: cannot find type `IsAssetDefinitionOwner` in this scope
   --> data_model/src/lib.rs:138:9
    |
138 |         IsAssetDefinitionOwner,
    |         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

```

Which I should be getting because I have removed this. I'm not sure where this error is coming from, however. Where do I tell the system to stop looking for this query?

**Comment by mversic** [comment]
@benhhack `cargo` literally tells you that you have a reference to `IsAssetDefinitionOwner` at line 138 in `data_model/src/lib.rs`. Go there and remove it. You can also just `grep` the whole repository and find where `IsAssetDefinitionOwner` is mentioned. Go to every file and delete
