### ISSUE TITLE
[refactor] : Make Iroha version ```2.0.0-pre-rc.19```compatible for Blockchain Explorer

### ISSUE THREAD

**Issue by horizenight** [hyperledger/iroha#3880]
## Description

Currently, the blockchain explorer backend requires various methods that were in Iroha version ```2.0.0-pre-rc.16``` but are not present / structured changed in  Iroha version ```2.0.0-pre-rc.19```. 
This patch will be addressing commits related to it.

**Comment by 0x009922** [comment]
I researched code more in-depth. There are big changes after the merge of #3621. It almost reverts the work I made back then in #2146 & #2147. Now `iroha_client` crate doesn't provide transport-agnostic functionality anymore.

Thus, the major point of this fix is to make it transport-agnostic again. Will try to solve it shortly.

**Comment by 0x009922** [comment]
Closing in favor of https://github.com/soramitsu/iroha2-block-explorer-backend/pull/44
