### ISSUE TITLE
Prune usage of V1 structs from codebase

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3887]
Let's see to what extent can we rewrite the code (source code or tests) that destructures versioned enum into a concrete type:
- for example `VersionedSignedBlock::V1` must not be used except in `data_model`
- no code outside of `data_model` should depend on a specific version

**Comment by Stukalov-A-M** [comment]
To hide internal structure of versioning structs from external users and a public API.
To keep access for internal crates.
