### ISSUE TITLE
[BUG]: `docker-compose.*.yml` for `iroha2-stable` aren't covered with CI

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3889]
## Description

Recently we started to use `kagami swarm` ([now `iroha_swarm`](https://github.com/hyperledger/iroha/pull/3841)) to generate Docker Compose configurations in the repo. It was introduced in the `iroha2-dev` branch. Thus, only `docker-compose.dev.*.yml` files were covered by that.

Now `kagami swarm` is integrated into `iroha2-stable`, but CI still targets `dev` branch:

https://github.com/hyperledger/iroha/blob/77d96c8577b148df4e2f000712807dbaca4d7a8a/scripts/check.sh#L59-L61

Docker Compose configurations for `stable` branch were **not updated** and are **not checked** by CI.

### Proposed Solution

Configure CI checks that way so in `iroha2-stable` it checks how `kagami swarm` generated configurations for `stable` channel.

...Or try to get rid of confusing approach of having configurations for all 3 branches in all 3 branches. Currently `iroha2-lts`, `iroha2-dev` and `iroha2-stable` all have docker compose files for `lts`, `stable` and `dev` branches (not sure about `lts` though, haven't checked). Maybe it makes sense in each branch to have configuration related to that branch. That way, the CI will be uniform.

**Comment by mversic** [comment]
this will likely not be an issue very soon if we'll drop `stable` and `lts`
