### ISSUE TITLE
[suggestion] Move `NewParameter` into Executor

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3901]
We should consider removing `NewParameter` ISI and only allow defining new parameters in Executor. During Executor migration old parameters will be removed and new ones can be added. The reason is that having an ISI doesn't make sense for an operation that can only be executed by the blockchain admin

**Comment by Arjentix** [comment]
I think that would be right

**Comment by 0x009922** [comment]
What means "move `NewParameter` into Executor"?

As far as I understand, Executor just has access to all parameters, to the key-value storage with some data. And, Executor just "interprets" certain keys in a certain way which defines Executor's behaviour.

Is it needed for Executor to define "known" parameters in some way?

**Comment by mversic** [comment]
just look at how permission tokens are defined in Executor. We need to replicate that mechanism

**Comment by alexstroke1** [comment]
This instruction has been removed, now there is only `SetParameter`
