### ISSUE TITLE
[refactor]: Shallow objects in `data_model`

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3921]
Currently objects in `data_model` are nested. `Domain`s contain `Account`s and `AssetDefinition`s inside it, `Account`s contains `Asset`s and `Role`s and so on.

We should consider making objects shallow: so that all `Asset`s would be sotred in the single place and only reference owner `Account` by it's `AccountId`.

This way iteration over objects will be more effective. 

As a sidenote such structure more closely resemble data organization typically encountered in relational databases.

**Comment by mversic** [comment]
let's consider after new wsv

**Comment by SamHSmith** [comment]
First PR was merged.

**Comment by nxsaken** [comment]
Apparently, we're moving to a sort of static Entity-Component-System / Struct of Arrays, so all data model structs should eventually disappear.

**Comment by SamHSmith** [comment]
This issue is about how the code should be structured. PR's containing these changes have been merged already. Therefore the issue is closed.
