### ISSUE TITLE
Remove `InstructionBox::Sequence`, `InstructionBox::Pair`, `InstructionBox::If`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3922]
following KSS, these ISI are entirely redundant:
* `InstructionBox::If` can be expressed with `Expression::If`
* `InstructionBox::Pair` is just `InstructionBox::Sequence` of length 2
* `InstructionBox::Sequence` can be expressed with transaction of the same length

**Comment by Erigara** [comment]
Could be done as part or after #4089

**Comment by mversic** [comment]
done in #4089
