### ISSUE TITLE
[BUG] failed wasm tests do not fail the CI

### ISSUE THREAD

**Issue by DCNick3** [hyperledger/iroha#3928]
For some reason (maybe because of `webassembly_test`), failed tests do not make the CI fail, making it useless ([example of a job that should've failed](https://github.com/hyperledger/iroha/actions/runs/6308478359/job/17126693246))

**Comment by mversic** [comment]
duplicate of #3933

**Comment by DCNick3** [comment]
That's a PR I just made to fix it?

**Comment by mversic** [comment]
yes
