### ISSUE TITLE
Lazy queries inside WASM

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3929]
We support lazy (kind-of) queries for basic clients, but it's not supported for WASM. 

This creates some problems. For example because of that we cannot move our queries execution into Executor causing stragne divergence: transctions and instructions are executed, but queries are not.

Need to implement lazy evaluation for WASM as well

**Comment by mversic** [comment]
> This creates some problems. For example because of that we cannot move our queries execution into Executor causing stragne divergence: transctions and instructions are executed, but queries are not.

This is not the reason to implement lazy queries in wasm. If query is executed from Executor the result should be cached on the host (i.e. not returned to the Executor) during validation because there is no point in dragging the result through Executor again

**Comment by mversic** [comment]
not to mention that it's a security issue to allow references to flow from host into smartcontract. A malicious smartcontract could execute several such queries until it induces OOM on the host
