### ISSUE TITLE
Add instruction expressions

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3942]
`InstructionExpr` at the moment is a special kind of expression

We need a support to evaluate an expression into an instruction that can be executed on the host.

As a consequence, `data_model::transaction::Executable` should be modified to something that looks like:
```rs
pub enum Executable {
    Instructions(Vec<EvaluatesTo<InstructionBox>>),
    Wasm(WasmSmartContract),
}
```

where `InstructionBox` is an actual instruction to be executed, it must not contain any expression to evaluate

**Comment by 0x009922** [comment]
Looks like a step towards ISA normalisation.

Anyway, could we come up with a use-case for that?
