### ISSUE TITLE
Update the MAINTAINERS.md in `iroha2-dev`

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3947]
At some point, we want `iroha2-dev` branch to become a `main` one.

After https://github.com/hyperledger/iroha/pull/3946 is merged and https://github.com/hyperledger/iroha/issues/3945 is resolved, I'd like to replace the severely outdated https://github.com/hyperledger/iroha/blob/iroha2-dev/MAINTAINERS.md with a new version, so at the later point, we don't accidentally add a version of `MAINTAINERS` from Iroha 1 and leave it.

**Comment by nxsaken** [comment]
@6r1d does this need any work done, or should I close it?
