### ISSUE TITLE
Decide the approach towards Iroha 1

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3948]
This topic is raised often, but I need to raise it again: what do we do about Iroha 1 at the [`main`](https://github.com/hyperledger/iroha) branch?

The development effort is concentrated around Iroha 2, and most of our Developers are best in Rust, but we keep the Iroha 1 project, which adds some CI confusion and a lot of changes in docs.

At the same time, @baziorek contributes to Iroha 1, and CI-related testing is often confusing not only for him but everyone else.

Until which point do we keep Iroha 1 as it is?

**Comment by Mingela** [comment]
Most likely until Iroha2 'full' release at least

**Comment by nxsaken** [comment]
Superseded by #4433.
