### ISSUE TITLE
[suggestion]: Add `Domain` owner

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3953]
### Feature request

Request was received request to add support for `Domain` owner.
It's account with permissions to:
- Unregister domain
- Edit domain metadata 

I have 2 approaches in mind:

1. Require changes in `data_model` and `core`: add `owned_by` field to the `Domain` then reuse code from `AssetDefinition` which also had owner.
2. Require changes only in `validator`: on `Domain` registration give all required permissions to the account who registered it, user can grant permission to another account if user have this permission itself.

### Motivation

Without this concept `Domain`s are frozen entities...

### Who can help?

@Erigara

**Comment by mversic** [comment]
I find that approach 1 is preferred. A domain should be given a new field `Domain::owner`

>  It's account with permissions to:
    * Unregister domain
    * Edit account metadata

what should be permissions of domain owner. Obviously, Domain owner should have permissions to Unregister and modify domain metadata, but what about modifying domain data? Should this Domain owner have access to all accounts and asset definitions within the domain? Following our logic for asset definition in default validator I would say yes

Let's be clear, we're only discussing what is the behavior of default validator. A user can always write their own if they disagree with defaults provided

**Comment by mversic** [comment]
> > Following our logic for asset definition in default validator I would say yes
> 
> I agree, if user can unregister domain, it will also delete all accounts and asset definitions

just to be clear, this means that Domain admin is also an admin of all Accounts in this domain? It has the privilege to mint/burn assets for them, etc.

**Comment by Erigara** [comment]
> just to be clear, this means that Domain admin is also an admin of all Accounts in this domain? It has the privilege to mint/burn assets for them, etc.

Yes, i understand the implications of this. It sound scary that someone could burn/mint your assets. But it's the same level of concern that someone can just drop your account, no?

**Comment by mversic** [comment]
I think we agree then
