### ISSUE TITLE
Revise telemetry paths

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3959]
I would also like to revise the paths themselves:

- `/status` → `/telemetry/status`
- `/metrics` → `/telemetry/metrics`

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/3956#pullrequestreview-1659170245_

**Comment by mversic** [comment]
do we want to make this update of our URL paths?

**Comment by 0x009922** [comment]
My intention is to reduce confusion between two endpoints: `/health` and `/status`. Both are kind of "status checks". The purpose of each might be more clear with `/telemetry` nesting. Also, as we spoke in Telegram, it will be a _little bit_ easier for admins to guard all `/telemetry/*` endpoints from public access.

**Comment by mversic** [comment]
let's ask @mingela and other users do they see this as valuable

**Comment by 0x009922** [comment]
Had a small poll in the "Library Authors" chat. Only @Mingela expressed their opinion (fine either way).
