### ISSUE TITLE
[BUG]: Permission tokens aren't removed

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3962]
Currently permission tokens aren't removed when there associated entity is removed.

This makes scenarios like this one possible: 

1. Account A register asset definition and give account B token to unregister it
2. Account A unregister asset definition
3. Account C register asset definition with the same id
4. Account B can unregister this asset definition

**Comment by mversic** [comment]
we have the same problem with permissions for domains, accounts, asset definitions and assets. Just about any entity. This sounds like an issue that should be resolved from within executor, not the host

**Comment by mversic** [comment]
consider introducing a unique integer for every entity (AssetDefinition)

**Comment by Erigara** [comment]
another option is to prohibit reregistering entities with the same name
