### ISSUE TITLE
Docker-compose process exits with missing Iroha binary and genesis initialization errors.

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#3966]
### OS and Environment

MacOS, Docker Hub, hyperledger/iroha2:stable-2.0.0-pre-rc.19

### GIT commit hash

3119c23e

### Minimum working example / Steps to reproduce

```bash
docker-compose -f docker-compose.stable.yml up
```

### Actual result

Containers iroha-iroha2-1, iroha-iroha3-1, and iroha-iroha1-1 exit with a fatal error, indicating that the Iroha binary ${BIN_PATH}/iroha is missing. The iroha-iroha0-1 container logs a warning about a deprecated configuration parameter and exits with an error indicating that it failed to initialize genesis due to the missing file /config/./validator.wasm.

### Expected result

All containers should start without any errors, and services within should become operational.

### Logs in vbnet format

<details>
  <summary>Log contents</summary>
  
  ```vbnet
iroha-iroha2-1  | [FATAL tini (8)] exec ${BIN_PATH}/iroha failed: No such file or directory
iroha-iroha3-1  | [FATAL tini (7)] exec ${BIN_PATH}/iroha failed: No such file or directory
iroha-iroha1-1  | [FATAL tini (7)] exec ${BIN_PATH}/iroha failed: No such file or directory
iroha-iroha0-1  | 2023-10-05T12:04:40.883172Z  WARN iroha: The configuration parameter `DISABLE_PANIC_TERMINAL_COLORS` is deprecated. Set `TERMINAL_COLORS=false` instead.
iroha-iroha0-1  | 2023-10-05T12:04:40.884902Z  INFO iroha: Hyperledgerいろは2にようこそ！(translation) Welcome to Hyperledger Iroha! version=2.0.0-pre-rc.19 git_commit_sha="3119c23"
iroha-iroha0-1  | Error: Failed to initialize genesis.
iroha-iroha0-1  | 
iroha-iroha0-1  | Caused by:
iroha-iroha0-1  |    0: Failed to open "/config/./validator.wasm"
iroha-iroha0-1  |    1: No such file or directory (os error 2)
iroha-iroha0-1  | 
iroha-iroha0-1  | Location:
iroha-iroha0-1  |     genesis/src/lib.rs:167:22
iroha-iroha2-1 exited with code 127
iroha-iroha3-1 exited with code 127
iroha-iroha1-1 exited with code 127
iroha-iroha0-1 exited with code 1


  ```
</details>

### Who can help to reproduce?

@astrokov7 @Arjentix

### Notes

@AlexStroke : It appears that the Dockerfile for stable may be outdated or broken. This assumption is based on the fact that all client tests pass successfully in a bare metal environment. The current evidence suggests the docker-compose files may require updates before any merge to stable or LTS.

**Comment by timofeevmd** [comment]
the problem persists

```bash
➜  iroha git:(iroha2-stable) ✗ docker logs c3d25b9ce9fa
2023-11-08T11:15:02.529652Z  WARN iroha: The configuration parameter `DISABLE_PANIC_TERMINAL_COLORS` is deprecated. Set `TERMINAL_COLORS=false` instead. 
2023-11-08T11:15:02.531150Z  INFO iroha: Hyperledgerいろは2にようこそ！(translation) Welcome to Hyperledger Iroha! version=2.0.0-pre-rc.20 git_commit_sha="c99039b"
Error: Failed to deserialize raw genesis block from "/config/genesis.json"

Caused by:
    missing field `object` at line 95 column 9

Location:
    /iroha/genesis/src/lib.rs:118:75
```
