### ISSUE TITLE
[suggestion]: Extend functionality of `iroha_client_cli` 

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3974]
### Feature request

After merge of #3963 there is couple of features missing from `iroha_client_cli`.

- [x] Transferring `Domain` between users
- [x] Setting/Removing metadata for `Domain`
- [ ] Minting/Burning trigger repetitions

### Motivation

Help user to express what they what using `iroha_client_cli`.

### Who can help?

@Erigara

**Comment by timofeevmd** [comment]
@VAmuzing could you tell me, is it possible to add to the documentation what exactly the domain metadata set command takes as input?
It was not obvious to me as a user what type of parameters this command accepts
