### ISSUE TITLE
Why is `Action` parametrized by filter type?

### ISSUE THREAD

**Issue by QuentinI** [hyperledger/iroha#3986]
As per title: `iroha_data_model::trigger::Action` [is parametrized](https://github.com/hyperledger/iroha/blob/f5df08510436b7cad39aacad0ea1f2cd4fa51e1a/data_model/src/trigger.rs#L223) by `F: Filter`. There exists `TriggeringFilterBox` which is an enum listing all applicable filters - is there a reason it's not always the concrete type of `Action::filter`?

**Comment by QuentinI** [comment]
>   Assign @arjentix to the issue. He implemented it, he should know

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/3965#discussion_r1356899908_

**Comment by Arjentix** [comment]
Take a look here https://github.com/hyperledger/iroha/blob/f5df08510436b7cad39aacad0ea1f2cd4fa51e1a/core/src/smartcontracts/isi/triggers/set.rs#L41-L64

We store actions strongly typed by the exact filter, because they require different processing

**Comment by QuentinI** [comment]
> We store actions strongly typed by the exact filter, because they require different processing

We could have `HashMap<TriggerId, LoadedAction>` for all of those fields though. Is the purpose just expressing the nature of different maps with concrete types or are there any other reasons for this?

**Comment by Arjentix** [comment]
Closed in favor of #4259
