### ISSUE TITLE
[suggestion] Simplify genesis config

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4029]
## Description

I propose to simplify genesis configuration a little bit by moving it to config file & env and dropping the related CLI flag.

### How it works now

There are the following configurations:

- `--submit-genesis` CLI flag to enable submitting for a particular field
- `IROHA_GENESIS` env var with path to genesis file (defaults to `genesis.json`)
- `genesis.public_key` (`GENESIS_PUBLIC_KEY`) parameter that must be set for ALL peers
- `genesis.private_key` (`GENESIS_PRIVATE_KEY`) parameter that must be set when `--submit-genesis` is set.

What is wrong:

- `IROHA_GENESIS` can only be set via ENV
- Intention to submit genesis is duplicated by setting `--submit-genesis` and `genesis.private_key`

### Proposed change

- `genesis.public_key`, required for all
- `genesis.private_key` and `genesis.file` for the peer that submits the genesis
- `genesis.file` _might_ have a default value (`genesis.json`) which is applied if only `genesis.private_key` is set. Although it might make behaviour somewhat unclear. I think enforcing `genesis.file` to be set explicitly will be more reliable.

Benefits:

- Flexible: genesis might be configured via only config file, or via only ENV, or mixed
- Simple: no extra CLI flag

**Comment by 6r1d** [comment]
Thanks, that looks reasonable. If this issue is copied to the docs with minimal changes, it will help the users a lot in the setup stage.

**Comment by 0x009922** [comment]
Related discussion: https://github.com/hyperledger/iroha-2-docs/pull/397#discussion_r1342220725

**Comment by Mingela** [comment]
What is the error handling procedure in case multiple peers have genesis private key specified?

**Comment by 0x009922** [comment]
> What is the error handling procedure in case multiple peers have genesis private key specified?

@Mingela, I don't know how the situation of multiple peers submitting genesis blocks is handled now. Anyway, this proposal doesn't change anything here. It only changes the way of configuration.

**Comment by Mingela** [comment]
Fine to me then
