### ISSUE TITLE
Enhancing iroha_client_cli to Support Minting with BigQuantity, Fixed, and Store Types

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4035]
### Objective:
The objective of this task is to extend the iroha_client_cli tool to enable the minting of assets with additional parameters: BigQuantity, Fixed, and Store. This enhancement will allow users to mint assets with specific quantities in the format described below:

```bash
./iroha_client_cli asset mint --account=practice@popular --asset=LAY#popular --BigQuantity=340282366920938463463374607431768211456
```

### Requirements:
**Modification of iroha_client_cli**: Extend the iroha_client_cli tool to accept the `--BigQuantity`, `--Fixed`, and `--Store` parameters when executing the `asset mint` command.

**Comment by pesterev** [comment]
I would suggest suffixes to parse `BigQuantity` and `Fixed`:
- `100q` - Quantity

- `100Q` - BigQuantity

- `100f` - Fixed Quantity

**Comment by Erigara** [comment]
Not relevant anymore with introduction of `Numeric`
