### ISSUE TITLE
Make it possible for iroha_crypto to target wasm for JS SDK

### ISSUE THREAD

**Issue by DCNick3** [hyperledger/iroha#4046]
Currently JS SDK has to reimplement parts of `iroha_crypto`: https://github.com/hyperledger/iroha-javascript/tree/iroha2/packages/crypto/crypto-rs. It would be nice to remove the duplication and have the same codebase used for crypto operations between the node and js sdk.

After the PR for #3422 lands, it does make sense to try and make sure it compiles under wasm for js, so that JS SDK can use this code directly, without having to duplicate it.

**Comment by Arjentix** [comment]
In #4181 wasm support was implemented. @0x009922 can you check if it works for JS SDK now?

**Comment by 0x009922** [comment]
I have created https://github.com/hyperledger/iroha-javascript/issues/186 to track it.
