### ISSUE TITLE
[discussion] Revise configuration endpoints according to the RFC

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4063]
## Description

According to the Configuration Overhaul RFC (https://github.com/hyperledger/iroha/issues/2585), the current configuration endpoints should be revised.

### Current Design

> Iroha's API currently provides two endpoints related to configuration:
> 
> - `POST /configuration`: Allows runtime updating of the configuration. As of now, it only supports modifying the log level using a request body structured as `{"LogLevel":"<level>"}`.
> - `GET /configuration`: Serves a dual purpose; it can either return the entire configuration in a JSON format or provide documentation for a specific field.

_From the [Configuration Endpoints](https://github.com/hyperledger/iroha-rfcs/blob/main/text/001-config-overhaul.md#configuration-endpoints) section of the RFC_

### Detailed Proposal

For the reasoning please refer to the [Proposal 9](https://github.com/hyperledger/iroha-rfcs/blob/main/text/001-config-overhaul.md#proposal-9---revise-configuration-endpoints) of the RFC.

- Remove documentation fetching via API
- Use the same naming conventions as used in the config file (or ENV)
- Use `GET`/`POST` `/configuration` for fetching and updating the subset of configuration parameters. The subset and format should be the same between the two endpoints for the sake of uniformity. 
- While updating the configuration accepts _partial_ structure (i.e. user might specify only those fields they need to update), retrieval always returns the whole subset. __Note:__ this is not relevant now because we only have a single dynamic parameter.

The only dynamic parameter as of now is `logger.level` (according to the updated naming of parameters). Therefore, the following JSON request might be used to update the value with `POST /configuration`:

```json
{
  "logger": {
    "level": "DEBUG"
  }
}
```

The same will be returned by `GET /configuration`.

### Caveats

In [that place](https://hyperledger.github.io/iroha-2-docs/guide/configure/peer-management.html#_2-set-up-a-peer) of the docs it is recommended to get peers' configuration in the network through the configuration endpoint. It suggests me that probably retrieval of the configuration might include more fields than only dynamic ones.

### Also

There is an issue:

- https://github.com/hyperledger/iroha/issues/3107

, which suggests using sub-routing in a way it is used in `GET /status` endpoint. In general, I don't see a conflict here and it might be adopted for the new configuration endpoints:

<details>

<summary>Samples</summary>

Getting whole configuration:

```http
GET /configuration
```

```json
{
  "logger": {
    "level": "DEBUG"
  }
}
```

Getting a `logger` part:

```http
GET /configuration/logger
```

```json
{
  "level": "DEBUG"
}
```

Getting `logger.level` precisely:

```http
GET /configuration/logger/level
```

```json
"DEBUG"
```

Updating `logger` parameters:

```http
POST /configuration/logger
```

```json
{
  "level": "DEBUG"
}
```

</details>

**Comment by Erigara** [comment]
> In [that place](https://hyperledger.github.io/iroha-2-docs/guide/configure/peer-management.html#_2-set-up-a-peer) of the docs it is recommended to get peers' configuration in the network through the configuration endpoint. It suggests me that probably retrieval of the configuration might include more fields than only dynamic ones.

Consensus critical parameters are now configured on-chain, so i'm not sure this section is still relevant.

**Comment by Erigara** [comment]
Other than that i have no objections.

**Comment by Mingela** [comment]
Fine to me as well

**Comment by Arjentix** [comment]
Looks fine to me too
