### ISSUE TITLE
Provide a way to query expression values from inside the instruction

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4074]
At the moment client cannot determine what was the result of a `Transaction` just by looking at the block. 

Let me illustrate with an example:
```rs
for block in client
    .listen_for_blocks(NonZeroU64::new(1).unwrap())
    .unwrap()
{
    let transactions = block.unwrap().payload().transactions;

    for tx in transactions {
        for executable in tx.payload().instructions() {
            match executable {
                Executable::Instructions(instructions) => {
                    for isi in instructions {
                        match isi {
                            InstructionExpr::Mint(mint) => {
                                let amount: &EvaluatesTo<Value> = mint.object();
                                // At this point we cannot determine what minted amount was 
                                // without evaluating the expression, 
                                // but expression can only be evaluated on the node
                            }
                            _ => {}
                        }
                    }
                }
                Executable::Wasm(_) => {}
            }
        }
    }
}
```

As is noted, client has no way of knowing what amount was minted without evaluating the expression. Especially, if the expression contained a query. This expression cannot even be evaluated on the host because the `wsv` that was actual at the time of executing the query in the expression doesn't exist anymore. 

All of the above indicates that we should store both the original transaction (as we do now) and evaluated transaction so that client can determine what happened in the transaction

**Comment by 6r1d** [comment]
> All of the above indicates that we should store both the original transaction (as we do now) and evaluated transaction so that client can determine what happened in the transaction

Agreed. I have a question, though: what is the best way to represent an evaluated transaction and should it contain a copy of the original data?

**Comment by mversic** [comment]
> Agreed. I have a question, though: what is the best way to represent an evaluated transaction and should it contain a copy of the original data?

my suggestion here is that alongside expression we should also store it's result. Because computing the result (i.e. evaluating the expression) at a later time is too expensive

**Comment by Mingela** [comment]
The evaluated transaction mode is likely the only one really interesting for a block stream subscriber. Is this applicable to both ISI and trigger executions?

**Comment by Erigara** [comment]
What is exact use case for this feature? because storing evaluated transaction would increase increase memory consumption (up to 2 times). 
And we already have event streams which kinda give us evaluated data.
Also even with evaluated transaction we can't restore full picture without whole state, like with evaluated transfer we would only know amount which was transferred, not absolute values (maybe this is enough, maybe not).

**Comment by Erigara** [comment]
Also we need to think about how block stream subscriber could verify that evaluated block is valid. With original one subscriber could check signatures at least.

**Comment by Erigara** [comment]
One more thing is how to deal with wasm? Should we provide trace of every executed instruction as evaluated wasm?
