### ISSUE TITLE
[refactor]: Move metrics into separate service

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4075]
it would be nice if we could remove `sumeragi` from `torii`. I see that it is only used with `sumeragi.metrics` and `sumeragi.update_metrics`. Maybe we can make a ticket for this to make metrics a separate service

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/4061#discussion_r1401915422_
            
It would be convenient to decouple `torii` and `sumeragii`. And after wsv update (#4061) the last thing that requires `torii` to depend on `sumeragi` is metrics which should be moved into separate service.

**Comment by mversic** [comment]
related to #3467
