### ISSUE TITLE
[suggestion] We need a profiler for iroha

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#4083]
### Feature request

I have created the startup benchmark which is good at consistently measuring iroha2 wsv performance. And it is setup to allow for easy profiling by an external tool. But sofar I have had issues when I tried to use valgrind, so some other tool will have to be used instead.

### Motivation

The profiler would allow us to better understand what parts of the code can be optimized.

**Comment by Erigara** [comment]
On linux i used heaptrack to measure memory consumption, allocations and so on. It worked quite good.

On macos and linux [samply](https://github.com/mstange/samply) could be used for performance profiling.
