### ISSUE TITLE
[suggestion] `NumericValue` serialization inconsistency

### ISSUE THREAD

**Issue by arndey** [hyperledger/iroha#4084]
### Feature request

It seems illogical to me that NumericValue should be serialized differently in different genesis instructions
```
{
  "SetKeyValue" : {
    "AssetId" : "foo#wonderland#alice@wonderland",
    "key" : {
      "Name" : "key2"
    },
    "value" : "100"
  }
}
```
```
{
  "Mint" : {
    "object" : "100_u32",
    "destination_id" : {
      "AssetId" : "xor#wonderland#bob@wonderland"
    }
  }
}
```

### Motivation

In Mint instructions it looks fine to me

### Who can help?

@mversic

**Comment by mversic** [comment]
"100_u32" is parsed as `NumericValue` and `"100"` is parsed as a string

**Comment by Erigara** [comment]
@mversic my plan is to make suffix `_{u32,u128,fx}` mandatory, currently it can be omitted for `Fixed` values.

**Comment by Mingela** [comment]
In case of `SetKeyValue`, how is `"100"` treated? `Fixed``Numeric` or `String`? 🤔

**Comment by Erigara** [comment]
> In case of `SetKeyValue`, how is `"100"` treated? `Fixed` `Numeric` or `String`? 🤔

It would be treated as `String` due to deserialization priority currently defined in our code.

**Comment by Erigara** [comment]
So imo parsing `100` as `Fixed` is ambiguous and suffix `_fx` should be used.

**Comment by Mingela** [comment]
> > In case of `SetKeyValue`, how is `"100"` treated? `Fixed` `Numeric` or `String`? 🤔
> 
> ~My guess is that it would be treated as `String` due to deserialization priority currently defined in our code.~
> 
> UPD: it will be treated as `Fixed`, because to parse it as `String` `{"String": "100"}` should be used.

I believe we should stick to the single approach, i.e. either use `{"<Type>": <value>}` for any type or have an exhaustive list of suffice options enabling `"<value_with_no_suffix>"` be treated as `String` without need of the nested structure.

**Comment by Erigara** [comment]
Afaik initial motivation was to be have less verbose representation

**Comment by Erigara** [comment]
> have an exhaustive list of suffice options enabling

You mean documented somewhere?

**Comment by Mingela** [comment]
@Erigara should this be closed?

**Comment by mversic** [comment]
It's in the "Verify" column on ZenHub. QA will close it once verified
