### ISSUE TITLE
[suggestion] Expand `PipelineStatus` with `SignatureAppended` value

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#4086]
### Feature request

When dealing with multi-signature transactions the traditional event subscription usage becomes confusing. When sending a multi-signature transaction waiting synchronously for its status to become `Committed` or `Rejected` does not make much sense due to potentially long wait for other signatures to appear. Though it'd be still relatively useful if there were another value indicating successful arrival of the transaction at the peer. Having that a client could drop the subscription without need of other workarounds to be applied to ensure everything is okay.

### Motivation

Low usability of existing transaction status stream for multi-signature transactions.

Examples of proposed streams:
* for multisignature transaction (2 keys)
```
SignatureAdded -> SignatureAdded -> Validating -> Committed
```
* for ordinary tx (1 key)
```
SignatureAdded -> Validating -> Committed
```

**Comment by mversic** [comment]
not relevant anymore
