### ISSUE TITLE
Return pending transactions in batches

### ISSUE THREAD

**Issue by arndey** [hyperledger/iroha#4091]
### Feature request

Return `BatchedResponse<Vec<SignedTransaction>>` instead of `Vec<SignedTransaction>`

### Motivation

It's hard to decode on our side without BatchedResponse

### Who can help?

@mversic

**Comment by mversic** [comment]
duplicate of #4072

**Comment by VAmuzing** [comment]
Closing the issue in favour of the new one #4183
