### ISSUE TITLE
 Implement a Command for Burning Keys in iroha_client_cli

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4093]
### Objective:
Develop and integrate a new command into the iroha_client_cli tool for burning (permanently deleting) public keys from an account in the Iroha blockchain network.

### Requirements:
The command should follow the existing syntax pattern of `iroha_client_cli`. It could be formatted as `key burn --account=[account_id] --key=[public_key]`, where `[account_id]` and `[public_key]` are placeholders for the user's account ID and the public key to be burned, respectively.

**Comment by SumitkumarSatpute** [comment]
Hi @AlexStroke  I would like to pick up this issue.

**Comment by AlexStroke** [comment]
> Hi @AlexStroke I would like to pick up this issue.
Hi @SumitkumarSatpute I don't have any objections.

**Comment by nxsaken** [comment]
Made obsolete by #2085
