### ISSUE TITLE
[BUG]  Websocket and Basic Auth Proxy on s1.tst.iroha2.iroha.tech

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4099]
### OS and Environment

- MacOS, Docker (Windows as well)
- Proxy Server: Basic Auth Enabled
- TORII_API_URL: http://s1.tst.iroha2.iroha.tech/
- Client: iroha_client_cli
- Network: Proxy enabled environment

### GIT commit hash

794fe35

### Minimum working example / Steps to reproduce

1. Configure the iroha_client_cli to use the TORII_API_URL http://s1.tst.iroha2.iroha.tech/ (with Basic Auth enabled on the proxy server)
2. Execute the command: ./iroha_client_cli events pipeline

### Actual result
Error: 
   0: Failed to listen for events.
   1: HTTP error: 400 Bad Request
![telegram-cloud-photo-size-2-5422658007092809261-y](https://github.com/hyperledger/iroha/assets/111361420/c1068a53-976e-463b-a20a-6f50f5282bc9)

### Expected result
Successfully events listening

### Who can help to reproduce?

@AlexStroke @Stukalov-A-M

**Comment by mversic** [comment]
@AlexStroke  I suspect that transaction gets applied but client fails to get a confirmation. Can you check that?

**Comment by mversic** [comment]
if you confirm, this is the same issue that @BAStos525 and @Artemkaaas encounter with websockets and proxy server. The problem is that when listening to an event that transaction was applied we use websocket protocol

**Comment by AlexStroke** [comment]
> @AlexStroke I suspect that transaction gets applied but client fails to get a confirmation. Can you check that?

@mversic I checked by query `domain list all` I can see that the transaction has not been applied.

**Comment by mversic** [comment]
if you confirm, this is the same issue that @BAStos525 and Artem encountered with websockets and proxy server. The problem is that when listening to an event that transaction was applied we use websocket protocol

**Comment by mversic** [comment]
> > @AlexStroke I suspect that transaction gets applied but client fails to get a confirmation. Can you check that?
> 
> @mversic I checked by query `domain list all` I can see that the transaction has not been applied.

can we see what the logs say, was transaction received and processed?

**Comment by Stukalov-A-M** [comment]
> > The tx wasn't received and processed. When we testet cli transaction flow the tx wasn't sent, because, i suppouse, the iroha_cli commands firs initiates ws listener and then send transactions. And if listener falls with an error, the command returns the error without transaction sending. Also i have a problem with all ws listeners on the Rust clients, they all fall with HTTP 400. But standart HTTP methods like: submit() work successfully, so i can submit any tx via Rust client.
> 
> yes, exactly this. The problem is websocket

In addition, i built my own Rust ws client using another libs and it works correctly. So, seems the problem not with websocket in general, but with client ws libs in particular

**Comment by mversic** [comment]
> > > The tx wasn't received and processed. When we testet cli transaction flow the tx wasn't sent, because, i suppouse, the iroha_cli commands firs initiates ws listener and then send transactions. And if listener falls with an error, the command returns the error without transaction sending. Also i have a problem with all ws listeners on the Rust clients, they all fall with HTTP 400. But standart HTTP methods like: submit() work successfully, so i can submit any tx via Rust client.
> > 
> > 
> > yes, exactly this. The problem is websocket
> 
> In addition, i built my own Rust ws client using another libs and it works correctly. So, seems the problem not with websocket in general, but with client ws libs in particular

can you be more specific about what you did?

**Comment by mversic** [comment]
@DCNick3 this might be related to #4047 ?

**Comment by mversic** [comment]
@AlexStroke which version of Iroha is running on the node?

**Comment by mversic** [comment]
>  If you don't mind i can commit a fix on the next week after finishing final checks

sounds good, assign yourself to the ticket

**Comment by Stukalov-A-M** [comment]
> > > > The tx wasn't received and processed. When we testet cli transaction flow the tx wasn't sent, because, i suppouse, the iroha_cli commands firs initiates ws listener and then send transactions. And if listener falls with an error, the command returns the error without transaction sending. Also i have a problem with all ws listeners on the Rust clients, they all fall with HTTP 400. But standart HTTP methods like: submit() work successfully, so i can submit any tx via Rust client.
> > > 
> > > 
> > > yes, exactly this. The problem is websocket
> > 
> > 
> > In addition, i built my own Rust ws client using another libs and it works correctly. So, seems the problem not with websocket in general, but with client ws libs in particular
> 
> can you be more specific about what you did?

I just built a simple ws client using the websocket library. It was rough, but it helped me to restrict the source of bug searching area.
```
use std::error::Error;
use iroha_data_model::block::stream::{BlockMessage, BlockSubscriptionRequest};
use parity_scale_codec::{DecodeAll, Encode};
use websocket::{ClientBuilder, Message, OwnedMessage};
use tokio_util::compat::{TokioAsyncReadCompatExt};
use websocket::header::{ Headers};
use websocket::native_tls::TlsConnector;
use websocket::ws::dataframe::DataFrame;
use crate::utils::non_zero_handler::non_zero_handler;


pub fn socket_init() -> Result<(), Box<dyn Error>> {
    let buf = b"Connection: Upgrade\n\
    Upgrade: websocket\n\
    Sec-WebSocket-Version: 13\n\
    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\n\
    Authorization: Basic VlFhUDJyUVNrbVhxT0Y5Z2RyTGdrdEJvWmI6TGVpV2xqTHpVczR2eFhwNXJQY3JQbTN3RE8=\n";
    let mut headers = [httparse::EMPTY_HEADER; 5];
    httparse::parse_headers(buf, &mut headers[..]).expect("");

    let headers = Headers::from_raw(&headers).unwrap();
    let mut client = ClientBuilder::new("https://s1.tst.iroha2.iroha.tech/block/stream")
        .unwrap()
        .custom_headers(&headers)
        .connect(TlsConnector::new().ok())
        .unwrap();
    let msg = Message::binary(BlockSubscriptionRequest::new(non_zero_handler(1)).encode()) ;

    let request = client.send_message(&msg).unwrap();
    let mut response = OwnedMessage::from(client.recv_message().unwrap()).take_payload();
    let rsp_msg = BlockMessage::decode_all(&mut response.as_slice()).unwrap();

    println!("{:?}", rsp_msg);

    Ok(())
}
```

**Comment by AlexStroke** [comment]
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNncrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5064f3e0ddd822e115cc4dfbd13acd547f103d4/telegram-cloud-photo-size-2-5443058182625807619-y.jpg" alt="telegram-cloud-photo-size-2-5443058182625807619-y.jpg" />

**Comment by mversic** [comment]
@AlexStroke the image cannot be opened

**Comment by AlexStroke** [comment]
![telegram-cloud-photo-size-2-5443058182625807619-y](https://github.com/hyperledger/iroha/assets/111361420/1aae4826-5494-4b84-90be-70084ea15041)
