### ISSUE TITLE
Implement Feature for Adding New Signatories via Client CLI

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4110]
### Objective:
We need to extend the functionality of our iroha_client_cli to allow users to add new signatories to existing accounts.

### Requirements:
   - Suggested command format:
     ```
     ./iroha_client_cli account add-signatory \
         --account_id="<account_id>" \
         --public_key="<new_public_key>"
     ```
   - Where `account_id` is the ID of the account to which the signatory is being added, and `public_key` is the public key of the new signatory.

**Comment by s8sato** [comment]
- blocked by #4373

may become obsolete after #4373 as signatories are planned to be immutable so far
