### ISSUE TITLE
[suggestion] Make query pagination usable in case of proxy/balancer

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#4119]
### Feature request

Enterprise customers may hide Iroha peers behind a load balancer (proxy). Currently this makes the pagination hardly usable since an original query gets continued on other peer (which does not have the query result state in its cache) making such a request unsatisfiable.

This could be considered from either core or Iroha infrastructure perspective. In the latter case, an exhaustive proxy configuration guide would be expected (on how to introduce kind of sticky sessions for that on a proxy side).

### Motivation

Query pagination usability in case of proxy/balancer

**Comment by mversic** [comment]
one possibility is to configure nginx to map the same client ip to the same node

**Comment by baotn166** [comment]
- There are many problems with sticky session to persist connection to the node like worker node restart, the iroha container restart itself, autoscaling, rollout application changes, etc. Users will be impacted in all of these cases. 
- Can we consider to use external cache, or the database for the session state. If the session state is a file, so we can use shared file system like EFS, NFS.
what do you think about it ? @mversic

**Comment by Mingela** [comment]
Closing in favor of https://github.com/hyperledger/iroha-2-docs/issues/454
