### ISSUE TITLE
Sumeragi class cannot use ThreadPool class from external directory.

### ISSUE THREAD

**Issue by rchatsiri** [hyperledger/iroha#412]
Hello all,  
I build Iroha core source by using  CMakeLists.txt file to create Iroha application. Make command line show an error by using ThreadPool class because it's cannot found ``` #include<thread_pool.hpp>  ```.  I found ThreadPool class is file from external library using name ```iroha/external/src/warchant_thread_pool```.  That's error from ```iroha/core/consensus/sumeragi.cpp``` file.  After found root cause from sumeragi.cpp, 
I add include directory support ```ThreadPool ``` class  to CMakeLists.txt on ```/iroha/core/consensus/```.

```include_libraries(../warchant_thread_pool/include/thread_pool/)```

Iroha source code compiled again by use ```make verbose=1``` command line. Core source code return an error as 

```
/roha/core/consensus/sumeragi.cpp:68:5: error: no matching function for call to ‘tp::ThreadPoolOptions::ThreadPoolOptions(<brace-enclosed initializer list>)’
     });
```
I not sure what problem from ```/iroha/external/src/warchant_thread_pool``` is not updated version.

**Comment by takemiyamakoto** [comment]
This is being refactored for v0.95. This should be somewhat usable next week in the develop branch.

**Comment by rchatsiri** [comment]
I waiting the new source codes upload to upstream.

**Comment by neewy** [comment]
Please, check new code base in develop branch. Thank you for your interest to the project!
