### ISSUE TITLE
[BUG]: Prevent cross chain replay attacks

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4126]
If two iroha networks had the same user (with the same pub key).

Then transaction on one network could be reused on the another network without user intention. 

Proposed solution is to use unique network identificator (configuration parameter) which would be included in the transaction. 

Workaround is avoid situation when user have the same pub key across network.

**Comment by Erigara** [comment]
@Mingela

>  I just don't get the concern/motivation. 

User (A) could just use transaction on one network (1) to transfer another user (B) assets on another network (2) without user (B) intention. Consider that you made payment to someone in (1), not recipient of payment can repeat this payment on (2) without your agreement.

> It's just the same recommendation as to use different passwords (key pairs in this case) for different websites.

I think situation is different with key pairs because with websites ways to authentication usually not visible to everyone and in case with transaction way to authenticate is signature (proof of ownership of private key) and transaction are visible to everyone. 

And also reusing public key is common case for wallets e.g. in Metamask i could switch Etherium Mainnet, BNB Smart Chain and so on preserving my original public key (i believe the same is true polkadot extension).

>  Is there a specific way different EVM-compatible networks handle that, do they allow the same transaction (given the nonce is the same etc) to be potentially applicable?

Etherium has mechanism for dealing with this [Simple replay attack protection](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

**Comment by Erigara** [comment]
> what should this ID look like? UUID? 

yes, or it could be just some number, most importantly we should provide clear guidance that operator of chain should pick unique id.

**Comment by Mingela** [comment]
@Erigara now I see what you mean, thanks. The threat is to send transactions of other users primarily originated in other chains.

How would we guarantee the id used is unique though?

**Comment by Arjentix** [comment]
We have `nonce` and `creation_time`. What is the possibility of having the same values as valid in another chain?

Although as I checked, we don't validate `creation_time` anyhow

**Comment by Erigara** [comment]
> We have nonce and creation_time. What is the possibility of having the same values as valid in another chain?

I'm talking about intentionally taking transaction from one network and send it to another, so `nonce` and `creation_time` won't give us any protection.
