### ISSUE TITLE
[discussion] Consider adopting `_macro` naming convention for crates

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4154]
should we do this consistently across codebase? I thought the practice was to name proc-macro crates `derive`. Whether or not they had `derive` macros, `attribute` macros or `function-like` macros

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/4139#discussion_r1427552415_

**Comment by DCNick3** [comment]
In my experience, `_derive` seems to be the more popular scheme
