### ISSUE TITLE
[suggestion] Stop encoding X25519 keys as Ed25519

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#4174]
While looks like it works fine I suggest refactoring that part to make it more clear.

Currently two completely different types are casted between each other in completely implicit and silent way. I suggest to make it clear that X25519 is used only for exchanging purposes.

**Comment by mversic** [comment]
also consider [this](https://github.com/hyperledger/iroha/pull/4181#discussion_r1440276612) comment when handling this issue
