### ISSUE TITLE
Split tokens into a separate crate 

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4214]
We should explore ways how to move `smart_contract/default/tokens.rs` into a separate crate that can be imported by both `iroha_executor` and `iroha_client`. The **big problem** to consider here is how to have that crate swappable because we want, not just default tokens,  but also user defined tokens to be provided by this crate.

The solution we find for tokens will be a foundation for creating `executor_data_model` crate which will contain all structures that are shared by `iroha_executor` and `iroha_client` such as custom expression system.

I somehow don't feel this is possible to do. I think that every executor will define it's own `executor_data_model` crate which will then be imported by the client. When a user creates their own `executor`, they will also make their own `executor_data_model` which can (but doesn't have to) re-export `iroha_default_executor_data_model`

**Comment by mversic** [comment]
so in essence we can define `iroha_default_executor_data_model` but users of iroha will have to define their own data model crates

**Comment by 0x009922** [comment]
I have a concern about swappable data model in general. Currently, probably the main reason to use an SDK is to safely build data model types. If data model is not static, then Iroha users (other devs) will have to build their own SDKs, which seems like a huge overhead.

Not entirely sure if my concern is 100% related to this issue.

**Comment by mversic** [comment]
> Not entirely sure if my concern is 100% related to this issue.

Yes, your concern is related and valid

**Comment by Arjentix** [comment]
Regarding SDK problem I think we should provide support for default types as we do now. But if users will decide that they need some kind of expressions or anything else they should be able to combine our SDK and their own data model

**Comment by mversic** [comment]
closed as part of #4791
