### ISSUE TITLE
[suggestion] Add a constructor for all default structs of executor

### ISSUE THREAD

**Issue by Stukalov-A-M** [hyperledger/iroha#4215]
### Feature request

Currently we build default permission token structs like this:
```
    let token = PermissionToken::new(
        "CanUnregisterDomain".parse().unwrap(),
        &json!({ "domain_id": kingdom_id }),
    );
```
I propose do it by using a constructor.
```
let mint_rose_permission: PermissionToken =
     CanMintUserAssetDefinitions::new(rose_definition_id).unwrap();
```

### Motivation

I assume that users won't be convenient using the current solution because:
* They must know token id of all tokens before they can use it, otherwise if they define the token id incorrect, they will get a rejected tx.
* To know all token id's, the users should write and execute a query that returns all existed token id's, hence:
       
   * Their code base will be expanded
   * Performance will be decreased
* Moreover, not all users want to create custom tokens. In projects like CBDC there is no business need to do it and the default tokens existence is enough.

**Comment by mversic** [comment]
this was done
