### ISSUE TITLE
[suggestion] Remove JSON encoding for API Version and Health requests, use plain text

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4218]
## Description

When you `GET /api_version`, you get a JSON:

```json
"1"
```

I think it is redundant to use JSON here and plain text would be just fine:

```
1
```

Same applies for `GET /health`:

```json
"Healthy"
```

There is no any reason to use JSON here over plain text.

### Benefits

Simplify API a little bit, remove redundancy.

### Research

A simple patch of this sections would suffice:

https://github.com/hyperledger/iroha/blob/565271dd043b6371c1fc2e4edce0754a3058c1bb/torii/src/routing.rs#L308-L317

https://github.com/hyperledger/iroha/blob/565271dd043b6371c1fc2e4edce0754a3058c1bb/torii/src/routing.rs#L139-L141

**Comment by gerceboss** [comment]
I'm new to iroha and would like  to contribute to learn more about it. Can you please assign me this issue ?

**Comment by mversic** [comment]
@gerceboss  you are assigned

**Comment by gerceboss** [comment]
@mversic  I have added the pull request featuring iroha2-dev branch .
Do I also have to generate requests for [maintainers_dev_Jan_2024](https://github.com/hyperledger/iroha/compare/maintainers_dev_Jan_2024) and [ci/docker_image_validator](https://github.com/hyperledger/iroha/compare/ci/docker_image_validator) ?
