### ISSUE TITLE
[suggestion] Consider Semantic PRs

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#4222]
### Feature request

The semantic PR action can help with asking outside contributors to conform to a specific set of requirements. 

### Motivation

the workflow in question is 

https://github.com/Ezard/semantic-prs

### Who can help?

@mversic @BAStos525

**Comment by mversic** [comment]
duplicate of #4502

**Comment by nxsaken** [comment]
Superseded by #4502.
