### ISSUE TITLE
Support encoding/decoding to/from JSON in `parity_scale_decoder`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4227]
1. rename `parity_scale_decoder` to `parity_scale_codec` or something similar
2. add support to encode/decode SCALE to/from JSON

atm, we're supporting only decoding to Rust debug format. I think we should just replace that with JSON, but we can also support different formats with some flag

**Comment by mversic** [comment]
also this small cli app should take input from `stdin` and return output to `stdout`. This is what we need atm

**Comment by dima74** [comment]
> also this small cli app should take input from `stdin` and return output to `stdout`. This is what we need atm

@mversic when converting from JSON to SCALE, should it print binary data (SCALE) to `stdout`?

**Comment by mversic** [comment]
> > also this small cli app should take input from `stdin` and return output to `stdout`. This is what we need atm
> 
> @mversic when converting from JSON to SCALE, should it print binary data (SCALE) to `stdout`?

yes, but support optional `-o` to print to a file
