### ISSUE TITLE
Iroha 2 README shows Yac as a main consensus algorithm

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#4234]
It seems I1 README is being displayed. I intend to add a small link to iroha.tech and ignore a [whitepaper](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/iroha_2_whitepaper.md#28-consensus) as it may be revised.

**Comment by nxsaken** [comment]
Closed by #4235. (I1 README is no longer displayed anyway.)
