### ISSUE TITLE
[BUG]: Remove permission tokens from role on unregistration

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4242]
Continuation of #3962. 

I've just noticed that as well as removing token from account we should also remove tokens from roles.

Problem is that roles aren't mutable right now.

**Comment by mversic** [comment]
1. we can unregister and register a role
2. we can make an internal update role isi

**Comment by Erigara** [comment]
> 1. we can unregister and register a role

currently role is removed on unregistration from every account so we have to do a lot of bookkeeping to do that

> 2. we can make an internal update role isi

and only allow execution from executor? maybe consider updating roles?
