### ISSUE TITLE
[suggestion] Make Permissions an entity that references accounts

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4243]
I'm suggesting here to swap the relation. We shouldn't have accounts hold permissions/roles, rather permissions/roles should hold accounts

**Comment by Erigara** [comment]
What is your motivation for doing that? 
We should analyze most frequent access patters for permission tokens.

In smart-contracts we use permission tokens in 2 ways:
1. To check permission token in account (we get all permission for account and check for certain permission)
2. Remove permission token from all accounts

For the only permission-related query we have right now `FindPermissionTokensByAccountId` current layout is convinient.

For the 2nd case having layout proposed by you is beneficial, but i'm not sure how frequent removal of token is.
