### ISSUE TITLE
REST API is no longer an option in 6 countries

### ISSUE THREAD

**Issue by developersteve** [hyperledger/iroha#425]
Due to a recent approval of a patent (in 6 countries) outlining rest API via a server, for same day settlement on payment between users, A rest API is no longer a valid option (not without challenged legal action).

see https://www.google.com/patents/WO2016099492A1

Connecting directly with the mobile methods is now the only option for direct connection then using the server as a validation point. 

This probably needs to be removed from the wiki as a possible option or at least a note made about it.

**Comment by takemiyamakoto** [comment]
IP concerns should be forwarded to legal@hyperledger.org
