### ISSUE TITLE
Remove predictable ordering hack from sumeragi

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4264]
This was introduced in #4263 to prevent consensus from operating if there is a bug in the implementation. We should make sure that consensus operation is well covered with tests and remove this backdoor

**Comment by Erigara** [comment]
Going to be removed in #4518

**Comment by AlexStroke** [comment]
I see in the code that that hack has been removed and it looks like iroha has been running successfully without it. But I can't understand if the sorting of peers has become unpredictable, which seems to be the main problem why this task was opened.

**Comment by mversic** [comment]
this is ok, we can close it
