### ISSUE TITLE
[suggestion] Update executor config in the genesis block

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4291]
## Description

> TL;DR: drop inline executor support; rename field to `executor_file`.

Genesis block contains `executor` field, which might either represent an inline base64-encoded WASM blob, or a file path to the WASM blob:

https://github.com/hyperledger/iroha/blob/964476722e2a219becaacdb3676ca058ec5748cd/configs/swarm/genesis.json#L185

This is backed by the `ExecutorMode` struct:

https://github.com/hyperledger/iroha/blob/964476722e2a219becaacdb3676ca058ec5748cd/genesis/src/lib.rs#L122-L131

As we discussed in #4239, `executor` field with file path should be renamed to `executor_file` for uniformity.

In addition to that, I propose to remove inline executor mode. It was effectively deprecated a long time ago: there was a warning printed when the inline mode is used (cannot find references for that). The reason is that inlining WASM blob makes the whole genesis file (1) clunky and (2) hardly reproducible due to WASM compilation intricacies.

**Comment by dchidindu5** [comment]
I'd like to know if this repo is still very active
