### ISSUE TITLE
[discussion] Rename `configs/swarm`?

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4293]
After #4239, docker-compose configs (YAML files and related Iroha configs) are placed into the `configs/swarm` directory. @mversic suggested that renaming it to `configs/docker` might be clearer. I would go further and suggest naming it `configs/docker_compose`, because _Docker_ configs (i.e. Dockerfiles) are still in the repo root.

**Comment by mversic** [comment]
related to #4320
