### ISSUE TITLE
where to put `genesis.json` and `executor.wasm`?

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4320]
I am not sure moving this is correct... A lot of other stuff expects to find `executor.wasm` (and `genesis.json`) there. I think this is why some of the consistency and all the integration tests are failing..

_Originally posted by @DCNick3 in https://github.com/hyperledger/iroha/pull/4304#discussion_r1495855633_

**Comment by 0x009922** [comment]
I moved it to the same directory with `docker-compose` files to reduce confusion.

There are indeed tests relying on these files, but I considered this coupling as secondary, while being docker-compose configurations as primary. If it is not the case, then, imo, there should be dedicated config files for docker-compose configurations not related to tests. Mixing both worlds is slippery.

**Comment by mversic** [comment]
> Mixing both worlds is slippery

I very much agree

**Comment by mversic** [comment]
not relevant anymore
