### ISSUE TITLE
Forbid `Unregister<Account>` if's referenced from elsewhere

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4329]
In `iroha_core`, we should prevent `Unregister<Account>` if it's listed in `Domain::owned_by` or `AssetDefinition::owned_by`. Custom defined executor can check for this and choose to transfer the account ownership to some other account before executing `Unregister<Account>`

**Comment by mversic** [comment]
this will not be an issue after #4411 since accounts will be globally unique and it won't be possible to steal ownership

**Comment by s8sato** [comment]
I wonder if this issue can be closed.
I thought this had nothing to do with account uniqueness, but was like implementing `ON DELETE PROTECT` in RDB

**Comment by s8sato** [comment]
> mingler, [2024/04/19 16:23]
> well, I was thinking that since after your changes with AccountId even "non-registered" accounts can be set as owners of domains/asset_definitions
> 
> mingler, [2024/04/19 16:23]
> just as you can send assets to non-registered account, you can also transfer ownership to non-registered accounts
> 
> S. Sato, [2024/04/19 16:29]
> Ok, I think account unregistration also should be reconsidered
> 
> S. Sato, [2024/04/19 16:29]
> I guess your point is that pointing unregistered account would be no longer a problem
> 
> mingler, [2024/04/19 16:31]
> unregistration of an account will now be like cleaning/wiping the account
> 
> mingler, [2024/04/19 16:31]
> it's not that accounts stops existing

This issue can stay closed. Instead, #4426 should properly address unregistration of accounts as well as registration
