### ISSUE TITLE
[documentation] ADOPTERS.md

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#4338]
### Documentation URL(s)

None

### Description

As discussed at Feb, 2, it should be a freeform Markdown file with the details about projects that use Iroha.
Our annual report contains such projects.

### Your suggestions

It should be present both on `main` and `iroha-2-dev` branches

**Comment by mversic** [comment]
I'm not sure we should do this inside our repository. We can place this into documentation repository
