### ISSUE TITLE
Adopting `iroha_crypto` for WASM in `iroha-javascript` - feedback

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4339]
While rewriting Crypto WASM in `iroha-javascript` using original `iroha_crypto` crate from this repo (https://github.com/hyperledger/iroha-javascript/issues/186), I faced a few issues with `iroha_crypto` API. Some of them are critical and block further process.

Here are my findings:

- **(critical)** Missing `Signature::from_raw`. While there are `PublicKey::from_raw` and `PrivateKey::from_raw` methods, there is no such for `Signature`.
    - Why it is needed:
        - to be consistent with other structures
        - to allow reproducing the `Signature` to then verify payloads. For example, in JS signatures might be represented as data-model objects. In order to translate such representation into crypto, `from_raw` is needed
    - If there is some _reason_ why this method "should not be exposed from `Signature`", I would remind that `Signature` could be still reproduced from raw using JSON deserialization. This way is suboptimal.
- **(critical)** `Signature`'s serialized form (i.e. JSON) contains `payload` as an array of bytes. It is inconsistent with `PrivateKey`'s representation, where `payload` is a hex-encoded string. Consider (de-)serializing `payload` in `Signature` as hex too.
- `Multihash` is no longer visible in Public API. However, `PublicKey`'s (de-)serialization and `FromStr`/`Display` are still based on `Multihash` parsing. This behaviour isn't documented. Apart from mentioning it in the docs, it would be nice to have doctests showing parsing from a multihash string
- `Signature::payload` - confusing documentation:
  https://github.com/hyperledger/iroha/blob/fbdd5914cdc3f792c73a15786b3a8447f14ccaee/crypto/src/signature/mod.rs#L61
- `iroha_crypto::error::Error` - should probably be exposed as `iroha_crypto::Error`, or at least as `iroha_crypto::prelude::Error`.
- `KeyPair::new` effectively has semantics of `from_raw` methods from other structs. Consider renaming.

**Comment by mversic** [comment]
> `KeyPair::new` effectively has semantics of from_raw methods from other structs. Consider renaming.

I don't get this point. `new` is perfectly applicable here

Otherwise, I'm fine with everything else

**Comment by 0x009922** [comment]
> > `KeyPair::new` effectively has semantics of from_raw methods from other structs. Consider renaming.
> 
> I don't get this point. `new` is perfectly applicable here

`KeyPair::new` creates a key pair from its components - `PublicKey` and `PrivateKey` - and validates that they are matching.

`PublicKey::from_raw` and `PrivateKey::from_raw` create a key from its components - algorithm and payload - and validate that they are matching.

They seem similar to me.

**Comment by mversic** [comment]
> `KeyPair::new` creates a key pair from its components - `PublicKey` and `PrivateKey` - and validates that they are matching.
> 
> `PublicKey::from_raw` and `PrivateKey::from_raw` create a key from its components - algorithm and payload - and validate that they are matching.

`new` is the usual name for constructors, you can see it all around code base. `from_raw` is the odd one out. We can consider renaming `from_raw` into `new` but I personally wouldn't. The reason being that `from_raw` indicates you are doing something that's frowned upon or sketchy and if you have other means. I would maybe rename it to `from_raw_bytes`

To get around all this conversation, I noticed that `from_raw` can be made private. So please make it private

**Comment by mversic** [comment]
how about we rename `from_raw` into `from_bytes`. This is what I would prefer actually

**Comment by 0x009922** [comment]
Okay, that makes sense. `from_bytes` would work.

As for making these methods private, I'd vote against it. For external use it is still useful to "reproduce" structures from and to raw data for conversion reasons.

**Comment by 0x009922** [comment]
Another issues found:

- you can create `KeyGenConfiguration::from_private_key` and then call `.with_algorithm()`. If the algorithm you set will differ from the private key's, there will be panic during generation.

    This will compile, but panic:
	```rust
	#[test]
	fn key_gen_from_private_key_and_different_algorithm() {
	    let _kp = KeyPair::generate_with_configuration(
	        KeyGenConfiguration::from_private_key(
	            PrivateKey::from_hex(
	                Algorithm::BlsSmall,
	                "8cb95072914cdd8e4cf682fdbe1189cdf4fc54d445e760b3446f896dbdbf5b2b",
	            )
	            .unwrap(),
	        )
	        .with_algorithm(Algorithm::BlsNormal),
	    );
	}
	```
- also, in `from_private_key` there is `Algorithm::default` inside. Therefore, if you try to generate a key pair from a non-ed25519 private key, it will also fail.

Addressing this with type-level guards.

**Comment by 0x009922** [comment]
@mversic, again about `KeyPair::new`: I found that there is a method `KeyPair::into_raw_parts -> (PublicKey, PrivateKey)`, which is the opposite of the `::new` method. So, I find it reasonable to rename to `KeyPair::from_raw_parts`.

**Comment by mversic** [comment]
Don't change `KeyPair::new`. Change or remove `into_raw_parts`. That's the odd one out

**Comment by mversic** [comment]
Don't change `KeyPair::new`. Change or remove `into_raw_parts`. That's the odd one out

You can remove because we also have a From implemented
