### ISSUE TITLE
Include event set bitmap info in schema

### ISSUE THREAD

**Issue by DCNick3** [hyperledger/iroha#4350]
With the implementation of #4240, we now have a family of `*EventSet`, which are encoded with scale codec as bit maps. We should figure out a way to encode bitmap values corresponding to each event in schema for SDKs consumption.

_Originally posted by @Erigara in https://github.com/hyperledger/iroha/pull/4240#discussion_r1516029587_

**Comment by Erigara** [comment]
@Mingela @0x009922 @SamHSmith what in your opinion would be suitable way to represent bitmaps in schema?

**Comment by DCNick3** [comment]
What I see as the most straightforward way to do this is to add a new metadata variant to schema:

```rust
pub struct BitfieldMeta {
  repr: core::any::TypeId,
  masks: Vec<BitfieldMask>,
}

pub struct BitfieldMask {
  name: String,
  mask: u64,
}
```

So in the schema JSON it will be something like this:

```json
{
  "DomainEventSet": {
    "repr": "u32",
    "masks": [
      {
        "name": "AnyAccount",
        "mask": 1,
      },
      {
        "name": "AnyAssetDefinition",
        "mask": 2,
      },
      {
        "name": "Created",
        "mask": 4,
      },
      {
        "name": "Deleted",
        "mask": 8,
      },
      {
        "name": "MetadataInserted",
        "mask": 16,
      },
      {
        "name": "MetadataRemoved",
        "mask": 32,
      },
      {
        "name": "OwnerChanged",
        "mask": 64,
      },
    ]
  }
}
```

Is this reasonable for the SDK implementation?

**Comment by 0x009922** [comment]
Yes, this works for me.
