### ISSUE TITLE
dynamic metadata value

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4353]
I think the values in metadata should be reconsidered. I'd be in favor of loosely typing it with `StringWithJson` and defer the parsing of the structure to executor as we do for permission tokens payload. But this is something I think should be explored in a separate PR

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/4305#discussion_r1515996223_

**Comment by Stukalov-A-M** [comment]
@mversic , @Erigara 
After some exploration I found a few options how to realize it:
1. Add Custom(jsonString) into MetadataValueBox and keep all current functions and realization.
2. Keep `pub struct Metadata(pub(super) BTreeMap<String, JsonString>)` and remove all nested operation methods.
3. Refactor the Metadata in `Metadata(JsonString)`, implement basic CRUD methods and move parsing implementation to the client side;

I like the #3 the most 

P.S.  (Set/Remove)KeyValue will be changed to (Set/Remove)Metadata

**Comment by Erigara** [comment]
I'm for option 2. because imo option 3. might be too coarse for some use cases, it might be costly to update whole metadata in one go.

On other hand nested operations look redundant and can be modeled with specific keys.

**Comment by mversic** [comment]
I like 2 as well. I don't see a point in having nested metadata. And it can always be implemented in a custom executor, no? Is there some old issue talking about the reason behind introducing nested metadata? @s8sato 

I find that 1. might be good option for performance reasons but then again I don't think we will see any noticeable benefit

I don't think 3 is even possible because of Store Assets. And I don't think we should change the concept of metadata into something else but key-value store

**Comment by s8sato** [comment]
I think the nested metadata just aimed a standard datastore. For nested structures I think `JsonString` would be enough, so I stand for 2. or 3.

Before accepting 2. I'd consider the reason for keeping the first keys outside `JsonString` when `JsonString` can represent complete key-value store:

- currently `SetKeyValue` `RemoveKeyValue` instructions and `Find*By*Key` queries rely on `key: Name`
  - a key (and a key-value) could be extended to a path in json
- currently `CanSetKeyValue*` permission allows changing entire metadata of the entity
  - could be more granular with the same structure as metadata that represents accessible paths in the metadata

Are there requirements that metadata should hold in terms of use cases we should support @Mingela ?

- related closed issues as far as I can see: #1144, #1371, #3082
