### ISSUE TITLE
[BUG] /api_version Endpoint Returns Non-Standard JSON Format and Inconsistent Versioning

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4359]
### OS and Environment

MacOS, bare metal

### GIT commit hash

96f84106

### Minimum working example / Steps to reproduce

```bash
curl --location 'http://127.0.0.1:8080/api_version'
```

### Actual result
The response is a plain string, not a JSON object, and the version is formatted as a single digit. 
```json
"1"
```

### Expected result
The response should be a well-structured JSON object following semantic versioning. Example:

```json
{
  "version": "1.0.0"
}
```

### Who can help to reproduce?

@astrokov7

**Comment by 0x009922** [comment]
I don't think it is a bug nor a defect.

First of all, the version that is returned is the current version of WSV:

https://github.com/hyperledger/iroha/blob/96bf9973c24eb7789c5389fc66890fb2f277d563/torii/src/routing.rs#L283-L294

It doesn't follow semantic versioning and is made for future development of Iroha and compatibility in production environment. AFAIK, the version is going to be a plain incremental number.

Secondly, **this is a valid JSON**. Yes, it is not a JSON _object_ - it is a JSON _string_.

Also, I've created a proposal some time ago to simplify this endpoint to just returning a number as plain text:

- https://github.com/hyperledger/iroha/issues/4218

**Comment by AlexStroke** [comment]
> I don't think it is a bug nor a defect.
> 
> First of all, the version that is returned is the current version of WSV:
> 
> https://github.com/hyperledger/iroha/blob/96bf9973c24eb7789c5389fc66890fb2f277d563/torii/src/routing.rs#L283-L294
> 
> It doesn't follow semantic versioning and is made for future development of Iroha and compatibility in production environment. AFAIK, the version is going to be a plain incremental number.
> 
> Secondly, **this is a valid JSON**. Yes, it is not a JSON _object_ - it is a JSON _string_.
> 
> Also, I've created a proposal some time ago to simplify this endpoint to just returning a number as plain text:
> 
> * [[suggestion] Remove JSON encoding for API Version and Health requests, use plain text #4218](https://github.com/hyperledger/iroha/issues/4218)

Agree, I close issue.
