### ISSUE TITLE
[BUG] CPU leak during load testing

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#4380]
### OS and Environment

k8s, linux

### GIT commit hash

2ffcd007e3f794f8ee32488a0446bc11c1242cd0

### Minimum working example / Steps to reproduce

run the job in Jenkins https://jenkins.soramitsu.co.jp/job/iroha2/job/deploy/job/iroha2-perf/
with the following parameters

```rust
testScenario maxPerf
logLevel INFO
configuration standard
concurrentUsers 2
times 7200
deachLevelLasting 10
separatedByRampsLasting 10
startingFrom 0
```
leave other parameters unchanged

iroha2 config recommended

```rust
"COMMIT_TIME_LIMIT_MS": 10000,
    "MAX_TRANSACTIONS_IN_BLOCK": 20,
    "ACTOR_CHANNEL_CAPACITY": 100,
    "GOSSIP_BATCH_SIZE": 500
    "GOSSIP_PERIOD_MS": 1000
  },
  "BLOCK_SYNC": {
    "GOSSIP_PERIOD_MS": 1000,
    "BLOCK_BATCH_SIZE": 4,
    "ACTOR_CHANNEL_CAPACITY": 100
  },
```

analytical info

1. [profiler](https://parca.tachi.soramitsu.co.jp/)
2. [iroha2 current state](https://grafana.soramitsu.co.jp/d/BD5RpSFVk/kubernetes-deployments?orgId=1&var-namespace=iroha2-test&from=now-30m&to=now&refresh=5s)
3. [iroha2 TPS / queue status](https://grafana.soramitsu.co.jp/d/1kmsWQQ4z/iroha2-qa?orgId=1&var-namespace=iroha2-test&from=now-30m&to=now&refresh=5s)
4. [iroha2 cluster monitoring](https://grafana.soramitsu.co.jp/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=default&var-project=tachi&var-namespace=iroha2-test&var-pod=iroha2-3&from=now-30m&to=now&refresh=5s)

### Actual result

- when running the script
- the load should increase evenly
- transactions should be accepted by the computer
- no CPU leaks should occur

### Expected result

When the load is applied, a leak in the CPU is observed, judging by the logs from the profiler, the problem is related to the regular calculation of the hash of blocks and transactions. Analytical information can be found at the link to the profiler

1. [profiler](https://parca.tachi.soramitsu.co.jp/?dashboard_items=icicle&expression_a=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta{}&from_a=1711026894862&to_a=1711027061223&time_selection_a=absolute:1711026894862-1711027061223&merge_from_a=1711027041600&merge_to_a=1711027041766.361&query_a=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta{app=%22iroha2%22,%20app_kubernetes_io_component=%22iroha2-backend%22,%20app_kubernetes_io_instance=%22iroha2%22,%20app_kubernetes_io_name=%22iroha2%22,%20apps_kubernetes_io_pod_index=%221%22,%20controller_revision_hash=%22iroha2-b69f6d9dd%22,%20instance=%2210.1.120.87:8080%22,%20job=%22iroha2-pods%22,%20kubernetes_namespace=%22iroha2-test%22,%20kubernetes_pod_name=%22iroha2-1%22,%20soramitsu_project_app=%22iroha2%22,%20soramitsu_project_name=%22iroha2-longevity%22,%20statefulset_kubernetes_io_pod_name=%22iroha2-1%22,%20version=%220.0.1%22}&profile_name_a=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta&labels_a=app=iroha2,app_kubernetes_io_component=iroha2-backend,app_kubernetes_io_instance=iroha2,app_kubernetes_io_name=iroha2,apps_kubernetes_io_pod_index=1,controller_revision_hash=iroha2-b69f6d9dd,instance=10.1.120.87:8080,job=iroha2-pods,kubernetes_namespace=iroha2-test,kubernetes_pod_name=iroha2-1,soramitsu_project_app=iroha2,soramitsu_project_name=iroha2-longevity,statefulset_kubernetes_io_pod_name=iroha2-1,version=0.0.1&filter_by_function=Hash&search_string=Hash)
2. [iroha2 current state](https://grafana.soramitsu.co.jp/d/BD5RpSFVk/kubernetes-deployments?orgId=1&var-namespace=iroha2-test&from=1711027040572&to=1711027508198)
3. [iroha2 TPS / queue status](https://grafana.soramitsu.co.jp/d/1kmsWQQ4z/iroha2-qa?orgId=1&var-namespace=iroha2-test&from=1711027046152&to=1711027654351)
4. [iroha2 cluster monitoring](https://grafana.soramitsu.co.jp/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=default&var-project=tachi&var-namespace=iroha2-test&var-pod=iroha2-3&from=1711026314623&to=1711029026402)
5. [OpenSearch](https://opensearch.soramitsu.co.jp/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-21T13:17:52.923Z',to:'2024-03-21T13:18:08.019Z'))&_a=(columns:!(kubernetes.pod.name,logdata),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.namespace,negate:!f,params:(query:iroha2-test),type:phrase),query:(match_phrase:(kubernetes.namespace:iroha2-test))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.container.name,negate:!f,params:!(iroha2),type:phrases,value:iroha2),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.container.name:iroha2))))))),index:'155ed930-ca2d-11ed-8130-f19d88adb388',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',asc))))

logs downloaded from the parca
[profile.pb.gz](https://github.com/hyperledger/iroha/files/14720011/profile.pb.gz)

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
 look at the profiler logs
  ```
</details>

### Who can help to reproduce?

@RamilMus

**Comment by mversic** [comment]
verify with rc21

**Comment by timofeevmd** [comment]
the problem persists when assembling Linux-based Alpine, the problem is solved when assembling Image based on Debian
