### ISSUE TITLE
Refactor config usage in integration tests

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4383]
Namely, `impl TestConfig for Config` and `iroha::samples::get_user_config`

https://github.com/hyperledger/iroha/blob/e1e8a1a3bc3410ba14d34e8c9dd089a1a8817016/core/test_network/src/lib.rs#L766

https://github.com/hyperledger/iroha/blob/50b5bc2af3198a39a045e174219161116482ef15/cli/src/samples.rs#L62

The use of configuration in tests is limited and unlikely to require building the user layer of it. As configuration validation logic (e.g. validating that `genesis.file` exists), these parts start to fall.

To be less abstract, I propose to refactor these parts to use the config in a way that is valid in tests and will not rely on what is not designed for tests. For example, it doesn't make sense to specify `genesis.file` in a test config when it will be never read there.

Related:

- #4136

**Comment by mversic** [comment]
@0x009922 is this still valid?

**Comment by 0x009922** [comment]
Yes. In fact, it is also to be going to closed by #5124
