### ISSUE TITLE
Allow multiple peers to submit genesis

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4388]
read discussion in #4225

**Comment by Erigara** [comment]
When implementing this feature care should be taken to insure that every peer produce the same genesis block. 

Currently while still having the same genesis transaction other parts of `BlockPayload` could differ. 
Most likely `commit_topology` and `timestamp_ms` in `BlockHeader`.

**Comment by mversic** [comment]
these are valid concerns, but this ticket is about allowing multiple peers to submit the same genesis block which was produced once by `kagami`

**Comment by mversic** [comment]
I was thinking that `kagami genesis sign` produces a genesis block? and that block which is produced only once can be submitted by any peer whatsoever

**Comment by dima74** [comment]
Implemented in #4775 (#4696)
