### ISSUE TITLE
[BUG] general degradation of the work of Iroha2 

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#4389]
### OS and Environment

linux, k8s

### GIT commit hash

2ffcd007e3f794f8ee32488a0446bc11c1242cd0

### Minimum working example / Steps to reproduce

The test was carried out with different load intensity from 1 to 15 virtual users, the test result was similar - a systematic decrease in tps

testing was carried out in several approaches
I tried to apply loads from 1500 to 125 tps in order to find a TPS indicator with which we can work stably. But the bad news is that the overall degradation pattern of Iroha2 was observed in every test. The presence or absence of a profiler does not affect the degradation of the system

**load model**
1. assemble Iroha2 with the parca profiler, at the request of @BAStos525 @RamioMustafin
the service is available via this link
2. start 4 virtual users, about 360tps and 3rps (if you turn off the profiler the indicator will be higher)

**preconditions:**
[genesis.json](https://github.com/soramitsu/iroha2-perf/blob/master/src/test/resources/genesis.json) contains
5 domains
1200 users
each user has 10,000 assets

**test script**
[jenkins job ](https://jenkins.soramitsu.co.jp/job/iroha2/job/deploy/job/iroha2-perf/)to start load testing

params:
```rust
testScenario=load
simulationClass=jp.co.soramitsu.load.simulation.transaction.StabilitySimulation
logLevel=INFO
configuration=standard
intensity=4
rampDuration=4
stageDuration=3600
```

[jenkins job](https://jenkins.soramitsu.co.jp/job/iroha2/job/deploy/job/iroha2-perf-klaus/) to clean up load generator
 
1. sending an asset from one user to another without waiting for the transaction status

**analytics tools**
[profiler](https://parca.tachi.soramitsu.co.jp/?search_string=&dashboard_items=icicle&filter_by_function=&compare_b=false&expression_a=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%3Adelta%7B%7D&from_a=1711466280000&to_a=1711466700000&time_selection_a=absolute:1711466280000-1711466700000&merge_from_a=1711466280000&merge_to_a=1711466700000) 

[profiler before and after degradation ](https://parca.tachi.soramitsu.co.jp/?search_string=&dashboard_items=icicle&filter_by_function=&compare_b=true&expression_b=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%3Adelta%7B%7D&from_b=1711466470000&to_b=1711466696000&time_selection_b=absolute:1711466470000-1711466696000&merge_from_b=1711466557827&merge_to_b=1711466558053&query_b=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta{app=%22iroha2%22,%20app_kubernetes_io_component=%22iroha2-backend%22,%20app_kubernetes_io_instance=%22iroha2%22,%20app_kubernetes_io_name=%22iroha2%22,%20apps_kubernetes_io_pod_index=%224%22,%20controller_revision_hash=%22iroha2-b69f6d9dd%22,%20instance=%2210.1.74.105:8080%22,%20job=%22iroha2-pods%22,%20kubernetes_namespace=%22iroha2-test%22,%20kubernetes_pod_name=%22iroha2-4%22,%20soramitsu_project_app=%22iroha2%22,%20soramitsu_project_name=%22iroha2-longevity%22,%20statefulset_kubernetes_io_pod_name=%22iroha2-4%22,%20version=%220.0.1%22}&profile_name_b=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta&labels_b=app=iroha2,app_kubernetes_io_component=iroha2-backend,app_kubernetes_io_instance=iroha2,app_kubernetes_io_name=iroha2,apps_kubernetes_io_pod_index=4,controller_revision_hash=iroha2-b69f6d9dd,instance=10.1.74.105%3A8080,job=iroha2-pods,kubernetes_namespace=iroha2-test,kubernetes_pod_name=iroha2-4,soramitsu_project_app=iroha2,soramitsu_project_name=iroha2-longevity,statefulset_kubernetes_io_pod_name=iroha2-4,version=0.0.1&compare_a=true&expression_a=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%3Adelta%7B%7D&from_a=1711466280000&to_a=1711466460000&time_selection_a=absolute:1711466280000-1711466460000&merge_from_a=1711466364842&merge_to_a=1711466365022&query_a=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta{app=%22iroha2%22,%20app_kubernetes_io_component=%22iroha2-backend%22,%20app_kubernetes_io_instance=%22iroha2%22,%20app_kubernetes_io_name=%22iroha2%22,%20apps_kubernetes_io_pod_index=%220%22,%20controller_revision_hash=%22iroha2-b69f6d9dd%22,%20instance=%2210.1.72.167:8080%22,%20job=%22iroha2-pods%22,%20kubernetes_namespace=%22iroha2-test%22,%20kubernetes_pod_name=%22iroha2-0%22,%20soramitsu_project_app=%22iroha2%22,%20soramitsu_project_name=%22iroha2-longevity%22,%20statefulset_kubernetes_io_pod_name=%22iroha2-0%22,%20version=%220.0.1%22}&profile_name_a=process_cpu:cpu:nanoseconds:cpu:nanoseconds:delta&labels_a=app=iroha2,app_kubernetes_io_component=iroha2-backend,app_kubernetes_io_instance=iroha2,app_kubernetes_io_name=iroha2,apps_kubernetes_io_pod_index=0,controller_revision_hash=iroha2-b69f6d9dd,instance=10.1.72.167:8080,job=iroha2-pods,kubernetes_namespace=iroha2-test,kubernetes_pod_name=iroha2-0,soramitsu_project_app=iroha2,soramitsu_project_name=iroha2-longevity,statefulset_kubernetes_io_pod_name=iroha2-0,version=0.0.1)
[iroha2 current state](https://grafana.soramitsu.co.jp/d/BD5RpSFVk/kubernetes-deployments?orgId=1&var-namespace=iroha2-test&from=1711466376636&to=1711466918795)
[iroha2 TPS/queue status](https://grafana.soramitsu.co.jp/d/1kmsWQQ4z/iroha2-qa?orgId=1&var-namespace=iroha2-test&from=1711466351000&to=1711466980000)
[iroha2 cluster monitoring](https://grafana.soramitsu.co.jp/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=default&var-project=tachi&var-namespace=iroha2-test&var-pod=iroha2-0&from=1711466379518&to=1711466966286)
[OpenSearch](https://opensearch.soramitsu.co.jp/app/discover#/context/155ed930-ca2d-11ed-8130-f19d88adb388/i_JZe44BWAwS1kBz4L_S?_g=(filters:!())&_a=(columns:!(kubernetes.pod.name,logdata),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.namespace,negate:!f,params:(query:iroha2-test),type:phrase),query:(match_phrase:(kubernetes.namespace:iroha2-test))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.container.name,negate:!f,params:!(iroha2),type:phrases,value:iroha2),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.container.name:iroha2))))))),predecessorCount:50,sort:!('@timestamp',desc),successorCount:50))

### Actual result

The expected TPS level is at least 350 throughout the scenario
There are no CPU or RAM leaks
Actual state of the world for each peer

### Expected result

TPS reaches the desired value and then begins to decrease to minimum values
Based on the profiler data, I assume that Iroha spends a large amount of time updating the state of the world

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

**Comment by mversic** [comment]
verify with rc21

**Comment by timofeevmd** [comment]
the problem persists when assembling Linux-based Alpine, the problem is solved when assembling Image based on Debian
