### ISSUE TITLE
[BUG]: Trigger is not callable by multiple users (stable)

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4418]
THIS ISSUE ALREADY FIXED ON LATEST `iroha2-dev` branch, however we should consider backport.

On the `iroha2-stable` branch, it's possible to call trigger only by single user.

This happens because `ExecuteTriggerEventFilter` allows accept only single account.

Solution would be to accept either single user or any user (permission to execute should be checked by executor).

**Comment by mversic** [comment]
has this backport been requested by anyone?

**Comment by Erigara** [comment]
yes, it's requested by @Mingela

**Comment by Erigara** [comment]
yes, it was requested by CBDC team (after discussion with @Stukalov-A-M).

**Comment by AlexStroke** [comment]
Scenario to check and automation:
1. Register the domain "kingdom".
2. Register the account "bob@kingdom".
3. Register the trigger "trigger$kingdom" to mint the asset "rose#wonderland".
4. Execute the trigger "trigger$kingdom" by the user "alice@wonderland".
5. Grant the permission token "CanExecuteUserTrigger" to "bob@kingdom".
6. Execute the trigger "trigger$kingdom" by the user "bob@kingdom".
7. Revoke the permission token "CanExecuteUserTrigger" from "bob@kingdom".
8. Attempt to execute the trigger "trigger$kingdom" again by the user "bob@kingdom".
