### ISSUE TITLE
[BUG]: Data model structs data isn't accessible

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4420]
We need to make sure that data model structs' fields are accessible inside client and data model through getters.

Currently it's often omitted due to restrictions of `iroha_ffi`.

**Comment by Erigara** [comment]
One example is `MetadataChanged` event fields.

**Comment by DCNick3** [comment]
AFAIK, the omission of fields in clients is by design. If you need to expose fields to the clients, you are supposed to derive getters

**Comment by Erigara** [comment]
@DCNick3 yeah, i will clarify that i mean lack of `getters` (or actually any other way to access struct data)

**Comment by mversic** [comment]
wherever there is a `TODO` comment saying a getter cannot be derived because of FFI we can make a manual getter implementation get around this issue
