### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4433]
regarding git branching model. I think we should make the following sequence of steps:
1. copy contents of current `main` to a new branch `iroha1-main`
2. copy `iroha2-stable` contents to `main` branch
3. copy contents of current `develop` branch to a new branch `iroha1-develop`
4. copy `iroha2-dev` contents to `develop` branch
5. create `stable` branch and copy contents of `iroha2-stable` into it
6. remove all branches with `iroha2-` prefix

The workflow would then be as follows:
1. we work on `develop` branch and merge all new features into it
2. periodically, we merge `develop` into `main` (this is a followed by a release announcement)
3. periodically (but with a lesser frequency) we merge `main` into `stable`

**Comment by Erigara** [comment]
What should be done with `iroha2-lts` branch?

**Comment by BAStos525** [comment]
Pay attention that i2 CI has several important bindings with branch names (triggers, image tag names...)

**Comment by mversic** [comment]
> What if we make iroha2-dev the main branch, while keeping release and stable in non-default branches? This way, the most recent project activity will be immediately visible, while reducing the likelihood of accidentally contributing directly to the release branch.

yeah, I was thinking about this and I'm leaning to agree with this even though it's not what GitFlow recommends. We don't need `develop` branch. Here is my revised suggestion:

1. copy contents of current `main` to a new branch `iroha1-main`
2. create `stable` branch and copy contents of `iroha2-stable` into it
3. copy `iroha2-dev` contents to `main` branch
6. remove all branches with `iroha2-` prefix
7. remove `develop` branch 

The workflow would then be as follows:
1. we work on `main` branch and merge all new features into it
2. periodically, we tag HEAD of the `main` branch to publish a new release 
3. for a hotfix:
3.1. create a new branch **from the previous tag** 
3.2. commit the hotfix changes on the new branch
3.3. tag the HEAD of the hotfix branch
3.4. merge hotfix branch back it into `main`

**Comment by mversic** [comment]
we don't even need `stable` branch, but let's keep it until we digest these changes. Afterwards, we can consider relying on git tags only

**Comment by mversic** [comment]
done
