### ISSUE TITLE
Release publishing

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4459]
On every tag that starts with `v2*` following docker images should be built:
1. `iroha:*` with alias `iroha:2.0.0-latest`
2. `iroha:*-profiling`

### Example

1. a tag **`v2.0.0-pre-rc-21`** is published then:
2. we build **`iroha:2.0.0-pre-rc-21`** and **`iroha:2.0.0-pre-rc-21-profiling`** docker images
3. we update docker alias **`iroha:2.0.0-latest`** to reference to `iroha:2.0.0-pre-rc-21`

notice that tags will always be prefixed with `v2` or `v1` but docker tags will strip the `v` prefix

### Alternate suggestions

please provide if you have

**Comment by nxsaken** [comment]
Should we have separate tags for the latest release and the latest RC?

**Comment by nxsaken** [comment]
What's the difference going to be between `iroha:v2*` and `iroha2:*`?

**Comment by mversic** [comment]
I think our choice here is put both iroha1 and iroha2 into one `hyperledger/iroha` docker repository and name images:
`iroha:v1.17.4` and `iroha:v2.0.0`
or leave them in separate docker repositories `hyperledger/iroha` and `hyperledger/iroha2` and name images:
`iroha:v1.17.4`, `iroha2:v2.0.0`

or if you have some alternative arrangement

**Comment by mversic** [comment]
@nxsaken IMO we should publish all `iroha2` docker images on `hyperledger/iroha` with proper versioning and get rid of `hyperledger/iroha2` in due time (not eagerly since others might depend on it) or archive it. Can we do this?

**Comment by Mingela** [comment]
I'd support placing both Iroha versions into the same docker repository (at least until Irohas are not split by GH repos) (`iroha:1.17.4` and `iroha:2.0.0` example)

As for RC's, I don't think they in general should overwrite `latest`. How about splitting those in two tracks, e.g.:
* `latest` where just all release versions are written to (e.g. `2.x.x` which is final, not `rc`)
* `snapshot`/`rc` (naming tbd) where any `v2*` tag build assigns to

**Comment by mversic** [comment]
> I'd support placing both Iroha versions into the same docker repository (at least until Irohas are not split by GH repos) (iroha:1.17.4 and iroha:2.0.0 example)

ok, that's out of the way than. This a standard practice

**Comment by nxsaken** [comment]
@mversic is anything needed here other than asking DevOps to configure CI for this?

**Comment by mversic** [comment]
@bogdan yes, I agree it's confusing. What we've been naming pre-RC should have been named `alpha` releases. Either:
1. call the next release `alpha-1`
2. call the next release `pre-rc-21`

I'm not sure if we want to switch the naming scheme now. IMO I would keep `pre-rc` naming and follow up with `rc`. This will be the last `pre-rc` release next release should be `rc`

as for the `latest` I just wanted a tag that will point to the latest `pre-rc`. I'm open to naming suggestions. It's also not necessary to have it but it might make a few things easier

**Comment by nxsaken** [comment]
How will SDK releases be handled?

**Comment by mversic** [comment]
in the same manner
