### ISSUE TITLE
Cleaning schema dir

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#448]
`iroha/schema` looks overflowed, maybe we can clear it out?

**Comment by neewy** [comment]
Hi! Can you tell me what might look overflowed?

**Comment by l4l** [comment]
I mean redundant files (that should be deleted) and files with one statement (that should be merged to other ones)

**Comment by neewy** [comment]
https://github.com/hyperledger/iroha/blob/master/schema/api_service.proto
and 
https://github.com/hyperledger/iroha/blob/master/schema/api.proto
are deleted. Close this issue if this is satisfactory or specify otherwise what correction is needed

**Comment by l4l** [comment]
Good, thanks!
Maybe a good idea will be merge of **{loader,block}.proto**, what do you think?

**Comment by neewy** [comment]
I think they serve different purpose. We can discuss it in chat — redundant files are removed now anyway
