### ISSUE TITLE
Rename `iroha_client_cli` into `iroha`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4512]
It makes much more sense for the end user to just call `iroha` when interacting with cli, wouldn't you agree?

**Comment by nxsaken** [comment]
Related: https://github.com/hyperledger/iroha-2-docs/pull/424#discussion_r1603190595

**Comment by DCNick3** [comment]
The peer executable should be renamed too then. Maybe `irohad`, like some common linux daemons?

**Comment by nxsaken** [comment]
Alternatively, it might be time to consult the Japanese dictionary? We already have Torii, which is one kind of interface. The client, client CLI, and the peer CLI are interfaces too, so we could make them consistent with the rest of the Iroha lore. Might be too much though.

**Comment by mversic** [comment]
> Alternatively, it might be time to consult the Japanese dictionary?

I wouldn't in this case. I think iroha and irohad would be more recognizable as a brand. Otherwise, it would be difficult to figure out how to use it
