### ISSUE TITLE
Release branch

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4540]
when tag `v2*.0` is published, run a CI job that creates a branch named as the tag (without `v` prefix) and changes the CI workflow `iroha2-dev-pr.yml` on that branch to target that branch.

This is so that all the fixes of the release have a base branch with a functional CI

**Comment by BAStos525** [comment]
Why to change `workflow iroha2-dev-pr.yml` trigger only? We have another workflows with tests and "branch name" trigger.

**Comment by mversic** [comment]
because it works just fine. Look at the last commit on the base branch [here](https://github.com/hyperledger/iroha/pull/4538). I don't quite understand how you would do it

**Comment by BAStos525** [comment]
`I2::Dev::Static` is not running there

**Comment by mversic** [comment]
good point. That file should be updated as well

**Comment by mversic** [comment]
as far as I see it. All workflows should update the target branch to be the version branch. All except `iroha2-dev.yml`. I'm not a big fan of this approach so I'm open to different suggestions

**Comment by mversic** [comment]
having published 2 patch releases, I don't think this is the way
