### ISSUE TITLE
Build `config/swarm/executor.wasm` in CI

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4549]
Currently, every developer builds executor on his own machine and commits it into git. Then this executor is used in tests. This creates too many unnecessary git conflicts and prevents me from merging backports directly into `main` branch. What was the reason for doing this in the first place?

We should build executor in the CI every time before running tests in the CI and not track `executor.wasm` in git at all

**Comment by mversic** [comment]
but will it be portable? Should user build it on their own machine?

**Comment by Erigara** [comment]
Github artifacts is tricky to deal with...

We can't simply get artifact by it's name like `executor`.
We either should specify artifact id which is not known in compose file or get list of artifacts with the same name and get latest which is not very convenient as well. 

Also i'm not sure it's artifacts are suitable for long term storage since every artifact has retantion timer associated with it.

**Comment by mversic** [comment]
we can:
1. persist artifacts somewhere publicly available
2. put executor in the docker image itself (not a big fan of this)

**Comment by mversic** [comment]
is it possible to run a script that build wasm before starting the container on `docker-compose up`?

**Comment by mversic** [comment]
> I supposed a public endpoint as AWS S3, but not everybody who is involved in custom genesis creations has even AWS accounts there. Thus, a lot of new routine are coming. Also additional secrets should be added to CI that it's always better to avoid if possible.

as far as we're concerned others can store `executor.wasm` in their repo and not change their workflow. I don't see why them not having access to AWS prevents us from doing this. This is my preferred option atm

**Comment by BAStos525** [comment]
> is it possible to run a script on the host that build wasm before starting the container on `docker-compose up`?
> 
> edit: seems not

Deployment (CD) should be clear of creation smth.

We can try to push executors to the outside special repository but it's a rough option too. FTP server is suitable here, but should be configured from scratch, so, an additional effort and time spending in this case.

**Comment by BAStos525** [comment]
> > I supposed a public endpoint as AWS S3, but not everybody who is involved in custom genesis creations has even AWS accounts there. Thus, a lot of new routine are coming. Also additional secrets should be added to CI that it's always better to avoid if possible.
> 
> as far as we're concerned others can store `executor.wasm` in their repo and not change their workflow. I don't see why them not having access to AWS prevents us from doing this. This is my preferred option atm

In this case we have to update all deployments either to download executor from S3 or from git. Also, does docker-compose files community users should download executors manually before to up docker-compose?

**Comment by s8sato** [comment]
What if we do the following:

- stop tracking any executor blobs
- make the executor path an environment variable
- introduce a hook to build with iroha binary for the default executor
- burn the default executor blob on the docker image
- have custom executors in docker volume as needed

**Comment by mversic** [comment]
I want to draw everyone attention to what has happened to me when publishing RC21.3 release.

I've been looking into why [this](https://github.com/hyperledger/iroha/actions/runs/8999980283/job/24725417016) CI job it fails. All of a sudden Iroha fails too boot from `docker-compose.yml` and it's unrelated to the changes in the PR. What has happened is that we have merged [this](https://github.com/hyperledger/iroha/pull/4541) PR and `docker-compose.yml` depends on `hyperledger/iroha:dev` image instead of build the one from the current repository

IMO all docker images should build themselves locally. This should be the default, and if someone wants to they can change to download the docker image. If we want to offer predefined network referencing a static docker image, we should do that in the documentation repository, not here. These images are for development, not for deployment

**Comment by s8sato** [comment]
I agree @mversic , there would be no good reason to pull the last published dev image and test it in the release workflow. I also think a test by pulling an image would duplicate a previous test by building the image

**Comment by BAStos525** [comment]
> I agree @mversic , there would be no good reason to pull the last published dev image and test it in the release workflow. I also think a test by pulling an image would duplicate a previous test by building the image

If you mean the step [`Test docker-compose.yml before pushing`](https://github.com/hyperledger/iroha/blob/bf789efa4c114db422c701737218f6c4202be759/.github/workflows/iroha2-dev.yml#L42), image from DockerHub shouldn't pulled there. We use `load: true` definition while building iroha with appreciate tags before. It allows do not build/pull iroha image from scratch again during docker-compose tests before docker-compose command is able to find these tags locally.

**Comment by s8sato** [comment]
@BAStos525  I mean [the corresponding step of the release workflow](https://github.com/hyperledger/iroha/blob/bf789efa4c114db422c701737218f6c4202be759/.github/workflows/iroha2-release.yml#L48-L51) would ignore `iroha:TAG` built in local and pull `iroha:dev` hardcoded in `docker-compose.yml`

**Comment by BAStos525** [comment]
> @BAStos525 I mean [the corresponding step of the release workflow](https://github.com/hyperledger/iroha/blob/bf789efa4c114db422c701737218f6c4202be759/.github/workflows/iroha2-release.yml#L48-L51) would ignore `iroha:TAG` built in local and pull `iroha:dev` hardcoded in `docker-compose.yml`

Right. For now only manual changing of docker-compose files between merging to the stable branch is available. Compose files are managed by swarm.
