### ISSUE TITLE
Check reason of rejection

### ISSUE THREAD

**Issue by enxtur** [hyperledger/iroha#4561]
From following lines, error looks like public field.
https://github.com/hyperledger/iroha/blob/ca37b7fdbf5c003e55db27bf792f3aab5abfe04e/data_model/src/transaction.rs#L174-L179

And I saw that accessing to error in tests
https://github.com/hyperledger/iroha/blob/ca37b7fdbf5c003e55db27bf792f3aab5abfe04e/client/tests/integration/burn_public_keys.rs#L95-L98

And I'm trying to access to error of `TransactionValue` like following snippets.
```rust
fn my_get(client: Client, hash_of: HashOf<SignedTransaction>) {
    let res: TransactionQueryOutput = client.request(FindTransactionByHash::new(hash_of)).unwrap();
    let transaction_value: &TransactionValue = res.transaction();
    if let Some(error) = transaction_value.error {
        
    }
}
```
But it says `field 'error' of 'TransactionValue' is private`.

How do I access to this error or is there any way to know reason of rejection?

**Comment by mversic** [comment]
use method access like this:
```rs
fn my_get(client: Client, hash_of: HashOf<SignedTransaction>) {
    let res: TransactionQueryOutput = client.request(FindTransactionByHash::new(hash_of)).unwrap();
    let transaction_value: &TransactionValue = res.transaction();
    if let Some(error) = transaction_value.error {
    }
}
```

**Comment by enxtur** [comment]
Thank you for the reply. But still has error and it says `no method named 'error' found for reference '&TransactionValue' in the current scope` `private field, not a method`
![Screenshot 2024-05-17 at 01 26 58](https://github.com/hyperledger/iroha/assets/604095/453450c7-53da-431a-ae1c-5a60b0a189e5)

**Comment by mversic** [comment]
ok, which release are you using?

**Comment by enxtur** [comment]
Hi, I'm using `2.0.0-pre-rc.20` which is `stable` branch.

**Comment by mversic** [comment]
you can try now, a fix was merged

**Comment by enxtur** [comment]
Yes, It is working. Thank you

**Comment by enxtur** [comment]
@mversic Thanks for the recommendation.
