### ISSUE TITLE
backporting workflow

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#4570]
> ![image](https://github.com/hyperledger/iroha/assets/49983831/78c34469-daf5-467d-8271-3e9a3854270f)
> https://blogs.oracle.com/linux/post/backporting-patches-using-git

Regarding backports, my suggestion is to first make commits on the main branch and then apply them to every release branch as needed.

> fixes should land on master first, be tested there, and only then be back-ported to older releases.
> https://stackoverflow.com/a/13275789

There are some actions that would help this approach:

- https://github.com/marketplace/actions/backporting
- https://github.com/marketplace/actions/backport-action

might be an example:
- https://github.com/kata-containers/community/blob/main/Backport-Guide.md

**Comment by mversic** [comment]
ok, what you suggest this seems better:
1. make a fix commit to the main branch
2. cherry-pick the commit to the release branch (forked of at the time of making the 1st tag)

This solves the issue with the `CHANGELOG.md`. The issue that remains is the CI. We need CI to run on every PR to release branch. I'm not sure how to do that best. Maybe we can have CI workflows that target all branches starting with a prefix, like `2.0.0` (currently we have a branch `2.0.0-pre-rc.21`). Or we should remain with `stable` branch for the latest public release

**Comment by s8sato** [comment]
What do you think about having `stable/2.0.0` etc. and filtering by `stable/` ? However, in that case, the current `stable` would not coexist with them

**Comment by mversic** [comment]
This is the description of Iroha's workflow:
1. We have `main` branch which everyone works on and merges their PRs to
2. We create new branch from main when we publish a new major version
3. We create git tag and publish to `crates.io` from this new branch

## Example

### New major release
Let's say we are releasing `2.0.0-rc.2.0` (previous release was ):
1. Create a  new entry in `CHANGELOG.md` (cut it from the `Unreleased` section if possible)
3. Create a branch called `2.0.0-rc.2`(notice the absence of the minor version) from the `main` branch
4. In the version branch create a tag `v2.0.0-rc.2.0` (tags are prefixed with `v` to make our life in CI easier)
5. Publish new `2.0.0-rc.2.0` release of all Iroha crates to `crates.io` from the version branch
6. In the `main` branch update version of Iroha in `Cargo.toml` files to `2.0.0-rc.3.0` (next release)

### New patch release
Making a bug fix for `2.0.0-rc.1` (notice the version is 1 behind latest release):
1. Commit the fix to the `main` branch first 
2. Update `CHANGELOG` in a separate commit (we must have an entry for patch versions as well)
2. Cherry-pick commits (all bugfix and `CHANGELOG`) from `main` into the version branch (in this case `2.0.0-rc.1`)
3. In the version branch update version of Iroha in `Cargo.toml` files to `2.0.0-rc.1.1`
4. In the version branch create a new tag `v2.0.0-rc.1.1`
5. Publish new release of all Iroha crates to `crates.io` from the version branch

**Comment by s8sato** [comment]
About the patch release section,
I'd like to disambiguate whether the separate commits should be on my fork or on the target branches. I guess a single commit on the target branches that are squashed from the separate commits on my fork would be enough:

> 1. Commit the fix to the `main` branch first
> 2. Update `CHANGELOG` in a separate commit (we must have an entry for patch versions in the `main` branch as well)
> 3. Cherry-pick commits (all bugfix and `CHANGELOG`) from `main` into the version branch (in this case `2.0.0-rc.1`)
> 4. In the version branch update version of Iroha in `Cargo.toml` files to `2.0.0-rc.1.1`

In this case, for example,

- The `main` branch should have a commit from a PR `fix: my patch (#0000)` that consists of `fix: my patch` and `chore: update CHANGELOG.md`
- The `2.0.0-rc.1` branch should have a commit from a PR `fix(BACKPORT): my patch (#0001)` that consists of `fix: my patch` and `chore: update CHANGELOG.md`, where the latter should be amended to increment the minor version to `2.0.0-rc.1.1`

Am I correctly understanding @mversic ?

**Comment by mversic** [comment]
yes except:

> where the latter should be amended to increment the minor version to 2.0.0-rc.1.1

shouldn't be amended but added as a new commit

**Comment by mversic** [comment]
you must push a tag:
`git push upstream tag v2.0.0-rc.1.`

**Comment by s8sato** [comment]
> ### New major release
> 
> 6. In the `main` branch update version of Iroha in `Cargo.toml` files to `2.0.0-rc.3.0` (next release)

Following best practices:

- Update the `version` fields in `Cargo.toml` only in the commit that publishes the release.
- Include the corresponding `CHANGELOG.md` update in the same PR.

https://users.rust-lang.org/t/managing-version-numbers-in-cargo-toml
