### ISSUE TITLE
coverage measurement targets

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#4584]
_Originally posted by @s8sato in https://github.com/hyperledger/iroha/pull/4573#discussion_r1596320435_

Define appropriate coverage measurement targets:

- Numerator:
   - Should coverage by `p2p/tests/integration` be considered?
- Denominator:
   - What parts of the code do not need to be covered by tests?

**Comment by s8sato** [comment]
Currently, our coverage is failing to ignore certain paths:
[The coverage generating command](https://github.com/hyperledger/iroha/blob/b9f28442bf4225f1647901629a4baed3b122cc3c/.github/workflows/iroha2-dev-pr.yml#L63) expects `client_cli` should be ignored, while [sonar](https://sonar.soramitsu.co.jp/component_measures?id=hyperledger%3Airoha&metric=uncovered_lines&selected=hyperledger%3Airoha%3Aclient_cli) (you may need to request access to DevOps) detects 753 uncovered lines in `client_cli/pytests`.
A weird thing is that the source of the coverage report (`lcov.info` as a CI artifact e.g. as seen [here](https://github.com/hyperledger/iroha/actions/runs/10446225949)) does not mention `client_cli` except for `client_cli/build.rs` which has 0 uncovered lines

**Comment by mversic** [comment]
@s8sato @BAStos525 can you close this if it's finished?
