### ISSUE TITLE
Update the contributing guide

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#4585]
Make sure that the contributing guide reflects these recent changes:

- we switched to Conventional Commits in #4502
- we stopped labeling new issues and PRs with `iroha2` in #4501
- we changed our branching model in #4433

**Comment by MukulKolpe** [comment]
Hey @nxsaken, can I work on this one?

**Comment by MukulKolpe** [comment]
Hey @nxsaken, just to be sure, The target branch for this issue is the main branch right?

**Comment by nxsaken** [comment]
@MukulKolpe hi, yes
