### ISSUE TITLE
Trigger execution order

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4602]
Maybe this is a non-issue, but we should define what the order of execution of triggers is when multiple triggers are triggered at the end of block. Also, impose ordering when multiple triggers are triggered by the same event

**Comment by Erigara** [comment]
So currently we have following trigger execution order:

1. Data events are execute trigger events are produced depending on block content, and for triggers match order depends on trigger id order.
2. Time events are emitted last so time triggers executed also based on trigger id ordering.

Let's consider the following:
1. Data events A, B, C
2. Execute trigger event E
3. Time event T
4. Ordering of the events is the following A, E, B, C, T (T is always last)
5. There is triggers:
    1. TA1, TA2 which triggers by A
    2. TB by B
    3. TC1 and TC2 by C
    4. TE by E: since execute trigger event contains trigger id only single matching trigger is possible
    6. TT1 have 1 match for T, TT2 have 2 matches for T, TT3 have 3 matches for T
6. There is ordering of trigger ids: TA1 < TA2, TC1 < TC2, TT1 < TT2 < TT3

Then the following execution queue will be created: TA1, TA2, TE, TB, TC1, TC2, TT1, TT2, TT2, TT3, TT3, TT3.

**Comment by Erigara** [comment]
@mversic is that should be documented somewhere?

**Comment by mversic** [comment]
ok, this looks fine to me
