### ISSUE TITLE
Remove a redundant trigger-domain_id connection

### ISSUE THREAD

**Issue by Stukalov-A-M** [hyperledger/iroha#4630]
# Remove a redundant trigger-domain_id connection

**ref**. https://github.com/hyperledger/iroha/pull/4616#issuecomment-2119188143

I think we should remove connection of a trigger with a domain_id. It doesn't make sense because each trigger's authority already has this connection. Moreover, it creates some redundant difficulties in cases of permission granting and checking ref is_trigger_owner()

# Minimum working example

Proposed a new trigger structure
```
    pub struct Trigger {
        /// [`Id`] of the [`Trigger`].
        pub id: Name,
        /// Action to be performed when the trigger matches.
        pub action: action::Action,
    }
```

**Comment by nxsaken** [comment]
I'd like to try handling this. Is that fine?

**Comment by Stukalov-A-M** [comment]
> I'd like to try handling this. Is that fine?

I have no objections
