### ISSUE TITLE
How block hash should be derived?

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4641]
Look like we sign over whole block not just header.
I see few problems with that:
- redundant becasue in the block header merkle root of transactions is alredy included
- might harm ability to verify block for light client, since in order to verify inclusion of transation we need whole transacaction set

I will create a ticket for discussion.

_Originally posted by @Erigara in https://github.com/hyperledger/iroha/pull/4518#discussion_r1611265234_

**Comment by mversic** [comment]
I agree here

**Comment by s8sato** [comment]
- It would be enough to sign `payload.header` if it derives `payload.commit_topology` and `payload.event_recommendations`
- In the inclusion proofs, the light client would test the other node to see if it can fill the missing path between the leaf and the root (`payload.header.transactions_hash`). I don't think block signatures are relevant

**Comment by s8sato** [comment]
Ah, I guess what you see as a problem is [`HashOf<SignedBlock>` implementation](https://github.com/hyperledger/iroha/blob/fad3e0c45fab4946af2c59e8b05e45051cfb2259/data_model/src/block.rs#L153-L156). If so, yeah, this would be a problem when the light client approach is required

**Comment by Erigara** [comment]
Yeah, it also the case that hash of block is not the same across block's lifetime

**Comment by s8sato** [comment]
It sounds natural to me that a block hash is transient until it become `CommittedBlock` It would not matter unless hash is used as an identifier

**Comment by Erigara** [comment]
In the logs i've encountered cases where there is message that block was created (one hash) and than block committed (another hash). 
This makes debugging less convenient.
Also imo it's natural to treat block hash as some kind of identifier.

**Comment by s8sato** [comment]
How about having two different hashes for a block:

- hash of `BlockPayload` to sign the block
- hash of `BlockHeader` to identify the block
