### ISSUE TITLE
`iroha_crypto` panic

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4649]
when I try to decode `04000001aeeba99f825cf8e4e6d7270b30fd927aa4c5b030df2ff891f28c2cc5b6d5d7990000
` hex string with `parity_scale_decoder` I get a panic like this:

```
thread 'main' panicked at crypto/src/signature/ed25519.rs:31:31:
range end index 32 out of range for slice of length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens on `v2.0.0-pre-rc.21.3` branch so it may not be a problem anymore

**Comment by DCNick3** [comment]
Still happens on main. Need to make the conversions to arrays in `iroha_crypto` fallible
