### ISSUE TITLE
failed to parse manifest, expected a boolean or an integer for key `profile.profiling.debug`[BUG] 

### ISSUE THREAD

**Issue by aug2uag** [hyperledger/iroha#4677]
### OS and Environment

MacOS13.4

### GIT commit hash

3ab24b02

### Minimum working example / Steps to reproduce

`cargo build`

### Actual result

error: failed to parse manifest at `/Users/me/iroha/Cargo.toml`

Caused by:
  expected a boolean or an integer for key `profile.profiling.debug`

### Expected result

    Updating git repository `https://github.com/akonradi-signal/displaydoc.git`
    Updating crates.io index
^[[1;2D       Fetch [=========>               ]  42.77%, (16121/105659) resolving deltas                                                                                                                               Updating git repository `https://github.com/Erigara/storage.git`
    Updating git repository `https://github.com/Erigara/pprof-rs`
...

### Logs

<details>
  <summary>Log contents</summary>
  
  ```json
[
  "% cargo build",
  "error: failed to parse manifest at `/Users/me/iroha/Cargo.toml`",
  "",
  "Caused by:",
  "  expected a boolean or an integer for key `profile.profiling.debug`"
]
  ```
</details>

**Comment by nxsaken** [comment]
What Rust toolchain version are you using? Strings are acceptable in that field.

**Comment by DCNick3** [comment]
We should start shipping `rust-toolchain.toml` so it would be more clear which toolchain we are using & supporting..
