### ISSUE TITLE
[BUG]: Snapshot tests failures

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4686]
Commit 7a41ae8edc1f0f9a8e969d9f3cbf28a6daa3cfa8 introduced failures in 2 tests: 
- snapshot::tests::can_read_snapshot_after_writing
- snapshot::tests::creates_all_dirs_while_writing_snapshots

**Comment by nxsaken** [comment]
There is a linking error that seems to have been introduced in the same commit: https://github.com/hyperledger/iroha/actions/runs/9284079730/job/25545677112#step:5:742

**Comment by Erigara** [comment]
@nxsaken i can't see the issue in latest `CodeQuality` jobs for some reason
