### ISSUE TITLE
[BUG] Error during key recovery: Transaction Rejected

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#4689]
### OS and Environment

MacOS, bare metal

### GIT commit hash

RC 20

### Minimum working example / Steps to reproduce

```json
[
  {
    "Mint": {
      "object": {
        "PublicKey": "ed25519...." 
      },
      "destination_id": {
        "AccountID": "alice@wonderland"
      }
    }
  },
  {
    "Burn": {
      "object": {
        "PublicKey": "ed25519...." 
      },
      "destination_id": {
        "AccountID": "alice@wonderland"
      }
    }
  }
]
```

### Actual result

Rejected transaction: TransactionPayload(creationTimeMs=1717157861428, authority=AccountId(domainId=DomainId(name=Name(string=one)), name=Name(string=bankonex)), instructions=Instructions(vec=[Mint(mintExpr=MintExpr(object=EvaluatesTo(expression=Raw(value=PublicKey(publicKey=PublicKey(digestFunction=jp.co.soramitsu.iroha2.generated.Algorithm$Ed25519@dc25d98e, payload=[-16, -86, -37, -4, -4, -58, 56, 40, 109, 0, 23, -117, -27, 39, 51, 3, 116, 38, 0, -32, 47, -68, -10, 106, 5, 119, -34, -34, 23, 12, 48, -48])))), destinationId=EvaluatesTo(expression=Raw(value=Id(idBox=AccountId(accountId=AccountId(domainId=DomainId(name=Name(string=one)), name=Name(string=qa7)))))))), Burn(burnExpr=BurnExpr(object=EvaluatesTo(expression=Raw(value=PublicKey(publicKey=PublicKey(digestFunction=jp.co.soramitsu.iroha2.generated.Algorithm$Ed25519@dc25d98e, payload=[78, 61, -106, -122, 105, 119, 86, -71, -77, 40, 73, 63, 55, 62, -78, 109, 98, 3, -120, -89, 105, -15, -13, 27, 50, -62, 107, 115, 10, 115, 113, -117])))), destinationId=EvaluatesTo(expression=Raw(value=Id(idBox=AccountId(accountId=AccountId(domainId=DomainId(name=Name(string=one)), name=Name(string=qa7))))))))]), timeToLiveMs=NonZeroOfu64(u64=86400000), nonce=NonZeroOfu32(u32=4164133955), metadata={})

### Expected result

no errors

### Logs

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

### Who can help to reproduce?

@AlexStroke

**Comment by mversic** [comment]
we ne longer have multiple keys for accounts
