### ISSUE TITLE
Allow multiple peers submit genesis

### ISSUE THREAD

**Issue by dima74** [hyperledger/iroha#4696]
As described in https://github.com/hyperledger/iroha/issues/4225#issuecomment-2087976958

**Comment by dima74** [comment]
Currently we have following behaviour:
* GenesisTransaction is provided to Leader peer
* Leader peer signs it and creates SignedBlock
* Leader peer sends SignedBlock to all peers
* Finally all peers have same SignedBlock (signed only by Leader peer)

Initially I planned to implement this task as follows:
* GenesisTransaction is provided to all peers
* Each peer extract executor and parameters from GenesisTransaction (they should be first and second instructions)
* Leader peer signs GenesisTransaction and creates SignedBlock
* Leader peer sends SignedBlock to all peers
* Peers receive SignedBlock and check that block payload equals to GenesisTransaction they have
* Finally all peers have same SignedBlock (signed only by Leader peer)

We discussed with @Erigara and found problem with this approach: all peers have all necessary data (GenesisTransaction), but still have to wait SignedBlock from the Leader. So we agreed on the following approach:
* `kagami genesis sign` will produce SignedBlock instead of GenesisTransaction. To do so `topology` field will be added to `genesis.json`
* SignedBlock is provided to all peers. All peers will use that SignedBlock directly as a first block without any communication. Note that first block will not be signed by any peer, that is `SignedBlock::signatures` will be empty.

@mversic @0x009922 what do you think?

**Comment by mversic** [comment]
>  `kagami genesis sign` will produce SignedBlock instead of GenesisTransaction. To do so `topology` field will be added to `genesis.json`

yes, this is also better because it hardcodes the initial topology

> SignedBlock is provided to all peers. All peers will use that SignedBlock directly as a first block without any communication. Note that first block will not be signed by any peer, that is SignedBlock::signatures will be empty.

why does it have to be provided to all initial peers and can't be also circulated via block sync? what happens when a new peer is added to the network?

**Comment by dima74** [comment]
> why does it have to be provided to all peers and can't be also circulated via block sync? what happens when a new peer is added to the network, how does it get genesis?

This is according to https://github.com/hyperledger/iroha/issues/4225#issuecomment-2087976958. @0x009922 did you propose to provide genesis to all peers including peers that are not in initial topology (added to the network later), or did I misunderstand your comment?

**Comment by mversic** [comment]
> > why does it have to be provided to all peers and can't be also circulated via block sync? what happens when a new peer is added to the network, how does it get genesis?
> 
> This is according to https://github.com/hyperledger/iroha/issues/4225#issuecomment-2087976958. @0x009922 did you propose to provide genesis to all peers including peers that are not in initial topology (added to the network later), or did I misunderstand your comment?

We need to have block sync work even for genesis block. What must be given to all peers is hash of the genesis block. Genesis block must be provided to at least one peer but can be provided to multiple at the same time. We don't want either of these to be treated as an error. From the perspective of any peer it doesn't matter how it receives the block, whether given on startup or delivered after startup (through block sync)
