### ISSUE TITLE
Snapshot seed serialization issue

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4726]
I have noticed that in `impl<'de> DeserializeSeed<'de> for WasmSeed<'_, World>` `next_key_seed` is not called before `next_value_seed` as documentation states should be done. Is this ok?

For `KuraSeed` as well

**Comment by Erigara** [comment]
@mversic we call `.next_key()` which is the same as calling `.next_key_seed(PhantomData)` ([link](https://docs.rs/serde/latest/src/serde/de/mod.rs.html#1857))
