### ISSUE TITLE
Constructors for tx/blocks

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#473]
So far we don't really have a good tool for creating transaction and that may lead to errors (e.g hash recalculation, missed timestamp, etc)

And, oh god, don't use macros for this. We have a templates in 2k18-1

**Comment by neewy** [comment]
We will create C++ library, which will calculate hash, put timestamp and increment tx_counter. I will close this issue, as this task now in backlog here: https://soramitsu.atlassian.net/browse/IR-360
