### ISSUE TITLE
Validate genesis instructions

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4743]
> A thing that I have noticed. We don't validate genesis instructions at all anymore because there is no initial executor. This is a bug, only the 1st instruction (which is upgrade) should not be validated, all others should

_Originally posted by @mversic in https://github.com/hyperledger/iroha/issues/4739#issuecomment-2178400860_

**Comment by mversic** [comment]
this can most easily be solved by enforcing genesis to have 2 transactions instead of 1 where 1st is `Upgrade<Executor>` and 2nd contains all other instructions

**Comment by AlexStroke** [comment]
[Uploading... image.png]<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXUwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e649ff7edce392daf273ee5512c28796ced03245/image.png" alt="image.png" />
