### ISSUE TITLE
Replace usage of `FromStr::from_str` with `str::parse` across the project

### ISSUE THREAD

**Issue by Stukalov-A-M** [hyperledger/iroha#4749]
It's best to use the inherent `str::parse<T: FromStr>` method across the project instead of `FromStr::from_str` since it doesn't require bringing `FromStr` into the scope.

**Comment by Stukalov-A-M** [comment]
Implemented `From<&str>`, replace parse to &str

**Comment by nxsaken** [comment]
@Stukalov-A-M `str::parse<T>` is more convenient that `Into<T>::into` in cases where type inference fails, thanks to the turbofish syntax. It is also more idiomatic in this case: `FromStr` carries the intent of extracting meaning from a string, while `(Try)From` is more suited for type conversions, where the string probably stays the same but the context around it is changed.

**Comment by Stukalov-A-M** [comment]
> @Stukalov-A-M `str::parse<T>` is more convenient than `Into<T>::into` in cases where type inference fails, thanks to the turbofish syntax. It is also more idiomatic in this case: `FromStr` carries the intent of extracting meaning from a string, while `(Try)From` is more suited for type conversions, where the string probably stays the same but the context around it is changed.

Could u pls. send the ref where it's said about idiomaticity ?


I found only info that parse::<T>() we're using were cast may bring to an error and Into::<T> where we sure that str will be casted into the the <T> without errors

**Comment by nxsaken** [comment]
Here are some discussions on it: 
- https://users.rust-lang.org/t/is-there-actually-a-semantic-difference-between-fromstr-and-tryfrom-str/92765/2
- https://internals.rust-lang.org/t/pre-rfc-deprecate-fromstr-in-favor-of-tryfrom-str/12331/5

If the parsing is infallible, it's possible to specify the bottom `Infallible` type as the `Err` associated type in `FromStr`.

**Comment by Stukalov-A-M** [comment]
> Here are some discussions on it:
> 
> * https://users.rust-lang.org/t/is-there-actually-a-semantic-difference-between-fromstr-and-tryfrom-str/92765/2
> * https://internals.rust-lang.org/t/pre-rfc-deprecate-fromstr-in-favor-of-tryfrom-str/12331/5
> 
> If the parsing is infallible, it's possible to specify the empty `Infallible` type as the `Err` associated type in `FromStr`.

Thanks a lot! I'll research discussions.

**Comment by mversic** [comment]
implemented
