### ISSUE TITLE
refactor(wasm): consider replacing lol_alloc with dlmalloc-rs

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4781]
We should consider replacing `lol_alloc` with `dlmalloc-rs`.

I would expect some benefits:
- `dlmalloc-rs` is used by rust std itself as default allocator for wasm target, so we can expect better support and less bugs
- might have better performance

Possible downsides:
- might increase size of the executor and smart-contracts

**Comment by Erigara** [comment]
Measured impact on changing allocator for default executor.
TLDR: slight increase in size, no noticeable difference in performance.

So the only benefit is stability (due to inclusion is rust std).
@mversic should i open PR or it doesn't wroth it?


```plain
Before:
476K    ./configs/swarm/executor.wasm
After:
480K    ./configs/swarm/executor.wasm
Delta: +0.8%

Before:
validate_blocks/validate_blocks
time:   [9.5776 s 9.7572 s 9.9737 s]
After:
validate_blocks/validate_blocks
time:   [9.4780 s 9.7702 s 10.079 s]
change: [-3.4595% +0.1333% +4.0266%] (p = 0.95 > 0.10)
No change in performance detected.

Heap allocations as well doesn't show significant difference.
``` 

Before:
![image](https://github.com/user-attachments/assets/0efdfefe-749d-4d20-8ed7-3934194b5d01)

After:
![image](https://github.com/user-attachments/assets/6ca67550-b894-4406-837a-ad32ea008718)

**Comment by mversic** [comment]
Yes, you can open a PR
