### ISSUE TITLE
refactor: how to represent parameters in genesis

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4813]
I would like for `parameters` to look like this:
```json
  "parameters": [
    {
      "sumeragi": {
        "block_time_ms": 2000
        "commit_time_ms": 4000
      }
    },
    {
      "block": {
        "max_transactions": 512
      }
    },
    {
      "transaction": {
        "max_instructions": 4096
        "smart_contract_size": 4194304
      }
    },
    {
      "executor": {
        "fuel": 55000000
        "memory": 55000000
      }
    },
    {
      "smart_contract": {
        "fuel": 55000000
        "memory": 55000000
      }
    }
```

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/4812#discussion_r1668502409_

**Comment by divyaranjan1905** [comment]
@Erigara Just to ensure, is this referring to [`data_model::parameter`](https://github.com/hyperledger/iroha/blob/main/data_model/src/parameter.rs) module?

**Comment by mversic** [comment]
in `genesis/src.lib.rs`

**Comment by Mingela** [comment]
Is it going to be reflected in the schema somehow? Would be great to see a proposal for that before merging the change.

**Comment by dima74** [comment]
> Is it going to be reflected in the schema somehow? Would be great to see a proposal for that before merging the change.

Yes, there is type `RawGenesisTransaction` in the schema, it will be changed accordingly (https://github.com/hyperledger/iroha/pull/5020/files#r1736862760)
