### ISSUE TITLE
Audit logs produced by iroha

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#4842]
Atm iroha produce to much logs on level INFO which cause x5 degradation in performance compared to ERROR level.

What could be done: 
- decrease log level
- remove logging from hot loops and print aggregated info
- less verbose printing (i.e. do not print whole transaction with all instructions)

**Comment by Erigara** [comment]
So far there is no significant amount of logs produced at level INFO.

Afaik situation improved when we moved to axum in #4718 after which endpoint related logs were moved to DEBUG level from INFO. 

Imo another round of performance testing should be made in order to check is issue resolved.

**Comment by timofeevmd** [comment]
For a comparative performance analysis, an image with the hash **50e81042** based on Debian was used. You can find it at the following link: **[Docker Image]**(https://docker.soramitsu.co.jp/harbor/projects/19/repositories/iroha/artifacts-tab/artifacts/sha256:704d8143ce7dc8e997749dfe22efbc397c6f23e14479f51c10cc3854e422ae37).

The maximum performance with logging level set to **INFO** is **1998** RPS, and with logging level set to **DEBUG** is **1945** RPS.
The throughput **degradation** was **2.64%**.

No resource utilization leaks were detected.

**Comment by dmitrivenger** [comment]
@Erigara can we close this task?

**Comment by Erigara** [comment]
@dmitrivenger yes, there were no issues which affected performance
