### ISSUE TITLE
Metrics impact on the performance should be mitigated

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#4845]
Currently `handle_metrics` is not async, which can affect performance measured via the metrics

**Comment by Erigara** [comment]
After @timofeevmd testing difference in performance was not found

**Comment by timofeevmd** [comment]
env: debian 5peers

transferAsset
txs - 947tps
txs + statusByTransaction - 2015 tps

env: debian 1peers
transferAsset
txs - 991 tps
txs + status - 2041 tps

before the fix metrics issue total throughput = 1800 tps
