### ISSUE TITLE
Getting no response from the server after running it in docker.

### ISSUE THREAD

**Issue by eizoefoer** [hyperledger/iroha#486]
So we have been following the tutorial to build iroha in docker:
https://github.com/hyperledger/iroha/blob/master/docker/README.md

we have had to tweak a few things like changing warhack/iroha-dev to hyperledger/iroha-dev in build_in_docker.sh

but when building the container it kept crashing. So we used tail -f to allow for a continuous running process to diagnose why it keeps crashing. 

Turns out we have to add sumeragi.json and the correct config.json. So after generating those (using make_sumeragi and using the internal ip's to configure the config file making sure they match the sumeragi file) we add them in and it gives us an ipv6 error.

Turns out ipv6 is disabled in the created docker containers. So after enabling it. We finally get it running, however calling the endpoint say curl localhost:50051 results in ??? (three question marks) See the screen shot below.

Does anyone have any idea of what is missing or what is going wrong? Do we also need to run a webserver or some sort of api gateway or should the project respond to this?

Refer to screeshots below for more info/ context.

![screen shot 2017-08-02 at 3 42 25 pm](https://user-images.githubusercontent.com/20200388/28859178-417a0aae-7799-11e7-8442-ac9f87bfd536.png)

![screen shot 2017-08-02 at 3 44 19 pm](https://user-images.githubusercontent.com/20200388/28859232-8c3a9e0a-7799-11e7-9bfc-b601f22a5967.png)

![screenshot_2017-08-02-13-56-32](https://user-images.githubusercontent.com/20200388/28859131-f89ae088-7798-11e7-89b0-54b58c862c35.png)

**Comment by zeroarst** [comment]
Have the same issue. Please help. No responses from our built server...not sure what we are missing...

**Comment by grimadas** [comment]
We are working now to fix this issue. In the meanwhile you can use one the development environments : For example:  `sh run-ametsuchi-dev.sh`

**Comment by zeroarst** [comment]
Thanks for tip. It is running. We can send money to other, it says OK. But no transactions actually came out. Totally have no idea whats going on...

**Comment by eizoefoer** [comment]
Any progress on this @grimadas ?

It seems to register fine, however no transactions get stored in the wallet. I have checked the postgres and redis containers that get launched as well and neither of contain the data.

Is there any other config file we are missing here? `sumeragi.json` is created with localhost ip (127.0.0.1) automatically when running `sh run-ametsuchi-dev.sh` but the containers ip is 192.168.9.2 would that be an issue?

Where exactly are the transactions that appear in the wallet meant to be stored? so far the only place with data is `/tmp/iroha_ledger`

**Comment by neewy** [comment]
@eizoefoer hi!

There is a problem with pipeline now, the hotfix is ready, please wait until we review and merge it. It is possible that transactions can freeze on the stage of simulator.

https://github.com/hyperledger/iroha/wiki/How-to-start-Iroha https://github.com/hyperledger/iroha/wiki/How-to-use-Iroha-client
follow these to startup the system right after hotfix would be merged.

Transactions are stored in blocks, while blocks are stored in flat files. In config file you specify the place for your flat files in `"block_store_path"`.

Thank you for your interest and contribution to the project!

**Comment by eizoefoer** [comment]
Hi @neewy, thanks for the info. It seems the hotfix has been merged now, however, I am getting the below image, any ideas? Cheers. Also do you have an idea of when the iroha-docker image will be updated?

![image](https://user-images.githubusercontent.com/20200388/29297489-ad6776ce-81a4-11e7-9b10-487922e2b695.png)

**Comment by eizoefoer** [comment]
Quick update @neewy @grimadas , building it from the new docker image, I get the image below.  It seems iroha-main is not being called anymore therefore only port 50051 is hosted which doesn't allow the app to access it (since it uses port 1204 as the http port). Is it possible to get the exact repo or image used to create the demo app? Since that is the functionality we need to integrate it in the project we are currently working on.

Cheers

![image](https://user-images.githubusercontent.com/20200388/29500153-3c3ad66e-8661-11e7-8e8d-cdc20aca91ff.png)

**Comment by developersteve** [comment]
I 2nd that @neewy @grimadas a copy of the image of the demo server would be great to be able to compare things against.

**Comment by neewy** [comment]
Please run Iroha node in docker container using script in develop branch: `sh scripts/run-iroha-dev.sh`

Also, we have a demo server, deployed by @lebdron. Tell me if you need to know how to use it, we can give you credentials

**Comment by neewy** [comment]
Please, reopen issue if it remains
