### ISSUE TITLE
Consider skipping CI jobs instead of filtering them

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#4861]
We have some required checks that are not always triggered. This describes possible workarounds: https://stackoverflow.com/questions/77996177/how-can-i-handle-a-required-check-that-isnt-always-triggered

**Comment by nxsaken** [comment]
@BAStos525

**Comment by BAStos525** [comment]
We've decided to disable some of `Require status checks to pass before merging` jobs in settings

**Comment by nxsaken** [comment]
Disabled conditional status checks
