### ISSUE TITLE
Sumeragi Leader sends only transaction list

### ISSUE THREAD

**Issue by SamHSmith** [hyperledger/iroha#4914]

**Comment by SamHSmith** [comment]
Currently during a consensus round the leader creates and verifies a block before sending it to the other peers. They then "run" the block by validating it, then sending signatures to the proxy tail. The idea is that we can have the leader select the transactions that go into the block and send only those to be assembled into a block on the receiving side. Then all the peers will be "running" the block at the same time instead of the leader then the other peers. The advantage of this is that it reduces total round latency and can therefore improve total TPS by up to 2x. This change was inspired by issue https://github.com/hyperledger/iroha/issues/4733 .

**Comment by mversic** [comment]
good idea
