### ISSUE TITLE
Consider renaming the bin crates for consistency

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#4915]
To install binaries via `cargo install`, crate names are used. This is confusing because the `iroha` binary belongs to the `iroha_client_cli` crate, while the `iroha` crate contains the client SDK. The WASM builder suffers from the same awkwardness. I propose we rename the crates once more:

* `iroha` -> `iroha_sdk`
* `iroha_client_cli` -> `iroha` (or merge into a lib+bin crate)
* Merge `iroha_wasm_builder_cli` and `iroha_wasm_builder` into a lib+bin crate similarly to `iroha_swarm`

If we want to eventually publish Iroha (#2933), we should also take into account that `iroha` and some related names like `iroha_derive` have been taken on crates.io already. We should ask the author of the crate to consider giving up the name, or come up with something else.

**Comment by nxsaken** [comment]
cc: @a-zorina

**Comment by mversic** [comment]
Love the suggestion. I think both should be merged into lib + bin

**Comment by nxsaken** [comment]
I did some research and found some issues with lib+bin consolidation.

There is no way to specify dependencies separately for the binary and the library: https://github.com/rust-lang/cargo/issues/1982. There is a [workaround](https://users.rust-lang.org/t/whats-the-convention-for-handling-a-hybrid-library-and-binary-crates-dependencies/84174/3) involving marking the binary-only dependencies as optional, and bundling them into a required feature for the `[[bin]]` spec.

This means that to build a binary, one would have to always pass `--features cli` or something like that, or else the build will fail (or in the case of a project-wide `cargo build`, the binary will be skipped silently).

Not marking the dependencies as optional would cause unneeded dependencies for those who just want the SDK.

This seems like too much hassle just to be able to `cargo install iroha`, but we could at least rename `iroha_client_cli` to `iroha_cli` so that it's `cargo install iroha_cli`.
