### ISSUE TITLE
Allow async execution of queries in client

### ISSUE THREAD

**Issue by DCNick3** [hyperledger/iroha#4935]
We should a mechanism that would allow query-related HTTP requests to be send asynchronously. For example, one can extend `QueryExecutor` trait with `QueryExecutorAsync` trait and add an async version of `QueryIterator`.

This is needed for iroha blockchain explorer, which currently implements its own [async-capable query builder](https://github.com/soramitsu/iroha2-block-explorer-backend/blob/71c2937294de3d461232d30d46a2556b68ef58e0/src/iroha_client_wrap.rs#L234).

Originally raised in https://github.com/hyperledger/iroha/pull/4833#issuecomment-2268342102.

**Comment by mversic** [comment]
this is part of the #3130 so I'm closing this issue
