### ISSUE TITLE
Build artifacts in CI

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4942]
as was discussed [here](https://github.com/hyperledger/iroha/pull/4931#issuecomment-2270946212) let's add artifacts to CI for quick reference.

We can include executor, genesis, configs, and other binaries (iroha, irohad, kagami, etc)

**Comment by s8sato** [comment]
Does this include a suggestion to stop tracking all that generative artifacts in git?

**Comment by BAStos525** [comment]
> Does this include a suggestion to stop tracking all that generative artifacts in git?

Executor tracking will be stopped
