### ISSUE TITLE
Kura cache

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4954]
Do we need an implementation of cache in `Kura`? Can unbounded `block_data` cause an `OOM`? This can happen as the network grows, but also when restarting a peer when there was no snapshot

If we do make a block cache we should make sure that it's not susceptible to probing attacks from `block_sync` or simple `FindBlocks` query execution

**Comment by dima74** [comment]
@mversic why do we need a cache? Can't we always keep the latest N blocks in memory and any older block always load from the disk when needed?

**Comment by mversic** [comment]
> @mversic why do we need a cache? Can't we always keep the latest N blocks in memory and any older block always load from the disk when needed?

that's a cache with the policy to keep N latest
