### ISSUE TITLE
Remove query store from snapshot

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4971]
Why is query store saved to the disk as part the snapshot functionality? When deserializing snapshot from the disk the query store should just be created as empty

**Comment by Erigara** [comment]
@mversic currently query store is not stored as part of snapshot, with pass it as seed on deserialization.

```
    /// Handle to the [`LiveQueryStore`].
    #[serde(skip)]
    pub query_handle: LiveQueryStoreHandle,
```
