### ISSUE TITLE
[feature request] Return block hashes from `FindBlockHeaders` query  

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4982]
## Use case

In Explorer, we need to display blocks basic data, without its transactions. We display transactions separately, with pagination, lazily.

### Problem

- `FindBlockHeaders` returns data without block hashes
- `FindBlocks` returns all blocks data, including all transactions. The amount of transactions could be vast, and it creates extra overhead for explorer to load them all eagerly.

### Desired solution

Implement `FindBlockHeaders` in a similar way to how `FindTransactions` works: it does not return a list of plain `CommittedTransaction`, but a list of `TransactionQueryOutput` - a wrap around `CommittedTransaction` with additional `block_hash` field.

**Comment by mversic** [comment]
> `FindBlockHeaders` returns data without block hashes

a block hash is the hash of it's header. I would close this issue

**Comment by 0x009922** [comment]
Understood, than it is fine!
