### ISSUE TITLE
[feature request] Support filtering transactions by block hash

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4985]
### Use case

In Explorer we sometimes need to fetch transactions relevant to a specific block.

### Problem

It is currently impossible to do - `FindTransactions` doesn't support filters yet. 
 
(It is possible to fetch all transactions and filter them on client side, but it doesn't scale).

### Possible solution

- Extend `FindTransactions` query with a filter by block hash
- Introduce a dedicated query, e.g. `FindTransactionsByBlockHash`

**Comment by DCNick3** [comment]
Implementing #5017 will allow this.
