### ISSUE TITLE
[feature request] Support sorting transactions by descending creation time

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4986]
### Use case

In Explorer, we need to display a list of all transactions. It makes sense to display them starting from the recent ones - like a blog, a history.

### Problem

It is currently not possible to do without fetching all transactions from Iroha.

### Possible solution

- Sort by descending creation time by default
- Add an option to change sorting of transactions (preferrably type-safe)

**Comment by mversic** [comment]
we should just implement descending solution

**Comment by mversic** [comment]
I think they should be sorted by descending block time. You don't care much about when was it created, but more about when was it executed
