### ISSUE TITLE
Unexpected feature flags

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#4993]
Since updating to Rust 1.80.0, which checks cfgs at compile-time, I've been noticing warnings about unexpected feature flags all over the project:

- unexpected `cfg` condition value: `ffi_import` (feature flag is commented out, might be related to https://github.com/hyperledger/iroha/issues/3102)
- unexpected `cfg` condition name: `crate_type` (seems unsupported: https://github.com/rust-lang/rust/issues/20267)
- unexpected `cfg` condition value: `metric-instrumentation` (feature flag missing)

**Comment by 0x009922** [comment]
There are also warnings about `#![cfg(not(coverage))]` in UI tests.
