### ISSUE TITLE
Lazy deserialization for PublicKey inside WASM

### ISSUE THREAD

**Issue by dima74** [hyperledger/iroha#5038]
In case of single peer tps performance, >60% of time takes WASM call for transaction validation, and most of time inside WASM takes `PublicKey::decode`/`PublicKey::from_bytes` (https://github.com/hyperledger/iroha/issues/4727#issuecomment-2329677940). However inside WASM public key is used mostly for comparison (`==`). Comparision can be performed without deserialization, so I propose to make deserialization lazy inside WASM. In particular adding wrapper like this for `PublicKeyInner`:
```rust
struct PublicKeyInnerLazy {
    algorithm: Algorithm,
    payload: Vec<u8>,
    key: OnceCell<PublicKeyInner>,
}
```

---

Background: why `PublicKey::from_bytes` is slow. Consider call of `PublicKey::from_bytes` with `Algorithm::Ed25519` and 32 bytes payload. The result of this call will be [`ed25519_dalek::VerifyingKey`](https://github.com/dalek-cryptography/curve25519-dalek/blob/0964f800ab2114a862543ca000291a6e3531c203/ed25519-dalek/src/verifying.rs#L58-L64):
```rust
struct VerifyingKey {
    // 32 bytes of original payload, unchanged
    compressed: CompressedEdwardsY,

    // 160 bytes, decompressed
    point: EdwardsPoint,
}
```
`VerifyingKey::point` [is obtained](https://github.com/dalek-cryptography/curve25519-dalek/blob/0964f800ab2114a862543ca000291a6e3531c203/ed25519-dalek/src/verifying.rs#L163) from `VerifyingKey::compressed` using operations like `square`, `pow2k` from `curve25519` crate.

---

cc @mversic @Erigara

**Comment by Erigara** [comment]
Does it mean that data required for key would be doubled?

Also why not use enum to represent key state?

```rust
struct LazyKeyInner {
    algorithm: Algorithm.
}

enum LazyKeyInnerState {
    Uninit(Vector<u8>),
    Init(KeyInner),
}
```

**Comment by dima74** [comment]
> Does it mean that data required for key would be doubled?
> 
> Also why not use enum to represent key state?

My original proposal is optimized for the assumption that `PublicKey` inside WASM in almost all cases is used only for comparisons. So if we add `Box`:
```rust
struct PublicKeyInnerLazy {
    algorithm: Algorithm,
    payload: Vec<u8>,
    key: OnceCell<Box<PublicKeyInner>>,
}
```
then in case `PublicKeyInner` is not needed, we will have even less memory consumption then now (unitialized OnceCell gives 8 bytes overhead). Do you know how often we need actual PublicKeyInner (that is some signing functionaligy) inside WASM?
