### ISSUE TITLE
[BUG] Queries fail with "Unknown query cursor"

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#5085]
### OS and Environment

macOS m1

### GIT commit hash

e68039713

### Minimum working example / Steps to reproduce

With the client SDK:

```rust
fn all(iroha: &Client) {
  iroha
    .query(FindDomains)
    .execute()
    .unwrap();
}

fn single(iroha: &Client, domain: DomainId) {
  iroha
    .query(FindDomains)
    .filter_with(|dom| dom.id.eq(domain))
    .execute_single()
    .unwrap();
}
```

With the client CLI:

```sh
$ iroha --config <PATH_TO_CONFIG_TOML> domain list all
```

### Actual result

All:
```sh
called `Result::unwrap()` on an `Err` value: Validation(QueryFailed(UnknownCursor))
```

Single:
```sh
called `Result::unwrap()` on an `Err` value: QueryError(Validation(QueryFailed(UnknownCursor)))
```

CLI:
```sh
Error: Failed to run the command
├╴at client_cli/src/main.rs:211:34
│
╰─▶ Failed to get all accounts
    ├╴at client_cli/src/main.rs:210:10
    ├╴Query validation error
    ├╴Query execution failed
    ╰╴Unknown query cursor
```

### Expected result

The object(s) or an appropriate error is returned

### Logs

-

### Who can help to reproduce?

@DCNick3

**Comment by nxsaken** [comment]
With #5086:

```sh
$ iroha --config <PATH_TO_CONFIG_TOML> domain list all

Error: Failed to run the command
├╴at crates/iroha_cli/src/main.rs:211:34
│
╰─▶ Failed to get all accounts
    ├╴at crates/iroha_cli/src/main.rs:210:10
    ├╴Query validation error
    ├╴Query execution failed
    ╰╴The server's cursor does not match the provided cursor.
```

**Comment by nxsaken** [comment]
Turned out to be a conflict between dockerized irohad and a bare-metal one left over from old pytests running in the background.

**Comment by DCNick3** [comment]
> Turned out to be a conflict between dockerized irohad and a bare-metal one left over from old pytests running in the background.

Hm, so one request went to one server and another to the other? Did they simultaneously listen on the same port?

**Comment by nxsaken** [comment]
Yeah, just a version mismatch
