### ISSUE TITLE
Ordering gate test bug fix

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#567]
We want to test the timing stuff of ordering but have some RC bug
You can checkout this [build](https://circleci.com/gh/hyperledger/iroha/3935)

I think issue can be due to this [line](https://github.com/hyperledger/iroha/blob/develop/test/module/irohad/ordering/ordering_gate_service_test.cpp?utf8=%E2%9C%93#L71), also this [pr](https://github.com/hyperledger/iroha/pull/537) can be useful as well

**Comment by Warchant** [comment]
outdated
