### ISSUE TITLE
Refactor pb_query_factory_test with overloading of equality operator for queries

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#627]
This is a good start to optimise the codebase for anyone who is curious about Iroha

There are 4 occurrences in pb_query_factory_test:
https://github.com/hyperledger/iroha/blob/5fd84ec8191ceaf69bd49991ffdcbb4f1fb0440d/test/module/irohad/model/converters/pb_query_factory_test.cpp#L36

**Comment by Warchant** [comment]
What is the status of this issue?

**Comment by l4l** [comment]
Seems that TODO is still here:
https://github.com/hyperledger/iroha/blob/78f152a85ee2b3b86db7b705831938e96a186c36/test/module/irohad/model/converters/pb_query_factory_test.cpp#L36

**Comment by l4l** [comment]
Seems redundant as we are going to move to the new model
