### ISSUE TITLE
Fix platform-dependent flat_file implementation

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#630]
Please, think about how to make this a platform independent implementation. It would be a good idea to use Boost.Filesystem, as it is done in CLI.
Example:
https://github.com/hyperledger/iroha/blob/5fd84ec8191ceaf69bd49991ffdcbb4f1fb0440d/iroha-cli/main.cpp#L150

https://github.com/hyperledger/iroha/blob/5fd84ec8191ceaf69bd49991ffdcbb4f1fb0440d/irohad/ametsuchi/impl/flat_file/flat_file.cpp#L29

https://github.com/hyperledger/iroha/blob/5fd84ec8191ceaf69bd49991ffdcbb4f1fb0440d/irohad/ametsuchi/impl/flat_file/flat_file.cpp#L138

**UPDATE**
- To use Boost.Filesystem makes the bug removed where using C functions. `scandir()` makes the code to use `free()`. It's bad for C++.

**Comment by motxx** [comment]
It's nice to remove memory leak while using `scandir` in `check_consistency`.

**Comment by neewy** [comment]
@motxx https://soramitsu.atlassian.net/browse/IR-409?
