### ISSUE TITLE
primitive.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

### ISSUE THREAD

**Issue by prajithparan** [hyperledger/iroha#666]
Hi All,
New error while building iroha in ubuntu 16

primitive.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
schema/CMakeFiles/primitiveproto_h.dir/build.make:61: recipe for target '../schema/primitive.pb.h' failed
make[2]: *** [../schema/primitive.pb.h] Error 1
CMakeFiles/Makefile2:653: recipe for target 'schema/CMakeFiles/primitiveproto_h.dir/all' failed
make[1]: *** [schema/CMakeFiles/primitiveproto_h.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Any idea ? I tried both PROTOC 2 and 3 versions

**Comment by l4l** [comment]
It seems that you're using old protobuf, just update it

**Comment by neewy** [comment]
@prajithparan have you checked your photo version?
