### ISSUE TITLE
error of cylix/cpp_redis

### ISSUE THREAD

**Issue by haojun** [hyperledger/iroha#669]
Hi, 

I encountered an error "irohad/ametsuchi/impl/mutable_storage_impl.hpp:21:38: fatal error: cpp_redis/redis_client.hpp: No such file or directory" when make iroha. 

I checked cpp_redis project and found the redis_client was renamed into client since v4.0, so I re-installed the cpp_redis with version 3.5.4, but still got an error "redis_connection.cpp: undefined reference to 'tacopie::tcp_client::connect". 

I reinstalled cpp_redis by:
1. delete cpp_redis & tacopie folder in /usr/local/include
2. check out 3.5.4 of cpp_redis
3, init & updating the submodule
4. make & make install

Not sure what's wrong, can you help with it? What's your cpp_redis version?

**Comment by kamilsa** [comment]
Hello! Thanks for sharing with us your problem.

Iroha can install all dependencies itself using cmake. So you might try to remove cpp_redis completely from your system and install iroha following steps from [this](https://hyperledger.github.io/iroha-api/#build) tutorial. 
If you want to install cpp_redis into your system you can checkout the on the same commit of cpp_redis that we use in cmake [here](https://github.com/hyperledger/iroha/blob/develop/cmake/Modules/Findcpp_redis.cmake). There you can find that the cpp_redis's commit hash is `727aa5f06c8ce498168cbab5a023cad5b9c00bc0` and tacopie's commit hash is `290dc38681f346adae41d3cc8feabbe534424675`

**Comment by haojun** [comment]
Thanks, the installation succeeds with those commit version
