### ISSUE TITLE
google/protobuf/empty.proto: File not found.

### ISSUE THREAD

**Issue by prajithparan** [hyperledger/iroha#674]
Dears
Again a issue with Protoc , following  errors is coming

```
[ 36%] Built target grpc_cpp_plugin
[ 37%] Generating ../../schema/ordering.pb.h, ../../schema/ordering.pb.cc, ../../schema/ordering.grpc.pb.h, ../../schema/ordering.grpc.pb.cc
google/protobuf/empty.proto: File not found.
ordering.proto: Import "google/protobuf/empty.proto" was not found or had errors.
ordering.proto:13:40: "google.protobuf.Empty" is not defined.
ordering.proto:17:61: "google.protobuf.Empty" is not defined.
schema/CMakeFiles/orderingproto_h.dir/build.make:61: recipe for target '../schema/ordering.pb.h' failed
make[2]: *** [../schema/ordering.pb.h] Error 1
CMakeFiles/Makefile2:842: recipe for target 'schema/CMakeFiles/orderingproto_h.dir/all' failed
make[1]: *** [schema/CMakeFiles/orderingproto_h.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
Any help much appreciated.

**Comment by prajithparan** [comment]
However I can see the file in my PC
/home/test-pc/iroha/external/src/google_protobuf/src/google/protobuf/empty.proto
Could be an issue with makefile creation

**Comment by prajithparan** [comment]
Or may be some environment settings... I forgot to mention

**Comment by neewy** [comment]
which branch are you trying to build? develop?
which version of protobuf are you using to build Iroha?

**Comment by neewy** [comment]
please, also clean up proto generated classes, using script clean.sh

**Comment by prajithparan** [comment]
test-pc@testpc-ThinkPad-T410:~$ protoc --version
**libprotoc 2.6.1**
Im trying to build full irohad by using the git download.
I used the following commands
https://github.com/hyperledger/iroha/blob/master/docs/how_to_build.rst

**Comment by neewy** [comment]
please use development branch for now and follow https://hyperledger.github.io/iroha-api/#build

**Comment by Warchant** [comment]
Currently we are on a way of big changes and the latest branch is `develop`.
Try to install all dependencies as in `docker/develop/Dockerfile`. Then, iroha easily can be built.

Or, you can just use prebuilt image with 
`sh scripts/run-iroha-dev.sh`

**Comment by prajithparan** [comment]
Thanks a lot . Let  me know when the new build is ready.
With docker is working
