### ISSUE TITLE
Improve codestyle

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#689]
As long as we pull new libraries these libraries have all kinds of codestyle conventions.

So after some time it was mixed up and there's a bit chaos in the code

Main issues for fix:
- functionShouldBeInCamelCase
- variables_in_snake_case
- code formatted according to [clang-format](https://github.com/hyperledger/iroha/blob/develop/.clang-format)
- Some unified types for submodules

If you're want to handle that, ping me I would like to help you with that

**Comment by Warchant** [comment]
If you'd write regexp for this, I could enable sonar rules to keep track of all names.

**Comment by l4l** [comment]
Regexp is not really good idea (e.g how can you define that some T is function name and not variable?)
I think it would be nice to just run clang-format on all (changed) files

**Comment by Warchant** [comment]
Sonar detects functions, variables, members, everything. I need to provide regexp only.

**Comment by l4l** [comment]
Some regexpes are added/improved in [sonar](https://sonar.soramitsu.co.jp/coding_rules#qprofile=AV6BROZmKITu8lzV99Ce|activation=false), for now it's fine I think
