### ISSUE TITLE
No such file or directory #include <json.hpp> 

### ISSUE THREAD

**Issue by shangmacun** [hyperledger/iroha#72]
/root/opensource/iroha/core/infra/service/peer_service_with_json.cpp:8:20: fatal error: json.hpp: No such file or directory
 #include <json.hpp>

**Comment by takemiyamakoto** [comment]
You need to run:

$ git submodules init
$ git submodules update

Then you should go into the submodule directors in core/vendor and make them.

**Comment by jzou3700** [comment]
After following above steps, the issue of lack of file json.hpp have been fixed. But the next issue appeared. 
/home/jzou/hyperledger/iroha/core/infra/smart_contract/jvm/java_virtual_machine.cpp:17:17: fatal error : jni.h: no such a file or directory

Thank you for help

**Comment by takemiyamakoto** [comment]
Any luck?

**Comment by shangmacun** [comment]
whether  all of submodules to make  ？

**Comment by MizukiSonoko** [comment]
Sorry, submodule has been bugged....

In core/infra/service/CMakeLists.txt
```cmake
set(JSON_PATH "${PROJECT_SOURCE_DIR}/core/vendor/json")
include_directories(
        ${JSON_PATH}/src
)
ADD_LIBRARY(peer_service_with_json STATIC peer_service_with_json.cpp)
```

So, You need clone [json](https://github.com/nlohmann/json) to core/vendor/json.
```sh
$ git clone https://github.com/nlohmann/json core/vendor/json
```

sorry
