### ISSUE TITLE
Iroha client returning success with transaction been written to postgres

### ISSUE THREAD

**Issue by eduardonunesp** [hyperledger/iroha#724]
Running the development branch in macOS after following the guide (https://hyperledger.github.io/iroha-api/#overview), and I noticed that the transaction was returned success in `iroha-cli` even tho the insertion in `postgres` wasn't actually happened.

Even if an error happened in this case when I accidentally typed the wrong address:
```
[00:27:27][th: 12088688020793015089][error] [GrpcResponseHandler] << Server is unavailable
Congratulation, your transaction was accepted for processing.
Its hash is d3f504d2b0b0ca335c61bdf8b472908713ae5bccb857bc9beb5ec39e30c97b50
```

In another case transaction of a new asset wasn't written to `postgres`, but in that case the `transaction` was right, except the `domain` wasn't right (test), but it created the transaction block in the `block_store` directory.

I think the expected behavior should be to reject the transaction, or at least, give me a status of why the transaction wasn't written in the database.

**Comment by neewy** [comment]
It seems to be a bug definitely. I will assign a milestone for correction soon.

**Comment by sjashwin** [comment]
Can I complete this?

**Comment by LiraLemur** [comment]
The issue with PRs seems outdated and can be closed
Hopefully, CLI will be fixed soon in general
