### ISSUE TITLE
Uniform API naming convention

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#729]
To avoid clients from being confused, we should use one of them.
- [ ] `SetQuorum` vs `SetAccountQuorum`
  - Proto: https://github.com/hyperledger/iroha/blob/develop/schema/commands.proto#L49
  - JSON: https://github.com/hyperledger/iroha/blob/19651930fa6851586bfb9f09c3f6f2f3d3a51eaf/irohad/model/converters/impl/json_command_factory.cpp#L105
  - Also, name of model is `SetQuorum`
- [ ] Role & Permissions
  - [ ] Remove prefix `Can`
    - We use `CanTransfer`, `CanGrant*`, `CanGrantCan*`, ... They are very complex.
    - Use `Transfer`, `Grant*` and so on, simply.
  - [ ] `(Can)ReadAssets` vs `(Can)Get*`
- [ ] Prural vs Singular
  - [ ] `GetAccountAssets`, `NO_ACCOUNT_ASSETS`
  - [ ] Protobuf: `repeated Type *s` vs `repeated Type *[^s]`
- [ ] `pubkey` vs `public_key`
  - `AddSignatory`/`RemoveSignatory`: `public_key`
  - vs `CreateAccount`: `main_pubkey`
- [ ] `domain_id` vs `domain_name`
  - `CreateDomain` uses `domain_name`. We may regard the value of `*_name` as not registered yet in the system. But it seems obvious.
  - Proposal: Use `domain_id` only.
- [ ] `SetAccountDetail` vs `(Can)SetAccountInfo`
  - https://github.com/hyperledger/iroha/blob/develop/irohad/model/permissions.hpp#L41
----
No problem about uniform, but potentially differ from clients expectation
- [ ] Fields of `first, second, third, fourth` in `uint256`
  - We cannot deduce from their names, which field is the highest or lowest bits.
  - Proposal fields: `highest, higher, lower, lowest`
- [ ] Field `main_pubkey` in `CreateAccount`
  - It occurs misleading `main_pubkey` as a special key, unlike other public keys to be added.
  - Proposal: `public_key`

Any other inconsistencies or improvements?

**Comment by neewy** [comment]
Good suggestion. It seems to be important in order to lower the grade of entropy in the project. As soon as we agree on release plan -- I will assign a milestone for this issue.

**Comment by neewy** [comment]
This should be performed as part of optimisations for the upcoming release

**Comment by l4l** [comment]
I believe most of it is resolved via shared model, consider opening a new issue if something is missed
