### ISSUE TITLE
Change ordering service/ordering service transport implementation for integration test

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#731]
In the integration test, we want to send multiple transactions but cannot guarantee the order of transactions. The way of waiting transactions are committed is bad because it requires polling `StatusAsync`. If some transactions are not sent, infinity loop occurs in the test code.

So inheriting from ordering service/ordering service transport is needed.
https://github.com/hyperledger/iroha/pull/709#issuecomment-346259310

**Comment by motxx** [comment]
Condition variable in `PeerCommunicationService` is used and it can be closed if the PR reviewed.

**Comment by neewy** [comment]
PR was reviewed, @motxx ?
