### ISSUE TITLE
No logic test in command executor

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#746]
Tests of `CommandExecutor` doesn't verify any logic.

Insert the bug into `AddAssetQuantityExecutor::execute()` of current develop branch.
https://github.com/hyperledger/iroha/commit/285444b543caa8a305a769742c56451f35fe068e
But all tests pass because there is no logic test in `command_validate_execute_test.cpp`. Just checking `EXPECT_CALL`
https://github.com/hyperledger/iroha/blob/master/test/module/irohad/model/command_validate_execute_test.cpp#L145

Mock of ametsuchi should not be used here. Use real database and verify the account asset value.

**Comment by l4l** [comment]
Fixed after #1123 merge
