### ISSUE TITLE
Validation of CreateDomain and CreateAccount inconsistency

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#748]
`validator::isValidDomainName()` is used in `CreateAccountExecutor::isValid()`
https://github.com/hyperledger/iroha/blob/develop/irohad/model/execution/impl/command_executor.cpp#L516-L519

Though account name is not domain name, it's **okay** that we use RFC 1035 and 1123 to validate account name.

But also, maybe this function can be used in `CreateDomainExecutor::isValid()`?
https://github.com/hyperledger/iroha/blob/develop/irohad/model/execution/impl/command_executor.cpp#L602-L607

**Comment by neewy** [comment]
@motxx specify exact method -- it is not meaningful in current develop

**Comment by Warchant** [comment]
What is the status of this issue?

**Comment by motxx** [comment]
I heard that we've already decided details of above constraints.
About above, finally we use RFC for domain_id, not account_id. And account_id and asset_id is regex rules.
