### ISSUE TITLE
Iroha daemon fails to start in Ansible environment

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#749]
**Given** macOS Sierra with ansible installed via brew, and commit of development branch https://github.com/hyperledger/iroha/commit/c81dd577b9779de6a679b5d6ea3bc38b61bc2114

**When** the Ansible network of peers is deployed according to https://soramitsu.atlassian.net/wiki/spaces/IS/pages/127008772/How+to+run+Iroha+network+with+ansible guide and I am attaching to any of the peers running docker containers with Iroha, redis and Postgres,

**Then** docker container with Iroha does not start:
```
iroha@instance-group-4-1c06:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
85956175c272        redis:3.2.8         "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        6379/tcp            iroha_redis
13e2b81030dc        postgres:9.5        "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        5432/tcp            iroha_postgres
```
**and** docker logs contain:
```
iroha@instance-group-4-1c06:~$ docker logs iroha
key=node0
/opt/iroha_data
iroha-cli: error while loading shared libraries: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory
irohad: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```

**Comment by x3medima17** [comment]
Fixed by https://github.com/hyperledger/iroha/pull/750 PR

**Comment by Warchant** [comment]
I close this issue? @x3medima17 @neewy

**Comment by neewy** [comment]
Fixed by https://github.com/hyperledger/iroha/pull/762

**Comment by l4l** [comment]
Not yet
