### ISSUE TITLE
Peer signature in QueryResponse

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#752]
To guarantee getting valid data from peers, we may need to use peer signatures in QueryResponse.
```proto
message QueryResponse {
  message Payload {
    oneof { ... }
  }
  Payload payload = 1;
  Signature signature = 2;
}
```
Clients can gurantee the response valid theoretically if they issue queries which have same commands to f + 1 nodes.
If lack of signature in query response, clients cannot know whether the value is from Iroha peers' or not.

**Comment by l4l** [comment]
I think it should be guaranteed by the transport

**Comment by Warchant** [comment]
There are two types of people who is typically issues query:
1. peer operator
2. client

Operator has full access to the peer data, so there is no reason to sign answers.

However, clients do not have access. For them it is preferable to use TLS (transport level security). It guarantees that data between client and server (peer) is encrypted, peer is authenticated. 

GRPC has option to turn TLS on. It is not implemented now in iroha, but eventually will be.

**Comment by motxx** [comment]
I see. Thank you. Then, I'll close this issue.
