### ISSUE TITLE
Maybe cannot distinguish latest key-value in nested-kv of SetAccountDetail?

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#753]
In https://github.com/hyperledger/iroha/pull/732/ nested-kv storage is adopted.
It seems to distinguish creator_account_id and grantee's account_id, but if they use the same key, how to know which one is the latest information?

Example:
```JSON
{ "my_account@domain" : { "same_key" : "foo" }, { "admin@domain" : { "same_key" : "bar" } } }
```

**Comment by grimadas** [comment]
Right now, if two users use same keys they are independent one from another.  admin@domain will have access for modification only to field with "admin@domain" key

**Comment by motxx** [comment]
Yes, but what is intended for? Maybe I missed some requirements?

If AccountDetail, that is a substitute for ComplexAsset, can be different depending on account_id,
maybe similarly AccountAsset needed to be different depending on account_id, but the latter one is obviously wrong.

**Comment by motxx** [comment]
I'm sorry, my understanding of kv-storage purpose is wrong. So I'll close this PR.
