### ISSUE TITLE
Outdated fuzzing library

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#766]
Right now, we have fuzzing implementation for Iroha which is 6 month old (/fuzz folder) and I am doubting the effectiveness of this tool at the moment. Can we investigate deeply into fuzzing with AFL or similar tools after alpha release?

**Comment by Warchant** [comment]
IMO we don't need fuzzing until we make big release.

**Comment by neewy** [comment]
can we delete the folder then?

**Comment by l4l** [comment]
fixed in #839
