### ISSUE TITLE
[Enhancement] Optimize block structure

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#774]
# Current design

Currently block has the following structure:
```protobuf
message Block {
  message Payload {
     repeated Transaction transactions = 1;
    uint32 tx_number = 2
    uint64 height = 3; 
    bytes merkle_root = 4;
    bytes prev_block_hash = 5;
    uint64 created_time = 6;
   }

  Payload payload = 1;
  repeated Signature signatures = 2;
 }
```

where `Transaction` is another complex proto object.
It is stored in a ledger as raw file. One file = one block.

Assume we have a query "give me a transaction with hash H", and assume we build an indexing system to make queries efficient. In this case we make an index `tx_hash -> block number` to know the block number for each transaction. 

Then, to query a single transaction, these actions must be performed:
1. find block with this transaction by looking at KV db (now Redis), normally O(1), if stored in hashmap.
2. given block number, query full block (read file, O(1) of ledger size)
3. for O(number of tx in block) search for given transaction blob.

IMO it is not efficient scheme, since query for specific transactions will be very frequent.

# Enhancement proposal

Store whole `block_store` in postgres:

Note: for now, ignore field `role`. 

![](https://i.imgur.com/0fpbuLp.png)

1. block is hashed (and therefore signed) with naive stream serializer (no protobuf, no boost::serialize), eg
    ```C++
    struct Block{
      uint64_t transactions;
      std::string tx_merkle_root;
      std::string prev_hash;
      uint64_t timestamp;
      std::string peer_merkle_root;
    };


    template <
        class CharT, 
        class Traits = std::char_traits<CharT>
    >
    std::basic_istream<CharT, Traits>& operator<< (std::basic_istream<CharT, Traits>& stream, const Block& b){
      // explicit order
      stream << b.transactions 
             << b.tx_merkle_root 
             << b.prev_hash 
             << b.timestamp 
             << b.peer_merkle_root;
      return stream;
    }

    // just example, can be used separate class Serializer or Hasher.
    Block b;
    std::istringstream ss;
    ss << b; 
    ss.str(); // serialized block, ready to be hashed and signed. Magic?

    ```

2. block has many signatures, 1-N  relation. therefore we need `signature` table with signature details. it is also possible to remove `id` field in `signature` table and make `<block_id, pubkey>` a primary key.

3. block itself does not store transactions, they are stored in a separate table **Transaction**. Current proposal does not include specific TX fields in DB, BUT it is strongly recommended NOT to store `HASH => BLOB`, but store `<hash, txfields...>`, because of efficient indexing and search.

4. to proove that transaction exists in specific block, merkle tree is used. merkle tree is stored as binary tree with max number of leafs = `MAX TX PER BLOCK` (2^14 is good start). It can be stored in postgres, or in any (possibly) more efficient on-disk data structure. It is important to store whole tree, because hash calculation is expensive by means of CPU time and query of intermediate nodes in tree is frequent operation.

It works like this:
- transactions are pushed to leafs, from the left to the right. 
- merkle tree is calculated during block creation, after we determined which transactions should be in the block.
- merkle tree is persisted on disk. 
- whenever anybody asks to proove that tx belongs to the block, we answer with a proof - **a path** from leaf (this tx) to the root, so that the one can calculate O(logN) hashes, obtain merkle root and compare it with `tx_merkle_root` from block, which is cryptographically signed.

    ![](https://image.slidesharecdn.com/bitcoinpdfversion-161119024130/95/intro-to-blockchain-using-bitcoin-as-an-example-10-638.jpg?cb=1479523864)

5. we have a requirement to add and remove peers on-the-fly. One way to solve this is to keep a list of available peers in the block and sign it, to prevent fraud. Problem arises: how to do it efficiently in terms of space? Because peers list may not be changed frequently, many blocks will have the same array and this is expensive in terms of disk space.

To understand who should have signed the block at the moment of block creation -- another merkle tree is used (`peer_merkle_tree`). It is used to proove that specific peer existed in the ledger at the moment of block creation. 

idea is the following:
- we maintain KV `peer_merkle_root -> [sorted array of peer pubkeys]` for all peer additions or removals. In other words, we maintain history of all `peer_merkle_root`s.
- when new peer is added, we push his pubkey to the `peer_merkle_tree`. accordingly, when removed - we remove its pubkey from merkle tree, resulting in creation of new record (change) ini `peer_merkle_root`s.

Example: one asks who signed the block `$given`. 
1. look at block `$given`, find `peer_merkle_root`
2. query array (lets call it ARR) of peer pubkeys from KV using `peer_merkle_root` from step above
3. PUBS=`SELECT pubkey FROM signature where block_id = $given;`. 
if:
   - `((len(ARR)-1) * 2. / 3.) <= len(PUBS)`  - number of signatures is more than 2/3 * N
   - `all([pubkey in ARR for pubkey in PUBS])`- all pubkeys are in array of peers from ARR
then:
   - answer with PUBS
 

Example: one asks, if peer A signed block 5?
1. look at block, find `peer_merkle_root`
2. find `peer A` in array of pubkeys by key `peer_merkle_root`
3. if found => it is a proof that he could not have signed tx, but definitely existed in the ledger at the moment of block 5 creation.
4. `SELECT * FROM signature where block_id = 5;`

This prevents storing redundant info many times, since we store only hash of pubkeys existed in ledger.

**Comment by l4l** [comment]
I like it

p.s: sorry for being short on so long post

**Comment by neewy** [comment]
By doing so we can also discard using complex redis indexing and use postgresql indices

**Comment by Warchant** [comment]
Bump

**Comment by LiraLemur** [comment]
See the issue in Jira: https://jira.hyperledger.org/browse/IR-190

**Comment by Warchant** [comment]
Outdated
