### ISSUE TITLE
Documentation issue (JSON)

### ISSUE THREAD

**Issue by Octarine-J** [hyperledger/iroha#779]
Some JSON examples for iroha-cli on the page
https://hyperledger.github.io/iroha-api/?json#get-roles
have trailing commas as in the following:
{
    "signature":
        {
            "pubkey": "…",
            "signature": "…"
        },
    "created_ts": …,
    "creator_account_id": "admin@test",
    "query_counter": 1,
    "query_type" : **"GetRoles",**
}

This leads to JSON parse error when executing 
iroha-cli  --grpc --json_query=query.json
(where query.json contains abovementioned query).

Please correct the documentation on the site.

**Comment by l4l** [comment]
Sorry, I'm not really sure that I clearly understood you
 
If you want to replace `...` in the example then imo it's not really good idea (at least for pubkey/signature). It basically can lead for using these objects with the default values (e.g keys) and that is not secure.
So it's intended being modified by the user in advance (thus built systems won't have backdoors)

**Comment by Octarine-J** [comment]
No, I mean the last comma in JSON file (shown in a bold font in the GetRoles example above) causes a parsing error.

**Comment by LiraLemur** [comment]
The issue seems outdated, I suggest closing it with the PR. Anyway, thank you fr noticing that issue!

There seems no issue with JSON at the moment (I believe it was fixed elsewhere).

**Comment by l4l** [comment]
iroha-api is considered deprecated actually, all docs are located at that repo
