### ISSUE TITLE
[Enhancement] Steps that must be taken before implementing test plan

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#794]
Given https://github.com/hyperledger/iroha/issues/786 and https://github.com/hyperledger/iroha/issues/787, 

I want to introduce a notion - **component** (look at terms for definition). Book [^1] (see issues above) describes few techniques on how to make large system more testable and maintainable. 

#### Dependency graph
![image](https://user-images.githubusercontent.com/1867551/34187766-5dec01f6-e576-11e7-8c85-1016a917d99a.png)

Given notation as above, we can build a physical (files) and logical (entities) dependency graph. In perfectly testable system in such graphs there are *no cycles* (in C++ terms - no circular dependencies) and system consists of clearly defined *components*, which may be combined in *packages*.

This graph then is topologically sorted -- this helps to visualize and *levelize* components (refer to terms for definition).

#### Levelization

![image](https://user-images.githubusercontent.com/1867551/34187756-5178b00e-e576-11e7-8b71-18946b48cd7a.png)

This is an example of levelized components for system. Given such graph, we can fix cross-dependencies problems.

Example of such problem: 
`common/types.hpp` has `class blob_t`. Internally this class uses `boost::optional`. Initially this file was created to store common types for iroha, such as hash type, pubkey type, etc.
For some reason someone added different functions and operators to this file. They do not have anything in common with `blob_t`, however `hash_t` does. 
Now, if I want to include `operator|` (monadic bind) in my class, I am **forced** to link against `boost`, because of `blob_t`, which I don't need at all.

#### What to do

I propose the following steps:
- [x]  we need to find a tool which helps to analyze physical and logical dependencies between components.
- [ ] we need to extract unrelated components from the same file in a separate files. Example of related components is `std::vector<T>` and `std::vector<T>::iterator`. Unrelated: `blob_t` and operators. Rationale: including one header we include one component. Not more.
- [ ] we need to remove cycled dependencies. 
- [ ] we need to remove unused headers from other `.h/.c`. This step can be  done with great tool [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use)
- [ ] we need to remove unnecessary libraries from link targets in `CMakeLists.txt`
- [ ] we need to follow rules from #787
- [ ] every *component* **must** have test, which covers 100% component's API (this test may not provide 100% branch coverage). such test is a **unit test**.

Please, read section 3.6 at http://users.encs.concordia.ca/~grogono/CourseNotes/SOEN-345-Notes.pdf to understand the benefits of such approach.

**Comment by Warchant** [comment]
Probably we can use something from
http://gernotklingler.com/blog/open-source-tools-examine-and-adjust-include-dependencies/

**Comment by Warchant** [comment]
There are some circular dependencies in shared_model:
![image](https://user-images.githubusercontent.com/1867551/34192284-766b2eb8-e590-11e7-953b-4629c1fc04cf.png)

**Comment by Warchant** [comment]
irohad:
![image](https://user-images.githubusercontent.com/1867551/34192542-eb0b02e2-e591-11e7-883c-12df9dc8c789.png)

**Comment by Warchant** [comment]
libs:
![image](https://user-images.githubusercontent.com/1867551/34192550-fbe2fe26-e591-11e7-8baf-ff54d5c3386d.png)

**Comment by l4l** [comment]
As for shared_model it's fine to has circle dependency on the interfaces, because it can't be tested by definition. So I think there's no need in this kind of work for this module.

irohad is obviously should be drastically refactored. Hopefully that may be eased after droppping support of the old model

libs also have a little problem but that can be fixed in few mins: just move either byteutils to the crypto or base64 to common

Thanks for reporting that!

**Comment by Warchant** [comment]
@l4l any circular dependency can be broken. Interfaces should not depend on the implementation, it is horrible mistake.

**Comment by muratovv** [comment]
Pls, verify what concrete wrong inside with concrete classes that broken. I feel, that there are (in most cases) no problems for dependencies at all.

**Comment by l4l** [comment]
> any circular dependency can be broken. Interfaces should not depend on the implementation, it is horrible mistake.

Yeah, i guess these better be moved to the interfaces/crypto

![screenshot_20171220_103731](https://user-images.githubusercontent.com/5658339/34196157-e4521370-e571-11e7-869a-fbbd7f3cb0fc.png)

**Comment by neewy** [comment]
@Warchant let’s run analysis over the project, decide how to localize circular dependencies and try to make tasks that are not cross-dependent

**Comment by l4l** [comment]
Outdated
