### ISSUE TITLE
ld: library not found for -lhash

### ISSUE THREAD

**Issue by lirm** [hyperledger/iroha#80]
Trying to build Iroha on Mac OS X, I'm running into the following error:

> [ 76%] Linking CXX executable ../bin/iroha-main
ld: warning: directory not found for option '-L/Users/e11778/work/_BLOCKCHAIN/iroha/core/vendor/ed25519/lib'
ld: warning: directory not found for option '-L/Users/e11778/work/_BLOCKCHAIN/iroha/core/vendor/KeccakCodePackage/bin/generic64'
ld: warning: directory not found for option '-L/Users/e11778/work/_BLOCKCHAIN/iroha/core/vendor/Aeron/cppbuild/Release/lib'
ld: warning: directory not found for option '-L/Users/e11778/work/_BLOCKCHAIN/iroha/core/vendor/leveldb/out-static'
ld: library not found for -lhash
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/iroha-main] Error 1
make[1]: *** [peer/CMakeFiles/iroha-main.dir/all] Error 2
make: *** [all] Error 2

**Comment by lirm** [comment]
A little extra information:

> cd ../core/infra/crypto/
> make
> g++   -std=c++0x -DKeccakP200_excluded -DKeccakP400_excluded -DKeccakP800_excluded -I../../vendor/KeccakCodePackage/bin/generic64/libkeccak.a.headers -c ../../vendor/KeccakCodePackage/SnP/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c -o KeccakP-1600-opt64.o
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
../../vendor/KeccakCodePackage/SnP/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c:18:10: fatal error: 'brg_endian.h' file not found
#include "brg_endian.h"
         ^
1 error generated.
make: *** [KeccakP-1600-opt64.o] Error 1

**Comment by lirm** [comment]
Got this resolved. I think build process needs some updating. Here are the steps to build the dependencies:

>cd $IROHA_HOME/core/vendor/KeccakCodePackage
make generic64/libkeccak.a

>cd $IROHA_HOME/core/vendor/ed25519/
make

>cd $IROHA_HOME/core/vendor/json/
make

>cd $IROHA_HOME/core/infra/crypto/
make

**Comment by MizukiSonoko** [comment]
Oh sorry,

I should write document...
And we research why CMake doesn't run.

**Comment by kansi** [comment]
@lirm really thankful for your update here, I have been trying to get it work. Also, I don't see much documentation on how to run and use Iroha. Could you please point me to some resources on how to run the ledger and execute transacitons ?

**Comment by lirm** [comment]
@kansi No problem. I've been trying to build and run it on my machine raw. I believe that currently suggested path for testing is to use Docker.

I've gotten to the point that everything builds (I still had to copy some libraries: `cp $IROHA_HOME/core/vendor/ed25519/lib/libed25519.* $IROHA_HOME/build/lib/`).

Now the next error I get is:

>[12:38:02] (LCHI092978) build:  (master)$ export IROHA_HOME=$PWD
[12:38:15] (LCHI092978) build:  (master)$ ./bin/iroha-main
1481222299 INFO [main] process is :62800
Fileが見つかりません
Fileが見つかりません
Fileが見つかりません
1481222299[sumeragi] +==ーーーーーーーーー==+
1481222299[sumeragi] |+-ーーーーーーーーー-+|
1481222299[sumeragi] || 　　　　　　　　　 ||
1481222299[sumeragi] || いろは合意形成機構 ||
1481222299[sumeragi] || 　　　すめらぎ　　 ||
1481222299[sumeragi] || 　　　　　　　　　 ||
1481222299[sumeragi] |+-ーーーーーーーーー-+|
1481222299[sumeragi] +==ーーーーーーーーー==+
1481222299[sumeragi] - 起動/setup
1481222299[sumeragi] - 初期設定/initialize
Fileが見つかりません
1481222299 INFO [sumeragi] My key is
1481222299 INFO [sumeragi] Sumeragi setted
1481222299 INFO [sumeragi] set number of validatingPeer
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: deque
Abort trap: 6

**Comment by kansi** [comment]
@lirm I got it running.
You are missing the [config file](https://github.com/hyperledger/iroha/blob/master/core/infra/service/peer_service_with_json.cpp#L19)

**Comment by lirm** [comment]
@kansi Thanks for the pointer!

A sample config file would be supremely helpful. I whipped the following by reading the code:

`
{
  "me": {
    "publicKey": "1",
    "privateKey": "2",
    "ip": "127.0.0.1"
  },
  "group": [
    {
      "ip": "127.0.0.1",
      "publicKey": "2"
    }
  ]
}
`

I then ran into a SEGFAULT with passing a null parameter list to Cappuccino server - parameter parsing exploded in getopt(). Apparently it doesn't expect null list - I've patched it up locally and that allowed me to, at least, bring up the process.

As far as examples of contracts and transactions - I'm waiting for documentation from the authors, but I'll poke around and see what I can figure out.

@MizukiSonoko I will close this one after the documentation is ready and I can do a clean build and run. Thank you.

**Comment by kansi** [comment]
@lirm I used this [config file](https://github.com/hyperledger/iroha-docker/blob/master/iroha/config1/sumeragi.json) as referecence to create the following config file,
```
{
  "me":{
    "ip":"127.0.0.1",
    "name":"iroha1",
    "publicKey":"jDQTiJ1dnTSdGH+yuOaPPZIepUj1Xt3hYOvLQTME3V0=",
    "privateKey":"iJy2wzgM0Ffmur2xDNlnhYK7CiAYZoup/045JXJTbUzuE9c6HeUIf7hoqtppEsZQncC1EEw+gGhboLcbMNKadw=="
  },
  "group":[
    {
    "ip":"127.0.0.1",
    "name":"iroha1",
    "publicKey":"jDQTiJ1dnTSdGH+yuOaPPZIepUj1Xt3hYOvLQTME3V0=",
    "privateKey":"iJy2wzgM0Ffmur2xDNlnhYK7CiAYZoup/045JXJTbUzuE9c6HeUIf7hoqtppEsZQncC1EEw+gGhboLcbMNKadw=="
  }
  ]
}
```
I starts the processes but they hog all my cpu. I guess it gets stuck in an infinite loop somewhere ?

**Comment by lirm** [comment]
@kansi Thanks for the pointer! Looks like iroha-docker repo has a lot of information on build. https://github.com/hyperledger/iroha-docker/tree/master/iroha-build has a lot. Maybe some of it should be detailed and available on the main repo's README/Wiki.

**Comment by kansi** [comment]
@lirm Iroha's main repo's README/wiki needs much more details that this !

**Comment by MizukiSonoko** [comment]
Currently how to build
https://github.com/hyperledger/iroha/blob/feature/add-how-to/docs/how_to_build.rst

Sorry for tha late...
