### ISSUE TITLE
Difficult to figure out why a transaction fails

### ISSUE THREAD

**Issue by Octarine-J** [hyperledger/iroha#803]
When performing a GRPC call (new transaction), a typical **irohad** output is:

> [15:26:03][th: 19345][info] [TxProcessor] << handle transaction
> [15:26:03][th: 19345][info] [SLV] << transaction validated
> [15:26:03][th: 19345][info] [PCS] << propagate tx
> [15:26:03][th: 19345][info] [OrderingGate] << propagate tx, tx_counter: 1 account_id: admin@test
> [15:26:03][th: 19345][info] [OrderingGate] << Propagate tx (on transport)
> [15:26:03][th: 19345][info] [TxProcessor] << stateless validation status: true
> [15:26:08][th: 19653][info] [OrderingGate] << receive proposal
> [15:26:08][th: 19653][info] [OrderingGate] << transactions in proposal: 1
> [15:26:08][th: 19653][info] [OrderingGate] << Received new proposal
> [15:26:08][th: 19653][info] [Simulator] << process proposal
> [15:26:08][th: 19653][info] [SFV] << transactions in proposal: 1
> [15:26:08][th: 19653][info] [SFV] << transactions in verified proposal: 0
> [15:26:08][th: 19653][info] [Simulator] << process verified proposal

As you can see, the verification fails for a transaction inside the proposal:
> [15:26:08][th: 19653][info] [SFV] << transactions in proposal: 1
> [15:26:08][th: 19653][info] [SFV] << transactions in verified proposal: 0
(For successful transactions, both numbers are 1.)

It is quite difficult to figure out what goes wrong. Can you consider enabling output of verification errors?

**Comment by neewy** [comment]
Yes, we do. In new model implementation all error related to validation will be clear and printed into log

**Comment by takemiyamakoto** [comment]
@neewy Does that mean this will be taken care of in Alpha? Is there documentation stating what the possible error codes are?

**Comment by rishavpiku** [comment]
My transaction logs seemed terrible ...

> ethTransactionInvoke 0xde895c2c73e9f5332c90e3e7ffa705f751f747b0 <tab>
balances              cancelRedemption      issue                 issuer                redeem                redemptionRequests    requestRedemption     totalSupply           transfer              uncommittedBalances
> ethInvoke 0xde895c2c73e9f5332c90e3e7ffa705f751f747b0 issue <tab>
<recipient, of type address>   ​ <amount, of type uint256>     ​ ​ <message, of type string>    ​ ​ ​                             issuer
> ethInvoke 0xde895c2c73e9f5332c90e3e7ffa705f751f747b0 issue 0xfbace661786d580ed4373c79689e7e8eb6ba05df 888 "Good luck!"
[info] V3 wallet found for '0x465e79b940bc2157e4259ff6b2d92f454497f1e4'
[info] Call data for function call: ebf469dc000000000000000000000000fbace661786d580ed4373c79689e7e8eb6ba05df00000000000000000000000000000000000000000000000000000000000003780000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000a476f6f64206c75636b2100000000000000000000000000000000000000000000
[info] Gas estimated for function call: 64486
[info] Called function 'issue', with args '0xfbace661786d580ed4373c79689e7e8eb6ba05df, 888, "Good luck!"', sending 0 wei to address '0xde895c2c73e9f5332c90e3e7ffa705f751f747b0' in transaction '0x6065dc98620f5f3e9683b1dd4941ed1e865eee3efd0d71a1868c9b302b2fbe90'.
[info] Receipt for transaction '0x6065dc98620f5f3e9683b1dd4941ed1e865eee3efd0d71a1868c9b302b2fbe90' not yet available, will try again in 15 seconds. Attempt 1/9.
[info] Receipt for transaction '0x6065dc98620f5f3e9683b1dd4941ed1e865eee3efd0d71a1868c9b302b2fbe90' not yet available, will try again in 15 seconds. Attempt 2/9.
[info] Receipt received for transaction '0x6065dc98620f5f3e9683b1dd4941ed1e865eee3efd0d71a1868c9b302b2fbe90':
[info] ClientTransactionReceipt(Keccak256[6065dc98620f5f3e9683b1dd4941ed1e865eee3efd0d71a1868c9b302b2fbe90],Unsigned256(6),Keccak256[574bb5fe35bdd82fa6a5f02ae2e74899665ffb76965e7dacc36d5e4d0fa14260],Unsigned256(2833845),Unsigned256(196033),Unsigned256(53739),None,List(EthLogEntry(EthAddress(ByteSeqExact20(0xde895c2c73e9f5332c90e3e7ffa705f751f747b0)),Vector(ByteSeqExact32(0x56efce5854bf1d184d330cc0c05667850247efb9dd786f6efac4c3cf93e7e60f), ByteSeqExact32(0x000000000000000000000000fbace661786d580ed4373c79689e7e8eb6ba05df)),ImmutableArraySeq.Byte(0x00000000000000000000000000000000000000000000000000000000000003780000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000a476f6f64206c75636b2100000000000000000000000000000000000000000000))))
[success] Total time: 61 s, completed Mar 29, 2018 3:41:29 PM

You get a lot of ugly noise when invoking a smart contract method. But one piece of information you do not get is a return value. When you want to look up information about a smart contract, do so by calling constant functions using the task ethInvokeConstant:

**Comment by takemiyamakoto** [comment]
Not sure if this is a dimensional rift or the Mandela Effect.

**Comment by neewy** [comment]
@rishavpiku are you sure to use Iroha?

**Comment by rishavpiku** [comment]
Yes

**Comment by neewy** [comment]
what version is that? 
we don't have support for smart contracts now, and the log seems to be either from other system or from old version (0.75)

**Comment by rishavpiku** [comment]
Yes, we dont have support for smart contracts now. It was done earlier in the old version.

**Comment by l4l** [comment]
It more looks like the ethereum logs. Nevertheless the 0.75 version isn't supported

**Comment by LiraLemur** [comment]
Issue seems outdated.
