### ISSUE TITLE
Build fails with taco pie dependency

### ISSUE THREAD

**Issue by neewy** [hyperledger/iroha#825]
Given master branch,
When I generate make files without `cpp_redis` and `tacopie` installed and try to build the project,
Then build fails with 

```Scanning dependencies of target irohad
[ 50%] Building CXX object irohad/main/CMakeFiles/irohad.dir/irohad.o
make[2]: *** No rule to make target `../external/src/cylix_cpp_redis-build/lib/libtacopie.a', needed by `bin/irohad'.  Stop.
make[1]: *** [irohad/main/CMakeFiles/irohad.dir/all] Error 2
make: *** [all] Error 2```

**Comment by l4l** [comment]
That's strange. Just tried a clean build - works fine for me
May you please remove _build_/_external_ dirs and try to rebuild simply with: `cmake .. && make`

**Comment by l4l** [comment]
Fixed
