### ISSUE TITLE
[new-cli] input cache proposition for easy using 

### ISSUE THREAD

**Issue by norihiro-ito** [hyperledger/iroha#827]
I want input cache of previous input for new-cli.
I think cache should do by every key.
for implementation example:

1st time:
```
Query is formed. Choose what to do:
1. Send to Iroha peer (send)
2. Save as json file (save)
0. Back (b)
> : 1
Peer address: localhost
Peer port: 50051
```

2nd time:
```
Query is formed. Choose what to do:
1. Send to Iroha peer (send)
2. Save as json file (save)
0. Back (b)
> : 1
Peer address(localhost): (only ENTER)
Peer port(50051): (only ENTER)

```

**Comment by neewy** [comment]
Exactly, this is inconvenient to type localhost every time. @grimadas do you think we can change it fast?

**Comment by coderwassananmol** [comment]
Hi, I would like to work on this issue. I am working on a patch for this and would revert back shortly.

**Comment by uditha-atukorala** [comment]
@coderwassananmol, are you still working on this? 

Had a quick look and there are already defaults for IP and port but `parseParams` won't allow empty input values ([iroha-cli/interactive/impl/interactive_common_cli.cpp#L127](https://github.com/hyperledger/iroha/blob/5efd87bd0014b54339dd7479192aed582bd31e44/iroha-cli/interactive/impl/interactive_common_cli.cpp#L127)). Happy to send a PR if no one else is working on this.

**Comment by coderwassananmol** [comment]
@uditha-atukorala Please feel free to submit PR. :)

**Comment by LiraLemur** [comment]
Seems like the PR on the issue has been merged. 
Great job 👍
