### ISSUE TITLE
Add asset quantity was not work

### ISSUE THREAD

**Issue by norihiro-ito** [hyperledger/iroha#829]
I tried add-asset-quantity by following steps. 
Perhaps my step was wrong, but it not work.
If my step is wrong, please teach me correct step for add-asset-quantity.

And I have something to worry about setting.
I m running redis and postgres server for irohad now.
redis is no password mode. postgres's password is same as irohad config.
But I have a question. When postgres's schema is created?
these servers setting is undocument yet. Perhaps it related?

1. run iroha-cli
`nito@ubuntu:~/misc/wk$ iroha-cli --interactive --name admin@test`
admin@test's has 3 roles.
```
[15:30:37][th: 51210][info] [QueryResponseHandler] << [Account]:
[15:30:37][th: 51210][info] [QueryResponseHandler] << -Id:- admin@test
[15:30:37][th: 51210][info] [QueryResponseHandler] << -Domain- test
[15:30:37][th: 51210][info] [QueryResponseHandler] << -Roles-: 
 admin money_creator user
[15:30:37][th: 51210][info] [QueryResponseHandler] << -Data-: {}
```
2. create asset
```
> : 14
Asset name: rpt
Domain Id: test
Asset precision: 2
```
it formed following JSON.
```
{
    "signatures": [
        {
            "pubkey": "407e57f50ca48969b08ba948171bb2435e035d82cec417e18e4a38f5fb113f83",
            "signature": "324d54c83ffc66632c15dae56f109efecb91559e6b2866e1f2519a9c9550aea1bebc738317176f86cf5cf3754a9f0e968c111f4490299e2722a83084b1716f00"
        }
    ],
    "created_ts": 1514442919500,
    "creator_account_id": "admin@test",
    "tx_counter": 1,
    "commands": [
        {
            "command_type": "CreateAsset",
            "asset_name": "rpt",
            "domain_id": "test",
            "precision": 2
        }
    ]
}
```
3. add asset quantity
```
> : 16
Account Id: admin@test
Asset Id: rpt#test
Amount to add (integer part): 10000 
Amount to add (precision): 11
```
it formed following JSON.
```
{
    "signatures": [
        {
            "pubkey": "407e57f50ca48969b08ba948171bb2435e035d82cec417e18e4a38f5fb113f83",
            "signature": "27455a787630eb7b6492f165bea30872402943ee45e9a102b99c25ee54fa0967122471beeaab9edc61c56972d36907a17593edc9d124b7b532b0b0768eb7fd01"
        }
    ],
    "created_ts": 1514443127341,
    "creator_account_id": "admin@test",
    "tx_counter": 3,
    "commands": [
        {
            "command_type": "AddAssetQuantity",
            "account_id": "admin@test",
            "asset_id": "rpt#test",
            "amount": {
                "value": "10000",
                "precision": 11
            }
        }
    ]
}
```
4. get accout's asset
```
> : 7
Requested account Id: admin@test
Requested asset Id: rpt#test
```
it returned error.
`[15:47:15][th: 51210][error] [QueryResponseHandler] << Account assets not found`
and irohad log reported following.
`[15:47:15][th: 43516][info] [PostgresWsvQuery] << Account admin@test does not have asset rpt#test`

**Comment by kamilsa** [comment]
Good day @norihiro-ito !

Thanks for posting your question.

For me it seems that the problem is with precision you set for Add Asset Quantity command. 
From [documentation](https://hyperledger.github.io/iroha-api/#create-asset) you can see that precision is the amount of digits after the comma. 
It was decided that precision for all commands corresponding to the same asset should be the same. I.e. if you created asset with precision 2, you need to add quantity for this asset using the same precision.

I just repeated steps you done, but changed precision in AddAssetQuantity command from 11 to 2 and everything was ok.

Regarding your concern about the timing of schema creation, you can check that it is created when irohad starts for the first time. Schema is hidden in [storage object](https://github.com/hyperledger/iroha/blob/master/irohad/ametsuchi/impl/storage_impl.hpp#L129) which initializes when you run irohad

**Comment by norihiro-ito** [comment]
@kamilsa. thanks for your help. I could get it.
But I wonder the prompt is "amount to add".  So i think it will be values after the decimal point.
Thanks again.

**Comment by neewy** [comment]
However, it is very confusing to pass integer part and then precision. We should improve this in our future implementation of CLI

**Comment by norihiro-ito** [comment]
I think integer part exists for historical reason.
Bitcoin has two units; BTC and satoshi. BTC transactions are managed in satoshi internally.
The reason of precision seems possiblity of denomination in future.

**Comment by chenrenjing** [comment]
I do all thing follow you,but still get '[09:11:45][th: 1600][error] [QueryResponseHandler] << Account assets not found
'  ,Can u tell why?
