### ISSUE TITLE
make[2]: *** [core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o] Error 1

### ISSUE THREAD

**Issue by tkyonezu** [hyperledger/iroha#83]
Yesterday and this morning (JST), Iroha can't build and show below messages.

[ 70%] Building CXX object core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp: In function 'void http::server(std::map<std::__cxx11::basic_string<char>, std::function<int(json_parse::Object)> >)':
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:89:10: error: no matching function for call to 'route(const std::__cxx11::basic_string<char>&, http::server(std::map<std::__cxx11::basic_string<char>, std::function<int(json_parse::Object)> >)::<lambda(std::shared_ptr<Cappuccino::Request>)>)'
         });
          ^
In file included from /opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:20:0:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:551:7: note: candidate: template<Cappuccino::Method m> void Cappuccino::route(const string&, std::function<Cappuccino::Response(std::shared_ptr<Cappuccino::Request>)>)
  void route(const string& path,std::function<Response(std::shared_ptr<Request>)> F){
       ^
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:551:7: note:   template argument deduction/substitution failed:
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:89:10: note:   couldn't deduce template parameter 'm'
         });
          ^
In file included from /opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:20:0:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp: At global scope:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:110:15: warning: 'void Cappuccino::Log::info(const string&)' defined but not used [-Wunused-function]
   static void info(const string& msg){
               ^
core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/build.make:62: recipe for target 'core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o' failed
make[2]: *** [core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o] Error 1
CMakeFiles/Makefile2:857: recipe for target 'core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/all' failed
make[1]: *** [core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2

**Comment by Warchant** [comment]
Confirmed.

I followed instruction from [docker build repo](https://github.com/hyperledger/iroha-docker#2-iroha) and after `docker build -t hyperledger/iroha .` got this error:

```
[ 70%] Building CXX object core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp: In function 'void http::server(std::map<std::__cxx11::basic_string<char>, std::function<int(json_parse::Object)> >)':
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:89:10: error: no matching function for call to 'route(const std::__cxx11::basic_string<char>&, http::server(std::map<std::__cxx11::basic_string<char>, std::function<int(json_parse::Object)> >)::<lambda(std::shared_ptr<Cappuccino::Request>)>)'
         });
          ^
In file included from /opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:20:0:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:551:7: note: candidate: template<Cappuccino::Method m> void Cappuccino::route(const string&, std::function<Cappuccino::Response(std::shared_ptr<Cappuccino::Request>)>)
  void route(const string& path,std::function<Response(std::shared_ptr<Request>)> F){
       ^
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:551:7: note:   template argument deduction/substitution failed:
/opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:89:10: note:   couldn't deduce template parameter 'm'
         });
          ^
In file included from /opt/iroha/core/infra/server/http_server_with_cappuccino.cpp:20:0:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp: At global scope:
/opt/iroha/core/infra/server/../../vendor/Cappuccino/cappuccino.hpp:110:15: warning: 'void Cappuccino::Log::info(const string&)' defined but not used [-Wunused-function]
   static void info(const string& msg){
               ^
core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/build.make:62: recipe for target 'core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o' failed
make[2]: *** [core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/http_server_with_cappuccino.cpp.o] Error 1
CMakeFiles/Makefile2:857: recipe for target 'core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/all' failed
make[1]: *** [core/infra/server/CMakeFiles/http_server_with_cappuccino.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Warchant** [comment]
Fixed in https://github.com/hyperledger/iroha-docker/pull/3

**Comment by tkyonezu** [comment]
Hi! everybody.

Sorry, to late read this mail.

Yes, this code seems so cool for us.

Thank you for your suggestion for our code, and I fully agree to
merge your code in iroha-docker.

—
Takeshi
