### ISSUE TITLE
gRPC calls from iOS app client crashing irohd

### ISSUE THREAD

**Issue by strfn** [hyperledger/iroha#833]
Irohad crash when called from a gRPC iOS client with the following error in the log:

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  blob_t: input string has incorrect length
```
Tested on iroha commit e96a186c36

### Client side protopbuf and gPRC stub:

I have generated the protobuf objects and the gRPC client stub using https://github.com/grpc/grpc-swift and https://github.com/apple/swift-protobuf plugins for the protobuf compiler.

I'm then sending messages to the peer with: 

```
 let queryServer = Iroha_Protocol_QueryServiceService(address: "\(ip):\(port)", secure: false)
        do {
            var message = createGetAccountInfoMessage()
            addSignatureTo(&message)
            print("============== TESTING QUERY SERVICE ================")
            print(message.textFormatString())   
            let find = try queryServer.find(message)
            print(find.textFormatString())
        } catch {
            print(error)
        }
        print("============== END TESTING QUERY SERVICE ================")
```

### Message signature
The message is signed using the iroha-ios cocoapod as:

```
private func addSignatureTo(_ query: inout Iroha_Protocol_Query) {
        let keypair = IrohaSwift.createKeyPair()
        var signature = Iroha_Protocol_Signature()
        signature.pubkey = keypair.publicKey.data(using: .utf8)!
        signature.signature = sign(publicKey: keypair.publicKey, privateKey: keypair.privateKey, message: try! query.payload.jsonString()).data(using: .utf8)!
        query.signature = signature
}
```

The signature validation should fail server side as the pub key is not registered on the network. but the daemon crash before outputting any validation error.

### Irohad configuration
Genesys block as generated by cli with peer list as localhost:20000

`../build/bin/irohad --config config.sample --genesis_block genesis.block --keypair_name node0`

config file

```
{
  "block_store_path" : "/tmp/block_store/",
  "torii_port" : 50051,
  "internal_port" : 20000,
  "pg_opt" : "host=iroha501_postgres_1 port=5432 user=postgres password=mysecretpassword",
  "redis_host" : "iroha501_redis_1",
  "redis_port" : 6379,
  "max_proposal_size" : 10,
  "proposal_delay" : 5000,
  "vote_delay" : 5000,
  "load_delay" : 5000
}
```

### irohad log

> [18:19:42][th: 5383][info] [MAIN] << start
> [18:19:42][th: 5383][info] [MAIN] << config initialized
> [18:19:42][th: 5383][info] [IROHAD] << created
> [18:19:42][th: 5383][info] [StorageImpl:initConnection] << Start storage creation
> [18:19:42][th: 5383][info] [StorageImpl:initConnection] << block store created
> [18:19:42][th: 5383][info] [StorageImpl:initConnection] << connection to Redis completed
> [18:19:42][th: 5383][info] [StorageImpl:initConnection] << connection to PostgreSQL completed
> [18:19:42][th: 5383][info] [StorageImpl:initConnection] << transaction to PostgreSQL initialized
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => storage
> [18:19:42][th: 5383][info] [StorageImpl] << Drop ledger
> [18:19:42][th: 5383][info] [StorageImpl] << drop dp
> [18:19:42][th: 5383][info] [StorageImpl] << drop redis
> [18:19:42][th: 5383][info] [StorageImpl] << drop block store
> [18:19:42][th: 5383][info] [MAIN] << Block is parsed
> [18:19:42][th: 5383][info] [MAIN] << Genesis block inserted, number of transactions: 1
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => converters
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => peer query
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => crypto provider
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => validators
> [18:19:42][th: 5383][info] [OrderingGate] << Subscribe
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => init ordering gate - [true]
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => init simulator
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => block loader
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => consensus gate
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => synchronizer
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => pcs
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => command service
> [18:19:42][th: 5383][info] [IROHAD] << [Init] => query service
> [18:19:42][th: 5383][info] [MAIN] << Running iroha
> [18:19:42][th: 5383][info] [IROHAD] << ===> iroha initialized

**Comment by strfn** [comment]
As @Warchant pointed out in the mailing list the problem is probably caused by a different representation of the signature between the Swift library and the server side.

The swift library represents the keypair and the message signature in base64 while the server side seems to expect those to be in HEX format.
I've also noticed a difference in the length of the private key when trying to convert from one system to another
i.e. the private key generated by Iroha-ios library is double the length of the public key while the keys automatically generated  when setting up the dev environment (e.g. the ones store in the  admin\@test.[pub|priv]) files seems to be of the same length.

Converting the signature to data using base64 encoding avoids the server to crash but still rejecting any query/transaction with the error:
`crypto verification broken` 

For reference see snip of the sign function:

 ```swift

var signature = Iroha_Protocol_Signature()
signature.pubkey = Data(fromHexEncodedString: hexFromB64(keypair.publicKey)!)!
        
//using directly query.payload.textFormatString() as the message to sign leads to the same errror.
let messageToSign = IrohaSwift.sha3_256(message: query.payload.textFormatString())
let proof = IrohaSwift.sign(publicKey: keypair.publicKey, privateKey: keypair.privateKey, message: messageToSign)      
signature.signature = Data(fromHexEncodedString: hexFromB64(proof)!)!

query.signature = signature
```

**Comment by l4l** [comment]
Hey, @strfn! May you recheck that behavior again? I think #920 should partially fix that

**Comment by l4l** [comment]
Hey, @strfn! May you recheck that behavior again? I think #920 should partially fix that

**Comment by neewy** [comment]
as shared model is not used in tori, the problem remains. However, we will migrate to shared model in this sprint :)

**Comment by l4l** [comment]
Migrated to the new model, that should be stable for now. Feel free to write here if you still have a similar issue
