### ISSUE TITLE
Iroha cpu usage issue

### ISSUE THREAD

**Issue by kansi** [hyperledger/iroha#84]
I am trying to run iroha using the following config:
```
{
  "me":{
    "ip":"127.0.0.1",
    "name":"iroha1",
    "publicKey":"jDQTiJ1dnTSdGH+yuOaPPZIepUj1Xt3hYOvLQTME3V0=",
    "privateKey":"iJy2wzgM0Ffmur2xDNlnhYK7CiAYZoup/045JXJTbUzuE9c6HeUIf7hoqtppEsZQncC1EEw+gGhboLcbMNKadw=="
  },
  "group":[
    {
    "ip":"127.0.0.1",
    "name":"iroha1",
    "publicKey":"jDQTiJ1dnTSdGH+yuOaPPZIepUj1Xt3hYOvLQTME3V0=",
    "privateKey":"iJy2wzgM0Ffmur2xDNlnhYK7CiAYZoup/045JXJTbUzuE9c6HeUIf7hoqtppEsZQncC1EEw+gGhboLcbMNKadw=="
  }
  ]
}
```
but whenever I start iroha using `./iroha-main` it start consuming 100% cpu. I tried to look into the code and it seems that sumeragi is running in an [infinite loop](https://github.com/hyperledger/iroha/blob/master/core/consensus/sumeragi.cpp#L383) .

Any help on how to resolve this ?

**Comment by MizukiSonoko** [comment]
Oh sorry.

Could you wait while we implement callback?

**Comment by kansi** [comment]
Yup, what option do I have  :-)

**Comment by kansi** [comment]
@MizukiSonoko I wish to contribute to Iroha, are there any available docs which can help me understand the current design of the project like consensus protocols, ledger handling, events etc ?

**Comment by MizukiSonoko** [comment]
Ok thanks!
I will publish descriptions as soon as possible.
and currently document is https://github.com/hyperledger/iroha/blob/master/docs/iroha_whitepaper.md

thanks

**Comment by takemiyamakoto** [comment]
Is this still a problem now that we changed the event model?
