### ISSUE TITLE
Iroha 2-way pegging with Bitcoin blockchain

### ISSUE THREAD

**Issue by krasi69** [hyperledger/iroha#840]
I have a proposal for development of module which allow 2-way pegging between Iroha and the Bitcoin blockchain. This module will support the Counterparty protocol - https://counterparty.io . So that the Counterparty tokens could be transferred to Iroha and from Iroha. This new module will allow Iroha to be used for transfer of value in the form of Bitcoin or Counterparty tokens. The Counterparty tokens can represent different financial instruments like stocks, bonds, futures, options, funds, currencies and commodities.

**Comment by neewy** [comment]
Nice! Thanks, we should check this out.
What about ERC20 tokens?

**Comment by krasi69** [comment]
The Counterparty tokens can be converted to Ethereum ERC20 tokens.

**Comment by takemiyamakoto** [comment]
Can you please elaborate?

**Comment by krasi69** [comment]
I can contribute. You can contact me at Skype : krasi1969 .

**Comment by neewy** [comment]
Solution is to open separate repo and continue work in it
