### ISSUE TITLE
[Question] How to identify Iroha ledger? 

### ISSUE THREAD

**Issue by MizukiSonoko** [hyperledger/iroha#846]
Currently, I fix iroha-cli. and I think it will support multi-ledger simultaneously.
But I think it happens in the future.
- A ledger and B ledger has some name 'a@japan` 
- cli load a@japan's key.

So cli wants to get ledger's Id like `E82A4F8D-F8BA-4A0D-A021-AE8128CE9D29` and identify Iroha.

Does Iroha have API supports it?

**Comment by muratovv** [comment]
Iroha doesn't support multi-ledger techniques. For solving your issue I suggest using a hash of genesis block.

**Comment by motxx** [comment]
How to know the addresses of all peers?

**Comment by neewy** [comment]
@motxx from which perspective?

**Comment by motxx** [comment]
This is just a quick question. If Iroha scales out a bit in order to use the same ledger in several companies, maybe we need some peer information from each other?

**Comment by muratovv** [comment]
Now we don't have a query for fetching all peers in the ledger.

**Comment by l4l** [comment]
Seems resolved
