### ISSUE TITLE
Is this correct iroha python usage?

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#849]
In master branch or v1.0_alpha
1. `docker pull hyperledger/iroha-docker-develop`
2. `./scripts/run-iroha-dev.sh`
3. `docker exec -it --user root CONTAINER`
4. Install swig with cloning repository from https://github.com/swig/swig/wiki/Getting-Started
  - `apt -y install swig` install old version, so maybe it cannot work?
5. Follow README before `./prepare.sh
`: https://github.com/hyperledger/iroha/tree/master/example/python
6. Build CMake to the latest version.
  - `apt -y install cmake` install old version 3.5.1. It shows: `Unknown CMake command "swig_add_library"`
7. `./prepare.sh`

**Comment by l4l** [comment]
Seems that some swig [debian's](https://packages.debian.org/sid/swig) [repo](https://packages.ubuntu.com/bionic/swig) are up-to-date. Moreover it probably may work with older ones
The rest looks good

**Comment by luckychess** [comment]
Just check Swig version, it should be at least 3.0.12. As I remember in our docker apt installs only 3.0.8 which does not support some C++ features we use; in that case you need to download sources for 3.0.12 and build them manually.
Also be careful about use of latest Swig from their master/some_else branch - some of us tried it and faced problems. Unfortunately Swig does not guarantee its master to work.
About CMake - you need at least version 3.8.

**Comment by neewy** [comment]
@motxx please confirm if this helps

**Comment by motxx** [comment]
Thank you very much.
So you mean swig version is not 4.0, but 3.x might be better, right?
And. thank you for testing with debian's repo.

**Comment by l4l** [comment]
Sorry, what do you mean by 4.0 version of swig?
![screenshot_20180112_131049](https://user-images.githubusercontent.com/5658339/34870105-2cb4d852-f79a-11e7-89e6-731c7720b4c2.png)
I personally tested that with 3.0.12-1, probably @luckychess used the same. Can't say anything about the other ones.
I guess we need to state it somewhere

**Comment by luckychess** [comment]
I used plain 3.0.12 on MacOS installed via brew and probably same as @l4l on Linux (can't check it at the moment).
Also our CMake requires at least 3.0.12. Theoretically everything should work even with 3.0.11 (after editing root CMakeLists.txt) but I've never tested it.

**Comment by motxx** [comment]
Okay. About 4.0, it is from master branch build (I checked by `swig -version`)
I understand preferred version is 3.0.12. Thank you so much.
