### ISSUE TITLE
Role permissions inconsistency

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#850]
About Role permissions,
- shared model uses protobuf expression snake_case "can_add_asset_qty"
- Iroha uses UpperCamel "CanAddAssetQuantity"
Stateful validator uses UpperCamel expression.

<strike>So in my understandings, maybe `CreateRole` transaction from shared model cannot work?</strike>

What are your thoughts on that? If something wrong with me, please correct.

UPDATE:
- Link to internal(old fashioned) model:
https://github.com/hyperledger/iroha/blob/develop/irohad/model/permissions.hpp

- Link to shared model: https://github.com/hyperledger/iroha/blob/develop/shared_model/builders/protobuf/transaction.hpp#L213

**Comment by l4l** [comment]
May you specify the permission strings at the shared model? I don't remember any of it (also didn't find at the develop)

**Comment by motxx** [comment]
Sorry for missing link.
https://github.com/hyperledger/iroha/blob/develop/shared_model/builders/protobuf/transaction.hpp#L213
I think it parses snake_case to protobuf type.

**Comment by l4l** [comment]
Ah, seems so

**Comment by motxx** [comment]
Unrelated to this PR, also, I found I missed `CanGetDomainTransactions` permission in `permissions.hpp`

**Comment by neewy** [comment]
that was fixed partially in https://github.com/hyperledger/iroha/commit/999a1c710dda7936d3cb78b158c536a6ab714232

@l4l can you check if other issues persist (I mean those that are mentioned above by @motxx)

**Comment by l4l** [comment]
The first issue is still here, though it will work in new one anyway

And I'm not really got the second issue. Which permission are you speaking of?
https://github.com/hyperledger/iroha/blob/0f1d5b522f1e7ed2485f1cd806c96a9a74806912/schema/commands.proto#L38-L41

**Comment by l4l** [comment]
Fixed in #921 and some of the following prs
