### ISSUE TITLE
How to run tests of SWIG bindings and include them in CI?

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#858]
In CMake, generating SWIG bindings is OFF.
https://github.com/hyperledger/iroha/blob/develop/CMakeLists.txt#L41-L43
I made them ON. But I don't know how to run tests of them. How to run these tests?
Also, it seems that CI doesn't do tests of SWIG bindings.
Maybe `ModelTransaction[Query]Builder` cannot be tested if they are lack. So how to include these tests in CI?

**Comment by l4l** [comment]
Ensure that related SWIG_* is on (e.g `SWIG_JAVA=ON`) and testing is enabled (`TESTING=ON`)
Build whole project and run `ctest` with related filters (or "as is" if you have time), e.g `ctest -R java`
Note also python protobuf generation is broken for now, so you need manually build it via `make python_tests`

**Comment by motxx** [comment]
I tried master and other branch but I cannot find `python_transaction_test` and `python_query_test` .
The result of master branch:
```
iroha@71dde693f7fb:/opt/iroha/build$ ctest -R python_*
Test project /opt/iroha/build
    Start 73: python_transaction_test
1/2 Test #73: python_transaction_test ..........***Failed    0.43 sec
    Start 74: python_query_test
2/2 Test #74: python_query_test ................***Failed    0.42 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   1.17 sec

The following tests FAILED:
	 73 - python_transaction_test (Failed)
	 74 - python_query_test (Failed)
Errors while running CTest
```

CMake diff:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 69a0aa6f..86f8e7c9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -38,9 +38,9 @@ option(PACKAGE_TGZ  "Create TGZ package"             OFF)
 option(PACKAGE_RPM  "Create RPM package"             OFF)
 option(PACKAGE_DEB  "Create DEB package"             OFF)
 option(ENABLE_LIBS_PACKAGING "Enable libs packaging" ON)
-option(SWIG_PYTHON  "Generate Swig Python bindings"  OFF)
-option(SWIG_JAVA    "Generate Swig Java bindings"    OFF)
-option(SWIG_CSHARP  "Generate Swig C# bindings"      OFF)
+option(SWIG_PYTHON  "Generate Swig Python bindings"  ON)
+option(SWIG_JAVA    "Generate Swig Java bindings"    ON)
+option(SWIG_CSHARP  "Generate Swig C# bindings"      ON)

 if (NOT CMAKE_BUILD_TYPE)
   SET(CMAKE_BUILD_TYPE Debug)
@@ -56,6 +56,9 @@ if(PACKAGE_TGZ OR PACKAGE_ZIP OR PACKAGE_RPM OR PACKAGE_DEB)
   set(SWIG_JAVA OFF)
 endif()

+set(SWIG_PYTHON ON)
+#set(SWIG_JAVA ON)
+
 message(STATUS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
 message(STATUS "-DTESTING=${TESTING}")
 message(STATUS "-DBENCHMARKING=${BENCHMARKING}")
```

**Comment by l4l** [comment]
That's strange, may you rerun this test with `--output-on-failure` flag? Just tested at 78f152a8 (aka master), works fine for me. Do you have also python2 installed on your system?

Btw you can set cmake params instead of fixing CMakeLists it's much easier; e.g for python:
`cmake .. -DSWIG_PYTHON=ON`

**Comment by motxx** [comment]
This is what I've not reproduced. If I did, I'll report this. 🙇

**Comment by l4l** [comment]
Ok, open if you have problem on this
