### ISSUE TITLE
[Question] Does Iroha support API for checking live status?

### ISSUE THREAD

**Issue by MizukiSonoko** [hyperledger/iroha#863]
In my opinion, Iroha should support API about checking live status. 
If Iroha supports this function, which I should use API for checking?

**Comment by neewy** [comment]
Please define live status, what is this checking?

**Comment by Warchant** [comment]
Live status -- status of transaction or peer's health?

**Comment by neewy** [comment]
@MizukiSonoko can you specify what you mean?
