### ISSUE TITLE
Python Binding; ValueError: blob_t: input string has incorrect length

### ISSUE THREAD

**Issue by a-r-g-v** [hyperledger/iroha#864]
I used iroha-python v1.0_alpha.
When I run tx-example.py with my keypairs  I got a below error.

```
Traceback (most recent call last):
  File "tx-example.py", line 22, in <module>
    me_kp = crypto.convertFromExisting(admin_pub, admin_priv)
  File "/home/debian/irohapy/iroha.py", line 921, in convertFromExisting
    return _iroha.ModelCrypto_convertFromExisting(self, public_key, private_key)
ValueError: blob_t: input string has incorrect length
````

my private key is
```
1d7e0a32ee0affeb4d22acd73c2c6fb6bd58e266c8c2ce4fa0ffe3dd6a253ffb
```

my public key is
```
407e57f50ca48969b08ba948171bb2435e035d82cec417e18e4a38f5fb113f83
```

Please help me, what am I wrong point?

**Comment by luckychess** [comment]
Looks like your keys are correct (at least in terms of length). Could you try to run ```git clean -idx```, then pull latest master and run ```example/python/prepare.sh```?

**Comment by a-r-g-v** [comment]
@luckychess 
I re-pulled this repository and re-built the SDK. But, The same error occurred.
Could you check to reproduce the problem in your environment?

**Comment by a-r-g-v** [comment]
Sorry, I just noticed my mistake.
A cause of the problem is the file of my key pairs contained a new-line code.
Thanks a lot.
