### ISSUE TITLE
Remove block hash in genesis block

### ISSUE THREAD

**Issue by motxx** [hyperledger/iroha#871]
1. We cannot create genesis block hash, as I mentioned: https://github.com/hyperledger/iroha/issues/866
2. Hash should not store in genesis.block because user cannot create it and specifying hash is no meaning.
https://github.com/hyperledger/iroha/blob/develop/irohad/model/converters/impl/json_block_factory.cpp#L45
https://github.com/hyperledger/iroha/blob/develop/irohad/model/converters/impl/json_block_factory.cpp#L86

And I think maybe hash is not needed in block store, but I don't know about it because there is already previous_hash in block store.

**Comment by l4l** [comment]
Looks like an inconsistency, there's no such a think in [block.proto](https://github.com/hyperledger/iroha/blob/master/schema/block.proto#L23)

**Comment by LiraLemur** [comment]
The issue seems outdated.
