### ISSUE TITLE
[Enhancement] Proposal for organization of iroha repositories

### ISSUE THREAD

**Issue by Warchant** [hyperledger/iroha#886]
# Introduction

Iroha is big project. It contains of the following modules:

- `irohad` - main binary for Iroha daemon
- `iroha-cli` - command line interface for peer operator and client
- `shared_model` - C++ library, which is used by irohad, iroha-cli and potentially many other modules.
- `python client lib` - autogenerated by swig
- `java client lib`- autogenerated by swig
- `c# client lib` - autogenerated by swig.

Potentially we may have lots of other modules, like client lib for iOS, Haskell or Rust.

Currently all modules reside inside main `hyperledger/iroha` repository.

# Problem 

We need to maintain every module:

- must be versioned with semver
- must have CI
- good to have bug tracker
- language-specific client libraries must be posted to library repositories (java - maven, python - pip, etc). Every lib **must** be versioned with semver.

# Solution

Here I will describe steps we need to do, to make good development process for all modules:

- [x] 1. Define list of modules, their names and dependencies between them
- [ ] 2. Assign maintainer for every module. Clarify responsibilities.
- [ ] 3. For `shared_model`:
            1. rename to `libiroha` to be consistent with naming of UNIX libs
            2. extract it to separate repository `hyperledger/libiroha`
            3. remove dependencies on irohad / libs
            4. fully move `libs` to `libiroha`
- [ ] 4. For client libraries:
         1. clear (?) the legacy code in existing repositories (`hyperledger/iroha-ios`, `hyperledger/iroha-javascript` and so on)
         2. for libs where we generate bindings (C#, Python, Java):
            1. generate them once
            2. create branches as in `git flow`: tagged versions, master = latest stable code, develop = latest code
            3. declare version `1.0.0` 
            4. push with this version to according library repository (mvn, pip). 
            5. setup CI
            6. write tests and documentation
- [ ] 5. For `irohad` create separate repository `hyperledger/irohad`, put `irohad` code there, add `libiroha` as dependency
- [ ] 6. For `iroha-cli`:
         1. rename to `iroha` - to be consistent with naming, as in Docker (docker + dockerd)
         2. use `hyperledger/iroha` for `cli` only.
         3. it will be "official" and "maintainable" CLI. Since iroha is an opensource project, people may create other CLIs, using even other programming languages.
- [ ] 7. for `libs`: remove this folder and move contents to `libiroha`
- [x] 8. Eventually merge `warchant/ed25519` to `hyperledger/libiroha`.

This will help to make code segregation (changes in one module does not affect other), better management, creates separate issue tracker for every module (github issues), separate versioning.

Dependency graph:

```
client[hyperledger/iroha-*language] --> |if binding| libiroha
client[hyperledger/iroha-*language] --> |if native|  ed25519
libiroha[hyperledger/libiroha]      --> ed25519[warchant/ed25519]
iroha[hyperledger/iroha]            --> libiroha
irohad[hyperledger/irohad]          --> libiroha
```

Vote with :+1: or :-1: for this proposal. If you voted :-1: please, comment why.

**Comment by l4l** [comment]
I have minor fix: it's better leave libiroha here, so don't remove/archive this repo

**Comment by muratovv** [comment]
I think this improvement not needed for now. We will work in this direction after creating a stable version. Pls, check the history of Ametsuchi repository.

**Comment by Warchant** [comment]
@l4l not only irohad and iroha-cli depend on libiroha. Bindings also depend on libiroha. 
If you leave libiroha inside repository with irohad/iroha-cli, then other projects will depend on the whole repository.

**Comment by l4l** [comment]
> not only irohad and iroha-cli depend on libiroha. Bindings also depend on libiroha.
If you leave libiroha inside repository with irohad/iroha-cli, then other projects will depend on the redundant code (whole repository).

Yeah, I meant actually leave only libiroha here and remove the rest

**Comment by muratovv** [comment]
@Warchant  I guess better task that related to this issue is make our dependencies as submodules or subtrees. The task will be useful in terms of build time and management of dependencies may be more native and clear.

**Comment by neewy** [comment]
We have decided to extract shared_model classes to a separate repository and eventually to store client libraries that depend on it and are stored in a separate repository for simplification of CI pipeline. Also, we have decided to rename shared_model to libiroha for better consistency with UNIX naming style

**Comment by neewy** [comment]
In the future, I hope that iroha-cli is going to be rewritten and not dependent on iroha repo

**Comment by l4l** [comment]
Issue seems pretty stale and it's pretty well-known, but the fixes are not coming soon probably
