### ISSUE TITLE
[Bug] Failed on building python example

### ISSUE THREAD

**Issue by stinger112** [hyperledger/iroha#904]
I'm trying to build python example of Iroha client lib and get some errors when running `examples/python/prepare.sh`:

```
[ 60%] No install step for 'jtv_libpqxx'
[ 63%] No test step for 'jtv_libpqxx'
[ 63%] Completed 'jtv_libpqxx'
[ 63%] Built target jtv_libpqxx
CMakeFiles/Makefile2:3258: recipe for target 'shared_model/bindings/CMakeFiles/irohapy.dir/rule' failed
make[1]: *** [shared_model/bindings/CMakeFiles/irohapy.dir/rule] Error 2
Makefile:903: recipe for target 'irohapy' failed
make: *** [irohapy] Error 2
```

`prepare.sh` script seems outdated because command
```
cd example
cmake .. -DSWIG_PYTHON=ON && make -j1
```
works for me.

### System environment ###

Ubuntu 16.04
Iroha \#d4f4e3ca3351bb92be99be7c3df440dc4bb8738a

### Additional information ### 
GCC 7.2.0
Boost 1.65.1
SWIG 3.0.12

**Comment by l4l** [comment]
Hmm, script works fine for me. May you post all of the logs?

**Comment by luckychess** [comment]
Also branch name, please. And it would be really great if you run ./clean.sh from root iroha's folder and remove everything from example/python/build/.

**Comment by stinger112** [comment]
You can close this PR. It seems outdated in the new dev branch.
