### ISSUE TITLE
Database connection string "pg_opt" and "database" config options should not be used both

### ISSUE THREAD

**Issue by kuvaldini** [hyperledger/iroha#907]
Please remove deprecated "pg_opt" from documentation.  
Please check this is the only place.

<img width="718" alt="изображение" src="https://user-images.githubusercontent.com/47349143/112638821-50d72a80-8e48-11eb-8f76-9ba6ce263492.png">

Please also address #898 

@LiraLemur Please consider to update `example/config.sample` and force Sphinx to load code sample from source-tree rather than copy contents to doc!

**Comment by LiraLemur** [comment]
@kuvaldini the database too, right? The whole block? Or only the pg_opt?

**Comment by kuvaldini** [comment]
"Database" is actual config, pgopt is old and deprecated.

**Comment by kuvaldini** [comment]
@LiraLemur the best way is to load content from file  example/config.sample'

**Comment by LiraLemur** [comment]
@kuvaldini it's possible for the general example but there's also a description part anyway, which is simply impossible to load and it's important.

**Comment by kuvaldini** [comment]
The file should be loaded, description should forget about pg_opt and use corresponding config keys under "database" config tree

**Comment by LiraLemur** [comment]
I will make it load the file but we need to load it from the default branch which is main atm and there there is no metrics yet. 
Just FYI @kuvaldini 

Should be fine when it's merged into the main though

**Comment by kuvaldini** [comment]
For branch `support/1.2.x` or any other please use `config.sample` exactly from the same branch. NOT from `main`. That is important. 

This does not touch anything about metrics.
