### ISSUE TITLE
Enable support/1.2.x branch in readthedocs

### ISSUE THREAD

**Issue by kamilsa** [hyperledger/iroha#921]
![image](https://user-images.githubusercontent.com/9370151/113296095-b708f500-9301-11eb-88d8-4b00684581ed.png)

We should also add support/1.2.x branch here

**Comment by LiraLemur** [comment]
@kamilsa enabled. But builds will be failing.
For it to work need to merge fixes from main to support/1.2.x

**Comment by LiraLemur** [comment]
https://iroha.readthedocs.io/en/support-1.2.x/

works now!
