### ISSUE TITLE
[CI] Migrate to Github actions

### ISSUE THREAD

**Issue by kamilsa** [hyperledger/iroha#948]
Currently some times builds fall due to lack of disk space, because some machines are for builds are shared among several projects

1. Compare performance of CIs in Jenkins and Gihub actions and make sure that actions are not slower.
2. Reimplement all scenarios that are currently executed with "before merge to trunk" job in jenkins in github actions.

**Comment by kuvaldini** [comment]
During work on this task I researched the next:

* GH Actions is one of the best CI systems on the market, has good documentation, convenient user interface and gives ability to write laconic workflows description 
* By default GH Actions povides slow (for us) **free** runners => need to buy GH Enterprise of connect/integrate with current Jenkins runners
* By default for free accounts maximum cache size is 5GB => it is not enough to store vcpkg mutable cache
* GitHub provides one fixed hardware configuration for their Linux virtual machines: 2-core CPU, 7 GB of RAM, 14 GB of SSD disk space. **TOO SLOW**, **NEED custom external runners**
* Time of runners is limited. **Is Hyperledger GitHub enterprise user**
  ![изображение](https://user-images.githubusercontent.com/47349143/116821114-3c8df800-ab81-11eb-9837-8cb3cac44dcc.png)

**Comment by kamilsa** [comment]
Commit to PR:
* MacOS apple-clang + burrow + ursa
* Linux gcc-9 + burrow + ursa

Commit to PR + comment in GH PR (mandatory before merge):
* Same as "Commit to PR" + tests
* Windows + burrow + ursa + tests
* (Separate task) MacOS arm (M1) + burrow + ursa

Nightly:
* gcc10
* s390
* arm

After commit to support/1.2.x (dev) or main:
* build docker image

**Comment by kuvaldini** [comment]
@kamilsa  WARN there is no ready-to-use github-runner binary for s390! So it could be a challenge to build github-runner written in dotnet on dramatically slow free IBM machine.

Do we really need build for s390?
