### ISSUE TITLE
Account detail values are not sanitized

### ISSUE THREAD

**Issue by Octarine-J** [hyperledger/iroha#975]
In irohad/ametsuchi/impl/postgres_wsv_command.cpp
In PostgresWsvCommand::setAccountKV
Around line 340

`+ transaction_.quote("\"" + val + "\"")`

val, which corresponds to the account detail being set, may itself contain quotes (for example, we may want to store a JSON string as an account detail). In that case, an exception will be thrown as PostgreSQL query syntax will be malformed.

I think 'val' variable should also be checked whether it contains quotes ( " ), in which case all of them should be sanitized by adding the backslash symbol ( \\" ) before storing it in the database.

For example, trying to store 

`{"id":"100","name":"Arnold","surname":"Schwarzenegger"}`

as a user detail, results in trying to store

`"{"id":"100","name":"Arnold","surname":"Schwarzenegger"}"`

whether it probably should be

`"{\"id\":\"100\",\"name\":\"Arnold\",\"surname\":\"Schwarzenegger\"}"`

This also may have further security-related implications (SQL injection vulnerabilities).

**Comment by l4l** [comment]
[Quote should do](http://pqxx.org/devprojects/libpqxx/doc/4.0/html/Reference/a00203.html#ga81fe65fbb9561af7c5f0b33a9fe27e5a) the thing, `"` are actually redundant

Just tested a few cases, both won't accepted by psql and escaped:
`24\"` -> `'"24""'`
`24\"\'` -> `'"24"''"'`

**Comment by takemiyamakoto** [comment]
What if someone tries to write: ```{'id':'100','name':'Arnold','surname':'Schwarzenegger'}```?

**Comment by l4l** [comment]
> What if someone tries to write: ```{'id':'100','name':'Arnold','surname':'Schwarzenegger'}```?

Not sure how is it quoted, but it insterted in the db as intended:
![screenshot_20180214_092746](https://user-images.githubusercontent.com/5658339/36190473-9ba6c566-1169-11e8-929c-e26fc1bd5a4b.png)

**Comment by Octarine-J** [comment]
Please note that our JSON string in the example contains double quotes ( " ) not single quotes ( ' ).
You probably won't be able to successfully execute setAccountDetail("\"").

**Comment by Warchant** [comment]
No visible activity. Closing.
