### ISSUE TITLE
Iroha documentation proposal

### ISSUE THREAD

**Issue by grimadas** [hyperledger/iroha#976]
# Documentation proposal

The document describes some ideas to improve current documentation. 

- Iroha "Get Started" Guides: 
   * Overview of Iroha. Main motivation 
   * Get started: build and install iroha
   * Get started: Setup machine, create account, asset, transfer
   * Get started: Iroha in production 
   * Mobile and web libraries. Features and focus of mobile applications
   * Relationship to Fabric and Sawtooth Lake
- Iroha core concepts: 
   * Account, User 
   * Peer, Ordering Service, Consensus
   * Transaction, Query 
- Business logic with use cases: 
   * Example usage of iroha-cli/irohad
   * Iroha Use cases in the wild 
   * Description of commands and validations
- API: 
   * Overview. Description, libs and current status. 
   * Administration. Configuration, preparing database, monitoring. 
   * Errors. Description of errors in Iroha 
   * Tutorials. Simple use case to demonstrate the Iroha API usage. 
   * Endpoints. Iroha endpoints for grpc 
   * C++ API
   * Java API
   * Python API
   * Node.JS API
   * C# API
- Iroha dev-ops:
  * Create swarm network of Iroha nodes 
  * How to run Iroha network with Ansible
  * Testing; How to run testing
- Contribution
  * Policy (code style, pr application, working agreement)
  * Architecture documentation
* Contact us
 - github issues
 - telegram
 - mailing list
 - gitter
 - rocket chat

**Comment by muratovv** [comment]
I think we need focus on roles of documentation consumers. Such as if u are a newcomer and want to look at the basic functionality - one documentation, you are interested to deploy the system in the production - another documentation.

In this case, need to clarify the consumers and make the focus on it.

**Comment by muratovv** [comment]
Also, keep in mind that this documentation will store in the Iroha's repository and there are possible to make cross-references for code documentation and vice versa.

**Comment by lebdron** [comment]
As it was said above, it would be great if a person can have a section based on his intentions. Please also consider the following structure:
```
* API documentation
 - C++ API
 - Java API
 - Python API
 - Node.JS API
 - C# API
 - Endpoints
 
* Iroha guide
 - Install
 - Single peer
 - Cluster

* Business logic (use cases)
 - Simple example
 - List of use cases...
 - Glossary: Description of commands and validations
 
* Contribution
 - Policy (code style, pr application, working agreement)
 - Architecture documentation
 - DevOps documentation
 
* Contact us
 - github issues
 - telegram
 - mailing list
 - gitter
 - rocket chat
```
References:
https://ripple.com/build/
https://www.stellar.org/developers/

**Comment by l4l** [comment]
Would be nice to add a section for iroha-cli/irohad usage with examples (not as detailed in as in devops section, and not as "high-level" as in getting started)

**Comment by neewy** [comment]
@grimadas can you please summarise those changes and present a finalised version of docs which we will implement with next release?

**Comment by neewy** [comment]
I guess we need to finish this work in 2 days (present the structure)

**Comment by neewy** [comment]
> Relationship to Fabric and Sawtooth Lake

why only them?

> Contribution
> …
> Architecture documentation

why architecture is in contribution? @lebdron @muratovv Architectural & design documents are a big part of the project and I am not sure what exactly you want to see there. Can you specify?

**Comment by neewy** [comment]
Do we have a glossary section?

**Comment by grimadas** [comment]
We can put glossary in iroha core concepts, they pretty much the same. 
>> Relationship to Fabric and Sawtooth Lake

> why only them?

As they are the in the same Hyperledger initiative, many questions are related to the comparison of Iroha and Fabric. We can discuss more, compare to all other systems in whitepaper. 

>> Contribution
>> …
>> Architecture documentation

>why architecture is in contribution? @lebdron @muratovv Architectural & design documents are a big part of the project and I am not sure what exactly you want to see there. Can you specify?

As I understand, this architecture (more of internal documentation) from developer and contributer point of view.  We can also put  a link  to internal documentations, and project (directory) structure here.

**Comment by neewy** [comment]
Ok!

**Comment by grimadas** [comment]
Lets fix for now the documentation structure and start writing them
